### ISSUE TITLE
Is there a way to add `vectorstore` to `ConversationChain` or memory to `ChatVectorDBChain`

### ISSUE THREAD

**Issue by westlinkin** [hwchase17/langchain#1015]
Great lib!!!

How to held a conversation with vector db context provided? 

Tried `ConversationChain`, but no way to add `vectorstore` to the chain.

Tried `ChatVectorDBChain`, but this easily exceeded the model's maximum context length:

```
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4695 tokens (4439 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
```

change `chain_type` to `refine` or `map_reduce`, also get error message:

```
pydantic.error_wrappers.ValidationError: 1 validation error for RefineDocumentsChain
prompt
  extra fields not permitted (type=value_error.extra)
```

Is there a way to add memory type to `ChatVectorDBChain` to reduce the context as the chat/conversation gets longer and longer?

Thanks in advance.

**Comment by hwchase17** [comment]
would love to collab with you on this

would you mind describing your ideal ux a bit more in detail?

it sounds like you want a chatbot with memory backed by a vectorstore

what are the entries in the vectorstore? are they previous messages/conversations?

**Comment by westlinkin** [comment]
Thank you very much for the help!

Basically, I want to build a chatbot with industry-specific knowledge. GPT is good enough, but it often gets wrong answers when it comes to some specific industries. So, I want to `ingest` all the documents related to an industry, get the vectorstore file stored, then users can learn industry-related knowledge from AI by chatting with AI. So the AI needs to have context about what some user previous chatting history, and when the conversation becomes longer and longer, optimize the prompt of every conversation.

**Comment by hwchase17** [comment]
ChatVectorDBChain is meant for this - the only different is that it expects chat_history to passed in as input. this is useful because often these chat bots are used in stateless servers. see https://github.com/hwchase17/chat-langchain for an example of doing so

does this answer your question?

**Comment by westlinkin** [comment]
Thanks! This helps a lot!

**Comment by alberduris** [comment]
Do you know if the chat history feature is functioning properly on the langchainjs library? I've been trying to get it to work, but it's not functioning as expected. I checked some well-known examples, but even though it looks like it's implemented correctly, it still doesn't work. 

You can find more details about the issue here: https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/65. Do you have any insight or suggestions? Thanks!
