### ISSUE TITLE
'from langchain.vectorstores import Chroma' could not find Chroma

### ISSUE THREAD

**Issue by ljhust** [hwchase17/langchain#1020]
following doc below:
https://langchain.readthedocs.io/en/latest/modules/utils/combine_docs_examples/vectorstores.html
from langchain.vectorstores import ElasticVectorSearch, Pinecone, Weaviate, FAISS, Qdrant, Chroma
could not find Chroma, as ref to the source code Chroma module has been delayed, please modify the doc correctly

**Comment by ljhust** [comment]
It is my version:  lanchain==0.0.84 and source below there is no Chroma included
<img width="650" alt="image" src="https://user-images.githubusercontent.com/5691352/218677942-fcb77db6-f838-433c-b3ef-ee357f3555f3.png">

**Comment by hwchase17** [comment]
should be fixed now

**Comment by CRortyDG** [comment]
App 2066 output: from langchain.vectorstores import Chroma
App 2066 output: ImportError: 
App 2066 output: cannot import name 'Chroma' from 'langchain.vectorstores' (/home/aidesign/virtualenv/groundskeeper/3.7/lib/python3.7/site-packages/langchain/vectorstores/__init__.py)

This error seems to still be present for me

**Comment by anton-b** [comment]
> App 2066 output: from langchain.vectorstores import Chroma App 2066 output: ImportError: App 2066 output: cannot import name 'Chroma' from 'langchain.vectorstores' (/home/aidesign/virtualenv/groundskeeper/3.7/lib/python3.7/site-packages/langchain/vectorstores/**init**.py)
> 
> This error seems to still be present for me


did you try to bump langchain in your requirements.txt, or take version constraint away and then:
pip install langchain --upgrade

**Comment by pvbang** [comment]
update langchain version

**Comment by Marbyun** [comment]
can someone help me 

i get this error 

> Traceback (most recent call last):
>   File "c:\Users\IvanRivaldo\anaconda3\envs\pytorch\Lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "C:\Users\IvanRivaldo\AppData\Local\Temp\ipykernel_10320\3217044270.py", line 16, in <module>
>     vectorstore = Chroma.from_texts(texts, embeddings) #,persist_directory=out_put_chroma
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "c:\Users\IvanRivaldo\anaconda3\envs\pytorch\Lib\site-packages\langchain\vectorstores\chroma.py", line 567, in from_texts
>     chroma_collection = cls(
>                         ^^^^
>   File "c:\Users\IvanRivaldo\anaconda3\envs\pytorch\Lib\site-packages\langchain\vectorstores\chroma.py", line 83, in __init__
> ...

this is my code:

```
fromlangchain.vectorstores import Chroma

....

vectorstore = Chroma.from_texts(texts, embeddings)
...
```

**Comment by manumklm** [comment]
After a long workaround i solved the issue like this.  override chromadb with pysqlite3-binary 
Please note that this is  applicable for linux only . In window i used python 3.11.5 to solve the issue.

1. install pysqlite3-binary
  pip install pysqlite3-binary

2. Add this in your project code where importing chroma


from langchain.vectorstores.chroma import Chroma
sys.modules['sqlite3'] = __import__('pysqlite3')

**Comment by Shoupadhyay** [comment]
what about mac ? also  i get error 24-06-13 10:14:35.016 Uncaught app exception
Traceback (most recent call last):
  File "/Users/shobhitupadhyay/anaconda3/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/shobhitupadhyay/Stream/main.py", line 9, in <module>
    chain = get_few_shot_db_chain()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shobhitupadhyay/Stream/langchain_helper.py", line 27, in get_few_shot_db_chain
    vectorstore = Chroma.from_texts(to_vectorize, embeddings, metadatas=few_shots)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shobhitupadhyay/anaconda3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 567, in from_texts
    chroma_collection = cls(
                        ^^^^
  File "/Users/shobhitupadhyay/anaconda3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 125, in __init__
    self._collection = self._client.get_or_create_collection(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shobhitupadhyay/anaconda3/lib/python3.11/site-packages/chromadb/api/client.py", line 237, in get_or_create_collection  even if i removes the metadatas argrument the link it provides is not available

**Comment by klopstock-dviz** [comment]
After the 'langchain.text_splitters' hard drop in favor of 'langchain_text_splitters', we cameback in dec 2025 to this old error !
After several months deploying langchain on several developpers without this error, it cameback 
I dont understand this array of instabilities

Note; in my original req.txt, i havn't specified a version:
langchain
langchain-community
...

This didn't got us any problem
