### ISSUE TITLE
SummaryChain output cutoff

### ISSUE THREAD

**Issue by cailurus** [hwchase17/langchain#1044]
Hey guys,

Happy to use this great tool to leverage LLM. Currently I'm trying to use it to summarize articles, and it's working very well most of the time.

Sometimes the output will be cut off due to OpenAI's issue like this, but in it's official WebUI I can type "continue" to let it finish, so do we have a way to address this in Langchain?

`{'output_text': '\n• Mayakovsky was a Soviet poet and playwright.\n• His most famous poem is “Clouds in Trousers”.\n• He was a Futurist poet and committed suicide at age 37.\n• His poetry reflects his pride and fragility.\n• He had a complicated love triangle with a married woman.\n• Maxim Gorky wrote the poem “Trousers of Clouds” in 1924.\n• The poem speaks of the power of love, art, system, and religion.\n• It encourages people`}

**Comment by batmanscode** [comment]
Have you tried increasing `max_tokens`?

https://github.com/hwchase17/langchain/blob/88bebb4caa66c51ab431a76abd3aab3b1cede530/langchain/llms/openai.py#L66

**Comment by cailurus** [comment]
@batmanscode  wow thanks, it worked.

**Comment by batmanscode** [comment]
> @batmanscode  wow thanks, it worked. 

Glad it worked! There's a default maximum set which gets applied if you don't specify
