### ISSUE TITLE
ImportError: cannot import name 'AI21' from 'langchain'

### ISSUE THREAD

**Issue by reletreby** [hwchase17/langchain#1071]
- Mac M1
- Conda env on Python 3.9
- langchain==0.0.87

`from langchain import AI21`
`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`ImportError: cannot import name 'AI21' from 'langchain' (/Users/reletreby/miniforge3/envs/gpt/lib/python3.9/site-packages/langchain/__init__.py)`

**Comment by trigaten** [comment]
`from langchain.llms import AI21` will likely work

**Comment by hwchase17** [comment]
echoing what @trigaten said, you should import it directly from the LLM module
