### ISSUE TITLE
How to control the number of parallel jobs in the MapReduce chain?

### ISSUE THREAD

**Issue by cailurus** [hwchase17/langchain#1073]
Hi guys,

I'm trying build a map_reduce chain to handle the long document summarization. Per my understanding, a long document will be cut into several parts firstly and then query the summary in map_reduce mode, that really make sense. However seems like OpenAI has a limitation on the query token per minute, is there a way to control the number of parallelization? 

`openai.error.RateLimitError: Rate limit reached for default-text-davinci-003 in organization org-xxx on tokens per min. Limit: 150000.000000 / min. Current: 2457600.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.`

**Comment by hwchase17** [comment]
yes! you can can control this with the `batch_size` parameter on the LLM. will add an example in the documentation

**Comment by msh01** [comment]
> 

this does not work for me 。 this is my code 。batch_size parameter on the LLM is setted
```JavaScript
    let path = "docs/epub/先秦学术概论-吕思勉.epub";
    const text = fs.readFileSync(path, "utf8");
    const model = new OpenAI({ temperature: 0 ,maxTokens: -1,batchSize:1});
    // const textSplitter = new RecursiveCharacterTextSplitter({ chunkSize: 1000 });
    const textSplitter = new RecursiveCharacterTextSplitter({ chunkSize: 2000 });
    const docs = await textSplitter.createDocuments([text]);

    // This convenience function creates a document chain prompted to summarize a set of documents.
    const chain = loadSummarizationChain(model, {
        type: "map_reduce",
        returnIntermediateSteps: true,
    });
    const res = await chain.call({
        input_documents: docs,
    });
    console.log('开始打印结果');
    console.log({ res });
```

**Comment by msh01** [comment]
openai respoonse 『openai.error.RateLimitError: Rate limit reached for。。。』
