### ISSUE TITLE
[Qdrant] `Qdrant.from_texts` Pydantic Validation Fails

### ISSUE THREAD

**Issue by ngundotra** [hwchase17/langchain#1098]
Pydantic error thrown on line 200 of `langchain/vectorstores/qdrant.py`

```python
points=rest.Batch(
  ids=[uuid.uuid4().hex for _ in texts],
  vectors=embeddings,
  payloads=cls._build_payloads(texts, metadatas),
)
```

Details:
- Python 3.9.7
- langchain 0.0.88

Additional context:
- Integration tests fail on fresh `langchain` repo install due to pydantic validation errors everywhere

Is this just a `python` versioning issue on myside? Do you have specific `typings` version I should pin?

**Comment by kacperlukawski** [comment]
@ngundotra Thanks for mentioning that. It should be fixed by #1114

**Comment by kacperlukawski** [comment]
@ngundotra I just realized you already made another PR #1102. Thanks a lot!

**Comment by hwchase17** [comment]
done with #1102
