### ISSUE TITLE
SQLDatabase chain having issue running queries on the database after connecting

### ISSUE THREAD

**Issue by nanditamohan** [hwchase17/langchain#1103]
Langchain SQLDatabase and using SQL chain is giving me issues in the recent versions. My goal has been this: 
- Connect to a sql server (say, Azure SQL server) using mssql+pyodbc driver (also tried mssql+pymssql driver)
`connection_url = URL.create(
            "mssql+pyodbc", 
            query={"odbc_connect": conn}
            )`
`sql_database = SQLDatabase.from_uri(connection_url)`

- Use this sql_database to create a SQLSequentialChain (also tried SQLChain)
`chain = SQLDatabaseSequentialChain.from_llm(
            llm=self.llm,
            database=sql_database,
            verbose=False,
            query_prompt=chain_prompt)`

- Query this chain

However, in the most recent version of langchain 0.0.88, I get this issue: 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/25394373/219547335-4108f02e-4721-425a-a7a3-199a70cd97f1.png">

And in the previous version 0.0.86, I was getting this: 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/25394373/219547750-f46f1ecb-2151-4700-8dae-e2c356f79aea.png">

A few days back, this worked - but I didn't track which version that was so I have been unable to make this work. Please help look into this.

**Comment by gocampo** [comment]
I found the same issue. It doesn't happen in 0.0.84. I still can't figure out why it's happening.

**Comment by jzluo** [comment]
Hi, this issue was introduced in #1081, and should be fixed by #1129. #1081 introduced a way to get the table definition statements, but in a sqlite3-specific way, so it broke compatibility with other database systems.

**Comment by nanditamohan** [comment]
@hwchase17 @jzluo 
Does the fix need a particular version of sqlalchemy or other things?
I am getting this error with 0.0.92: 


```[Tool(name='SalesSQL', description='useful for when you need to return a information about sales, product and customers', return_direct=True, verbose=False, callback_manager=<langchain.callbacks.shared.SharedCallbackManager object at 0x7f2d88cad100>, func=<bound method SQLGenerator.predict_str of <__main__.SQLGenerator object at 0x7f2d872cd2e0>>, coroutine=None)]
e6042b3c-d9df-4fba-82c6-ba8ab9816f14,BakerAgent Exception: (pymssql._pymssql.ProgrammingError) (102, b"Incorrect syntax near '1'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL:  SELECT MIN(DOB) as "Minimum Date of Birth" FROM Customers LIMIT 1]```

**Comment by jzluo** [comment]
Hi, this is an issue with the prompt, not SQLAlchemy. #1242 should fix this
