### ISSUE TITLE
Chroma embedding_function not a keyword for _client on most recent pull request

### ISSUE THREAD

**Issue by OmriNach** [hwchase17/langchain#1123]
<img width="716" alt="Screen Shot 2023-02-17 at 12 31 43 PM" src="https://user-images.githubusercontent.com/32659330/219725974-db991b3a-441d-4838-becd-2d9795734c05.png">
<img width="1004" alt="Screen Shot 2023-02-17 at 12 31 17 PM" src="https://user-images.githubusercontent.com/32659330/219725985-5d3aa4b9-f598-48b9-af53-d78730f2d5b9.png">

**Comment by OmriNach** [comment]
Had to upgrade chromadb

**Comment by AlKun25** [comment]
I am getting the same error, though I did try the above fix

**Comment by LukasMosser** [comment]
Can confirm, same error.
