### ISSUE TITLE
How to control parallelism of map-reduce/map-rerank QA chain?

### ISSUE THREAD

**Issue by nqbao** [hwchase17/langchain#1145]
Currently it is making up to N requests for all provided documents 

```
        results = self.llm_chain.apply(
            # FYI - this is parallelized and so it is fast.
            [{**{self.document_variable_name: d.page_content}, **kwargs} for d in docs]
        )
```

This cause a problem when i have a large doc (1000+ tokens) and I hit openai rate limit very fast. Can we add a parameter to control the concurrency overthere?

**Comment by hwchase17** [comment]
you can set that on the LLM level by setting `batch_size=N`

default is to 20

does this help?

**Comment by data-xyz** [comment]
do  [{**{self.document_variable_name: d.page_content}, **kwargs} for d in docs] means the chain will run one after one?
not just throw the task in the meantime?
it seem to be sync code, it will wait the response of llm_chain.apply single doc processing...
