### ISSUE TITLE
Receiving the error 'ImportError: failed to find libmagic.  Check your installation' when I try to use Document Loaders in local environment

### ISSUE THREAD

**Issue by akshayvkt** [hwchase17/langchain#1148]
I've been trying to use document loaders and when I run the code, I always receive the error 'ImportError: failed to find libmagic.  Check your installation'. I've uninstalled and reinstalled python-magic, done the same for the parent folder as well, but I still see the issue.

I've previously used langchain document loaders and I did not have any issue then. I've only been seeing this the past couple days. I believe this is an issue in my local env (VS code and Jupyter notebook), but I'm not sure what to do (I've tested in Google Colab and I'm able to use the document loaders there). Help much appreciated!

**Comment by akshayvkt** [comment]
Was able to resolve it - asked chatGPT and ran 'brew install libmagic'

**Comment by jinec** [comment]
@akshayvkt  apt install -y libmagic1 libmagic-dev  seems work
