### ISSUE TITLE
bug: `return_intermediate_steps=True` doesn't work for `"zero-shot-react-description"` agent 

### ISSUE THREAD

**Issue by AjinkyaIndulkar** [hwchase17/langchain#1171]
## Description

I was going through the Intermediate Steps documentation: https://langchain.readthedocs.io/en/latest/modules/agents/examples/intermediate_steps.html. 

My use case is to use this feature for conversation agent.

Sample code:

```
from langchain.agents import initialize_agent, load_tools
from langchain.chains.conversation.memory import ConversationBufferWindowMemory
from langchain.llms import OpenAI

llm = OpenAI(temperature=0, model_name="text-davinci-002")
tools = load_tools(["llm-math"], llm=llm)

agent = initialize_agent(
    tools,
    llm,
    agent="conversational-react-description",
    memory=ConversationBufferWindowMemory(memory_key="chat_history"),
    verbose=True,
    return_intermediate_steps=True,
)

response = agent(
    {
        "input": "Who is Leo DiCaprio's girlfriend? What is her current age raised to the 0.43 power?"
    }
)
```

### Actual Result

I get a `ValueError`:

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    response = agent(
  File "/home/ubuntu/miniconda3/envs/langchain-test/lib/python3.10/site-packages/langchain/chains/base.py", line 144, in __call__
    return self.prep_outputs(inputs, outputs, return_only_outputs)
  File "/home/ubuntu/miniconda3/envs/langchain-test/lib/python3.10/site-packages/langchain/chains/base.py", line 183, in prep_outputs
    self.memory.save_context(inputs, outputs)
  File "/home/ubuntu/miniconda3/envs/langchain-test/lib/python3.10/site-packages/langchain/chains/conversation/memory.py", line 146, in save_context
    raise ValueError(f"One output key expected, got {outputs.keys()}")
ValueError: One output key expected, got dict_keys(['output', 'intermediate_steps'])
```

### Expected Result

It should work similar to `"zero-shot-react-description"` agent from the docs.

## Remarks

I'd be happy to contribute to solve this issue.

**Comment by AjinkyaIndulkar** [comment]
For the moment, I am able to make it work with this quick hack:

```
from langchain.chains.conversation.memory import ConversationBufferWindowMemory as LangChainConversationBufferWindowMemory

class ConversationBufferWindowMemory(LangChainConversationBufferWindowMemory):
    """Custom ConversationBufferWindowMemory class.

    Overrides the `save_context` method to be compatible with conversation agents
    with `return_intermediate_steps=True`.
    """

    def save_context(self, inputs: Dict[str, Any], outputs: Dict[str, str]) -> None:
        """Save context from this conversation to buffer."""
        if "intermediate_steps" in outputs:
            outputs = outputs.copy()
            outputs.pop("intermediate_steps")

        super().save_context(inputs, outputs)
```

I am assuming that all the memory classes are affected by this, so a long term solution is required. We could add a new variable called `skip_intermediate_steps` to the `save_context` method but it will require changes in the Agent classes as well.

@hwchase17 thoughts?

**Comment by hwchase17** [comment]
i think it should work if you set `output_key="ouput"` when creating the memory object? eg

```
memory=ConversationBufferWindowMemory(memory_key="chat_history", output_key="output")
```

does that fix it?

**Comment by AjinkyaIndulkar** [comment]
It does! Awesome. Thanks for the quick response.

Is this already documented somewhere? If not, it might be useful to do so. 😄

**Comment by hwchase17** [comment]
its not... not sure of right place to document it tbh. will close for now, if happens to others will think more deeply

**Comment by amirsaffari** [comment]
A quick question: where do you pass the new `memory` object created? I tried passing it to the `initialize_agent` but still run to the same problem reported above.

**Comment by ajndkr** [comment]
@amirsaffari 

See if the following works:

```
agent = initialize_agent(
    tools,
    llm,
    agent="conversational-react-description",
    memory=ConversationBufferWindowMemory(memory_key="chat_history", output_key="output"),
    verbose=True,
    return_intermediate_steps=True,
)
```

**Comment by amirsaffari** [comment]
@ajndkr It resulted in the same. I tried also:

```
agent = initialize_agent(
    tools,
    llm,
    agent="conversational-react-description",
    agent_kwargs={'memory': ConversationBufferWindowMemory(memory_key="chat_history", output_key="output")},
    verbose=True,
    return_intermediate_steps=True,
)
```

I suspect one needs to get in to `LLMChain` [here](https://github.com/hwchase17/langchain/blob/882f7964fb0c5364bce0dcfb73abacd8ece525e4/langchain/agents/agent.py#L200)

**Comment by ajndkr** [comment]
@amirsaffari 

Hmm... can you open a new issue for this? Might be a bug in the recent versions. I suggest to also dump the traceback error log and langchain version for others to investigate it.

**Comment by amirsaffari** [comment]
For now, calling `agent` directly (i.e., not using `run` which bypasses the check throwing the exception) seem to work even without a new `memory` object.
