### ISSUE TITLE
UnstructuredFileLoader with unstructured.partition `file` in addition to `filename`

### ISSUE THREAD

**Issue by NathanJGaul** [hwchase17/langchain#1182]
I am trying to load a document using the `UnstructuredFileLoader` class but the file isn't accessible via the local file system and a filename. Instead the document is accessible through an `fsspec` filesystem on a remote system via an `OpenFile` object ([see the docs](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.core.OpenFile)). I believe the `Unstructured.partition` function used by `UnstructuredFileLoader._get_elements` method allows for something like this using the `file: Optional[IO]` parameter, but this is not exposed with `UnstructuredFileLoader`

**Comment by hwchase17** [comment]
how does that pr look? eg separate class. found it a bit easier than if/else
