### ISSUE TITLE
Link missing for Question Answering Notebook

### ISSUE THREAD

**Issue by glahoti6** [hwchase17/langchain#1189]
Until last week [LangChain 0.0.86], there used to be a link associated with "Question Answering Notebook" on this page -- https://langchain.readthedocs.io/en/latest/use_cases/question_answering.html). But it's not there anymore. Can it be fixed?

None of the links here https://github.com/hwchase17/langchain/blob/master/docs/use_cases/question_answering.md seem to be working.

@ShreyaR @hwchase17

**Comment by glahoti6** [comment]
@ShreyaR could you please help with this?

**Comment by glahoti6** [comment]
@hwchase17 FYI

**Comment by hwchase17** [comment]
thanks for flagging, will fix
