### ISSUE TITLE
Implement similarity_search_by_vector in the weaviate VectorStore

### ISSUE THREAD

**Issue by hsm207** [hwchase17/langchain#1212]
We should implement all abstract methods in VectorStore so that  users can use weaviate as the vector store for any use case.

**Comment by cs0lar** [comment]
similarity_search_by_vector is now implemented in the Weaviate Vector store

**Comment by cs0lar** [comment]
I don't really know, the method was already implemented (and is in the master branch) when I started taking over the weaviate issues but this ticket was still here..
