### ISSUE TITLE
notebooks (.ipynb) loader

### ISSUE THREAD

**Issue by klein-t** [hwchase17/langchain#1248]
I was looking for a .ipynb loader and realized that there isn't one. I already started to build one where you can specify if to include cell outputs, set a max length for output to include, and decide if to include newline characters. This latter feature is to avoid useless token usage, as openai models can detect spaces (at least davinci does), but could be useful to include it for other applications.

**Comment by eilone** [comment]
Hi!
I have some problem with the `NotebookLoader` loader:
I'm trying to access my repo and detect all of the `.ipynb` files, and then load them to the LLM Chain I'm implementing using LangChain. The repo can be viewed [here](https://github.com/eilone/RepoReader/tree/eilon-br) 


```
    for ext in extensions:
        glob_pattern = f'**/*.{ext}'
        try:
            loader = None
            if ext == 'ipynb':
                loader = **NotebookLoader**(str(repo_path), include_outputs=True, max_output_length=20,
                                        remove_newline=True,  loader_kwargs={"content_type": "text/plain"})
```

Yet I don't know how to pass the `glob_pattern` to this loader, resulting in going to the base dir and not being able to look for the notebook files...

```
[Errno 21] Is a directory: 'my_dir'
```

Can you please help me figure it out? Considering I don't want to pass each `ipynb` file-path individually?
