### ISSUE TITLE
unstructured_inference module not found even after  pip install unstructured[local-inference]

### ISSUE THREAD

**Issue by mitch-parker** [hwchase17/langchain#1267]
I created a virtual environment and ran the following commands:

pip install 'langchain [all]'
pip install 'unstructured[local-inference]'

However, when running the code below, I still get the following exception:

loader = UnstructuredPDFLoader("<path>")
data = loader.load()

ModuleNotFoundError: No module named 'layoutparser.models'

...

Exception: unstructured_inference module not found... try running pip install unstructured[local-inference] if you installed the unstructured library as a package. If you cloned the unstructured repository, try running make install-local-inference from the root directory of the repository.

**Comment by prasann** [comment]
I'm facing the same problem when trying to run the code inside a docker container. However, i see the container has this installed. any hint on how to go about this issue?

**Comment by linmou** [comment]
unstructured_inference is another lib,  'pip install unstructured_inference ' can solve this problem.

**Comment by AkshithaRao123** [comment]
> unstructured_inference is another lib, 'pip install unstructured_inference ' can solve this problem.

Tried that. This did not work too.
