### ISSUE TITLE
OpenAIChat error with async calls

### ISSUE THREAD

**Issue by teamclouday** [hwchase17/langchain#1372]
Hi, thanks for developing this great library!

I was using `chain.apredict` inside an async method and just updated to use `OpenAIChat` in `v0.0.98`.\
Now it's giving me error:
```
NotImplementedError: Async generation not implemented for this LLM.
```
The error was generated from this line:
https://github.com/hwchase17/langchain/blob/4b5e850361bd4b47ac739748232d696deac79eaf/langchain/llms/base.py#L337

**Comment by hwchase17** [comment]
will be in tmrws release

**Comment by teamclouday** [comment]
Thanks I see the release. Closing!

**Comment by varshasathya** [comment]
Hi
When I try to 'arun' the below chain using Sagemaker Endpoint, I'm receiving the following error.
chain = LLMChain(llm = SagemakerEndpoint(endpoint_name=llm_ENDPOINT), prompt=prompt)

NotImplementedError: Async generation not implemented for this LLM.

Is the Async calls available for other LLM chains other than Openai? If not, is there a workaround for the same.

Thanks in advance.

**Comment by rasharab** [comment]
@varshasathya https://github.com/langchain-ai/langchain/issues/9773

Hit the same issue, was surprised and we're bottlenecked by it...

**Comment by varshasathya** [comment]
@rasharab why is issue #9773 closed if there is no solution yet?
