### ISSUE TITLE
AWS Lambda - Read Only

### ISSUE THREAD

**Issue by Joepetey** [hwchase17/langchain#1412]
Langchain trys to download the GPT2FastTokenizer when I run a chain. In a Lambda function this doesnt work because the Lambda is read only. Any run into this, or know how to fix this?

**Comment by ellisonbg** [comment]
@3coins may be able to help with this.

**Comment by Joepetey** [comment]
That would be great if I could get some help with this, or some documentation! 

Thank you!

**Comment by juankysoriano** [comment]
Ah, I have also seen this issue. As I was mentioning on the langchain discord:

`OpenAIChat` uses `GPT2TokenizerFast.from_pretrained("gpt2")` for calculating the number of tokens, while `tiktoken.get_encoding("gpt2")` uses `tiktoken.

The first one is not usable when going serverless (AWS lambdas, or Google Cloud Functions). And it might represent a deal breaker for a more than valid use case. I'd even say a desirable use case, the serverless scenario.

So far I have been able to find a workaround, but it's not ideal and will be likely to suffer breaking changes as they continue updating langchain (which happens very frequently).

The workaround is to create a custom implementation of `OpenAIChat` overriding the problematic function.

```
class TikOpenAIChat(OpenAIChat):
    def __init__(self):
        super().__init__()

    def get_num_tokens(self, text: str) -> int:
        import tiktoken
        enc = tiktoken.get_encoding("gpt2")
        tokenized_text = enc.encode(text)
        return len(tokenized_text)
```

I hope this helps on your scenario @Joepetey , and let's aim for an official solution from @hwchase17

**Comment by juankysoriano** [comment]
Alternatively we could continue using `GPT2FastTokenizer` but we need facilitate a way of selecting where are those models going to be stored, serverless functions has typically some available space on `/tmp`.

Now, having to download everytime (serverless is stateless) is going to make things very slow I believe.

I am talking btw without being an expert.

**Comment by furlat** [comment]
the problem is in this function https://github.com/hwchase17/langchain/blob/763f87953686a69897d1f4d2260388b88eb8d670/langchain/llms/openai.py#L421

`encoder = "gpt2"
        if self.model_name in ("text-davinci-003", "text-davinci-002"):
            encoder = "p50k_base"
        if self.model_name.startswith("code"):
            encoder = "p50k_base"
        # create a GPT-3 encoder instance
        enc = `tiktoken.get_encoding(encoder)`

this should fix it 
if self.model_name.startswithl('gpt-3.5-turbo'):
    enc  = tiktoken.encoding_for_model('gpt-3.5-turbo')

if you do not use this you are going to miscalculate the tokens from the role\user assistant part of the message.

**Comment by juankysoriano** [comment]
I have opened a PR that would solve this issue.

https://github.com/hwchase17/langchain/pull/1457

**Comment by Joepetey** [comment]
Wow thank you @juankysoriano this is so helpful!

**Comment by juankysoriano** [comment]
solved by https://github.com/hwchase17/langchain/pull/1457

**Comment by Joepetey** [comment]
Quick question, when can we expect this to be available in a release?

**Comment by juankysoriano** [comment]
I don't know but the owner is typically very fast on doing releases, they are very frequent. It shouldn't take more than a couple of days in my experience. Will see

**Comment by juankysoriano** [comment]
@Joepetey if the recent release, `0.0.102` solved your problem, the issue can be closed.

**Comment by gmpetrov** [comment]
> Alternatively we could continue using `GPT2FastTokenizer` but we need facilitate a way of selecting where are those models going to be stored, serverless functions has typically some available space on `/tmp`.
> 
> Now, having to download everytime (serverless is stateless) is going to make things very slow I believe.
> 
> I am talking btw without being an expert.

With AWS you can mount an EFS to a lambda to cache a pre-trained model.
Checkout this example https://github.com/aws-samples/zero-administration-inference-with-aws-lambda-for-hugging-face

Also if you're using HuggingFaceEmbeddings (which uses sentence_transformers.SentenceTransformer) you need to use SENTENCE_TRANSFORMERS_HOME env variable to download the model at a specific location

**Comment by Joepetey** [comment]
Thank you Juanky, it worked!
