### ISSUE TITLE
Is proxy setting allowed for langchain.llm LLM like openai.proxy=os.getenv(HTTP_PROXY) ? please add if possible.

### ISSUE THREAD

**Issue by peter65374** [hwchase17/langchain#1423]
Is proxy setting allowed for LLM like openai.proxy = os.getenv(HTTP_PROXY) ? please add if possible.

openai-python api  has a attribute openai.proxy, which is very convenient for HTTP/WS proxy setting as :

```
import openai
import os

openai.proxy = os.getenv(HTTP_PROXY)  # HTTP_PROXY="your proxy server:port" is put in local .env file
```

How to set the attribute in langchain LLM instance? Give me a hint, thanks.

**Comment by peter65374** [comment]
I am handling one the issue myself and will submit a PR request today to solve it. I made testing locally and solved the proxy setting.

**Comment by peter65374** [comment]
> https://github.com/hwchase17/langchain/pull/1453  PR is submitted to solve the issue #1423. Please review it, thanks.

**Comment by hwchase17** [comment]
is there documentation on openAIs side about when/why to do this?

**Comment by peter65374** [comment]
> is there documentation on openAIs side about when/why to do this?

openai documentation [error code](https://platform.openai.com/docs/guides/error-codes/python-library-error-types) doesnt explicitly indicate the reason to set openai.proxy for APIConnectionError, while I noticed that [chat-langchain](https://github.com/hwchase17/chat-langchain) client-side **failed to make WebSocket connection** if the client browser was behind a firewall (company or others) in **async mode + streaming mode** (without **"in-code"**proxy setup). However, it works smoothly in sync mode(with "out-code" normal proxy).

To use lang-server tracing and prototype verification in Jupyter notebook, it was figured out that aiohttp package is the reason. Check the aiohttp documentation about [proxy support](https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support), which explains HTTP_PROXY or WS_PROXY setup in environment **"in-code"**. 

```
async with aiohttp.ClientSession() as session:
        async with session.get("http://python.org",
                           proxy="http://proxy.com") as resp:
        print(resp.status)
```


After "think step by step" trick😄, the simple solution is to **"in-code"** assign openai.proxy attribute as HTTP_PROXY variable from .env file.  

I could move the block to function-build_extra from func-validate_environment if you think the implementation in PR is not elegant since it might not be a popular situation for the common users.

**Comment by peter65374** [comment]
It seems that I finally figured out the How-to solve the issue. AzureOpenAI sample seems not the answer since not all of attributes are extracted from env setting in "openai/openai-python/init.py"
However, [langchain/ecosystem/Helicone docs](https://langchain.readthedocs.io/en/latest/ecosystem/helicone.html#how-to-enable-helicone-caching) show a valid example, which is straight and cool.

Tried in Juypter, it worked. I will withdraw my PR after a while.

**Comment by youngfreeFJS** [comment]
Hi @peter65374 
I have this same problem, have you found a resolution yet?
```
Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response'))).
```

**Comment by haohao0103** [comment]
@youngfreeFJS hello ,请问你的问题解决了吗？我也遇到这个情况了。谢谢啦
