### ISSUE TITLE
OpenAIChat token usage callback returns 0

### ISSUE THREAD

**Issue by artyemk** [hwchase17/langchain#1429]
When I try to get token usage from **get_openai_callback**, I always get 0. Replacing **OpenAIChat** with **OpenAI** works.

Reproducable example (langchain-0.0.100):

```
from langchain.llms import OpenAIChat
from langchain.callbacks import get_openai_callback

llm = OpenAIChat(temperature=0)

with get_openai_callback() as cb:
    result = llm("Tell me a joke")
    print(cb.total_tokens)
```

**Comment by JackNgWeiMing** [comment]
#1370 
Has been fixed after upgrading my package to  "0.0.101".

**Comment by rishabh-ti** [comment]
It does not work with ChatOpenAI.

**Comment by stephenleo** [comment]
Just submitted a PR to fix this: https://github.com/hwchase17/langchain/pull/1748

**Comment by stephenleo** [comment]
Submitted another PR for this: #1924 
Would love to get some feedback
