### ISSUE TITLE
Should Prompt Templates auto-detect variables?

### ISSUE THREAD

**Issue by pixegami** [hwchase17/langchain#1432]
I just started using LangChain and realised you to input the same data twice. Consider the template:

```
"What is a good name for a company that makes {product}?"
```

Rather than make users also input the variables like this `input_variables=["product"],`, wouldn't it be more useful to get detect and automatically figure out what the variables are in the `__post_init__`?

```python
pattern = r"\{(\w+)\}"
input_variables = re.findall(pattern, template)
```

If this sounds interesting, I can make a contribution.

**Comment by timothyasp** [comment]
+1 

I'd love to see this - it feels like I spend a silly amount of time fiddling with these params.  I haven't thought enough about the downsides, but it seems like validation will error if it's missing something, and the user can add memory or modify their input to the chain to fill in the necessary details.

**Comment by hwchase17** [comment]
there is `PromptTemplate.from_template(template)` that should do just that!

**Comment by pixegami** [comment]
Oh, I see — thanks for pointing that out. It does work. I'll resolve this issue, but my feedback is I feel like that should have been the default constructor. I generally prefer when libraries (and quick-start guides) are strongly opinionated to simple defaults.

Thanks for your response and your work on this incredible project!
