### ISSUE TITLE
Embedding Memory

### ISSUE THREAD

**Issue by chris-boson** [hwchase17/langchain#1448]
Would it make sense to add a memory that works similar to the QA chain with sources? As the conversation develops, we generate embeddings and store them in a vector DB. During inference we determine which memories are the most relevant and retrieve them.

This could be more efficient as we don't need to generate explicit intermediate summaries.

**Comment by chris-boson** [comment]
Seems related https://github.com/openai/chatgpt-retrieval-plugin/tree/main/examples/memory

**Comment by jordanparker6** [comment]
Related: https://github.com/hwchase17/langchain/issues/2256

**Comment by chris-boson** [comment]
Addressed in https://github.com/hwchase17/langchain/pull/2804
