### ISSUE TITLE
Ability to user Azure OpenAI

### ISSUE THREAD

**Issue by mkeywood1** [hwchase17/langchain#1506]
Firstly, awesome job here - this is great !! :)
However with the ability to now use OpenAI models on Microsoft Azure, I need to be able to set more than just the openai.api_key.
I need to set:

openai.api_type = "azure"
openai.api_base = "https://xxx.openai.azure.com/"
openai.api_version = "2022-12-01"
openai.api_key = "xxxxxxxxxxxxxxxxxx"

How can I set these other keys?
Thanks

**Comment by lakshyaag** [comment]
There is an `AzureOpenAI` class in the package. Please refer to:
1. https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L513
2. https://langchain.readthedocs.io/en/latest/modules/llms/integrations/azure_openai_example.html

**Comment by mkeywood1** [comment]
I missed that - thank you..

**Comment by speedyankur** [comment]
https://python.langchain.com/en/harrison-docs-refactor-3-24/modules/models/text_embedding/examples/azureopenai.html
