### ISSUE TITLE
Allow max_tokens = -1 for ChatOpenAI

### ISSUE THREAD

**Issue by adlindenberg** [hwchase17/langchain#1532]
The Chat API allows for not passing a max_tokens param and it's supported for other LLMs in langchain by passing `-1` as the value. Could you extend support to the ChatOpenAI model? Something like the image seems to work?

![image](https://user-images.githubusercontent.com/72746229/223863665-0708cef9-780f-4c17-bca9-7eb145036e7f.png)

**Comment by Aratako** [comment]
This solution seems to effectively resolve the issue.
Do you plan to create a pull request yourself? If not, I can make the necessary changes. Would that be alright?

**Comment by adlindenberg** [comment]
@Aratako that'd be fine with me, thank you!
