### ISSUE TITLE
Getting KeyError:'source' on calling chain after load_qa_with_sources_chain

### ISSUE THREAD

**Issue by prabhatranjan** [hwchase17/langchain#1535]
I am trying the question answer with sources notebook,
chain = load_qa_with_sources_chain(OpenAI(temperature=0), chain_type="stuff")
chain({"input_documents": docs, "question": query}, return_only_outputs=True)

The above gives an error:
File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py:65, in <dictcomp>(.0)
     62     base_info = {"page_content": doc.page_content}
     63     base_info.update(doc.metadata)
     64     document_info = {
     65         k: base_info[k] for k in self.document_prompt.input_variables
     66     }
     67     doc_dicts.append(document_info)
     68 # Format each document according to the prompt

KeyError: 'source'

**Comment by hwchase17** [comment]
you need to have a source field in your document metadata. or if you have a different field, you need to update the `self.document_prompt.input_variables`

**Comment by prabhatranjan** [comment]
It works now, thanks
