### ISSUE TITLE
ChatOpenAI vs OpenAIChat

### ISSUE THREAD

**Issue by rcanand** [hwchase17/langchain#1556]
There are currently two very similarly named classes - `OpenAIChat` and `ChatOpenAI`. Not sure what the distinction is between the two, which one to use, whether one is/will be deprecated?

**Comment by hwchase17** [comment]
OpenAIChat is deprecated, we will be going with ChatOpenAI in the future. all mentions of OpenAIChat should be removed from the documentation (if not the case, let me know)

**Comment by lethe3000** [comment]
`OpenAIChat` is a `BaseLLM` subclass, and `ChatOpenAI` is a `BaseChatModel` subclass.
@hwchase17 do you mean `ChatOpenAI` would also be a `BaseLLM` subclass so we could use `ChatOpenAI` to create `LLMPredictor` instance?

current code would report warning.
```
LLMPredictor(llm=OpenAIChat(**args))
```

**Comment by thdoan** [comment]
I know this is closed, but today I was led to this page from Google, which was confusing because it uses the deprecated class name: https://js.langchain.com/docs/category/classes-107

Maybe this page needs to be purged from Google results?
