### ISSUE TITLE
langchain.embeddings.OpenAIEmbeddings is not working with AzureOpenAI

### ISSUE THREAD

**Issue by JonAtDocuWare** [hwchase17/langchain#1560]
When using the AzureOpenAI LLM the OpenAIEmbeddings are not working.  After reviewing source, I believe this is because the class does not accept any parameters other than an api_key.  A "Model deployment name" parameter would be needed, since the model name alone is not enough to identify the engine.  I did, however, find a workaround.  If you name your deployment exactly "text-embedding-ada-002" then OpenAIEmbeddings will work.

edit: my workaround is working on version .088, but not the current version.

**Comment by aajn88** [comment]
I'm having the same issue. However, in my case, my deployment is also called `text-embedding-ada-002` too but it's failing with the following error:

`InvalidRequestError: Too many inputs for model None. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.`

I printed the name of the model right before the call was done in the source code and it's correct, so no sure what's happening

**Comment by aajn88** [comment]
Actually, by reading the error again, it seems like it's not related to the name of the model and azure just throttling.

So, in order to configure langchain embeddings properly, I have to replace [this part](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/faiss.py#L250) with my desired chunk_size:

`embeddings = embedding.embed_documents(texts, 1)`

Of course, ideally this should be sent by parameter

**Comment by floleuerer** [comment]
I ran into the same issue with the chunk_size in AzureOpenAIEmbeddings and provided a fix. The easiest way is to initialize your AzureOpenAIEmbeddings with chunk_size=1 - it works in other helper functions too when you can't pass the chunk_size e.g. <vecstore>.from_documents()...

```
embeddings = OpenAIEmbeddings(chunk_size=1)
```

For the deployment name, it should work with names != `text-embedding-ada-002`:

```
embeddings = OpenAIEmbeddings(engine=<your deployment name>)
```

**Comment by aajn88** [comment]
@floleuerer wait, there's no `AzureOpenAIEmbeddings`, is there? Were you referring to `AzureOpenAI` instead?

**Comment by floleuerer** [comment]
Ah sorry my bad! it' s `OpenAIEmbeddings` of course.

**Comment by aajn88** [comment]
Thanks for confirming. Got excited to think they had a version for Azure! Although it doesn't make a big difference as it's just a config matter.

I just got to my laptop and tried. It fails with the following message:

```
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAIEmbeddings
chunk_size
  extra fields not permitted (type=value_error.extra)
```

Maybe I have the wrong version? I forked version 0.0.100 - could you confirm yours?

**Comment by floleuerer** [comment]
The fix should be in 0.0.106.

**Comment by aajn88** [comment]
Gotcha! I'll try to fork the new version this week.

**Comment by deb007** [comment]
Is this issue fixed? Am on 0.0.107 version, but still getting below error with trying to use OpenAIEmbeddings with the azure openai service. Tried both FAISS as well as Pinecone vector stores. from_documents() fails with 
`openai.error.InvalidRequestError: Too many inputs for model None. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions`

**Comment by aajn88** [comment]
> I ran into the same issue with the chunk_size and Embeddings in Azure OpenAI Services and provided a fix. The easiest way is to initialize your OpenAIEmbeddings with chunk_size=1 - it works in other helper functions too when you can't pass the chunk_size e.g. .from_documents()...
> 
> ```
> embeddings = OpenAIEmbeddings(chunk_size=1)
> ```
> 
> For the deployment name, it should work with names != `text-embedding-ada-002`:
> 
> ```
> embeddings = OpenAIEmbeddings(engine=<your deployment name>)
> ```

@deb007 did you try @floleuerer solution?

**Comment by deb007** [comment]
> > I ran into the same issue with the chunk_size and Embeddings in Azure OpenAI Services and provided a fix. The easiest way is to initialize your OpenAIEmbeddings with chunk_size=1 - it works in other helper functions too when you can't pass the chunk_size e.g. .from_documents()...
> > ```
> > embeddings = OpenAIEmbeddings(chunk_size=1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For the deployment name, it should work with names != `text-embedding-ada-002`:
> > ```
> > embeddings = OpenAIEmbeddings(engine=<your deployment name>)
> > ```
> 
> @deb007 did you try @floleuerer solution?

Yes, I tried `OpenAIEmbeddings(document_model_name="<deployment_name>", chunk_size=1)` - it gives error -
`openai.error.InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.`

`OpenAIEmbeddings(document_model_name="<deployment_name>")` gives error - 
`openai.error.InvalidRequestError: Too many inputs for model None. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.`

`OpenAIEmbeddings(engine="<deployment_name>")` gives below error:
`extra fields not permitted (type=value_error.extra)`

**Comment by aajn88** [comment]
> Actually, by reading the error again, it seems like it's not related to the name of the model and azure just throttling.
> 
> So, in order to configure langchain embeddings properly, I have to replace [this part](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/faiss.py#L250) with my desired chunk_size:
> 
> `embeddings = embedding.embed_documents(texts, 1)`
> 
> Of course, ideally this should be sent by parameter

@deb007 this 👆 worked for me.

**Comment by tomasfernandez1212** [comment]
> embeddings = OpenAIEmbeddings(chunk_size=1)

This also worked for me. Thanks! 

However, what are the implications of setting chunk size to 1?

**Comment by Huyueeer** [comment]
Unfortunately, I have tasted all the above methods and they have not worked, including deployment_name is set to text-davinci-003... Or change the version. I'm confused about openai.api_base and openai.api_type doesn't work. When I comment out the code, I find that there is no difference, and I still report an error as follows:
```shell
openai.error.InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
```

**Comment by aajn88** [comment]
> > embeddings = OpenAIEmbeddings(chunk_size=1)
> 
> This also worked for me. Thanks!
> 
> However, what are the implications of setting chunk size to 1?

I think latency. If I’m not mistaken, you can add multiple texts in one call. I remember reading this somewhere but I couldn’t find it in their docs anymore. However, the error seems align with what I’m saying.

**Comment by csiebler** [comment]
I'm on langchain-0.0.117 and as long as I use `OpenAIEmbeddings()` without any parameters, it works smoothly with Azure OpenAI Service, but requires the model deployment to be named `text-embedding-ada-002`.

**Comment by csiebler** [comment]
> @floleuerer @aajn88
> 
> Setting the `chunk_size `explicity while initializing the `OpenAIEmbeddings()` embeds worked for me. Setting the deployment name explicitly did not help to overcome the max_input error.
> 
> `langchain v=0.0.117` (latest)

Agreed, I was not able to get it to work with setting the model name manually.

**Comment by germanpinzon807** [comment]
I'm on langchain=0.0.119 but `OpenAIEmbeddings()` throws an AuthenticationError: Incorrect API key provided... it seems that it tries to authenticate through the OpenAI API instead of the AzureOpenAI service, even when I configured the OPENAI_API_TYPE and OPENAI_API_BASE previously. Does anyone have the same problem?... tried with version 0.0.117 but the problem persists

**Comment by Granine** [comment]
A straight forward yet messy solution seems to be updating 
`validate_enviroment` validator function in `langchain/embeddings/openai.py` by adding a check-and-fix. As this is where openai seem to be first provoked.

**Comment by emigre459** [comment]
I'm suffering from these same issues, although my error message is a bit different (likely since I'm using LangChain v0.0.123:

```python
2023-03-25 19:47:29.827 INFO    openai: error_code=429 error_message='Requests to the Embeddings_Create Operation under Azure OpenAI API version 2022-12-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 5 seconds. Please contact Azure support service if you would like to further increase the default rate limit.' error_param=None error_type=None message='OpenAI API error received' stream_error=False
2023-03-25 19:47:29.831 WARNING langchain.embeddings.openai: Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Requests to the Embeddings_Create Operation under Azure OpenAI API version 2022-12-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 5 seconds. Please contact Azure support service if you would like to further increase the default rate limit..
```

It seems to me like the wait time between retries (which have clearly been handled in multiple places in LangChain) may not be the issues so much as the number of async workers sent to Azure in the space of a minute ([since the limit is something like 300 per minute for embeddings](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quotas-limits)). Does anyone know where in the LangChain code the number of max async workers is defined such that we could throttle it down to avoid this error perhaps?

**Comment by Granine** [comment]
> I'm suffering from these same issues, although my error message is a bit different (likely since I'm using LangChain v0.0.123:
> 
> ```python
> 2023-03-25 19:47:29.827 INFO    openai: error_code=429 error_message='Requests to the Embeddings_Create Operation under Azure OpenAI API version 2022-12-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 5 seconds. Please contact Azure support service if you would like to further increase the default rate limit.' error_param=None error_type=None message='OpenAI API error received' stream_error=False
> 2023-03-25 19:47:29.831 WARNING langchain.embeddings.openai: Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: Requests to the Embeddings_Create Operation under Azure OpenAI API version 2022-12-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 5 seconds. Please contact Azure support service if you would like to further increase the default rate limit..
> ```
> 
> It seems to me like the wait time between retries (which have clearly been handled in multiple places in LangChain) may not be the issues so much as the number of async workers sent to Azure in the space of a minute ([since the limit is something like 300 per minute for embeddings](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quotas-limits)). Does anyone know where in the LangChain code the number of max async workers is defined such that we could throttle it down to avoid this error perhaps?

Don't really think this is the same issue, Maybe open a new issue page? I did encounter the same problem tho. My dumb solution is to add a sleep inside the langchain library source code (I do not require high performance). I did not find a usage or performance limiter available to use.

**Comment by emigre459** [comment]
Apologies, I copied the wrong error (this is a related one, but caused when you try to use embeddings in a vector store using `llama-index`). My actual LangChain-only error is `Too many inputs for model None. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False`

@Granine  where did you put the sleep call (at the top of the [openai.py module](https://github.com/hwchase17/langchain/blob/master/langchain/embeddings/openai.py) perhaps; or maybe in [the embedding loop](https://github.com/hwchase17/langchain/blob/b83e8265102514d1722b2fb1aad29763c5cad62a/langchain/embeddings/openai.py#L253))? I'm (currently) fine with something like that, but it seems like that just repeats the retry logic doesn't it? But if it works for you, I'm willing to give it a whirl!

**Comment by germanpinzon807** [comment]
> > I'm on langchain=0.0.119 but `OpenAIEmbeddings()` throws an AuthenticationError: Incorrect API key provided... it seems that it tries to authenticate through the OpenAI API instead of the AzureOpenAI service, even when I configured the OPENAI_API_TYPE and OPENAI_API_BASE previously. Does anyone have the same problem?... tried with version 0.0.117 but the problem persists
> 
> For some reason, the suggested implementation on the documentation (by setting environmental variables) does not work. However, a workaround is before `openAIEmbedding` is ever called, import `openai` package and set parameters manually eg:
> 
> ```
> import openai
> openai.api_base = "www.x.com/" 
> openai.api_type = 'azure'
> openai.api_version = "2022-12-01" 
> # optionally, set key
> ```
> 
> then
> 
> ```
> OpenAIEmbeddings(document_model_name="MODEL_NAME", chunk_size=1)
> ```



> > I'm on langchain=0.0.119 but `OpenAIEmbeddings()` throws an AuthenticationError: Incorrect API key provided... it seems that it tries to authenticate through the OpenAI API instead of the AzureOpenAI service, even when I configured the OPENAI_API_TYPE and OPENAI_API_BASE previously. Does anyone have the same problem?... tried with version 0.0.117 but the problem persists
> 
> For some reason, the suggested implementation on the documentation (by setting environmental variables) does not work. However, a workaround is before `openAIEmbedding` is ever called, import `openai` package and set parameters manually eg:
> 
> ```
> import openai
> openai.api_base = "www.x.com/" 
> openai.api_type = 'azure'
> openai.api_version = "2022-12-01" 
> # optionally, set key
> ```
> 
> then
> 
> ```
> OpenAIEmbeddings(document_model_name="MODEL_NAME", chunk_size=1)
> ```

it worked! thank you! @Granine

**Comment by LewisLebentz** [comment]
@EAYoshi I've been trying to play around with the code here: https://github.com/alphasecio/llama-index/blob/main/index.py to get it working on Azure, changed it to use `from langchain.llms import AzureOpenAI` but not having any luck. Getting the same error as you, tried setting chunk size to 1 but all I get is this:

`error_code=DeploymentNotFound error_message='The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.' error_param=None error_type=None message='OpenAI API error received' stream_error=False`

Do you think this is related?

**Comment by EAYoshi** [comment]
Likely, yes.

First, make sure these environment variables are set correctly in the context of your code
```
OPENAI_API_BASE=<azure OpenAI base URL without deployment>
OPENAI_API_KEY=<azure key>
OPENAI_API_TYPE=azure
```

Then, make sure you have an Azure deployment named text-davinci-003 that is set to use the `text-davinci-003` model

Finally, try changing [this](https://github.com/alphasecio/llama-index/blob/main/index.py#L10) line to be 
```
llm_predictor = LLMPredictor(llm=OpenAI(model_kwargs={'engine':'text-davinci-003'}))
```
then play around with the temperature once it works, I'm not sure where that parameter should go

**Comment by licesun** [comment]
This issue is actually a bug in Azure, as the address to access is end_point/deployments/[Model deployment name]/embedding. The system failed to retrieve the name of the model deployment and instead retrieved the model name, which is text-embedding-ada-002. If your model deployment name is different from the model name, it will result in a "not found" error. Therefore, the solution is to rename your model deployment to text-embedding-ada-002. Happy Coding.

**Comment by jazzpujols34** [comment]
I've been stuck all day and this thread solved my problems. Thank everyone who contributed to this thread!

**Comment by waundme** [comment]
I'm also on Azure, Embeddings work in code like this:
`embeddings = OpenAIEmbeddings(model="embed", chunk_size=1)
 vectorstore = FAISS.from_documents(pages, embeddings)`

But it doen't work when I'm trying to use the SemanticSimilarityExampleSelector: 

`# SemanticSimilarityExampleSelector will select examples that are similar to your input by semantic meaning
example_selector = SemanticSimilarityExampleSelector.from_examples(
    # This is the list of examples available to select from.
    examples, 
    
    # This is the embedding class used to produce embeddings which are used to measure semantic similarity.
    OpenAIEmbeddings(model="embed", chunk_size=1), 
    
    # This is the VectorStore class that is used to store the embeddings and do a similarity search over.
    FAISS, 
    
    # This is the number of examples to produce.
    k=2
)`

I'm getting the error:
`KeyError: 'Could not automatically map embed to a tokeniser. Please use `tiktok.get_encoding` to explicitly get the tokeniser you expect.'`

Am I doing something wrong, is this a bug in langchain or on Azure?

(langchain version 0.0.135)

**Comment by Joldnine** [comment]
Hi, in Azure,  is there any workaround to have a bigger chunk_size instead of chunk_size=1? 

The problem with chunk_size=1 in Azure is performance. In native OpenAI API, we can set chunk_size=1000, which is much more faster than chunk_size=1 in Azure for embedding.

**Comment by sweetlilmre** [comment]
I'm not sure if this helps, but I was porting AutoGPT to work on Azure. With a recent update it broke with a similar embedding issue. The devs were using `openai.Embedding.create(input=[text], model="text-embedding-ada-002")["data"][0]["embedding"]` to create an embedding. The working Azure flavour for me was to use: `openai.Embedding.create(input=[text], engine=cfg.openai_embedding_deployment_id)["data"][0]["embedding"]` where the deployment id for the embedding model is specified in `.env`. Note the change from `model` to `engine` and `engine` specifying the deployment id.

**Comment by EAYoshi** [comment]
> Hi, in Azure, is there any workaround to have a bigger chunk_size instead of chunk_size=1?
> 
> The problem with chunk_size=1 in Azure is performance. In native OpenAI API, we can set chunk_size=1000 for doing embedding., which is much more faster than the one with chunk_size=1 in Azure

As of time of writing, Azure only supports one chunk. The message you get back from the API says it's temporary and they're working on it, so I'm pretty sure it's server side and there's nothing to be done about it. Talk to your Azure TAM if you have one.

**Comment by tunayokumus** [comment]
> 

it seems the issue with model vs. deployment separation was reintroduced with the tiktoken checks.
I opened a PR to finally add proper support for Azure OpenAI embedding models.
https://github.com/hwchase17/langchain/pull/3076

**Comment by dishujindal** [comment]
> When using the AzureOpenAI LLM the OpenAIEmbeddings are not working. After reviewing source, I believe this is because the class does not accept any parameters other than an api_key. A "Model deployment name" parameter would be needed, since the model name alone is not enough to identify the engine. I did, however, find a workaround. If you name your deployment exactly "text-embedding-ada-002" then OpenAIEmbeddings will work.
> 
> edit: my workaround is working on version .088, but not the current version.

could you explain how did you resolve passing an open API key for Azure open API key problem? Like you mentioned azure  open api key is api_key as when using with llm it expects it should be openai_api_key

**Comment by HakjunMIN** [comment]
Resolved just using `embeddings = OpenAIEmbeddings(model="text-embedding-ada-002", chunk_size=1)` for my case.

**Comment by sai-kiran-adusumilli** [comment]
#I have installed langchain v0.0.146 but still i am getting error 
from langchain.embeddings.openai import OpenAIEmbeddings
embeddings = OpenAIEmbeddings(deployment ='embeddingModel',model="text-embedding-ada-002",
                              openai_api_key=" ",chunk_size=1)
text = "This is a test query."
query_result = embeddings.embed_query(text)
ValidationError: 1 validation error for OpenAIEmbeddings
deployment
  extra fields not permitted (type=value_error.extra)

**Comment by sai-kiran-adusumilli** [comment]
> You can specify the Azure OpenAI Service deployment name since v0.0.146 OpenAIEmbeddings(deployment="your-azure-deployment-name", model="text-embedding-ada-002", chunk_size=1)

**Comment by sai-kiran-adusumilli** [comment]
> You can specify the Azure OpenAI Service deployment name since v0.0.146 OpenAIEmbeddings(deployment="your-azure-deployment-name", model="text-embedding-ada-002", chunk_size=1)

**Comment by sai-kiran-adusumilli** [comment]
![Capture1](https://user-images.githubusercontent.com/127498589/235081134-caf614df-66e3-49c2-908a-641609373a8f.JPG)
 i am using langchain v0.0.146 , but still i am facing error 


# Configure OpenAI API
openai.api_type = "azure"
openai.api_version = "2022-12-01"
openai.api_base = os.getenv('')
openai.api_key = os.getenv("")

deployment_name = "davinci"
deployment_name1 = "embeddingModel"

# Create LLM via Azure OpenAI Service
llm = AzureOpenAI(deployment_name=deployment_name,openai_api_key="")
llm_predictor = LLMPredictor(llm=llm)
embedding_llm = LangchainEmbedding(OpenAIEmbeddings(deployment ='embeddingModel',model="text-embedding-ada-002",
                              openai_api_key="",chunk_size=1))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor,chunk_size_limit=2000,embed_model=embedding_llm)

# Read txt files from data directory
documents = SimpleDirectoryReader(r'C:\Users\skiranadusum\Desktop\Philips\data').load_data()
index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)



# APIConnectionError: Error communicating with OpenAI: Invalid URL 'None/openai/deployments/embeddingModel/embeddings?api-version=2022-12-01': No scheme supplied. Perhaps you meant https://none/openai/deployments/embeddingModel/embeddings?api-version=2022-12-01?

**Comment by JonAtDocuWare** [comment]
well it's clear that a base endpoint for your azure services is not defined.

what do you expect this line of code to do:

[openai.api_base = os.getenv('')](url)

**Comment by JonAtDocuWare** [comment]
@sai-kiran-adusumilli  you also exposed your API key in your first post.  You edited it, but any user can view the edit history.  You need to trash that key now and get a new one... unless you want a huge Azure bill.

**Comment by sai-kiran-adusumilli** [comment]
> @sai-kiran-adusumilli you also exposed your API key in your first post. You edited it, but any user can view the edit history. You need to trash that key now and get a new one... unless you want a huge Azure bill.

if i delete the comment ? can users still see it

**Comment by JonAtDocuWare** [comment]
> if i delete the comment ? can users still see it

well I get email notifications for comments and that is where I first saw you exposed your API key.... deleting the comment here isn't going to delete the email in my inbox.

**Comment by zioproto** [comment]
@JonAtDocuWare I proposed #3711 to address this issue.

According to the docs:
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#embeddings

The `POST` request should look like:

```
POST https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/embeddings?api-version={api-version}
```
However my current PR is not working because it generates

`https://xxxxxx.openai.azure.com/openai/engines/text-embedding-ada-002/embeddings`

I am currently debugging this problem.

**Comment by simhallq** [comment]
Explicitly passing texts to embed as "input" resovled this for me. On openai==0.27.6

`openai.Embedding.create(input=texts, model="text-embedding-ada-002")`

**Comment by fms-santos** [comment]
I was having the same issue but using `OpenAIEmbeddings(model="text-embedding-ada-002", chunk_size=1)` fixed the it.
Now I'm getting the `INFO:openai:error_code=429 error_message='Requests to the Embeddings_Create Operation under Azure OpenAI API version 2022-12-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 1 second. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.' error_param=None error_type=None message='OpenAI API error received' stream_error=False
` error

**Comment by That1Panda** [comment]
> openai.Embedding.create(input=texts, model="text-embedding-ada-002")

This worked for me On openai==0.27.1

**Comment by fms-santos** [comment]
Thanks! I'm in west europe. I'll try that

**Comment by kingname** [comment]
The prefect way to solve this problem is:

```python
from langchain.document_loaders import TextLoader
from langchain.indexes import VectorstoreIndexCreator
from langchain.embeddings import OpenAIEmbeddings

loader = TextLoader('text.txt')
embeddings = OpenAIEmbeddings(model='text-embedding-ada-002',
                              deployment='your deployment name',
                              openai_api_base='https://your-resource-name.openai.azure.com',
                              openai_api_type='azure',
                              openai_api_key='your key',
                              chunk_size=1)
index = VectorstoreIndexCreator(embedding=embeddings).from_loaders([loader])
```

**Comment by JonAtDocuWare** [comment]
has been resolved, closing this issue.

**Comment by parth-patel2023** [comment]
I am getting error 

Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..

I am using this code 


embeddings = OpenAIEmbeddings(
    openai_api_key=OPENAI_API_KEY)
    
 langchain==0.0.113

**Comment by DSgUY** [comment]
you only need this:
```

embeddings: OpenAIEmbeddings = OpenAIEmbeddings(
    openai_api_base= f"https://{AZURE_OPENAI_SERVICE}.openai.azure.com",
    openai_api_type='azure',
    deployment='text-embedding-ada-002',
    openai_api_key=AZURE_OPENAI_API_KEY,
    chunk_size=1,
)

query_result = embeddings.embed_query("is this issue solve?")
```

My deployment name and model name are the same: **_text-embedding-ada-002_**

**Comment by pietz** [comment]
I had a few issues yesterday without knowing about this thread. Let me share some updates and additional information that I haven't see here:

- The maximum `chunk_size` is still `1` which makes the functionality almost useless. Using Azure OpenAI to embed 1000 chunks takes 170 seconds while OpenAI with chunk size 1000 takes 12 seconds. That's `14x` slower.
- It's not a langchain problem but an Azure limitation. Same behavior with the OpenAI library.
- Naming your deployment `text-embedding-ada-002` results in not having to set the deployment parameter in `OpenAIEmbeddings` because that's the default value. You can name your deployment anything you want.
- Using environment variables works just fine if 1) you stick to the official naming convention (like the parameters but in caps) 2) best don't set the `openai_api_version` (default works for now) 3) No trailing slash  `/` in the `openai_api_base` URL.
- The code sample from @DSgUY works if your deployment has the same name as the model

`langchain 0.0.235`
`openai 0.27.8`

**Comment by DSgUY** [comment]
@pietz I'm also having this problem:[https://github.com/hwchase17/langchain/issues/7841]( https://github.com/hwchase17/langchain/issues/7841)

**Comment by babsy3** [comment]
I'm getting the same error, and none of the workarounds above work for me! Were you able to resolve your error?

**Comment by JordanRex** [comment]
classic microsoft. with 16 its bit more bearable but still infeasible for larger embeddings. probably best to have local bert embeddings even than to use the azure openai for now until they can increase it around 100 at the least

**Comment by gclem** [comment]
Found a workarround : 

```
const embeddings = new OpenAIEmbeddings({
  batchSize : 16
});
```

batchSize since the same of chunksize, for langchainJS

**Comment by floleuerer** [comment]
> hi! just wanna check. chunk_size is currently 16 at this date? 15-05-2024?
> 
> thanks

The max batch size is 2048 now
