### ISSUE TITLE
Missing support for SQLAlchemy v2

### ISSUE THREAD

**Issue by tunayokumus** [hwchase17/langchain#1578]
SQLAlchemy v2 is out and has important new features.
I suggest relaxing the dependency requirement from `SQLAlchemy = "^1"` to `SQLAlchemy = ">=1.0, <3.0"`

**Comment by hwchase17** [comment]
we will look into this. there are some things that we'd need to update so i dont think its as simple as that

**Comment by jzluo** [comment]
Please see #1272 for more details
