### ISSUE TITLE
Token Lengths

### ISSUE THREAD

**Issue by slavakurilyak** [hwchase17/langchain#1580]
There are [rumors](https://twitter.com/transitive_bs/status/1628118163874516992) that GPT-4 (code name DV?) will feature a whopping 32k max context length. It's time to build abstractions for new token lengths.

![](https://pbs.twimg.com/media/Fpg81tNaIAALkiY?format=jpg&name=large)

**Comment by jtiagodev** [comment]
+1

**Comment by slavakurilyak** [comment]
Implementations here:

- [https://python.langchain.com/en/latest/search.html?q=tokens_limit](https://python.langchain.com/en/latest/search.html?q=tokens_limit)
- [https://github.com/search?q=repo%3Ahwchase17%2Flangchain%20tokens_limit&type=code](https://github.com/search?q=repo%3Ahwchase17%2Flangchain%20tokens_limit&type=code)
- [https://github.com/search?q=repo%3Ahwchase17%2Flangchainjs+maxTokens&type=code](https://github.com/search?q=repo%3Ahwchase17%2Flangchainjs+maxTokens&type=code)
