### ISSUE TITLE
ImportError: cannot import name 'AIMessage' from 'langchain.schema'

### ISSUE THREAD

**Issue by sopmacvan** [hwchase17/langchain#1595]
I've been trying things out from the [docs](https://langchain.readthedocs.io/en/latest/modules/memory/getting_started.html) and encountered this error when trying to import the following:
`from langchain.memory import ChatMessageHistory`
ImportError: cannot import name 'AIMessage' from 'langchain.schema'

`from langchain.memory import ConversationBufferMemory`
ImportError: cannot import name 'AIMessage' from 'langchain.schema'

**Comment by nglelinh** [comment]
I got the same issue
environment: Window

**Comment by MattKovtun** [comment]
Same issues
Was trying to follow this [example](https://github.com/jerryjliu/llama_index/blob/main/examples/vector_indices/SimpleIndexDemo-ChatGPT.ipynb)
`from langchain.chat_models import ChatOpenAI` crashes
langchain-0.0.109
Python 3.8.10
Ubuntu 20.04

**Comment by Tushar11Raj** [comment]
Update langchain and llama_index(if u r using) packages to latest versions. use python 3.10.10.

**Comment by sopmacvan** [comment]
It works now. thank you!

llama-index 0.4.25, 
langchain 0.0.107,
python 3.10.9
