### ISSUE TITLE
Cannot import `PromptTemplate`

### ISSUE THREAD

**Issue by teoh** [hwchase17/langchain#160]
Hello,

When running the "Map Reduce" [demo](https://langchain.readthedocs.io/en/latest/examples/demos/map%20reduce.html), I see the error below:
```
ImportError                               Traceback (most recent call last)
Cell In [3], line 1
----> 1 from langchain import OpenAI, PromptTemplate, LLMChain
      2 from langchain.text_splitter import CharacterTextSplitter
      3 from langchain.chains.mapreduce import MapReduceChain

ImportError: cannot import name 'PromptTemplate' from 'langchain' (/Users/mteoh/projects/langchain_sandbox/.env/lib/python3.9/site-packages/langchain/__init__.py)
```

I see it defined here: https://github.com/hwchase17/langchain/blob/c02eb199b6587aeeb50fbb083693572bd2f030cc/langchain/prompts/prompt.py#L13

And mentioned here:
https://github.com/hwchase17/langchain/blob/c02eb199b6587aeeb50fbb083693572bd2f030cc/langchain/__init__.py#L35

However, when grepping in the library directory, I do not find it:
```
:~/projects/langchain_sandbox/.env/lib/python3.9/site-packages/langchain $ grep -r PromptTemplate .
```

Relevant versions of my packages:
```
$ pip freeze | grep "langchain\|openai"
langchain==0.0.16
openai==0.25.0
```

Any advice? Thanks! Excited about this work.

**Comment by hwchase17** [comment]
sorry, docs got a bit ahead of the release. am cutting a new relese now, but you can also just use Prompt instead of PromptTemplate for the time being. sorry again!

**Comment by hwchase17** [comment]
should be fixed with newly released version 0.0.17!

**Comment by teoh** [comment]
thanks! for my understanding only: is `PromptTemplate` a recently-made abstraction that made it to the latest docs before it made its way to latest release?

**Comment by hwchase17** [comment]
yes exactly. i dont have a super great build pipeline for the docs set up so it just builds off of latest. i try to update and tehn cut with minimal time in between, but in this case i had some :/

**Comment by teoh** [comment]
Got it, thanks!
