### ISSUE TITLE
[Feature suggestion] Multi-modal Langchain

### ISSUE THREAD

**Issue by hav4ik** [hwchase17/langchain#1677]
With the rise of multi-modal models (GPT-4 announced today), and how popular LangChain is among the research community, we should be ready for new modalities. Ideally, the user should be able to do something like:

```python
vllm = OpenAI(model_name='gpt-4', max_tokens=through_the_roof)
prompt = PromptTemplate(
        input_variables=["user_text", "image", "prompt"],
        template="{prompt} {image} Question: {user_text}")
vl_chain = VLLMChain(vllm=vllm, prompt=prompt, verbose=True)

vl_chain.predict(prompt=prompt, image=pil_image, user_text=user_text)
```

If no one is working on this currently, I'm willing to try to add this functionality in my spare time.

The uncertain part is, we don't know if GPT-4 is going to be like Flamingo (allowing you to put multiple images in a specific position and order the document) or like BLIP-2 (cross-attention between image and text, but in no particular order). My educated guess is the former.

**Comment by ansh** [comment]
@hav4ik How do I use GPT-4 with LangChain?
