### ISSUE TITLE
on_agent_action was never awaited

### ISSUE THREAD

**Issue by ChrisB1123** [hwchase17/langchain#1708]
I've just implemented the AsyncCallbackManager and handler, and everything works fine except for the fact I receive this warning

> /usr/local/lib/python3.10/site-packages/langchain/agents/agent.py:456: RuntimeWarning: coroutine 'AsyncCallbackManager.on_agent_action' was never awaited
> self.callback_manager.on_agent_action(
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Which seems to prevent the logging I'm trying to implement with the handler.

Relevant code snippet:
https://github.com/hwchase17/langchain/blob/3c2468452284ee37b8a88a20b864255fa4385b65/langchain/agents/agent.py#L456-L458

Looking at the codebase, it looks like the other callback manager calls are awaited, but not sure if I'm using the wrong executor?
https://github.com/hwchase17/langchain/blob/3c2468452284ee37b8a88a20b864255fa4385b65/langchain/agents/agent.py#L384-L387

**Comment by AgeOfMarcus** [comment]
I'm also encountering this issue. Using the AsyncCallbackManager on a custom class based off AsyncCallbackHandler. Same issue even if I base the class off BaseCallbackHandler

**Comment by ChrisB1123** [comment]
Do you still get the warning saying on_agent_action was never awaited?

My main file looks like this:
```
my_callback_hander = MyCallBackHandler()
my_callback_manager = AsyncCallbackManager([bubble_callback_hander])

# build and run agent executor
agent_executor = AgentExecutor.from_agent_and_tools(agent=agent, tools=tools, verbose=True, max_iterations=5, callback_manager=my_callback_manager)
```

My handler is defined like this:
```
class MyCallBackHandler(AsyncCallbackHandler):
    def __init__(self, bubble_client) -> None:
        ....
    ....
    async def on_agent_action(self, action: AgentAction, **kwargs: Any) -> None:
        print(action.log)
```

It sounds like you may not be printing in the correct on_... function?

**Comment by AgeOfMarcus** [comment]
I am doing everything the same, except using `initialize_agent` from
`langchain.agents`. Should I use an agent executor instead?

**Comment by ChrisB1123** [comment]
Yea that would be the only thing I could suggest - I'm not familiar enough with the rest of the codebase to know the difference between the 2.
