### ISSUE TITLE
bug(QA with Sources): source parsing is not reliable

### ISSUE THREAD

**Issue by ajndkr** [hwchase17/langchain#1712]
I was going through [Vectorstore Agent](https://langchain.readthedocs.io/en/latest/modules/agents/agent_toolkits/vectorstore.html?highlight=vectorstore%20agent#vectorstore-agent) tutorial and I am facing issues with the `VectorStoreQAWithSourcesTool`.

Looking closely at the code https://github.com/hwchase17/langchain/blob/3c2468452284ee37b8a88a20b864255fa4385b65/langchain/chains/qa_with_sources/base.py#L119-L120

it appears, the parsing rule might be too strict for extract the list of sources. Often, when the agent is fetching information from the vectorstore, the `VectorStoreQAWithSourcesTool` output is something like `....SOURCES:\n<source1>\n<source2>...` instead of `...SOURCES: <source1>,<source2>...`.

Due to this, the `VectorStoreQAWithSourcesTool` output is broken and the agent response is impacted.

P.S. I used `Chroma` as the vectorstore db and `OpenAI(temperature=0)` as the LLM.

**Comment by walterbm** [comment]
@ajndkr yes, I was able to verify that this was fixed for my use-case in the v0.0.126 release. If it doesn't work as expected for you please let me know!

**Comment by ajndkr** [comment]
thanks! I will close this issue in the meantime.
