### ISSUE TITLE
Two different document loaders for Microsoft Word files

### ISSUE THREAD

**Issue by klein-t** [hwchase17/langchain#1716]
Hello, I've noticed that after the latest commit of @MthwRobinson there are two different modules to load Word documents, could they be unified in a single version? Also there are two notebooks that do almost the same thing.

[docx.py](https://github.com/hwchase17/langchain/blob/3c2468452284ee37b8a88a20b864255fa4385b65/langchain/document_loaders/docx.py) and [word_document.py](https://github.com/hwchase17/langchain/blob/3c2468452284ee37b8a88a20b864255fa4385b65/langchain/document_loaders/word_document.py)

[microsoft_word.ipynb](https://github.com/hwchase17/langchain/blob/3c2468452284ee37b8a88a20b864255fa4385b65/docs/modules/document_loaders/examples/microsoft_word.ipynb) and [word_document.ipynb](https://github.com/hwchase17/langchain/blob/3c2468452284ee37b8a88a20b864255fa4385b65/docs/modules/document_loaders/examples/word_document.ipynb)

Or am I just missing something?

**Comment by Janldeboer** [comment]
I agree!
There doesn't seem to be much to unify:
`docx` is only working with docx while the `word` version also supports `doc`, so `docx` is obsolete.

**Comment by nithinreddyyyyyy** [comment]
I'm unable to load all the word files present in the folder. Below is the code

txt_loader = UnstructuredWordDocumentLoader(folder_path, glob="./*.docx")  # Select TXT files
documents += txt_loader.load()

but below code is working only for 1 file.
```
txt_loader = UnstructuredWordDocumentLoader("Q&A with PDF & Txt\Documents\Data Scientist.docx", mode="elements") 
documents += txt_loader.load()
```

is there any method to overcome this?

**Comment by MthwRobinson** [comment]
@nithinreddyyyyyy - That seems like it should work. Could you post in here your `unstructured` version and the error message you're getting? You can also pass the `UnstructuredWordDocumentLoader` explicitly to the `DirectoryLoader` like this:

```python
loader = DirectoryLoader(folder_path, glob="./*.docx", loader_cls=UnstructuredWordDocumentLoader)
```
