### ISSUE TITLE
example sql_database toolkit agent notebook throws "KeyError" in create_sql_agent

### ISSUE THREAD

**Issue by ndaugreal** [hwchase17/langchain#1721]
the example notebook at https://github.com/hwchase17/langchain/blob/master/docs/modules/agents/agent_toolkits/sql_database.ipynb is broken at the following line.

``` python
agent_executor = create_sql_agent(
    llm=OpenAI(temperature=0),
    toolkit=toolkit,
    verbose=True
)
```

It produces a `KeyError: 'tools'`

This error is related to another error`TypeError("cannot pickle 'module' object")`. It appears that during the Pydantic validation process for any of the SQLDataBaseTools (e.g., QuerySQLDataBaseTool), there is an attempt to deep copy the `db` attribute, which is a SQLDatabase object. The method used is `rv = reductor(4)`. However, that is followed up with a call to `_reconstruct(x, memo, *rv)`. That call will throw an error for creating the new SQLDataBase object because the required `engine` attribute is missing. 

A workaround is to define a `__deepcopy__()` method in SQLDatabase. If the deep copy is not necessary, the method may simply return `self` or do a shallow copy. But need to make sure what is the right approach here.

**Comment by iyjian** [comment]
same error

**Comment by srishino1016** [comment]
@ndaugreal  Which version of Langchain are you using?

**Comment by ndaugreal** [comment]
It was the latest version as of the reporting. The issue appears to have been fixed now.

**Comment by srishino1016** [comment]
@ndaugreal ok awesome, I also got this issue but got resolved by changing the version.
