### ISSUE TITLE
parrallize the map/reduce chain

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchain#176]
make the calls in the "map" part concurrently

**Comment by vshulman** [comment]
might be helpful to also make the intermediate outputs of the map step accessible to the caller

**Comment by devonbrackbill** [comment]
I understand the map/reduce chain to currently do 1 step of map and then "stuff" all of the results into 1 final query. I'm running into token limits on the final "stuff". Is there an obvious way to call map on the intermediate summaries until the input to the final "stuff" is below the token threshold?

**Comment by hwchase17** [comment]
sorry @devonbrackbill i did not see this earlier! i think this should be addressed now - could you confirm?

**Comment by devonbrackbill** [comment]
Yes, this is addressed. Thank you
