### ISSUE TITLE
Update poetry lock to allow SQLAlchemy v2

### ISSUE THREAD

**Issue by baron** [hwchase17/langchain#1766]
It seems that #1578 adds support for SQLAlchemy v2 but the [poetry lock file](https://github.com/hwchase17/langchain/blob/8685d53adcdd0310e76349ecb4e2b87f980c4673/poetry.lock#L6211) is still at 1.4.46.

**Comment by baron** [comment]
It seems that jupyter-cache is another blocking dependency:

jupyter-cache
https://github.com/hwchase17/langchain/blob/master/poetry.lock#L2526
https://github.com/executablebooks/jupyter-cache/issues/92
https://github.com/executablebooks/jupyter-cache/pull/93

**Comment by jzluo** [comment]
`jupyter_cache` is a dependency for myst-nb which is used in creating the docs. [I do have a PR open with `jupyter-cache` to allow SQLAlchemy 2.](https://github.com/executablebooks/jupyter-cache/pull/93)

**Comment by baron** [comment]
Thanks for the clarification and your efforts. Added some reactions and a "+1".

**Comment by winstxnhdw** [comment]
`jupyter-cache` hasn't been maintained for more than 9 months, should we start looking for alternatives?

**Comment by elonzh** [comment]
Should we add `SALAlchemy`  as an optional dependency?

**Comment by ryugonomura** [comment]
> Should we add `SALAlchemy` as an optional dependency?

Please add SALAlchemy 2.0.

**Comment by KennyRich** [comment]
@hwchase17 Please any update on this? Can I open a PR to fix this?

**Comment by vnktsh** [comment]
@jzluo Can we mark `myst-nb` as optional dependency? SQLAlchemy is such an important library for many data projects and being blocked because of rarely used feature is big pain.
