### ISSUE TITLE
chain.run threw 403 error

### ISSUE THREAD

**Issue by mzhadigerov** [hwchase17/langchain#1795]
I'm using the pipeline for Q&A pipeline on non-english language:

```
pinecone.init(
    api_key=PINECONE_API_KEY,  # find at app.pinecone.io
    environment=PINECONE_API_ENV  # next to api key in console
)
index_name = "langchain2"
embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)

docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

llm = OpenAI(temperature=0, openai_api_key=OPENAI_API_KEY)
chain = load_qa_chain(llm, chain_type="stuff")

query = "QUESTION"
docs = docsearch.similarity_search(query, include_metadata=True)

res = chain.run(input_documents=docs, question=query)
print(res)
```
It stucks in `res = chain.run(input_documents=docs, question=query)` lane. I'm waiting for ~20 mins already. What's the reason for that and how to investigate?

---------------

**UPD**

After ~30 mins I got 

```
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).
```
What's the reason for that and how can I fix it?

**Comment by dlqqq** [comment]
This looks like an issue with the upstream API and not LangChain itself. LangChain is not responsible for upstream API availability or rate limiting policies.

**Comment by mzhadigerov** [comment]
@dlqqq How can I set a limit for response time? I'm using `signal` library from python. Wondering If there are alternative ways

**Comment by dlqqq** [comment]
@mzhadigerov Unfortunately, a quick glance at the `pinecone.py` source seems to show that there isn't timeout support at the moment for Pinecone. The community is still working to bring timeouts to classes throughout the repo: https://github.com/hwchase17/langchain/pull/1798

**Comment by mzhadigerov** [comment]
sorry @dlqqq ,but what it has to do with pinecone? The problem arises in openai side, not in pinecone side. Please, correct me If I misunderstood you.

**Comment by dlqqq** [comment]
@mzhadigerov Can we close this issue?
