### ISSUE TITLE
Document loader for Azure Blob storage 

### ISSUE THREAD

**Issue by amitmukh** [hwchase17/langchain#1805]
Lots of customers is asking if langchain have a document loader like AWS S3 or GCS for Azure Blob Storage as well. As you know Microsoft is a big partner for OpenAI , so there is a real need to have native document loader for Azure Blob storage as well. We will be very happy to see this feature ASAP.

**Comment by eavanvalkenburg** [comment]
PR created!

**Comment by eavanvalkenburg** [comment]
And merged! Just connection strings though
