### ISSUE TITLE
Add support for OpenAI Completion's Suffix Parameter

### ISSUE THREAD

**Issue by EandrewJones** [hwchase17/langchain#181]
Hi, is there any chance you could add support for the suffix parameter to the OpenAI class/call?

[https://beta.openai.com/docs/api-reference/completions/create](https://beta.openai.com/docs/api-reference/completions/create)

I could land this if you don't have the time, but it should be simple enough that you could land it faster than I could fork the repo and make a PR.

**Comment by hwchase17** [comment]
Yup - will get this in by fridays release

**Comment by EandrewJones** [comment]
Thank you - very much appreciated.

Love the library, by the way.

Best

Evan Jones
Website: www.ea-jones.com

**Comment by hwchase17** [comment]
@EandrewJones i'm thinking of doing something like this: https://github.com/hwchase17/langchain/pull/182

namely, expose something where you can be like OpenAI(model_kwargs={"create_completion": "foo"})

its less explicit than adding it directly, BUT it does let you specify arbitrary things (there are other parameters from OpenAI i haven't added yet. thoughts?

another option would be to do some parsing so you can still do OpenAI(create_completion="foo") but it just gets stored the same way (in model_kwargs) under the hood. now tht im talking outloud im guessing the second might be preferble...?

what are your thoughts

**Comment by EandrewJones** [comment]
Either works but the second would be more consistent with the way the rest
of the parameters are configured and would allow everything the be unpacked
OpenAI(**model_kwargs) with a single dict. This is especially nice if
you're using this behind an API because then you can let people optionally
specify as many or as few of the model params in the call as they want and
they only need pass a single model_kwargs JSON argument to do so or nothing
at all and then you invoke defaults.

Best

Evan Jones
Website: www.ea-jones.com

**Comment by EandrewJones** [comment]
Thanks Harrison!

Best

Evan Jones
Website: www.ea-jones.com
