### ISSUE TITLE
LLMMathChain to allow ChatOpenAI as an llm

### ISSUE THREAD

**Issue by cnndabbler** [hwchase17/langchain#1834]
1. Cannot initialize match chain with ChatOpenAI LLM

llm_math = LLMMathChain(llm=ChatOpenAI(temperature=0)) 

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[33], line 1
----> 1 llm_math = LLMMathChain(llm=ChatOpenAI(temperature=0))

File ~/anaconda3/envs/gpt_index/lib/python3.8/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for LLMMathChain
llm
  Can't instantiate abstract class BaseLLM with abstract methods _agenerate, _generate, _llm_type (type=type_error)

2. Works ok with OpenAI LLM

llm_math = LLMMathChain(llm=OpenAI(temperature=0))

**Comment by lethe3000** [comment]
I met the same problem.
the warning message said: 
You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`

But I cannot use `ChatOpenAI` instance as the `llm` args for `LLMPredictor` if I follow the warning's instructions.
```
from langchain import OpenAI
from langchain.chat_models import ChatOpenAI
from langchain.llms import OpenAIChat
# will report wanrings
llm_math = LLMPredictor(llm=OpenAI(temperature=0))
# will also report warnings
llm_math = LLMPredictor(llm=OpenAIChat(temperature=0))
# will validation error
llm_math = LLMPredictor(llm=ChatOpenAI(temperature=0))
```

**Comment by apelliciari** [comment]
same error with SQLDatabaseChain + ChatOpenAI
```
    db = SQLDatabase.from_uri("sqlite://...")
    llm = ChatOpenAI(temperature=0)
    db_chain = SQLDatabaseChain(llm=llm, database=db, verbose=True)
```

**Comment by alanpog** [comment]
> same error with SQLDatabaseChain + ChatOpenAI
> 
> ```
>     db = SQLDatabase.from_uri("sqlite://...")
>     llm = ChatOpenAI(temperature=0)
>     db_chain = SQLDatabaseChain(llm=llm, database=db, verbose=True)
> ```

Actually it was fixed for `SQLDatabaseChain` last week in this commit: b1c4480d7cdf0b86d204641fc126188929a46439 .

However, it still requires a `BaseLLM` in `LLMMathChain` as reported by [cnndabbler](https://github.com/cnndabbler) .

**Comment by cnndabbler** [comment]
> @cnndabbler Are you currently working on this? Otherwise, I would take on this issue.
> 
> Apart from changing the typing of `LLMMathChain.llm` to allow for a `BaseChatModel`, I would also suggest changing the default prompt.
> 
> Currently, it lets the language model choose whether to use python code or not, which works with `text-davinci-003`, but leads to an invalid answer with `gpt-3.5-turbo` (something like "Sorry, as a Language Model I cannot...."), when running the example from the docs. I would modify it to ask the model **only** for python code. I cannot imagine any problem that a language model can confidently solve by itself that it cannot solve via python code.

**Comment by MAhmedIrfan** [comment]
> 1. Cannot initialize match chain with ChatOpenAI LLM
> 
> llm_math = LLMMathChain(llm=ChatOpenAI(temperature=0))
> 
> ValidationError Traceback (most recent call last) Cell In[33], line 1 ----> 1 llm_math = LLMMathChain(llm=ChatOpenAI(temperature=0))
> 
> File ~/anaconda3/envs/gpt_index/lib/python3.8/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.**init**()
> 
> ValidationError: 1 validation error for LLMMathChain llm Can't instantiate abstract class BaseLLM with abstract methods _agenerate, _generate, _llm_type (type=type_error)
> 
> 2. Works ok with OpenAI LLM
> 
> llm_math = LLMMathChain(llm=OpenAI(temperature=0))

I am facing this issue with both SQLDatabaseChain + ChatOpenAI and SQLDatabaseChain + ChatOpenAI. What is the way around this?

**Comment by cnndabbler** [comment]
from langchain import LLMMathChain
llm_math = LLMMathChain(llm=ChatOpenAI(temperature=0))

now generates no error :). Thank you for fixing this !

**Comment by stakes** [comment]
i think i fixed it with https://github.com/hwchase17/langchain/pull/3808
