### ISSUE TITLE
Add Program of Thoughts Prompting or Program-Aided Language Model

### ISSUE THREAD

**Issue by Glavin001** [hwchase17/langchain#185]
- [PAL: PROGRAM-AIDED LANGUAGE MODELS](https://arxiv.org/pdf/2211.10435.pdf)
- [Program of Thoughts Prompting: Disentangling Computation from Reasoning for Numerical Reasoning Tasks](https://wenhuchen.github.io/images/Program_of_Thoughts.pdf)

**Comment by amayuelas** [comment]
I could try to implement the Program of Thoughts Prompting
