### ISSUE TITLE
Bibtex Citation

### ISSUE THREAD

**Issue by trigaten** [hwchase17/langchain#188]
Do you have a bibtex citation for this repo?

e.g. something like the following (from https://github.com/bigscience-workshop/promptsource)
```
@misc{bach2022promptsource,
      title={PromptSource: An Integrated Development Environment and Repository for Natural Language Prompts},
      author={Stephen H. Bach and Victor Sanh and Zheng-Xin Yong and Albert Webson and Colin Raffel and Nihal V. Nayak and Abheesht Sharma and Taewoon Kim and M Saiful Bari and Thibault Fevry and Zaid Alyafeai and Manan Dey and Andrea Santilli and Zhiqing Sun and Srulik Ben-David and Canwen Xu and Gunjan Chhablani and Han Wang and Jason Alan Fries and Maged S. Al-shaibani and Shanya Sharma and Urmish Thakker and Khalid Almubarak and Xiangru Tang and Xiangru Tang and Mike Tian-Jian Jiang and Alexander M. Rush},
      year={2022},
      eprint={2202.01279},
      archivePrefix={arXiv},
      primaryClass={cs.LG}
}
```

**Comment by hwchase17** [comment]
There currently is not a bibtex citation, but will look into it, probably using https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by zaemyung** [comment]
@hwchase17 Thank you for your contributions. I would like to cite the tool as well - any update on this?

**Comment by trigaten** [comment]
> @hwchase17 Thank you for your contributions. I would like to cite the tool as well - any update on this?

Closing this since citation has been added.
`
@software{Chase_LangChain_2022,
author = {Chase, Harrison},
month = oct,
title = {{LangChain}},
url = {https://github.com/hwchase17/langchain},
year = {2022}
}
`
