### ISSUE TITLE
Combining Conversation Chain and Agents

### ISSUE THREAD

**Issue by andrewgleave** [hwchase17/langchain#189]
Is there a current API for hooking a conversational chain with an agent so, during the conversation, actions can be performed (e.g. db lookup etc)? 

If not, how would you see this working architecturally?

**Comment by hwchase17** [comment]
@sjwhitmore was excited to see this! coming soon :)

**Comment by hwchase17** [comment]
just added some documentation for how to use an agent with memory (will need to update to version 0.0.22) https://langchain.readthedocs.io/en/latest/examples/memory/agent_with_memory.html

does this answer your question? if not happy to add more docs - please be honest if anything could be more clear!

**Comment by andrewgleave** [comment]
Great work! I'll check it out over the weekend and let you know. At a cursory glance, it looks like it answers the questions I have at the moment.

**Comment by andrewgleave** [comment]
Docs look great. Closing

**Comment by majorelalexis-stack** [comment]
esting discussion! We're building MAXIA, an AI-to-AI marketplace where agents can discover and trade services using USDC on 11 chains (Solana, Base, ETH, XRP, Polygon, Arbitrum, Avalanche, BNB, TON, SUI, TRON). Happy to collaborate or integrate. Check it out: maxiaworld.app
