### ISSUE TITLE
how to escape {} for the PromptTemplate

### ISSUE THREAD

**Issue by jianming** [hwchase17/langchain#1914]
How to add a json example into the prompt template. Currently, it errors.

Here is one example prompt

human_template = """Summarize user's order into the json format keys:"name","size", "topping", "ice", "sugar", "special_instruction".
                    Here are two examples of the order JSON object:
                    {
                    "name": "Jasmine Green Tea/Milk Tea",
                    "quantity": 2,
                    "size": "Large",
                    "ice": "25%",
                    "sugar": "100%",
                    "toppings": "Pearl, Green Bean, Grass Jelly"
                    },
                    {
                    "name": "Popcorn Chicken",
                    "quantity": 1,
                    "special_instruction": "Make it spicy"
                    }
                    {extra_store_instruction}
                    """

I will get this error:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/langchain/prompts/chat.py", line 67, in from_template
    prompt = PromptTemplate.from_template(template)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/langchain/prompts/prompt.py", line 130, in from_template
    return cls(input_variables=list(sorted(input_variables)), template=template)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate
__root__
  Invalid format specifier (type=value_error)

**Comment by Aratako** [comment]
This?

https://github.com/hwchase17/langchain/issues/1660#issuecomment-1469320129

**Comment by jianming** [comment]
thanks!

**Comment by luozixuan** [comment]
Thanks for the solution . But will this keep the prompt have "{{" in it instead of the original "{" ? @Aratako

**Comment by chrisguerrero** [comment]
+1 to @luozixuan — For my use case, I want to include an expected JSON response structure in the prompt. Escaping the curly brackets fixes the "Invalid prompt schema." error I'm getting from langchain, but then the prompt passed to the llm contains the double brackets, so the response I get back is not what I want.

**Comment by luozixuan** [comment]
@chrisguerrero  
Hi, I am not sure if you have resolved your error, but I made it by using "{{{{" , hope it helps

**Comment by andrea-mucci** [comment]
I have the following error and, at the moment i don't have any solution

i have a dictionary in python

```python

dict_example = {
                            "keyfeatures": [
                                {
                                    "title": "Search for Charitable Activities",
                                    "description": "The system must provide a search function that allows users to enter keywords and returns a list of charitable activities that match those keywords."
                                },
                                {
                                    "title": "Display Charitable Activities",
                                    "description": "The system must display the search results in a user-friendly format."
                                },
                                {
                                    "title": "Filter and Sort Charitable Activities",
                                    "description": "The system must provide options for users to filter and sort the search results."
                                },
                                {
                                    "title": "View Details of a Charitable Activity",
                                    "description": "The system must allow users to select a charitable activity from the search results and view more detailed information about it."
                                },
                                {
                                    "title": "Save or Bookmark Charitable Activities",
                                    "description": "The system must allow users to save or bookmark charitable activities that they're interested in."
                                }
                            ]
                        }
```

and i will convert that dict to a json string

```python
json_string = json.dumps(example["example_software_architect"])

```
and i pass that string to a prompt

```python

AIMessagePromptTemplate.from_template(json_string)

```

and i get the following error

```text

File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate
__root__
  Invalid prompt schema; check for mismatched or missing input parameters. '"title"' (type=value_error)

```

In my opinion, is needed to introduce some kind of parameter, like an escape parameter that can control if have sense to parse the string or modify the variables into the string from {variable} to {% variable %}

I hope someone can give a solution to that soon

**Comment by Pauldevillers** [comment]
Hello @andrea-mucci , did you find any other solution, facing same, problem

**Comment by alicercedigital** [comment]
Need an option for this. It is becoming very common send json objects on prompt.

**Comment by Pythonista7** [comment]
Would passing the json examples as partial variables help ?

**Comment by bioshazard** [comment]
@Pythonista7 , this was the answer for me, thank you. Solved as follows:

```
export const systemCiteSourcesPSD = new PromptTemplate({
  inputVariables: ["foor", "metadata"],
  template:`
REDACTED...
...

{foo}

<metadata>
{metadata}
</metadata>

...

`.trim(),
  partialVariables: {
    metadata: () => {
      return JSON.stringify({ bar: "abc"  })
    }
  }
})
```

**Comment by bioshazard** [comment]
@Pythonista7 , this was the answer for me, thank you. Solved as follows:

```
export const myPromptTemplate = new PromptTemplate({
  inputVariables: ["foor", "metadata"],
  template:`
REDACTED...
...

{foo}

<metadata>
{metadata}
</metadata>

...

`.trim(),
  partialVariables: {
    metadata: () => {
      return JSON.stringify({ bar: "abc"  })
    }
  }
})
```

**Comment by Pythonista7** [comment]
@bioshazard Don't think you really need to stringify them if im not wrong , also I later discovered that the prompt template class allows you pass a template engine format which can be helpful in such cases. [Docs Link](https://api.python.langchain.com/en/latest/prompts/langchain_core.prompts.prompt.PromptTemplate.html)
> param template_format: Literal['f-string', 'mustache', 'jinja2'] = 'f-string'
The format of the prompt template. Options are: ‘f-string’, ‘mustache’, ‘jinja2’.

**Comment by wenjoy** [comment]
`https://github.com/langchain-ai/langchain/issues/1660#issuecomment-1469320129` is not work for me when I try to embed  a json string with `json.dump`

**Comment by muhammad-faizan-122** [comment]
also work fine `{{` for example json
