### ISSUE TITLE
ChatOpenAI isn't compatible with create_pandas_dataframe_agent

### ISSUE THREAD

**Issue by sundar7D0** [hwchase17/langchain#1931]
I tried creating a pandas dataframe agent (using create_dataframe_agent) with ChatOpenAI from promptlayer or otherwise just plain version (ChatOpenAI) as the LLM! But langchain isn't able to parse the LLM's output code. If I modify some regular expression manually, it works (but again fails if the code is a single line, etc.). Basically the regex and parsing logic for figuring out Action, Action_input for chat models needs to be changed. This probably means lot of other existing chains with ChatOpenAI as LLM are up for a toss! 

Code:

```
  chat = PromptLayerChatOpenAI(pl_tags=["langchain"])
  df_agent = create_pandas_dataframe_agent(chat, haplo_insuf, verbose=True) 
  df_agent.run("find the maximum number of employees working in any company based on the range. a-b means minimum a, maximum b!")

````

Output:

```
Entering new AgentExecutor chain...
Thought: We need to extract the minimum and maximum number of employees from the "df" dataframe and find the maximum value.
Action: python_repl_ast
Action Input:```max_emp = df['# Employees'].str.split('-', expand=True).astype(int).max(axis=1)max_emp.max()```
Observation: invalid syntax (<unknown>, line 2)
Thought:There seems to be a syntax error in the code. Let me fix it.
Action: python_repl_ast
Action Input:```max_emp = df['# Employees'].str.split('-', expand=True).astype(int).max(axis=1)max_emp.max()```
Observation: invalid syntax (<unknown>, line 2)
Thought:...

```

**Comment by rishibh7** [comment]
+1

**Comment by djpecot** [comment]
+1

**Comment by MohammedAlhajji** [comment]
I think this might actually, I think this is a general problem with `gpt-3.5-turbo` if instead you try `gpt-4` it will work. 

`gpt-3.5-turbo` adds backticks in the action input which causes the syntax error.

**Comment by Architectshwet** [comment]
@sundar7D0 , does this issue got resolved? Chat model working with pandas agent?

**Comment by sundar7D0** [comment]
I think with some fixes as suggested here and in other issues to resolve the parsing bottleneck, now chat model works with pandas agent!

**Comment by brayniacapp** [comment]
> issues to resolve the parsing bottleneck

Hey @sundar7D0 ! Any chance you can point out the other issues? 🙏

**Comment by sundar7D0** [comment]
Please check #1358 thread

**Comment by mrothroc** [comment]
I am still experiencing this on v0.0.163.  I don't have access to gpt4, unfortunately.  I don't see a manual workaround here in the thread.  Is the fix supposed to be in the repo already?

**Comment by adamcolon** [comment]
I solved this problem by Using AgentType.OPENAI_FUNCTIONS:
`create_pandas_dataframe_agent(ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo'), df, verbose=True, agent_type=AgentType.OPENAI_FUNCTIONS)`
