### ISSUE TITLE
How to work with multiple csv files in the same agent session ? is there any option to call agent with multiple csv files, so that the model can interact multiple files and answer us.

### ISSUE THREAD

**Issue by balaji-skoruz** [hwchase17/langchain#1958]

**Comment by pradosh-abd** [comment]
+1

**Comment by pmcray** [comment]
I would also be interested in whether there is some way of ingesting two or more CSV files of pandas dataframes. I would try doing a Compare and Contrast on the two files.

**Comment by skylark400** [comment]
+1

**Comment by MohammedAlhajji** [comment]
The easiest way I think you'd be able to do this is through specifying them in the input variables and adding them to the prefix

**Comment by shakyawar-dev** [comment]
+1

**Comment by kresnandika** [comment]
+1

**Comment by JustinGOSSES** [comment]
+1

**Comment by Uchoa-Gui** [comment]
+1

**Comment by Jonny-P** [comment]
+1

**Comment by ViolaSongsy** [comment]
> The easiest way I think you'd be able to do this is through specifying them in the input variables and adding them to the prefix

could you please elaborate on this? thanks!

**Comment by injuryholmes** [comment]
+1 Any Pro has a solution yet?
