### ISSUE TITLE
AttributeError: type object 'YoutubeLoader' has no attribute 'from_youtube_url'

### ISSUE THREAD

**Issue by aai-tarun** [hwchase17/langchain#1962]
I am trying to load load video and came across below issue.
I am using langchain version 0.0.121

![image](https://user-images.githubusercontent.com/99241695/227492256-c22f93e2-9666-4971-b0a9-0eba7b3dfc8e.png)

**Comment by ToxicNaPalm** [comment]
I got that as well. I had success with using from_youtube_channel and just using the url of the individual video.

**Comment by Aximande** [comment]
i have same issue unfortunately - unable to overcome it

**Comment by johna1203** [comment]
I was able to get it that way. using the video id.

```python
from langchain.document_loaders import YoutubeLoader
import sys

def main(vid: str):
    loader = YoutubeLoader(vid, True)
    docs = loader.load()
    print(docs)

if __name__ == '__main__':
    sys.exit(main("_w0Ikk4JY7U"))

```

**Comment by mkacki98** [comment]
> 

Do you have problems later on e.g. with splitters when you use `YouTubeLoader` instead of using `YouTubeLoader.from_youtube_api`?

**Comment by afdallah** [comment]
Tried it today, got the same issue

**Comment by jdmccarty** [comment]
> I got that as well. I had success with using from_youtube_channel and just using the url of the individual video.

This worked for me as well, thanks!
