### ISSUE TITLE
QueryCheckerTool creates LLMChain object, does not allow manual specification of openai_api_key

### ISSUE THREAD

**Issue by hinsley** [hwchase17/langchain#1982]
### Summary
The QueryCheckerTool function currently creates an LLMChain object internally but does not provide a way to specify the `openai_api_key` manually via supplied arguments. This can cause issues for users who do not want to place their API key in environment variables.

### Steps to Reproduce
Run this code
```python
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI
from langchain.agents import AgentExecutor

import sqlite3
with sqlite3.connect("data.db") as conn:
    pass

db = SQLDatabase.from_uri("sqlite:///data.db")
toolkit = SQLDatabaseToolkit(db=db)
llm = OpenAI(temperature=0, openai_api_key="your key here")

agent_executor = create_sql_agent(
    llm=llm,
    toolkit=toolkit,
    verbose=True
)

while True:
    prompt = input("> ")
    response = agent_executor.run(prompt)
    print(response)
```

### Expected Behavior
`create_sql_agent` should not require me to supply an OpenAI API key, nor should it require me to have this stored in an environment variable.

### Actual Behavior
`create_sql_agent` generates an error when I call it without first setting the `OPENAI_API_KEY` environment variable.

### Obvious Solution
`create_sql_agent` should supply its argument `llm` to functions it calls, obviously. In particular, this line https://github.com/hwchase17/langchain/blob/b83e8265102514d1722b2fb1aad29763c5cad62a/langchain/tools/sql_database/tool.py#L85 is the source of the error.

### Environment
- LangChain version: 0.0.123
- Python version: 3.9.16
- Operating System: Windows 10

**Comment by weiliu1031** [comment]
try this way
```
import os
os.environ['OPENAI_API_KEY'] = "yuor open api key"
```

and it works for me in your case

![image](https://user-images.githubusercontent.com/108661493/227750320-8a86b249-32b5-4c6c-a095-bab98dde0bd1.png)

**Comment by hinsley** [comment]
I assume that works, thanks. But it makes the use of the kwarg a little silly. Might be worth looking into deprecating the kwarg?
