### ISSUE TITLE
New search chain that doesnt use serpapi

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchain#199]
too few free trials, too expensive

**Comment by hwchase17** [comment]
https://stackoverflow.com/questions/37083058/programmatically-searching-google-in-python-using-custom-search

**Comment by conceptofmind** [comment]
@hwchase17 From my initial testing setting up a custom google search API through GCP produces nearly identical scraped results when compared with serpapi. The only difference being the addition of 1 or two new lines which shouldn't be an issue at all. For example, here is a comparison of the text produced: https://www.diffchecker.com/L4oCHMUA

**Comment by ilyazub** [comment]
> too few free trials, too expensive

Thanks for your work, @hwchase17! Let me know if you need SerpApi search credits for research and development.

**Comment by hwchase17** [comment]
thanks for offering @ilyazub ! very generous. big fan of serpapi so i'm personally fine paying atm (not doing a ton of research)

closing this issue as we have both a google search and bing alternative

**Comment by maeyouf** [comment]
hi im dev api i have devlop google search api and puplich in rapidapi is cheap and more speed plze try it i will very hapy
now i recive 300k request per month the price pay as you go 0.3$/1k
search for my service in rapidapi name is google search open
