### ISSUE TITLE
Pinecone in docs is outdated

### ISSUE THREAD

**Issue by Oredna** [hwchase17/langchain#2009]
In [here](https://python.langchain.com/en/latest/modules/indexes/vectorstore_examples/pinecone.html) - Pinecone.from_documents doesn't exist.

In the code [here](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/pinecone.py) it is from_texts

**Comment by AksAman** [comment]
- The correct documentation link is at [Pinecone notebook](https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/pinecone.html)

- `from_documents` doesn't exist at [pinecone.py](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/pinecone.py), but rather in the [vectorstores/base.py](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/base.py) as it inherits from there.

**Comment by gulatisukaran** [comment]
This issue should be closed I guess?

**Comment by gulatisukaran** [comment]
@Oredna has this issue been solved?

**Comment by Oredna** [comment]
Yes

**Comment by abemdxb** [comment]
I can't seem to find pinecone.from_documents in [base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/base.py) or the [pinecone.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/pinecone.py) today either? Could someone help?

By comparison I can find it in the [Chroma.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/chroma.py) file
