### ISSUE TITLE
Setting Chroma persist_directory says "Using embedded DuckDB without persistence"

### ISSUE THREAD

**Issue by josephgardner** [hwchase17/langchain#2022]
Trying to use `persist_directory` to have Chroma persist to disk:

```python
index = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory": "db"})
```
and it displays this warning message that implies it won't be persisted:
```
Using embedded DuckDB without persistence: data will be transient
```
However, it does create files to the `db` directory. The warning appears to originate from https://github.com/chroma-core/chroma/pull/204#issuecomment-1458243316.    Do I have the setting correct?

**Comment by Rishika-Bonagiri** [comment]
> Trying to use `persist_directory` to have Chroma persist to disk:
> 
> ```python
> index = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory": "db"})
> ```
> 
> and it displays this warning message that implies it won't be persisted:
> 
> ```
> Using embedded DuckDB without persistence: data will be transient
> ```
> 
> However, it does create files to the `db` directory. The warning appears to originate from [chroma-core/chroma#204 (comment)](https://github.com/chroma-core/chroma/pull/204#issuecomment-1458243316). Do I have the setting correct?

I have the same issue

**Comment by csiebler** [comment]
Same when using:

```python
db = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory="db/")
```

returns:
```
Using embedded DuckDB without persistence: data will be transient
```

langchain==0.0.123
chromadb==0.3.13

**Comment by Launchable-AI** [comment]
Not sure if this is relevant in your cases, but I was experiencing this issue when setting chroma client_settings directly, eg, Chroma(client_settings=Settings(anonymized_telemetry=False)).

I think this is coming from the init method of Chroma, where will set client_settings if you set persist_directory.

See here

https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/chroma.py#L70

    def __init__(
        self,
        collection_name: str = _LANGCHAIN_DEFAULT_COLLECTION_NAME,
        embedding_function: Optional[Embeddings] = None,
        persist_directory: Optional[str] = None,
        client_settings: Optional[chromadb.config.Settings] = None,
    ) -> None:
        """Initialize with Chroma client."""
        try:
            import chromadb
            import chromadb.config
        except ImportError:
            raise ValueError(
                "Could not import chromadb python package. "
                "Please install it with `pip install chromadb`."
            )

        if client_settings:
            self._client_settings = client_settings
        else:
            self._client_settings = chromadb.config.Settings()
            **if persist_directory is not None:
                self._client_settings = chromadb.config.Settings(
                    chroma_db_impl="duckdb+parquet", persist_directory=persist_directory
                )**
        self._client = chromadb.Client(self._client_settings)
        self._embedding_function = embedding_function
        self._persist_directory = persist_directory
        self._collection = self._client.get_or_create_collection(
            name=collection_name,
            embedding_function=self._embedding_function.embed_documents
            if self._embedding_function is not None
            else None,
        )

**Comment by jeffchuber** [comment]
Hi everyone, really sorry about this. 

This is now fixed in chromadb `0.3.14`

Here is the PR https://github.com/chroma-core/chroma/pull/243

**Comment by josephgardner** [comment]
Verified with `0.3.14`, thanks!
```
❯ python app.py
Using embedded DuckDB with persistence: data will be stored in: db
```

**Comment by SimonB97** [comment]
thanks for solving this, but how do i load the persistent index once saved?

**Comment by nishanthc-nd** [comment]
I am facing the same issue as @SimonB97,
 persist_directory = 'chroma_db_store/index/' or 'chroma_db_store'
 docsearch = Chroma(persist_directory=persist_directory, embedding_function=embeddings)
 
 NoIndexException: Index not found, please create an instance before querying
 
 Folder structure
 chroma_db_store:
       - chroma-collections.parquet  
       - chroma-embeddings.parquet  
       - index/

**Comment by lighteternal** [comment]
+1 same problem as @nishanthc-nd  and @SimonB97

**Comment by kavlata** [comment]
+1 same problem as @nishanthc-nd and @SimonB97

**Comment by josephgardner** [comment]
This issue is resolved. Please create a new one.

**Comment by nishanthc-nd** [comment]
> This issue is resolved. Please create a new one if you need additional support.
Sure please track it here
https://github.com/hwchase17/langchain/issues/2491

**Comment by yash261** [comment]
> Same when using:
> 
> ```python
> db = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory="db/")
> ```
> 
> returns:
> 
> ```
> Using embedded DuckDB without persistence: data will be transient
> ```
> 
> langchain==0.0.123 chromadb==0.3.13

I am facing the same issue. Has you issue resolved?

**Comment by SimonB97** [comment]
> > Same when using:
> > ```python
> > db = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory="db/")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > returns:
> > ```
> > Using embedded DuckDB without persistence: data will be transient
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > langchain==0.0.123 chromadb==0.3.13
> 
> I am facing the same issue. Has you issue resolved?

Nope. Currently using pinecone instead, also because of slightly better retrieval results with hybrid search retriever.

**Comment by jeffchuber** [comment]
@SimonB97 can you update chroma to `0.3.21`?

**Comment by sidsarasvati** [comment]
same issue with me
```    vectordb = Chroma(PRESISTENT_PATH, embedding_function=OpenAIEmbeddings())```

I am using the same path to persist. can see files written in the folder. But it does not load index: 
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

**Comment by jeffchuber** [comment]
@sidsarasvati hey - if you can share a minimal example with me at hello@trychroma.com i will try to get to the bottom of this

we are also changing how persist works that will fix all of these issues once and for all

**Comment by josephgardner** [comment]
I believe this thread has moved to https://github.com/hwchase17/langchain/issues/2491

**Comment by mehul-vaidya** [comment]
I am still getting this error for chromadb==0.3.21

**Comment by mehul-vaidya** [comment]
This issue got solved . basically i have to use vectordb.persist()  after creation reading document. also specify name of persist_directory.

vectordb = Chroma.from_documents(texts, embeddings,persist_directory=persist_directory)
vectordb.persist()
