### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.utilities'

### ISSUE THREAD

**Issue by qaiwiz** [hwchase17/langchain#2029]
I just installed langchain and when I try to import WolframAlphaAPIWrapper using "from langchain.utilities.wolfram_alpha import WolframAlphaAPIWrapper", this error message is returned. I checked site-packages to see if the utilities is there, these are the list of files and no utilities:
VERSION			chains			formatting.py		prompts			sql_database.py
__init__.py		docstore		input.py		py.typed		text_splitter.py
__pycache__		embeddings		llms			python.py		utils.py
agents			example_generator.py	model_laboratory.py	serpapi.py		vectorstores

**Comment by alvarosevilla95** [comment]
Have you checked you're using the latest version of the lib? You can check running `pip show langchain`. Current version is 0.0.123

**Comment by qaiwiz** [comment]
Perhaps not, I get this:
Name: langchain
Version: 0.0.27
Summary: Building applications with LLMs through composability
Home-page: https://github.com/hwchase17/langchain
Author: 
Author-email: 
License: MIT
...
I simply used pip install langchain? should I specify the version number: pip install langchain=123 or something?

**Comment by qaiwiz** [comment]
I tried this: 
$pip install git+https://github.com/hwchase17/langchain
and it returns: 
$ERROR: Package 'langchain' requires a different Python: 3.7.15 not in '<4.0,>=3.8.1'

I am using python 3.7.15. I tried this with Python 3.9.6 and it returns: 
$ERROR: Could not build wheels for langchain which use PEP 517 and cannot be installed directly

**Comment by qaiwiz** [comment]
I tried this: 
$pip install git+https://github.com/hwchase17/langchain
and it returns: 
$ERROR: Package 'langchain' requires a different Python: 3.7.15 not in '<4.0,>=3.8.1'

I am using python 3.7.15. I tried this with Python 3.9.6 and it returns: 
$ERROR: Could not build wheels for langchain which use PEP 517 and cannot be installed directly

**Comment by mofahad** [comment]
> Perhaps not, I get this: Name: langchain Version: 0.0.27 Summary: Building applications with LLMs through composability Home-page: https://github.com/hwchase17/langchain Author: Author-email: License: MIT ... I simply used pip install langchain? should I specify the version number: pip install langchain=123 or something?

Try to install like this pip install langchain==0.0.123

**Comment by qaiwiz** [comment]
I am closing this issue noting that python > 3.8.1 is required, althought pip install lancgain will setup on lower version, it does not operate as it should.
