### ISSUE TITLE
Add prefix_messages property to ChatOpenAI

### ISSUE THREAD

**Issue by lethe3000** [hwchase17/langchain#2036]
Since `llms.OpenAIChat` is deprecated and `chat_models.ChatOpenAI` is sugguested in latest releases, I think it is necessary to add `prefix_messages` to `ChatOpenAI`, just like it in `OpenAIChat` so that we can provide messages to this chat model, for example, provide a system message helps set the behavior of the assistant.

```
m = ChatOpenAI(prefix_messages=[SystemMessage(content='you are a helpful assistant')])
```

**Comment by lethe3000** [comment]
I'm using `llama-index` to create LLM predictor, it works well with `OpenAIChat` with prefix_messages, but not so well with `ChatOpenAI`

```
from llama_index.indices.base import BaseGPTIndex
from langchain.llms import OpenAIChat
from langchain.chat_models import ChatOpenAI
from langchain.schema import BaseMessage

# create an openai predictor
def create_llm_predictor(prefix_messages: Optional[List[BaseMessage]]) -> LLMPredictor:
    args = dict(
        model_name=GptModels.GPT_35_TURBO.value,
        temperature=0.1,
        max_tokens=2000,
    )
    if prefix_messages:
        args['prefix_messages'] = prefix_messages

    return LLMPredictor(
        # works
        llm=OpenAIChat(**args),
       # cannot provide system, user or assistant messages as context
        llm=ChatOpenAI(**args),
    )
```

**Comment by thehunmonkgroup** [comment]
Also curious about this issue, as I try to transition my `llm` for agents to `ChatOpenAI` -- not sure if prefixing a system message would be necessary in this case or not.

**Comment by lethe3000** [comment]
as author said, this should be handled by using a prompt template to generate the messages to pass in

https://python.langchain.com/en/latest/getting_started/getting_started.html#building-a-language-model-application-chat-models
