### ISSUE TITLE
Redirect vebose logs

### ISSUE THREAD

**Issue by alvarosevilla95** [hwchase17/langchain#2045]
Is there a way to redirect the verbose logs away from stdout? I'm working on a frontend app, and I'd like to collect the logs to display in the frontend, but couldn't find in the docs a way to capture them into a variable or similar.

**Comment by alvarosevilla95** [comment]
Ok so I had a look at the code, and I see there's the handler abstraction, and an alternative implementation for wandb, so I should be able to implement my own to suit my needs.

However, I want to run this as an app that serves multiple users, and would like each user to have access to their own traces, but I don't see a way for the handlers to get this signaled in anyway. In my head, I would want to be able to id my individual chain runs / else with a user id, and have that propagated to the handler so it can break it up. 

Did I miss a way to currently do this? Or would it need to be implemented from scratch?

**Comment by MohammedAlhajji** [comment]
maybe what you're looking for is `return_intermediate_steps`

**Comment by alvarosevilla95** [comment]
Ah yes that's exactly what I needed thank you! Went down the wrong rabbit hole with the handlers, and completely missed the easy way to do it :)

**Comment by HARISHKUMAR1112001** [comment]
@alvarosevilla95 @MohammedAlhajji , Can you please tell me how you achieved. I am also facing the similar issue.
