### ISSUE TITLE
 'langchain' is not a package

### ISSUE THREAD

**Issue by JayK31** [hwchase17/langchain#2079]
Trying to run a simple script:

```
from langchain.llms import OpenAI
llm = OpenAI(temperature=0.9)
text = "What would be a good company name for a company that makes colorful socks?"
print(llm(text))
```

I'm running into this error:
`ModuleNotFoundError: No module named 'langchain.llms'; 'langchain' is not a package`

I've got a virtualenv installed with langchains downloaded. 
```⇒  pip show langchain
Name: langchain
Version: 0.0.39
Summary: Building applications with LLMs through composability
Home-page: https://www.github.com/hwchase17/langchain
Author:
Author-email:
License: MIT
Location: /Users/jkaye/dev/langchain-tutorial/venv/lib/python3.11/site-packages
Requires: numpy, pydantic, PyYAML, requests, SQLAlchemy
```

```
⇒  python --version
Python 3.11.0
```

I'm using zsh so I ran `pip install 'langchain[all]'`

**Comment by mofahad** [comment]
that is pretty old version of langchain. The current version is 0.0.123 ,try to install it python 3.9. The same code is working for me

**Comment by JayK31** [comment]
Using python 3.9 and updated langchain but still no luck
```
[venv]~/dev/langchain-tutorial|
⇒  pip install langchain
Requirement already satisfied: langchain in ./venv/lib/python3.9/site-packages (0.0.123)
......

```

Getting the same issues: `ModuleNotFoundError: No module named 'langchain.llms'; 'langchain' is not a package`

**Comment by alvarosevilla95** [comment]
Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

**Comment by franklan010** [comment]
> 

This should be highlighted, I'm one of them named file as langchain.py.
Thank you!

**Comment by zjmvwb1** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

you saved my life!

**Comment by blackwhites** [comment]
I think the reason is I have a langchain.py exist in my folder,solved

**Comment by yousonnet** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

it's helpful! thx

**Comment by Procyon1996** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

That's why! Thanks!!

**Comment by VidhyaSiva** [comment]
Sorry I do not have this file langchain.py in my folder but still getting import error 
from langchain.llms import OpenAI
when I run this in my notebook. I am on Ventura 13.0, python 3.9.6

**Comment by wmbutler** [comment]
I'm running Python 3.11.3

My script:

```
import os
os.environ["OPEN_AI_KEY"] = "REDACTED"
from langchain.llms import OpenAI
```

Error: Import "langchain.llms" could not be resolved

**Comment by glorinli** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

How stupid am I

**Comment by liangwei1229git** [comment]
ahaha, seems not just me name file as langchain.py lol

**Comment by Xmaspro** [comment]
I am experiencing the same issue because one of my files was named langchain.py.

**Comment by Alex-Smith-1234** [comment]
maybe my file was named as langchain.py

**Comment by cavemanbravo** [comment]
Hahaha! There's power in numbers! #langchain.py_power

**Comment by Zabidev2** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

You saved my life brother. RESPECT

**Comment by AmSiyabi** [comment]
> I'm running Python 3.11.3
> 
> My script:
> 
> ```
> import os
> os.environ["OPEN_AI_KEY"] = "REDACTED"
> from langchain.llms import OpenAI
> ```
> 
> Error: Import "langchain.llms" could not be resolved

same here, were you able to resolve the issue?

**Comment by EelcoB23** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

That fixed it for me, thanks!

**Comment by kapilboraste** [comment]
I renamed it from Newlangchain and now its working 🤣

**Comment by ldco2016** [comment]
I used the following import statetement:

`from langchain.llms import OpenAI `

And I am getting the following error:

```
pycode python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from langchain.llms import openai
ImportError: No module named langchain.llms
```

I am using Python 3.11.6 and I installed the packages using `pip3 install openai langchain`

**Comment by younger027** [comment]
> I used the following import statetement:
> 
> `from langchain.llms import OpenAI `
> 
> And I am getting the following error:
> 
> ```
> pycode python main.py
> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>     from langchain.llms import openai
> ImportError: No module named langchain.llms
> ```
> 
> I am using Python 3.11.6 and I installed the packages using `pip3 install openai langchain`

i have same problem, how to solve it? help

**Comment by Ikee8919** [comment]
ModuleNotFoundError: No module named 'langchain.llms.prompts'

**Comment by ningninger** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again
you're wonderful

**Comment by ningninger** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

you 're wonderful !!!

**Comment by WaterDrop-EarthDivision** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

Thank you very much !!!

**Comment by Gl00ria** [comment]
> Is one of the files in your project named langchain.py by any chance? If so that's what it'll be actually importing, rename it and check again

The GOAT
