### ISSUE TITLE
load_summarize_chain cannot run

### ISSUE THREAD

**Issue by taoisu** [hwchase17/langchain#2081]
Was trying to follow the document to run summarization, here's my code:

```python
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains.mapreduce import MapReduceChain
from langchain.prompts import PromptTemplate

llm = OpenAI(temperature=0, engine='text-davinci-003')

text_splitter = CharacterTextSplitter()
with open("./state_of_the_union.txt") as f:
    state_of_the_union = f.read()
texts = text_splitter.split_text(state_of_the_union)

from langchain.docstore.document import Document

docs = [Document(page_content=t) for t in texts[:3]]
from langchain.chains.summarize import load_summarize_chain

chain = load_summarize_chain(llm, chain_type="map_reduce")
chain.run(docs)
```

Got errors like below:
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/30015018/228138989-1808a102-4246-412b-a86a-388d60579543.png">

Any ideas how to fix this? langchain version is 0.0.123

**Comment by mofahad** [comment]
![Screenshot 2023-03-28 160715](https://user-images.githubusercontent.com/19353524/228210439-8e29714e-e785-46e6-9730-e02bca103773.png)
I am able to run it properly . It looks like the error is in openai /api_requestor.

**Comment by taoisu** [comment]
Thanks @mofahad ! I'll dig deeper into it.

**Comment by taoisu** [comment]
Looks like there's a bug in the OpenAI library, the real reson is this:

```
'The response was filtered due to the prompt triggering Azure OpenAI’s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766'
```

It seems as long as texts[0] is included this issue will be triggered, which is:

```
Madam Speaker, Madam Vice President, our First Lady and Second Gentleman. Members of Congress and the Cabinet. Justices of the Supreme Court. My fellow Americans. 
```

I guess it's a weird bug on the azure side.

**Comment by skanda1005** [comment]
How do we use callback to handle such errors?
