### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by 0xj7r** [hwchase17/langchain#2088]
No module 'datasets' found in langchain.evaluation

**Comment by 0xj7r** [comment]
Code to reproduce error: 

`from langchain.evaluation.loading import load_dataset
dataset = load_dataset("sql-qa-chinook")
`

Error:

`ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/zr/v4vml1cs6nl2phqlhc69h29r0000gn/T/ipykernel_72987/3934802754.py in <module>
----> 1 dataset = load_dataset("sql-qa-chinook")

~/opt/anaconda3/lib/python3.9/site-packages/langchain/evaluation/loading.py in load_dataset(uri)
      3 
      4 def load_dataset(uri: str) -> List[Dict]:
----> 5     from datasets import load_dataset
      6 
      7     dataset = load_dataset(f"LangChainDatasets/{uri}")

ModuleNotFoundError: No module named 'datasets'`

**Comment by dcbark01** [comment]
Just ran into the same issue. All you need to do is run `pip install datasets` to install the HuggingFace `datasets` library. See the [docs here](https://github.com/huggingface/datasets).
