### ISSUE TITLE
How to pass filter down to Chroma db when using ConversationalRetrievalChain

### ISSUE THREAD

**Issue by tomeck** [hwchase17/langchain#2095]
I need to supply a 'where' value to filter on metadata to Chromadb `similarity_search_with_score` function.  I can't find a straightforward way to do it.    Is there some way to do it when I kickoff my chain? Any hints, hacks, plans to support?

**Comment by Arttii** [comment]
@tomeck doing something like this Should work on the latest version
```python
chain=ChatVectorDBChain(  vectorstore=vector_store,search_kwargs={"filter":{"type":"things"}},top_k_docs_for_context=1,  ...)
```
`search_kwargs` should work for the other vectorstore chains as well I think

**Comment by suneelmatham** [comment]
Since `ChatVectorDBChain` is being deprecated, I have been trying to use `ConversationalRetrievalChain`. So, I've been passing search_kwargs to the retriever but it's been giving an unexpected keyword arg error. I'm using the latest version.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/54971275/228285414-a9a3adea-89b2-4017-84a2-95fb50ca4646.png">

**Comment by Arttii** [comment]
Can't you pass the kwargs to the chain itself and not the retriever?

**Comment by suneelmatham** [comment]
I am using the latest release 0.0.123 which is missing kwargs in the `as_retriever` function in the same file which caused this issue for me. Just noticed in the repo, that it's been fixed in master branch

**Comment by Arttii** [comment]
For me, it still complains if I pass the args to `as_retriever`, maybe I am having some version clashes from pulling the latest from master, I am not certain.

**Comment by tomeck** [comment]
Master implementation of ```as_retriever``` takes no args.

```    
def as_retriever(self) -> VectorStoreRetriever:
        return VectorStoreRetriever(vectorstore=self)
```

Would something like this work?  

```
    retriever = vectorstore.as_retriever()
    retriever.search_kwargs = {"filter":{"type":"filter"},"k":1}
    qa = ConversationalRetrievalChain.from_llm(OpenAI(temperature=0),
                        retriever,
                        callback_manager=manager,
                        verbose = True,
                        return_source_documents=True)
```

**Comment by tomeck** [comment]
ok thanks, this got me a lot further.

```Python
    qa = ConversationalRetrievalChain.from_llm(
                        OpenAI(temperature=0),
                        VectorStoreRetriever(vectorstore=vectorstore, search_kwargs={"filter":{"tenant":"commerce-hub"}}),
                        callback_manager=manager,
                        verbose = True,
                        return_source_documents=True)
```

**Comment by Arttii** [comment]
Don't forget to set the `k` if you want to get more or less than 4 similar documents. That's the default.

**Comment by tomeck** [comment]
FYI - I am using Chroma as my vectorstore.  I had to hack Chroma.py, specifically ```similarity_search``` 

to change

```Python
docs_and_scores = self.similarity_search_with_score(query, k, where=filter)
```

to this

```Python
docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
```

**Comment by Arttii** [comment]
@tomeck that should be fixed in the latest master

**Comment by perryrobinson** [comment]
I know this is closed but for those of you who figured out how to filter, could you show me another example? I am trying to initialize a retriever with a filter based on an id. Basically trying to build a retriever that is scoped to a single doc_id. I was trying this but no luck:

`search_kwargs = {
    'top_k': 5
    'filters': [
        {'type': 'term', 'field': 'ids', 'value': doc_id}
    ]
}`

Here is a sample of my chroma collection.

`{
  "ids": [
    "849f739c-313a-56e5-95be-e3da7d142766"
  ],
  "documents": [
    "blah blah blah blah"
  ],
  "metadatas": [
    {
      "hash_code": "96efcee6a43aaa8a699bbf90c1d002c35e358d1d44c08ce178a1d522c3d7d6fd",
      "source": "garbage.pdf",
      "doc_type": "pdf"
    }
  ]
}`

**Comment by vibha0411** [comment]
@perryrobinson Upgrading to the latest version of langchain (0.0.157) would help.

**Comment by vibha0411** [comment]
is there a way to filter by multiple file names?
Looks like. you can only have on filter on a attribute currently

**Comment by perryrobinson** [comment]
> is there a way to filter by multiple file names?
> Looks like. you can only have on filter on a attribute currently

I ended up just writing my own custom retriever wrapper and it's working great

**Comment by vyakhya** [comment]
any plans to support filtering on a list of values? like search_kwargs={"filter":{"type":["thing1", "thing2"]}}. I'm using ChatVectorDBChain with Chroma. Any hacks?

**Comment by Amigs** [comment]
Si necesitan pasar filtros en: from langchain.chains import RetrievalQA, se puede hacer así:
retriever = vectordb.as_retriever(search_kwargs={"filter": {"source": "PDF/Others/Astronomical forcing of meter-scale organic-rich mudstone–limestone cyclicity in the Eocene Dongying sag, China Implications for shale reservoir exploration.pdf"}, "k": 4})
qa_chain = RetrievalQA.from_chain_type(llm=model, chain_type="stuff", retriever=retriever, return_source_documents=True)

**Comment by daviibf** [comment]
> Si necesitan pasar filtros en: from langchain.chains import RetrievalQA, se puede hacer así: retriever = vectordb.as_retriever(search_kwargs={"filter": {"source": "PDF/Others/Astronomical forcing of meter-scale organic-rich mudstone–limestone cyclicity in the Eocene Dongying sag, China Implications for shale reservoir exploration.pdf"}, "k": 4}) qa_chain = RetrievalQA.from_chain_type(llm=model, chain_type="stuff", retriever=retriever, return_source_documents=True)

If I use this solution, it answers almost always "I don't know.". And when I check the results source_documents, if gives me an empty list. Am I missing anything ?

**Comment by nareshr8** [comment]
> any plans to support filtering on a list of values? like search_kwargs={"filter":{"type":["thing1", "thing2"]}}. I'm using ChatVectorDBChain with Chroma. Any hacks?

`search_kwargs={"filter":{'$or': [{'source': {'$eq': './SampleDoc/Bikes.pdf'}},
  {'source': {'$eq': './SampleDoc/IceCreams.pdf'}}]}}`
  
  This would work

**Comment by PTTrazavi** [comment]
Does "where_document" work in ConversationalRetrievalChain?
My code is as follow but it doesn't work.
```python
retriever = vectordb.as_retriever(
    search_kwargs={
        "k": 4, 
        "where_document": {'$contains': 'KEYWORD'}
    }
)

qa = ConversationalRetrievalChain.from_llm(
    llm,
    retriever=retriever,
    memory=self.memory,
    return_source_documents=True,
    combine_docs_chain_kwargs={"prompt": qa_prompt}
)
```

**Comment by mLpenguin** [comment]
> Does "where_document" work in ConversationalRetrievalChain? My code is as follow but it doesn't work.
> 
> ```python
> retriever = vectordb.as_retriever(
>     search_kwargs={
>         "k": 4, 
>         "where_document": {'$contains': 'KEYWORD'}
>     }
> )
> 
> qa = ConversationalRetrievalChain.from_llm(
>     llm,
>     retriever=retriever,
>     memory=self.memory,
>     return_source_documents=True,
>     combine_docs_chain_kwargs={"prompt": qa_prompt}
> )
> ```

I also am having trouble using "$contains" when using then vectordb.as_retriever() function. I am using chromadb as the vectorstore. 

I am able to filter documents hardcoding the search value like `vectordb.as_retriever(search_kwargs = {"filter": {"source": "/../../pdf source file test.pdf"} } )` returns the correct files

However, the filter no longer works if I use any of the chroma Where filters as described here ([https://docs.trychroma.com/usage-guide#using-where-filters](url)) such as $contains, $in or $eq. e.g. `vectordb.as_retriever(search_kwargs = {"filter": {"source": {'$contains': 'test'} } })` returns nothing

Any help would be appreciated

**Comment by biagiomaf** [comment]
Hello guys, just want to share with you that in my experience, passing a small number let's say 5 in the "k" paramter of the search_kwargs for rteteving the  top 5 documents in chromadb works only if you have a limited number of docs indexed in the db, since I have more than 30000 docs, I had to set the k with a number greatera than 30000 (in runtime i will be automaticly adjusted with the lenght of the docs array) to let the retreiver get in the first positions of the  docs array the correct documents. Which it does in the right manner, in docs[0] I get exatly what I was searching for. So I assume that it is a bug of Chroma for big db or the k parameter doesn't really work as the top documents retreived in the whole DB. Anyone explored what really the k parameter does for the chromadb?
