### ISSUE TITLE
SQLDatabaseChain expects only select statements

### ISSUE THREAD

**Issue by andrewgleave** [hwchase17/langchain#213]
Running some CRUD-like statements to an agent throws 

`ResourceClosedError: This result object does not return rows. It has been closed automatically.`

From the implementation it appears that it always expects to see rows which are then cast to `str` and returned as part of the chain. What would the impact of modifying this behaviour be on the expected usecase for the SQL chain as it is?

https://github.com/hwchase17/langchain/blob/261029cef3e7c30277027f5d5283b87197eab520/langchain/sql_database.py#L70-L71

**Comment by andrewgleave** [comment]
I realise the attack vector this opens up in public cases (hence why select only is the default).

**Comment by hwchase17** [comment]
thanks for tackling @andrewgleave ! will include in the release tmrw
