### ISSUE TITLE
RetrievalQAWithSourcesChain causing openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens

### ISSUE THREAD

**Issue by limcheekin** [hwchase17/langchain#2133]
I want to migrate from `VectorDBQAWithSourcesChain` to `RetrievalQAWithSourcesChain`. The sample code use Qdrant vector store, it work fine with VectorDBQAWithSourcesChain.

When I run the code with RetrievalQAWithSourcesChain changes, it prompt me the following error:
```
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4411 tokens (4155 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
```

The following is the `git diff` of the code:
```diff
diff --git a/ask_question.py b/ask_question.py
index eac37ce..e76e7c5 100644
--- a/ask_question.py
+++ b/ask_question.py
@@ -2,7 +2,7 @@ import argparse
 import os
 
 from langchain import OpenAI
-from langchain.chains import VectorDBQAWithSourcesChain
+from langchain.chains import RetrievalQAWithSourcesChain
 from langchain.vectorstores import Qdrant
 from langchain.embeddings import OpenAIEmbeddings
 from qdrant_client import QdrantClient
@@ -14,8 +14,7 @@ args = parser.parse_args()
 url = os.environ.get("QDRANT_URL")
 api_key = os.environ.get("QDRANT_API_KEY")
 qdrant = Qdrant(QdrantClient(url=url, api_key=api_key), "docs_flutter_dev", embedding_function=OpenAIEmbeddings().embed_query)
-chain = VectorDBQAWithSourcesChain.from_llm(
-        llm=OpenAI(temperature=0, verbose=True), vectorstore=qdrant, verbose=True)
+chain = RetrievalQAWithSourcesChain.from_chain_type(OpenAI(temperature=0), chain_type="stuff", retriever=qdrant.as_retriever())
 result = chain({"question": args.question})
 
 print(f"Answer: {result['answer']}")
```
If you need the code of data ingestion (create embeddings), please check it out:
https://github.com/limcheekin/flutter-gpt/blob/openai-qdrant/create_embeddings.py

Any idea how to fix it?

Thank you.

**Comment by kxykxyou** [comment]
same issue here

**Comment by qingtian1771** [comment]
I met the same problem when I want to query in some chinese documents which I put them into chromadb

```
embeddings = OpenAIEmbeddings(openai_api_key=os.environ['OPENAI_API_KEY'])
docsearch = Chroma.from_documents(texts, embeddings)
retriever = docsearch.as_retriever()
qa = RetrievalQA.from_llm(llm=OpenAI(), retriever=retriever)

query = "what"
qa.run(query)
```

You can see my prompt is very short, but it says:
InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 6990 tokens (6734 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

**Comment by harithzulfaizal** [comment]
You can try setting `reduce_k_below_max_tokens=True`, it is supposed to limit the number of results to return from store based on tokens limit. But for some reason, it seems that it only works on chat models (GPT-3.5/GPT-4), at least from my testing.

**Comment by limcheekin** [comment]
> You can try setting `reduce_k_below_max_tokens=True`, it is supposed to limit the number of results to return from store based on tokens limit. But for some reason, it seems that it only works on chat models (GPT-3.5/GPT-4), at least from my testing.

That's works! Please review the latest code at https://github.com/limcheekin/flutter-gpt/blob/openai/ask_question.py, appreciate if you spot any improvement.

Thanks.

**Comment by wen020** [comment]
> You can try setting `reduce_k_below_max_tokens=True`, it is supposed to limit the number of results to return from store based on tokens limit. But for some reason, it seems that it only works on chat models (GPT-3.5/GPT-4), at least from my testing.

this a good job，but i dont know how to set reduce_k_below_max_tokens=True？Can you give me some examples

**Comment by limcheekin** [comment]
Please see my code example at https://github.com/limcheekin/flutter-gpt/blob/openai/ask_question.py#L42

**Comment by qingtian1771** [comment]
Thanks, @limcheekin , I saw your code, but in your code you use RetrievalQAWithSourcesChain, which has reduce_k_below_max_tokens field, as following reference said.
https://python.langchain.com/en/latest/reference/modules/chains.html#langchain.chains.RetrievalQAWithSourcesChain

But I use RetrievalQA, it did not has reduce_k_below_max_tokens field, please check this reference
https://python.langchain.com/en/latest/reference/modules/chains.html#langchain.chains.RetrievalQA

should I change to RetrievalQAWithSourcesChain? what's the different between them?

Thanks!

**Comment by Jeru2023** [comment]
There is a more fundamental fix for this issue:
retriever=VectorStoreRetriever(vectorstore=vectorstore, search_kwargs={"filter":{"type":"filter"},"k":3},),

I guess it will work for qdrant as well

**Comment by frankg1** [comment]
> Thanks, @limcheekin , I saw your code, but in your code you use RetrievalQAWithSourcesChain, which has reduce_k_below_max_tokens field, as following reference said. https://python.langchain.com/en/latest/reference/modules/chains.html#langchain.chains.RetrievalQAWithSourcesChain
> 
> But I use RetrievalQA, it did not has reduce_k_below_max_tokens field, please check this reference https://python.langchain.com/en/latest/reference/modules/chains.html#langchain.chains.RetrievalQA
> 
> should I change to RetrievalQAWithSourcesChain? what's the different between them?
> 
> Thanks!

我也有这个问题，我用的是openai.ChatCompletion

**Comment by ZiyadMoraished** [comment]
@wen020 

There seems to be max_tokens_limit parameter, but that is not reflected in the documentation.

This fixed my issue:

ConversationalRetrievalChain.from_llm(OpenAI(temperature=0), vectorstore.as_retriever(search_kwargs={"k": 1}), max_tokens_limit=4097)

**Comment by qixiaobo** [comment]
same issue here

**Comment by GitNinja42** [comment]
This does not work with RetrievalQA, it only works with RetrievalQAWithSourcesChain

**Comment by budhewarvijay0407** [comment]
@ZiyadMoraished The solution works only for one type of chain ConversationalRetrievalChain, for others its not working

**Comment by limcheekin** [comment]
First of all, on data preparation, how you split the text into chunks is important, please look into the following video and notebook to understand more:
https://www.youtube.com/watch?v=eqOfr4AGLk8
https://github.com/pinecone-io/examples/blob/master/generation/langchain/handbook/xx-langchain-chunking.ipynb

Also, the recent blog post from LangChain official blog:
https://blog.langchain.dev/improving-document-retrieval-with-contextual-compression/

These two solutions should solve the issue, I will close the issue if it is quiet for a week.

Thanks.

**Comment by kruulik** [comment]
Hi, trying to implement the suggested solutions myself right now; where would one add these parameters? 
Thanks!

**Comment by bluusun** [comment]
Still have that same issue with RetrievalQA.from_chain_type

**Comment by limcheekin** [comment]
Please read the issue from start to finish, there are few solutions being mentioned. Try it out one by one, it should fix the issue. Otherwise, please open a new issue for the problem you have and share the Github repo so that it is ease for other to re-produce the problem and help you. 

The issue is dated. I think most people here got their solution or workaround for the issue, I will close the issue for now.

**Comment by bluusun** [comment]
I am not sure :)

I switched to this which seemed to work:

chain = VectorDBQAWithSourcesChain.from_llm(
        llm=OpenAI(temperature=0, verbose=True), vectorstore=store, verbose=True)
result = chain({"question": args.question})

Which got me:

 UserWarning: `VectorDBQAWithSourcesChain` is deprecated - please use `from langchain.chains import RetrievalQAWithSourcesChain`
  warnings.warn(


And I modified to this:
 qa= RetrievalQAWithSourcesChain.from_chain_type(
    llm=OpenAI(),
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=True
    
    )

And I am back at the same error ...

openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 5541 tokens (5285 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

**Comment by gisligeir** [comment]
> > You can try setting `reduce_k_below_max_tokens=True`, it is supposed to limit the number of results to return from store based on tokens limit. But for some reason, it seems that it only works on chat models (GPT-3.5/GPT-4), at least from my testing.
> 
> That's works! Please review the latest code at https://github.com/limcheekin/flutter-gpt/blob/openai/ask_question.py, appreciate if you spot any improvement.
> 
> Thanks.

I'm new to this, where should I add this code?

Thanks

**Comment by hyp530** [comment]
> 

same question

**Comment by limcheekin** [comment]
The following notebook should be helpful:
https://github.com/openai/openai-cookbook/blob/main/examples/Embedding_long_inputs.ipynb

If none of the solution above fixed your problem, most likely that the issue is caused by the data, so make sure you understand your data preparation process.

**Comment by tevslin** [comment]
if you are using an agent without chains but have a vector store(pinecone in my case) as a retrieval tool, where would you limit either max_tokens or top_k?

**Comment by limcheekin** [comment]
The following answer is come from above:
```
vectorstore.as_retriever(search_kwargs={"k": 1})
```

**Comment by xumeng** [comment]
> I met the same problem when I want to query in some chinese documents which I put them into chromadb
> 
> ```
> embeddings = OpenAIEmbeddings(openai_api_key=os.environ['OPENAI_API_KEY'])
> docsearch = Chroma.from_documents(texts, embeddings)
> retriever = docsearch.as_retriever()
> qa = RetrievalQA.from_llm(llm=OpenAI(), retriever=retriever)
> 
> query = "what"
> qa.run(query)
> ```
> 
> You can see my prompt is very short, but it says: InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 6990 tokens (6734 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

Same error, Any updates here?

**Comment by GeneralLHW** [comment]
> 第2140章



> 当我想查询一些中文文档并将其放入 chromadb 时，我遇到了同样的问题
> 
> ```
> embeddings = OpenAIEmbeddings(openai_api_key=os.environ['OPENAI_API_KEY'])
> docsearch = Chroma.from_documents(texts, embeddings)
> retriever = docsearch.as_retriever()
> qa = RetrievalQA.from_llm(llm=OpenAI(), retriever=retriever)
> 
> query = "what"
> qa.run(query)
> ```
> 
> 您可以看到我的提示非常短，但它显示： InvalidRequestError: This model's max context length is 4097 tokens, but you requests 6990 tokens (提示中为 6734；完成时为 256)。请减少提示；或完成长度。

How did you solve it？？

**Comment by saaspeter** [comment]
@GeneralLHW , I think the error is saying: your context is too long, the context is from the chromadb, so it is the document in the chromadb is too long, I think. You can set verbose=true, to see the complete question and response to OpenAI.

**Comment by GeneralLHW** [comment]
@saaspeter ,
```python
llm=ChatOpenAI(max_tokens=4096, model_name='gpt-3.5-turbo',temperature=0, verbose=True)
qa = RetrievalQA.from_chain_type(llm, chain_type="map_rerank", retriever=docsearch.as_retriever(), verbose=True)
result = qa.run('1+1')
```
I added parameters, but I still haven't seen the complete question and reply, what should I do?

**Comment by saaspeter** [comment]
@GeneralLHW ,  try to add this:  _langchain.debug = True_  in your python file ? for me, by doing this, I can see the full call parameters and response.

**Comment by GeneralLHW** [comment]
@saaspeter 
I added langchain.debug = True, I saw the requested information, but did not see the returned information, probably because the token limit was exceeded. But there are two strange phenomena, the first one is why there are so many input information? The second is why the prefix of the output prompt has a lot of information that I don’t need. Is it input by langchain itself?
```python
[chain/start] [1:chain:RetrievalQA] Entering Chain run with input:
{
  "query": "1+1"
}
[chain/start] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain] Entering Chain run with input:
[inputs]
[chain/start] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain > 4:chain:LLMChain] Entering Chain run with input:
{
  "input_list": [
    {
      "context": "14.如果只有夫妻其中一人透过协助在美国华美银行开户（以下假设为「夫」）",
      "question": "1+1"
    },
    {
      "context": "一、过户办理： 1.办理产权过户一定要在美国本地才可以进行吗？",
      "question": "1+1"
    },
    {
      "context": "13.客户夫妻两人均没有美国身分和绿卡，考量若按原合约写一个人单独持有房产，万一过世时，恐有大笔遗产税要缴交，造成资产损失。若改为夫妻共同持有，其中任一方过世，另一方变成100%单独拥有房产，是否会",
      "question": "1+1"
    },
    {
      "context": "property制度下，夫妻共同持有房产的时候，每个人所持有的财产基础成本被视为相等的。",
      "question": "1+1"
    }
  ]
}
[llm/start] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain > 4:chain:LLMChain > 5:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nIn addition to giving an answer, also return a score of how fully it answered the user's question. This should be in the following format:\n\nQuestion: [question here]\nHelpful Answer: [answer here]\nScore: [score between 0 and 100]\n\nHow to determine the score:\n- Higher is a better answer\n- Better responds fully to the asked question, with sufficient level of detail\n- If you do not know the answer based on the context, that should be a score of 0\n- Don't be overconfident!\n\nExample #1\n\nContext:\n---------\nApples are red\n---------\nQuestion: what color are apples?\nHelpful Answer: red\nScore: 100\n\nExample #2\n\nContext:\n---------\nit was night and the witness forgot his glasses. he was not sure if it was a sports car or an suv\n---------\nQuestion: what type was the car?\nHelpful Answer: a sports car or an suv\nScore: 60\n\nExample #3\n\nContext:\n---------\nPears are either red or orange\n---------\nQuestion: what color are apples?\nHelpful Answer: This document does not answer the question\nScore: 0\n\nBegin!\n\nContext:\n---------\n14.如果只有夫妻其中一人透过协助在美国华美银行开户（以下假设为「夫」）\n---------\nQuestion: 1+1\nHelpful Answer:"
  ]
}
[llm/start] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain > 4:chain:LLMChain > 5:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nIn addition to giving an answer, also return a score of how fully it answered the user's question. This should be in the following format:\n\nQuestion: [question here]\nHelpful Answer: [answer here]\nScore: [score between 0 and 100]\n\nHow to determine the score:\n- Higher is a better answer\n- Better responds fully to the asked question, with sufficient level of detail\n- If you do not know the answer based on the context, that should be a score of 0\n- Don't be overconfident!\n\nExample #1\n\nContext:\n---------\nApples are red\n---------\nQuestion: what color are apples?\nHelpful Answer: red\nScore: 100\n\nExample #2\n\nContext:\n---------\nit was night and the witness forgot his glasses. he was not sure if it was a sports car or an suv\n---------\nQuestion: what type was the car?\nHelpful Answer: a sports car or an suv\nScore: 60\n\nExample #3\n\nContext:\n---------\nPears are either red or orange\n---------\nQuestion: what color are apples?\nHelpful Answer: This document does not answer the question\nScore: 0\n\nBegin!\n\nContext:\n---------\n一、过户办理： 1.办理产权过户一定要在美国本地才可以进行吗？\n---------\nQuestion: 1+1\nHelpful Answer:"
  ]
}
[llm/start] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain > 4:chain:LLMChain > 5:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nIn addition to giving an answer, also return a score of how fully it answered the user's question. This should be in the following format:\n\nQuestion: [question here]\nHelpful Answer: [answer here]\nScore: [score between 0 and 100]\n\nHow to determine the score:\n- Higher is a better answer\n- Better responds fully to the asked question, with sufficient level of detail\n- If you do not know the answer based on the context, that should be a score of 0\n- Don't be overconfident!\n\nExample #1\n\nContext:\n---------\nApples are red\n---------\nQuestion: what color are apples?\nHelpful Answer: red\nScore: 100\n\nExample #2\n\nContext:\n---------\nit was night and the witness forgot his glasses. he was not sure if it was a sports car or an suv\n---------\nQuestion: what type was the car?\nHelpful Answer: a sports car or an suv\nScore: 60\n\nExample #3\n\nContext:\n---------\nPears are either red or orange\n---------\nQuestion: what color are apples?\nHelpful Answer: This document does not answer the question\nScore: 0\n\nBegin!\n\nContext:\n---------\n13.客户夫妻两人均没有美国身分和绿卡，考量若按原合约写一个人单独持有房产，万一过世时，恐有大笔遗产税要缴交，造成资产损失。若改为夫妻共同持有，其中任一方过世，另一方变成100%单独拥有房产，是否会\n---------\nQuestion: 1+1\nHelpful Answer:"
  ]
}
[llm/start] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain > 4:chain:LLMChain > 5:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nIn addition to giving an answer, also return a score of how fully it answered the user's question. This should be in the following format:\n\nQuestion: [question here]\nHelpful Answer: [answer here]\nScore: [score between 0 and 100]\n\nHow to determine the score:\n- Higher is a better answer\n- Better responds fully to the asked question, with sufficient level of detail\n- If you do not know the answer based on the context, that should be a score of 0\n- Don't be overconfident!\n\nExample #1\n\nContext:\n---------\nApples are red\n---------\nQuestion: what color are apples?\nHelpful Answer: red\nScore: 100\n\nExample #2\n\nContext:\n---------\nit was night and the witness forgot his glasses. he was not sure if it was a sports car or an suv\n---------\nQuestion: what type was the car?\nHelpful Answer: a sports car or an suv\nScore: 60\n\nExample #3\n\nContext:\n---------\nPears are either red or orange\n---------\nQuestion: what color are apples?\nHelpful Answer: This document does not answer the question\nScore: 0\n\nBegin!\n\nContext:\n---------\nproperty制度下，夫妻共同持有房产的时候，每个人所持有的财产基础成本被视为相等的。\n---------\nQuestion: 1+1\nHelpful Answer:"
  ]
}
[chain/error] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain > 4:chain:LLMChain > 5:llm:ChatOpenAI] [133.883ms] Chain run errored with error:
"InvalidRequestError(message=\"This model's maximum context length is 4097 tokens. However, you requested 4443 tokens (347 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.\", param='messages', code='context_length_exceeded', http_status=400, request_id=None)"
[chain/error] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain > 4:chain:LLMChain] [135.041ms] Chain run errored with error:
"InvalidRequestError(message=\"This model's maximum context length is 4097 tokens. However, you requested 4443 tokens (347 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.\", param='messages', code='context_length_exceeded', http_status=400, request_id=None)"
[chain/error] [1:chain:RetrievalQA > 3:chain:MapRerankDocumentsChain] [135.9ms] Chain run errored with error:
"InvalidRequestError(message=\"This model's maximum context length is 4097 tokens. However, you requested 4443 tokens (347 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.\", param='messages', code='context_length_exceeded', http_status=400, request_id=None)"
[chain/error] [1:chain:RetrievalQA] [275.25699999999995ms] Chain run errored with error:
"InvalidRequestError(message=\"This model's maximum context length is 4097 tokens. However, you requested 4443 tokens (347 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.\", param='messages', code='context_length_exceeded', http_status=400, request_id=None)"
```

**Comment by saaspeter** [comment]
@GeneralLHW ,  the context is from the vectorDB, it is the retriver to do the search in vectorDB.  for the prompt, it is the chain default prompt, you can define yours, just click the source code and track it, you can see it.

**Comment by GeneralLHW** [comment]
@saaspeter  Thank you, I tracked it down, but the token is still beyond the limit, which is very strange, because my content is very short and not much, but this error is still there
