### ISSUE TITLE
Rate limit error when using davinci model

### ISSUE THREAD

**Issue by complete-dope** [hwchase17/langchain#2204]
WARNING:langchain.llms.openai:Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..

**Does anyone has a solution for this error ??**

**Comment by sohailzia97** [comment]
Make sure to activate OpenAI paid account. Visit the https://beta.openai.com/account/billing page, and add your credit card info. 

If Still not working?

Check out this, [https://community.](https://community.openai.com/t/rate-limit-error/14769)[openai.com/t/rate-limit-error/](https://community.openai.com/t/rate-limit-error/14769)[14769](https://community.openai.com/t/rate-limit-error/14769)

From https://beta.openai.com/account/api-keys, you can delete the old OpenAI key and create a new OpenAI key if it still does not work.

**Comment by complete-dope** [comment]
cant we use openai free account for testing purpose ?

**Comment by sohailzia97** [comment]
We can. But it has its limitations.
U can check out the rate limits here. 
https://platform.openai.com/docs/guides/rate-limits/overview

**Comment by complete-dope** [comment]
But I tried a very simple code from the official doc of langchain and it gave this error . 

can you please tell what tweeks should I make in this code so it starts working

**Comment by sohailzia97** [comment]
Can you try to use openai api using your api key elsewhere? e.g, by running the following script. 
```
response = openai.Completion.create(
        model="text-davinci-003",
        prompt=<your prompt>
        temperature=0.5,
        max_tokens=len(text),
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0
    )
```

If this runs successfully , then the reason why it's not working in langchain is probably because langchain invokes the openai api several times in the backend and so it hits your rate limit.

**Comment by complete-dope** [comment]
Yup I tried with a new api key then it worked !!

Thank you for helping
