### ISSUE TITLE
'VectorStoreIndexWrapper' object has no attribute 'similarity_search'

### ISSUE THREAD

**Issue by try-agaaain** [hwchase17/langchain#2235]
When running `docs/modules/chains/index_examples/question_answering.ipynb`, the following error occurs:

![image](https://user-images.githubusercontent.com/52828870/229178901-83d00b12-64ca-494b-84f3-22550e23db74.png)

I didn't change the code, just ran the file directly.

**Comment by Officeyutong** [comment]
Change `docsearch.similarity_search` to `docsearch.vectorstore.similarity_search`. The docs seem to be outdated.

**Comment by try-agaaain** [comment]
Thanks, It's helpful.
