### ISSUE TITLE
how to use TextSplitter for GPTSimpleVectorIndex

### ISSUE THREAD

**Issue by oashua** [hwchase17/langchain#2265]
how can I use `TextSplitter` for `GPTSimpleVectorIndex` to split document by such “\n” or/and other?

**Comment by nasirus** [comment]
CharacterTextSplitter has a default parameter separator="\n\n" , you can use another one 
`text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0, separator="\n\n")`

**Comment by oashua** [comment]
thanks a lot!
