### ISSUE TITLE
Add optional version attribute to BasePromptTemplate

### ISSUE THREAD

**Issue by sjwhitmore** [hwchase17/langchain#229]
I would like to track versions of PromptTemplates through time. an optional version attribute would help with this.

**Comment by hwchase17** [comment]
would you also want some sort of prompt name so you could group prompts toghether?
eg:
prompt-name: conversation
prompt-version: 4

**Comment by sjwhitmore** [comment]
Yes great idea I would

**Comment by sjwhitmore** [comment]
will track this externally for now
