### ISSUE TITLE
temperature not work in ChatOpenAI

### ISSUE THREAD

**Issue by slovx2** [hwchase17/langchain#2292]
This code not work
`llm = ChatOpenAI(temperature=0)`

 It seems that Temperature has not been added to the **kwargs of the request In ChatOpenAI

And this code is working fine
`llm = ChatOpenAI(model_kwargs={'temperature': 0})`

**Comment by slovx2** [comment]
#2152

**Comment by andy-tmpt-me** [comment]
Thanks for the workaround! I see this behavior as well in langchain 0.0.130. Temperature is set as an attribute on the ChatOpenAI object, but never gets into the parameters passed to completion_with_retry (chat_models/openai.py)

**Comment by Dobatymo** [comment]
I am using `langchain==0.0.191` and it seems to be fixed there.
