### ISSUE TITLE
Allow different LLM objects for each PromptTemplate in SequentialChain

### ISSUE THREAD

**Issue by sjwhitmore** [hwchase17/langchain#231]
I would like to use SequentialChain with the option to use a different LLM class at each step. The rationale behind this is that I am using different temperature settings for different prompts within my chain. I also potentially may use different models for each step in the future.

a rough idea for config -- have a json dict specifying LLM config, and pass in a list of configs (or list of LLM objects) which is the same length as the number of prompttemplates in the chain if you want to use different objects per chain, or one LLM object or config object in the case where you want to use the same for all

**Comment by hwchase17** [comment]
@sjwhitmore is this already in there? or is more work needed?

**Comment by sjwhitmore** [comment]
yes, confirmed that SequentialChain will handle this, can be closed
