### ISSUE TITLE
Redis "as_retriever": k and score_threshold parameters are lost

### ISSUE THREAD

**Issue by frazur** [hwchase17/langchain#2332]
The following code snippet doesn't work as I expect:

    # Query
    rds = Redis.from_existing_index(embeddings, redis_url="redis://localhost:6379", index_name='iname')
    query = "something to search"
    retriever = rds.as_retriever(search_type="similarity_limit", k=2, score_threshold=0.6)
    results = retriever.get_relevant_documents(query)

The returned values are always 4, that is, the default.
Looking in debug, I see that k and score_threshold parameters are not set in RedisVectorStoreRetriever

**Comment by Veeeetzzzz** [comment]
Modify the as_retriever method in the RedisVectorStore class to accept and pass the custom values of k and score_threshold to the RedisVectorStoreRetriever class and it should store those parameters

Also ensure the get_relevant_documents method in the RedisVectorStoreRetriever class uses the custom k and score_threshold values when performing the search.

**Comment by tylerhutcherson** [comment]
Will work on addressing this -- thanks for raising this issue!

**Comment by tylerhutcherson** [comment]
@frazur this should now be addressed with latest on master.

**Comment by frazur** [comment]
it works, thanks!
