### ISSUE TITLE
How to calculate pricing for ChatGPT API using Sequential Chaining ?

### ISSUE THREAD

**Issue by karndeepsingh** [hwchase17/langchain#2336]
Hi,
I have been using Langchain for my usecase with ChatGPT and I would like to know the expected pricing for my prompts + outputs that I generate. Is there any way we can calculate pricing for it using lang-chain?

Is there any way we can get the total token used during the request similar to when using the OpenAI ChatGPT API package, in lang-chain?

Please help me out.

Thanks

**Comment by akira-fukue** [comment]
I don't know if it answers your question, but to track some things I'm using this documentation as a basis [token_usage_tracking](https://python.langchain.com/en/latest/modules/models/llms/examples/token_usage_tracking.html).

**Comment by karndeepsingh** [comment]
> I don't know if it answers your question, but to track some things I'm using this documentation as a basis [token_usage_tracking](https://python.langchain.com/en/latest/modules/models/llms/examples/token_usage_tracking.html).

Thanks @akira-fukue 
Just a quick questions, How are your thoughts on Giving the same prompts to Chatgpt and FLAN_T5 models or free available generative models for specific tasks? Will that be a great option?

Is there any free available opensource model working similar to chatgpt?

**Comment by karndeepsingh** [comment]
> I don't know if it answers your question, but to track some things I'm using this documentation as a basis [token_usage_tracking](https://python.langchain.com/en/latest/modules/models/llms/examples/token_usage_tracking.html).

When using sequential chaning with FLAN-XL model how the total token size is being calculated? Does it also takes in prompt tokens as consideration with generating the output?

Please help me to understand how the token size is being take to sum up the total 512 token limit in flan-xl when I have multiple chains?
