### ISSUE TITLE
SQLDatabaseChain & the SQL Database Agent do not support generating queries over views

### ISSUE THREAD

**Issue by wadihpazos** [hwchase17/langchain#2356]
This is because the SQLDatabase class does not have view support.

**Comment by wadihpazos** [comment]
@konrad-cadlabs : Not with the current implementation.  The agent takes a dbengine object which is tied to one connection alone.  Interested in your specific use case.  Maybe the right solution is working multiple agents in parallel with the same prompt across different data sources.

**Comment by konrad-cadlabs** [comment]
makes sense, will try with multiple agents. thanks! the use case would be that in one db we have proprietary data of our partner (with read access) and in the other db we have public datasets so we don't have a way to have it in one place.
