### ISSUE TITLE
Unable to import from langchain.document_loaders

### ISSUE THREAD

**Issue by sguti** [hwchase17/langchain#2389]
Unable to import from `langchain.document_loaders`
![image](https://user-images.githubusercontent.com/13831812/229774519-63b09330-494d-4d37-94cd-0193e64d65a8.png)

`Exception has occurred: ModuleNotFoundError
No module named 'langchain.document_loaders'
  File "D:\\repos\gpt\scenarios\chat-with-document\app.py", line 2, in <module>
    from langchain.document_loaders import TextLoader
ModuleNotFoundError: No module named 'langchain.document_loaders'`

I have installed everything mentioned in the langchain docs, but I am still not able to make it work.

Please find attached the [requirements.txt](https://github.com/hwchase17/langchain/files/11147776/requirements.txt)

**Comment by sguti** [comment]
Fixed after installing the latest version 
`pip3 install langchain==0.0.130`

**Comment by jplnasa5** [comment]
Collecting langchain==0.0.130
  Could not find a version that satisfies the requirement langchain==0.0.130 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27)
No matching distribution found for langchain==0.0.130

**Comment by mathewgit** [comment]
try from langchain_community.document_loaders import TextLoader
