### ISSUE TITLE
[ConversationEntity Memory Prompt Template] - issues with customisation

### ISSUE THREAD

**Issue by seanbetts** [hwchase17/langchain#2434]
I’m having a few issues with a prompt template using ConversationChain and ConversationEntity Memory.

Currently I’m using a template as follows:
```
template = """Assistant is a large language model based on OpenAI's chatGPT…

The user Assistant is speaking to is a human and their first name is {first_name} and their surname is {last_name}.

Entities:
{entities}

Conversation history:
{history}

user: {input}
panda:"""
```
I’m then dynamically passing in the first_name and last_name variables as follows, whilst passing over the entities, history and input variables so they can be picked up later:
```
    new_template = template.format(
        first_name=first_name,
        last_name=last_name,
        entities="{entities}",
        history="{history}",
        input="{input}"
    )
```
I then build my prompt:
```
    prompt = PromptTemplate(
        input_variables=["entities", "history", "input"], 
        template=new_template
    )
```
And then run as normal. However, when I inspect the final template in PromptLayer I see that the variables have been replaced as follows:

        first_name=“{input}”,
        last_name=first_name,
        entities=last_name,
        history="{entities}",
        input="{history}"

So none of the variables have mapped properly, and have been mapped in order but with ”{input}” being passed first.

Ideally, I’d take all the input_variables out of the PromptTemplate and set everything up manually, but I don’t think ConversationChain with ConversationEntityMemory will let me do that as I think it’s expecting {entities}, {history}, and {input} variables to be passed in the PromptTemplate.
```
conversation = ConversationChain(
        llm=llm, 
        verbose=False,
        prompt=prompt,
        memory=ConversationEntityMemory(llm=OpenAI(openai_api_key=settings.OPENAI_API_KEY))
    )
```

**Comment by seanbetts** [comment]
I managed to debug this - problem on my end, apologies

**Comment by vignxs** [comment]
Hey Sean, may I know how did you solved it?
