### ISSUE TITLE
Create discord channel for Langchain

### ISSUE THREAD

**Issue by mzhadigerov** [hwchase17/langchain#2448]
Hello! Are you considering creating a Discord channel? Perhaps one already exists, but I was unable to locate it.

**Comment by odiseo0** [comment]
It does exist. It's this one [Discord](https://discord.gg/ZJ48Q7Qm)

**Comment by mzhadigerov** [comment]
@odiseo0 Oh. Thanks! I didn't see

**Comment by andreibondarev** [comment]
Is there an active Discord invite link? The above linked above had expired.
