### ISSUE TITLE
Index configuration does not support sparse values

### ISSUE THREAD

**Issue by mzhadigerov** [hwchase17/langchain#2451]
Hi! I tried to use pinecon's hybrid search as in this tutorial:

https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/pinecone_hybrid_search.html

The only difference is that I created the indices beforehand, so without this chunk of code:

```python
pinecone.create_index(
   name = index_name,
   dimension = 1536,  # dimensionality of dense model
   metric = "dotproduct",
   pod_type = "s1"
)
```

On the chunk below, I'm getting: `HTTP response body: {"code":3,"message":"Index configuration does not support sparse values","details":[]}`

```python
result = retriever.get_relevant_documents("foo")
```

**Comment by acatav** [comment]
Hi, sparse values are supported only with "dotproduct" metric. Is it possible that you used some other metric in your index creation? (note that default metric is "cosine")

**Comment by mzhadigerov** [comment]
@acatav Yes, you are correct. Thank you!
