### ISSUE TITLE
KeyError: 'context' when using PineconeHybridSearchRetriever

### ISSUE THREAD

**Issue by mzhadigerov** [hwchase17/langchain#2459]
When I call

```python

retriever = PineconeHybridSearchRetriever(embeddings=embeddings, index=index, tokenizer=tokenizer)

retriever.get_relevant_documents(query)

```
I'm getting the error:

```
final_result.append(Document(page_content=res["metadata"]["context"]))
KeyError: 'context'
```
What is that `context`?

**Comment by SimonB97** [comment]
hi, i'm facing the same issue as you @mzhadigerov , did you solve this and if so, how?

**Comment by mzhadigerov** [comment]
@SimonB97 Yes, I solved this. You need to explicitly add "context" key to your Document metadata and add page_content value there as a value

**Comment by pd2871** [comment]
@mzhadigerov can you also provide a sample document? It would really help, Thanks
