### ISSUE TITLE
Error while loading saved index in chroma db 

### ISSUE THREAD

**Issue by nishanthc-nd** [hwchase17/langchain#2491]
persist_directory = 'chroma_db_store/index/' or 'chroma_db_store'
docsearch = Chroma(persist_directory=persist_directory, embedding_function=embeddings)
query = "Hey"
docs = docsearch.similarity_search(query)

NoIndexException: Index not found, please create an instance before querying

Folder structure
chroma_db_store:
- chroma-collections.parquet
- chroma-embeddings.parquet
- index/

**Comment by kavlata** [comment]
I tried the code given by @sergerdn  still not working. The place where I am retrieving the persistent storage is in RetrievalQA method.

collection_name="long-docs"
persist_directory="/content/sample_data/chromadb/"
client_settings = Settings(
    chroma_db_impl="duckdb+parquet",
    persist_directory=persist_directory, # Optional, defaults to .chromadb/ in the current directory
    anonymized_telemetry=False
)

**vectorstore** = Chroma(
        collection_name=collection_name,
        embedding_function=embeddings,
        client_settings=client_settings,
        persist_directory=persist_directory,
    )

Then for QA 
qar = RetrievalQA.from_chain_type(llm=local_llm, chain_type="stuff", 
      retriever = **vectorstore.as_retriever()**, chain_type_kwargs=chain_type_kwargs,return_source_documents=True)

The vectorstore here is not accessible. I have persisted the db using persist(). Yet I see this error.
Error: NoIndexException: Index not found, please create an instance before querying

Index folder structure :
chromadb
    index
       chroma-collections.parquet
       chroma-embeddings.parquet

**Comment by kavlata** [comment]
The following code didnt work. I ran this on google colab.

#Load DB
import chromadb
from chromadb.config import Settings
collection_name="long-docs"
persist_directory="/content/sample_data/chromadb/"
client_settings = Settings(
    chroma_db_impl="duckdb+parquet",
    persist_directory=persist_directory, # Optional, defaults to .chromadb/ in the current directory
    anonymized_telemetry=False
)

vectorstore = Chroma(
        collection_name=collection_name,
        embedding_function=embeddings,
        client_settings=client_settings,
        persist_directory=persist_directory,
    )
result = vectorstore.similarity_search_with_score(query="contract", k=4)
print(result)

Error: NoIndexException: Index not found, please create an instance before querying

**Comment by kavlata** [comment]
Thanks @sergerdn for guiding. Python code is below.

```python
from langchain.text_splitter import CharacterTextSplitter, TextSplitter #, NLTKTextSplitter
from llama_index import SimpleDirectoryReader
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
import chromadb
from chromadb.config import Settings

documents = SimpleDirectoryReader('/content/sample_data/',required_exts='.txt').load_langchain_documents() 
from langchain.text_splitter import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(chunk_size=400,chunk_overlap=20,length_function=len,separators=["\n\n", "\n", " ", ""])
texts = text_splitter.split_documents(documents)
collection_name="long-docs"
persist_directory="/content/sample_data/chromadb/"
docsearch_db = Chroma.from_documents(texts, embeddings, collection_name=collection_name, persist_directory=persist_directory)
docsearch_db.persist()


collection_name="long-docs"
persist_directory="/content/sample_data/chromadb/"
client_settings = Settings(
    chroma_db_impl="duckdb+parquet",
    persist_directory=persist_directory, # Optional, defaults to .chromadb/ in the current directory
    anonymized_telemetry=False
)

vectorstore = Chroma(
        collection_name=collection_name,
        embedding_function=embeddings,
        client_settings=client_settings,
        persist_directory=persist_directory,
    )
result = vectorstore.similarity_search_with_score(query="contract", k=1)
print(result)

**Comment by kavlata** [comment]
Thanks so very much @sergerdn It works now.

add_documents and then persist() is working. Thanks !!!

The documentation I was referring to is below

[Documentation link](https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/chroma.html?highlight=from_documents%20persist#initialize-peristedchromadb)

![image](https://user-images.githubusercontent.com/741870/230429419-3d611012-eddb-4ed2-9c94-14f818ae4870.png)

**Comment by chat-guy** [comment]
@sergerdn 
Unfortunately, the above code has a dimensionality error when using Huggingface embeddings (though it works great for OpenAI embeddings).

Tested on Windows; here is the code (and further below is the error).
Any thoughts on a solution?

```python
import logging
import os
import pathlib

import chromadb
from dotenv import load_dotenv
from langchain.document_loaders import PyPDFLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.embeddings.huggingface import HuggingFaceEmbeddings

load_dotenv()
logging.basicConfig(level=logging.DEBUG)

ABS_PATH = os.path.dirname(os.path.abspath(__file__))
DB_DIR = os.path.join(ABS_PATH, "db")

def get_documents():
    return PyPDFLoader("fixtures/pdf/MorseVsFrederick.pdf").load()


def init_chromadb():
    client_settings = chromadb.config.Settings(
        chroma_db_impl="duckdb+parquet",
        persist_directory=DB_DIR,
        anonymized_telemetry=False
    )
    #embeddings = OpenAIEmbeddings()
    model = str(pathlib.Path().resolve().joinpath("sentence-transformers_all-mpnet-base-v2"))
    embeddings = HuggingFaceEmbeddings(model_name=model)

    vectorstore = Chroma(
        collection_name="langchain_store",
        embedding_function=embeddings,
        client_settings=client_settings,
        persist_directory=DB_DIR,
    )

    vectorstore.add_documents(documents=get_documents(), embedding=embeddings)
    vectorstore.persist()


def query_chromadb():
    client_settings = chromadb.config.Settings(
        chroma_db_impl="duckdb+parquet",
        persist_directory=DB_DIR,
        anonymized_telemetry=False
    )

    #embeddings = OpenAIEmbeddings()
    model = str(pathlib.Path().resolve().joinpath("sentence-transformers_all-mpnet-base-v2"))
    embeddings = HuggingFaceEmbeddings(model_name=model)

    vectorstore = Chroma(
        collection_name="langchain_store",
        embedding_function=embeddings,
        client_settings=client_settings,
        persist_directory=DB_DIR,
    )
    result = vectorstore.similarity_search_with_score(query="FREDERICK", k=4)
    print(type(result))


def main():
    init_chromadb()
    #query_chromadb()


if __name__ == '__main__':
    main()
```

```
PS C:\Users\a\Desktop\test> python 1.py
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: C:\Users\a\Desktop\test\sentence-transformers_all-mpnet-base-v2
INFO:sentence_transformers.SentenceTransformer:Use pytorch device: cuda
INFO:chromadb:Running Chroma using direct local API.
WARNING:chromadb:Using embedded DuckDB with persistence: data will be stored in: C:\Users\a\Desktop\test\db
INFO:clickhouse_connect.driver.ctypes:Successfully imported ClickHouse Connect C data optimizations
INFO:clickhouse_connect.driver.ctypes:Successfully import ClickHouse Connect C/Numpy optimizations
INFO:clickhouse_connect.json_impl:Using python library for writing JSON byte strings
INFO:chromadb.db.duckdb:loaded in 16 embeddings
INFO:chromadb.db.duckdb:loaded in 1 collections
INFO:chromadb.db.duckdb:collection with name langchain_store already exists, returning existing collection
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.32s/it]
Traceback (most recent call last):
  File "C:\Users\a\Desktop\test\1.py", line 71, in <module>    main()
  File "C:\Users\a\Desktop\test\1.py", line 66, in main
    init_chromadb()
  File "C:\Users\a\Desktop\test\1.py", line 40, in init_chromadb
    vectorstore.add_documents(documents=get_documents(), embedding=embeddings)
  File "C:\Users\a\AppData\Local\Programs\Python\Python39\lib\site-packages\langchain\vectorstores\base.py", line 48, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "C:\Users\a\AppData\Local\Programs\Python\Python39\lib\site-packages\langchain\vectorstores\chroma.py", line 114, in add_texts
    self._collection.add(
  File "C:\Users\a\AppData\Local\Programs\Python\Python39\lib\site-packages\chromadb\api\models\Collection.py", line 112, in add
    self._client._add(ids, self.name, embeddings, metadatas, documents, increment_index)
  File "C:\Users\a\AppData\Local\Programs\Python\Python39\lib\site-packages\chromadb\api\local.py", line 140, in _add
    self._db.add_incremental(collection_uuid, added_uuids, embeddings)
  File "C:\Users\a\AppData\Local\Programs\Python\Python39\lib\site-packages\chromadb\db\clickhouse.py", line 543, in add_incremental
    index.add(uuids, embeddings)
  File "C:\Users\a\AppData\Local\Programs\Python\Python39\lib\site-packages\chromadb\db\index\hnswlib.py", line 127, in add
    self._check_dimensionality(embeddings)
  File "C:\Users\a\AppData\Local\Programs\Python\Python39\lib\site-packages\chromadb\db\index\hnswlib.py", line 114, in _check_dimensionality
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Dimensionality of (768) does not match index dimensionality (1536)
INFO:chromadb.db.duckdb:PersistentDuckDB del, about to run persist
INFO:chromadb.db.duckdb:Persisting DB to disk, putting it in the save folder: C:\Users\a\Desktop\test\db
```

**Comment by chintan-donda** [comment]
Facing the same issue even after following steps from [here](https://github.com/hwchase17/langchain/issues/2491#issuecomment-1499274206).

Also installed libs with the exact version as specified.

`chromadb.errors.NoIndexException: Index not found, please create an instance before querying`

It works if I call like this:
```
def main():
    init_chromadb()
    query_chromadb()
```
==> This essentially loads the documents, persist it, and then makes query to vectorstore.

But **fails if I restart the Jupyter kernel and run** with below code:
`def main():
    query_chromadb()
 `
==> This tries to load the vectorstore and makes query to vectorstore.


Any suggestion please, how can I fix?

**Comment by chintan-donda** [comment]
@sergerdn When to create directory? At the time of init_chromadb() step or query_chromadb()?
Can u pls share the sample code snippet?

**Comment by chintan-donda** [comment]
@sergerdn I'm already creating the directory if not exist, before you suggested. Still the same issue.

**Comment by chintan-donda** [comment]
@sergerdn Thanks for the code snippet. However it still fails with the same error `chromadb.errors.NoIndexException: Index not found, please create an instance before querying`.
Below is my configuration:
`chromadb==0.3.17
fastapi==0.95.1
langchain==0.0.132
python-dotenv==1.0.0
Python 3.9.6
Macbook Pro M1, OS - Venture 13.3.1
`

**Comment by chintan-donda** [comment]
It's working fine for me with the below code and lib versions:

```
import json
import logging
import os
import re
import sys

from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.document_loaders import PyPDFLoader
from fastapi.encoders import jsonable_encoder
from dotenv import load_dotenv

load_dotenv()
logging.basicConfig(level=logging.DEBUG)

ABS_PATH = os.path.dirname(os.path.abspath(__file__))
DB_DIR = os.path.join(ABS_PATH, "db")


def replace_newlines_and_spaces(text):
    # Replace all newline characters with spaces
    text = text.replace("\n", " ")
    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)
    return text


def get_documents():
    return PyPDFLoader("fixtures/pdf/MorseVsFrederick.pdf").load()


def init_chromadb():
    # Delete existing index directory and recreate the directory
    if os.path.exists(DB_DIR):
        import shutil
        shutil.rmtree(DB_DIR, ignore_errors=True)
        os.mkdir(DB_DIR)

    documents = []
    for num, doc in enumerate(get_documents()):
        doc.page_content = replace_newlines_and_spaces(doc.page_content)
        documents.append(doc)

    # Split the documents into chunks
    text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
    texts = text_splitter.split_documents(documents)

    # Select which embeddings we want to use
    embeddings = OpenAIEmbeddings()

    # Create the vectorestore to use as the index
    vectorstore = Chroma.from_documents(texts, embeddings, persist_directory=DB_DIR)
    vectorstore.persist()
    print(vectorstore)
    vectorstore = None

def query_chromadb():
    if not os.path.exists(DB_DIR):
        raise Exception(f"{DB_DIR} does not exist, nothing can be queried")

    # Select which embeddings we want to use
    embeddings = OpenAIEmbeddings()
    # Load Vector store from local disk
    vectorstore = Chroma(persist_directory=DB_DIR, embedding_function=embeddings)

    result = vectorstore.similarity_search_with_score(query="who is FREDERICK?", k=4)
    jsonable_result = jsonable_encoder(result)
    print(json.dumps(jsonable_result, indent=2))

def main():
    init_chromadb()
    query_chromadb()

if __name__ == '__main__':
    main()
```

Note: `init_chromadb()` creates a subdirectory with name `**index**` under the `DB_DIR`. If it doesn't create it then you will get the error `chromadb.errors.NoIndexException: Index not found, please create an instance before querying`.
But with the above code, it'd work without any issue.


Libs installed and their version:
```
langchain==0.0.132
fastapi==0.95.1
python-dotenv==1.0.0
Python 3.9.6
Macbook Pro M1, OS - Venture 13.3.1
```

**Comment by Wzy232303** [comment]
> @chintan-donda
> 
> Tested and it works. Make sure to uncomment `init_chromadb()` during the first run to create the database with documents. During the second run, only execute `query_chromadb`.
> 
> Please do not use Python notebooks, as they create isolated environments, and you may not have the same environment during a second run.
> 
> ```python
> import json
> import logging
> import os
> import re
> 
> import chromadb
> from dotenv import load_dotenv
> from fastapi.encoders import jsonable_encoder
> from langchain.document_loaders import PyPDFLoader
> from langchain.embeddings import OpenAIEmbeddings
> from langchain.vectorstores import Chroma
> 
> load_dotenv()
> logging.basicConfig(level=logging.DEBUG)
> 
> ABS_PATH = os.path.dirname(os.path.abspath(__file__))
> DB_DIR = os.path.join(ABS_PATH, "db")
> 
> 
> def replace_newlines_and_spaces(text):
>     # Replace all newline characters with spaces
>     text = text.replace("\n", " ")
> 
>     # Replace multiple spaces with a single space
>     text = re.sub(r'\s+', ' ', text)
> 
>     return text
> 
> 
> def get_documents():
>     return PyPDFLoader("fixtures/pdf/MorseVsFrederick.pdf").load()
> 
> 
> def init_chromadb():
>     if not os.path.exists(DB_DIR):
>         os.mkdir(DB_DIR)
> 
>     client_settings = chromadb.config.Settings(
>         chroma_db_impl="duckdb+parquet",
>         persist_directory=DB_DIR,
>         anonymized_telemetry=False
>     )
>     embeddings = OpenAIEmbeddings()
> 
>     vectorstore = Chroma(
>         collection_name="langchain_store",
>         embedding_function=embeddings,
>         client_settings=client_settings,
>         persist_directory=DB_DIR,
>     )
>     documents = []
>     for num, doc in enumerate(get_documents()):
>         doc.page_content = replace_newlines_and_spaces(doc.page_content)
>         documents.append(doc)
> 
>     vectorstore.add_documents(documents=documents, embedding=embeddings)
>     vectorstore.persist()
>     print(vectorstore)
> 
> 
> def query_chromadb():
>     if not os.path.exists(DB_DIR):
>         raise Exception(f"{DB_DIR} does not exist, nothing can be queried")
> 
>     client_settings = chromadb.config.Settings(
>         chroma_db_impl="duckdb+parquet",
>         persist_directory=DB_DIR,
>         anonymized_telemetry=False
>     )
> 
>     embeddings = OpenAIEmbeddings()
> 
>     vectorstore = Chroma(
>         collection_name="langchain_store",
>         embedding_function=embeddings,
>         client_settings=client_settings,
>         persist_directory=DB_DIR,
>     )
>     result = vectorstore.similarity_search_with_score(query="who is FREDERICK?", k=4)
>     jsonable_result = jsonable_encoder(result)
>     print(json.dumps(jsonable_result, indent=2))
> 
> 
> def main():
>     #init_chromadb()
>     query_chromadb()
> 
> 
> if __name__ == '__main__':
>     main()
> ```

notebook not work， you are right

**Comment by bakongi** [comment]
Try to comment "collection_name="langchain_store"," in query_chromadb()

**Comment by dsaks9** [comment]
I used the from_texts method to persist my embeddings, as shown below:

` 
embedder = OpenAIEmbeddings()
db = Chroma.from_texts(texts = embedding_input['texts'],
                        embedding=embedder,
                        metadatas=embedding_input['metadatas'],
                        ids=embedding_input['ids'],
                        persist_directory=f'.../embeddings/{dir_name}_chroma',
                          )
                          
 db.persist()
`

The persist_directory is populated as shown below:

|--- {dir_name}_chroma
       |--- index
             |--- id_to_uuid_9f0....
             |--- index_9f5...
             |--- index_metadata_9f0...
             |--- uuid_to_id_9f0...
       |--- chroma-collections.parquet
       |--- chroma-embeddings.parquet
       

If I comment the `db.persist()` line of code the directory remains the same.

I use the following code, based on the previous replies, to fetch the embeddings from the directory

`
import chromadb
from langchain.vectorstores import Chroma
from langchain.embeddings.openai import Embeddings, OpenAIEmbeddings

collection_name = 'col_name'
dir_name = '/dir/dir1/dir2'

client_settings = chromadb.config.Settings(
        chroma_db_impl="duckdb+parquet",
        persist_directory=dir_name,
        anonymized_telemetry=False
)

embeddings = OpenAIEmbeddings()

db = Chroma(
        collection_name=collection_name,
        embedding_function=embeddings,
        client_settings=client_settings,
        persist_directory=dir_name,
    )

result = db.similarity_search_with_score(query="profit", k=4)
print(result)
`

I still get the following error:

NoIndexException: Index not found, please create an instance before querying

**Comment by chintan-donda** [comment]
@dsaks9 Create the dir_name directory first before the call to Chroma.

```
import chromadb
from langchain.vectorstores import Chroma
from langchain.embeddings.openai import Embeddings, OpenAIEmbeddings

collection_name = 'col_name'
dir_name = '/dir/dir1/dir2'

# Delete existing index directory and recreate the directory
if os.path.exists(dir_name):
    import shutil
    shutil.rmtree(dir_name, ignore_errors=True)
    os.mkdir(dir_name)

client_settings = chromadb.config.Settings(
        chroma_db_impl="duckdb+parquet",
        persist_directory=dir_name,
        anonymized_telemetry=False
)

embeddings = OpenAIEmbeddings()

db = Chroma(
        collection_name=collection_name,
        embedding_function=embeddings,
        client_settings=client_settings,
        persist_directory=dir_name,
    )

result = db.similarity_search_with_score(query="profit", k=4)
print(result)
```

Check if it works?

**Comment by dsaks9** [comment]
@chintan-donda thanks for the suggestion, although still running into the same error.

**Comment by dsaks9** [comment]
Realized I had just forgotten to include the collection name when first creating the embeddings; once I supply collection_name to the from_texts method the code works properly.

**Comment by annjawn** [comment]
I am facing a unique use while using `Chroma.from_documents` Up until yesterday the parquet files were being created but all of a sudden now the the embedding and collections parquet aren't being created at all.

my code is as simple as -

```python
Chroma.from_documents(documents=texts, 
                                      embedding=embeddings, 
                                      persist_directory=self.persist_dir, 
                                      collection_name=self.collection_id)
```

When i look into the file system i see this

```bash
/mnt/content/user-1e9f1de7-9a9f-4623-bcea-0a8ce2b99649,
/mnt/content/user-1e9f1de7-9a9f-4623-bcea-0a8ce2b99649/index",
/mnt/content/user-1e9f1de7-9a9f-4623-bcea-0a8ce2b99649/index/index_metadata_b27bfcbb-0b96-4f75-a575-f6382975afff.pkl,
/mnt/content/user-1e9f1de7-9a9f-4623-bcea-0a8ce2b99649/index/index_b27bfcbb-0b96-4f75-a575-f6382975afff.bin,
/mnt/content/user-1e9f1de7-9a9f-4623-bcea-0a8ce2b99649/index/uuid_to_id_b27bfcbb-0b96-4f75-a575-f6382975afff.pkl,
/mnt/content/user-1e9f1de7-9a9f-4623-bcea-0a8ce2b99649/index/id_to_uuid_b27bfcbb-0b96-4f75-a575-f6382975afff.pkl
```

I see that the `chroma-embeddings.parquet` and `chroma-collections.parquet` are missing altogether. Wonder why.

**Comment by Kefan-pauline** [comment]
Upgrade chromadb to 0.3.23 solved my issue.

**Comment by budhewarvijay0407** [comment]
I used the huggingface model to create the vectorindex in google colab and stored (persisted) the vectordatabase in my drive , now I want to use this drive to get the results when i run it on my local machine 

Im usigng the index folder created in my drive when i ran the colab notebook , however when im using it now (local) its throwing me the error for "NoIndexException: Index not found, please create an instance before querying"

Any suggestion?

**Comment by dankolesnikov** [comment]
If you are still facing `Error: NoIndexException: Index not found`, my solution was to bump the version of your chromadb package, I belive there was a bug there that is now resolved.

`pip install --upgrade chromadb`

@nishanthc-nd can you please try and see if we can close this issue?

**Comment by dankolesnikov** [comment]
my solution was to bump the version of your chromadb package, I believe there was a bug there that is now resolved.

`pip install --upgrade chromadb`

**Comment by lexsf** [comment]
I'm getting this as well.  As soon as I end the python process, I can no longer read the persisted index.   If I create a new chroma client while the process is going on, it seems to read from the persisted dir.  But if create a completely new process, it doesn't work.

**Comment by alberduris** [comment]
Same issue here

**Comment by lastrei** [comment]
some one can help me my code is bellow:

```import os
import re
import uuid

from fastapi import FastAPI, UploadFile
import uvicorn
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from uuid import UUID


app = FastAPI()

DB_DIR = "./db"
embeddings = HuggingFaceEmbeddings(model_name="nghuyong/ernie-3.0-medium-zh")


def replace_newlines_and_spaces(text):
    # Replace all newline characters with spaces
    text = text.replace("\n", " ")
    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)
    return text


def get_documents(file_path):
    return TextLoader(file_path, encoding="utf-8").load()


def init_chromadb(file_path):
    if not os.path.exists(DB_DIR):
        os.mkdir(DB_DIR)

    documents = []
    for num, doc in enumerate(get_documents(file_path)):
        doc.page_content = replace_newlines_and_spaces(doc.page_content)
        documents.append(doc)

    # Split the documents into chunks
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=20, length_function=len,
                                                   separators=["\n\n", "\n", " ", "", "。"])
    texts = text_splitter.split_documents(documents)
    print(len(texts))
    # Create the vectorestore to use as the index
    ids_list = []
    for i in range(len(texts)):
        ids_list.append(str(uuid.uuid1()))
    vectorstore = Chroma.from_documents(texts, embeddings, ids=ids_list, persist_directory=DB_DIR)
    vectorstore.persist()


@app.post("/process-file")
async def process_file(file: UploadFile):
    try:
        random_name = str(uuid.uuid1())
        index_path = "./upload_file/" + random_name + "/"
        file_path = index_path + file.filename
        if not os.path.exists("./upload_file/" + random_name):
            os.mkdir("./upload_file/" + random_name)
        with open(file_path, "wb") as buffer:
            buffer.write(file.file.read())

        init_chromadb(file_path)

        return {"status": "success"}
    except Exception as e:
        return {"status": "failure", "error": str(e)}


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=7777)
```

i make a api use langchain, when the api is runing i use db.get() i can see the documents but when i close the api , and run db.get() again , there is only the documents i first upload.
why?..

**Comment by nishanthc-nd** [comment]
> Thanks so very much @sergerdn It works now.
> 
> add_documents and then persist() is working. Thanks !!!
> 
> The documentation I was referring to is below
> 
> [Documentation link](https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/chroma.html?highlight=from_documents%20persist#initialize-peristedchromadb)
> 
> ![image](https://user-images.githubusercontent.com/741870/230429419-3d611012-eddb-4ed2-9c94-14f818ae4870.png)

This solution seemed to work for me, I am closing this issue.

**Comment by suryakantk94** [comment]
@sergerdn I am getting this same error of illegal instruction. What exactly did you do different in your code so that it started working? Here is more about my issue:

I am getting an Illegal instruction error while trying to initialize chroma db with the saved persist_directory (the vectordb line) while running this in kubernetes cluster. The code throws no exception, just this error.  I was not getting this error while running this locally on apple M2. Any help is appreciated from everyone here.

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
persist_directory = "v7_chroma"

    try:
        embedding_hugg=HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2", 
                                                                    model_kwargs={"device": "cpu"}, 
                                                                    encode_kwargs={"normalize_embeddings": False},)

vectordb = Chroma(persist_directory=persist_directory, embedding_function=embedding_hugg, client_settings=Settings(anonymized_telemetry=False, persist_directory=persist_directory))*

    except Exception as e:

        print("An error occurred:", e)

    retriever = vectordb.as_retriever()

    index = retriever

    results = index.vectorstore.similarity_search(query=data, k=4)
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by ShubhamZoro** [comment]
> I tried the code given by @sergerdn still not working. The place where I am retrieving the persistent storage is in RetrievalQA method.
> 
> collection_name="long-docs" persist_directory="/content/sample_data/chromadb/" client_settings = Settings( chroma_db_impl="duckdb+parquet", persist_directory=persist_directory, # Optional, defaults to .chromadb/ in the current directory anonymized_telemetry=False )
> 
> **vectorstore** = Chroma( collection_name=collection_name, embedding_function=embeddings, client_settings=client_settings, persist_directory=persist_directory, )
> 
> Then for QA qar = RetrievalQA.from_chain_type(llm=local_llm, chain_type="stuff", retriever = **vectorstore.as_retriever()**, chain_type_kwargs=chain_type_kwargs,return_source_documents=True)
> 
> The vectorstore here is not accessible. I have persisted the db using persist(). Yet I see this error. Error: NoIndexException: Index not found, please create an instance before querying
> 
> Index folder structure : chromadb index chroma-collections.parquet chroma-embeddings.parquet
Did you solve this problem can share your repo

**Comment by Mihika21** [comment]
# load some documents
documents = SimpleDirectoryReader(input_files=['uber_2021.pdf']).load_data()

# initialize client, setting path to save data
db = chromadb.PersistentClient(path="./chroma_db")

# create collection
chroma_collection = db.get_or_create_collection("quickstart")

# assign chroma as the vector_store to the context
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

# create your index
index = VectorStoreIndex.from_documents(
    documents, storage_context=storage_context
)
its giving me this error
RuntimeError: Chroma is running in http-only client mode, and can only be run with 'chromadb.api.fastapi.FastAPI' as the chroma_api_impl.             see https://docs.trychroma.com/usage-guide?lang=py#using-the-python-http-only-client for more information.
help me with solution

**Comment by charlesdwright** [comment]
Chroma is an absolute waste of time.
