### ISSUE TITLE
partial_variables and Chat Prompt Templates

### ISSUE THREAD

**Issue by Nemunas** [hwchase17/langchain#2517]
Not sure where to put the partial_variables when using Chat Prompt Templates.

```
chat = ChatOpenAI()

class Colors(BaseModel):
    colors: List[str] = Field(description="List of colors")

parser = PydanticOutputParser(pydantic_object=Colors)
format_instructions = parser.get_format_instructions()    

prompt_text = "Give me a list of 5 colors."

prompt = HumanMessagePromptTemplate.from_template(
    prompt_text + '\n {format_instructions}',
    partial_variables={"format_instructions": format_instructions}    
)
chat_template = ChatPromptTemplate.from_messages([prompt])


result = chat(chat_template.format_messages())
```

```---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[90], line 16
      9 prompt = HumanMessagePromptTemplate.from_template(
     10     prompt_text + '\n {format_instructions}',
     11     partial_variables={"format_instructions": format_instructions}    
     12 )
     13 chat_template = ChatPromptTemplate.from_messages([prompt])
---> 16 result = chat(chat_template.format_messages())

File ~/dev/testing_langchain/.venv/lib/python3.10/site-packages/langchain/prompts/chat.py:186, in ChatPromptTemplate.format_messages(self, **kwargs)
    180 elif isinstance(message_template, BaseMessagePromptTemplate):
    181     rel_params = {
    182         k: v
    183         for k, v in kwargs.items()
    184         if k in message_template.input_variables
    185     }
--> 186     message = message_template.format_messages(**rel_params)
    187     result.extend(message)
    188 else:

File ~/dev/testing_langchain/.venv/lib/python3.10/site-packages/langchain/prompts/chat.py:75, in BaseStringMessagePromptTemplate.format_messages(self, **kwargs)
     74 def format_messages(self, **kwargs: Any) -> List[BaseMessage]:
---> 75     return [self.format(**kwargs)]

File ~/dev/testing_langchain/.venv/lib/python3.10/site-packages/langchain/prompts/chat.py:94, in HumanMessagePromptTemplate.format(self, **kwargs)
     93 def format(self, **kwargs: Any) -> BaseMessage:
---> 94     text = self.prompt.format(**kwargs)
     95     return HumanMessage(content=text, additional_kwargs=self.additional_kwargs)

File ~/dev/testing_langchain/.venv/lib/python3.10/site-packages/langchain/prompts/prompt.py:65, in PromptTemplate.format(self, **kwargs)
     50 """Format the prompt with the inputs.
     51 
     52 Args:
   (...)
     62     prompt.format(variable1="foo")
     63 """
     64 kwargs = self._merge_partial_and_user_variables(**kwargs)
---> 65 return DEFAULT_FORMATTER_MAPPING[self.template_format](self.template, **kwargs)

File ~/.pyenv/versions/3.10.4/lib/python3.10/string.py:161, in Formatter.format(self, format_string, *args, **kwargs)
    160 def format(self, format_string, /, *args, **kwargs):
--> 161     return self.vformat(format_string, args, kwargs)

File ~/dev/testing_langchain/.venv/lib/python3.10/site-packages/langchain/formatting.py:29, in StrictFormatter.vformat(self, format_string, args, kwargs)
     24 if len(args) > 0:
     25     raise ValueError(
     26         "No arguments should be provided, "
     27         "everything should be passed as keyword arguments."
     28     )
---> 29 return super().vformat(format_string, args, kwargs)

File ~/.pyenv/versions/3.10.4/lib/python3.10/string.py:165, in Formatter.vformat(self, format_string, args, kwargs)
    163 def vformat(self, format_string, args, kwargs):
    164     used_args = set()
--> 165     result, _ = self._vformat(format_string, args, kwargs, used_args, 2)
    166     self.check_unused_args(used_args, args, kwargs)
    167     return result

File ~/.pyenv/versions/3.10.4/lib/python3.10/string.py:205, in Formatter._vformat(self, format_string, args, kwargs, used_args, recursion_depth, auto_arg_index)
    201     auto_arg_index = False
    203 # given the field_name, find the object it references
    204 #  and the argument it came from
--> 205 obj, arg_used = self.get_field(field_name, args, kwargs)
    206 used_args.add(arg_used)
    208 # do any conversion on the resulting object

File ~/.pyenv/versions/3.10.4/lib/python3.10/string.py:270, in Formatter.get_field(self, field_name, args, kwargs)
    267 def get_field(self, field_name, args, kwargs):
    268     first, rest = _string.formatter_field_name_split(field_name)
--> 270     obj = self.get_value(first, args, kwargs)
    272     # loop through the rest of the field_name, doing
    273     #  getattr or getitem as needed
    274     for is_attr, i in rest:

File ~/.pyenv/versions/3.10.4/lib/python3.10/string.py:227, in Formatter.get_value(self, key, args, kwargs)
    225     return args[key]
    226 else:
--> 227     return kwargs[key]

KeyError: 'format_instructions'```

**Comment by Nemunas** [comment]
looks like the correct way of doing it is

`prompt = HumanMessagePromptTemplate(
        prompt=PromptTemplate(
            template=prompt_text + '\n {format_instructions}',
            input_variables=[],
            partial_variables={"format_instructions": format_instructions}    
        )
    )`

**Comment by pycharmwizard** [comment]
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from langchain.prompts import ChatPromptTemplates
      2 prompt_template=ChatPromptTemplate.from_template(template_string)

ImportError: cannot import name 'ChatPromptTemplates' from 'langchain.prompts' (C:\Users\Lenovo\anaconda3\an\Lib\site-packages\langchain\prompts\__init__.py) HAVING THIS ERRO R

**Comment by aybeedee** [comment]
> ImportError Traceback (most recent call last) Cell In[1], line 1 ----> 1 from langchain.prompts import ChatPromptTemplates 2 prompt_template=ChatPromptTemplate.from_template(template_string)
> 
> ImportError: cannot import name 'ChatPromptTemplates' from 'langchain.prompts' (C:\Users\Lenovo\anaconda3\an\Lib\site-packages\langchain\prompts__init__.py) HAVING THIS ERRO R

`ChatPromptTemplate` instead of `ChatPromptTemplates` :)

**Comment by jelasin** [comment]
from dotenv import load_dotenv
import os
import uvicorn
from fastapi import FastAPI
from typing import List
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_openai import ChatOpenAI
from langserve import add_routes

load_dotenv()

os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
os.environ["OPENAI_API_BASE"] = os.getenv("OPENAI_API_BASE")
os.environ["LANGCHAIN_API_KEY"] = os.getenv("LANGCHAIN_API_KEY")
os.environ["LANGCHAIN_TRACING_V2"] = os.getenv("LANGCHAIN_TRACING_V2")

model = ChatOpenAI(model="gpt-4")

system_template = "Translate the following into {language}:"
prompt_template = ChatPromptTemplate.format_messages([
    ('system', system_template),
    ('user', '{text}'),
])

parser = StrOutputParser()

chain = prompt_template | model | parser

app = FastAPI(
    title="LangChain Server",
    version="1.0",
    description="A simple API server using LangChain's Runnable interfaces",
)

add_routes(
    app,
    chain,
    path="/chain",
)

if __name__ == "__main__":
    uvicorn.run(app, host="localhost", port=8000)


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 21
     18 model = ChatOpenAI(model="gpt-4")
     20 system_template = "Translate the following into {language}:"
---> 21 prompt_template = ChatPromptTemplate.format_messages([
     22     ('system', system_template),
     23     ('user', '{text}')
     24 ])
     28 parser = StrOutputParser()
     30 chain = prompt_template | model | parser

File c:\Users\30487\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\prompts\chat.py:1134, in ChatPromptTemplate.format_messages(self, **kwargs)
   1124 def format_messages(self, **kwargs: Any) -> List[BaseMessage]:
   1125     """Format the chat template into a list of finalized messages.
   1126 
   1127     Args:
   (...)
   1132         list of formatted messages.
   1133     """
-> 1134     kwargs = self._merge_partial_and_user_variables(**kwargs)
   1135     result = []
   1136     for message_template in self.messages:

AttributeError: 'list' object has no attribute '_merge_partial_and_user_variables'

**Comment by jelasin** [comment]
i use langchain 0.2.10

**Comment by aybeedee** [comment]
> system_template = "Translate the following into {language}:" prompt_template = ChatPromptTemplate.format_messages([ ('system', system_template), ('user', '{text}'), ])

Use `from_messages` instead of `format_messages` like below:
```python
prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", system_template),
        ("user", "{text}"),
    ]
)
