### ISSUE TITLE
ConversationalRetrievalChain memory problem

### ISSUE THREAD

**Issue by Ioannis-Pikoulis** [hwchase17/langchain#2536]
Hello everyone.

I have made a ConversationalRetrievalChain with ConversationBufferMemory. The chain is having trouble remembering the last question that I have made, i.e. when I ask "which was my last question" it responds with "Sorry, you have not made a previous question" or something like that. Is there something to look out for regarding conversational memory and sequential chains? 

Code looks like this:
```

llm = OpenAI(
    openai_api_key=OPENAI_API_KEY,
    model_name='gpt-3.5-turbo',
    temperature=0.0
)

memory = ConversationBufferMemory(memory_key='chat_history', return_messages=False)

conversational_qa = ConversationalRetrievalChain.from_llm(llm=llm, 
                                                          retriever=vectorstore.as_retriever(),
                                                          memory=memory)

**Comment by kartikbhardwaj2000** [comment]
ConversationalRetrievalChain uses condense_question_prompt to find the question. Its default prompt is CONDENSE_QUESTION_PROMPT.
have a look at this snipped from ConversationalRetrievalChain class

`@classmethod
    def from_llm(
        cls,
        llm: BaseLanguageModel,
        retriever: BaseRetriever,
        condense_question_prompt: BasePromptTemplate = CONDENSE_QUESTION_PROMPT,
        qa_prompt: Optional[BasePromptTemplate] = None,
        chain_type: str = "stuff",
        **kwargs: Any,
    ) -> BaseConversationalRetrievalChain:
        """Load chain from LLM."""
        doc_chain = load_qa_chain(
            llm,
            chain_type=chain_type,
            prompt=qa_prompt,
        )
        condense_question_chain = LLMChain(llm=llm, prompt=condense_question_prompt)
        return cls(
            retriever=retriever,
            combine_docs_chain=doc_chain,
            question_generator=condense_question_chain,
            **kwargs,
        )`
        
        
      The default prompt inside CONDENSE_QUESTION_PROMPT is 
      `"""Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:"""`


Perhaps, The current CONDENSE prompt does not solve for your requirement. You can pass your own prompt template and experiment with it. Let me know what worked.

**Comment by kartikbhardwaj2000** [comment]
@Ioannis-Pikoulis  Hope my answer helps

**Comment by Ioannis-Pikoulis** [comment]
The default prompt includes the chat history. So the LLM has access to my previous question. I believe the problem lies elsewhere

**Comment by homanp** [comment]
> I solved the issue changing the format of the QA_PROMPT, i.e. including the chat history explicitly as input.

Could you share the prompt you used. Or at least the setup of the prompt @Ioannis-Pikoulis

**Comment by pratham-saraf** [comment]
@homanp  the prompt is available here 
https://github.com/hwchase17/langchain/blob/624554a43a1ab0113f3d79ebcbc9e726faecb339/langchain/chains/conversational_retrieval/prompts.py#L12

**Comment by majumba** [comment]
Can anyone suggest a good prompt to solve this issue. Also encountering this problem
