### ISSUE TITLE
add caching for LLM calls

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchain#263]
calling an LLM can be expensive - would make sense to cache queries!

**Comment by thepok** [comment]
Using a notebook while developing reduces calls a lot too.

a local SQLite where every call is optionally saved could be a easy solution

**Comment by thepok** [comment]
i ll do this next. Any suggestions how to do it?

**Comment by hwchase17** [comment]
yeah - was chatting with @asamant21 about it.

step 1 i think is be able to serialize a LLM configuration to json

once that is done, we can just create a key-value store (in sqlite, whereever) with the key being (input string, llm configuration)

i think @asamant21 was going to work on the llm json stuff?

**Comment by thepok** [comment]
on inspection, at least OpenAI() implements a "_identifying_params" thats well suited?!?

**Comment by thepok** [comment]
import json
openai = OpenAI(model="text-davinci-003")
json.dumps(openai._identifying_params, sort_keys=True)

**Comment by thepok** [comment]
ChatGPT is realy smart:

**Comment by thepok** [comment]
it just wanted to help by showing options :) i have no preference.

current system seems fine. Maybe add some kind of option, that only caches if LLM is in deterministic mode or if active demanded

**Comment by hwchase17** [comment]
yeah i think some flag for whether or not to cache each llm call is probably good, will work on tht

**Comment by devonbrackbill** [comment]
I have a use case where it would be generally useful to flexibly include or exclude an already cached LLM call. For example, you could cache the summarization phase of a large document with `chain = load_summarize_chain(llm, chain_type="map_reduce", combine_prompt=PROMPT)`, but then call the final `combine_prompt` LLM and have it ignore the cache and generate a new output. (Realize you can specify `n` calls to an LLM, but it's often useful to retry the final step interactively.) This could also be useful earlier in a chain as well. 

I'm thinking something that flexibly allows you to *ignore* an already cached LLM and recompute it, rather than a flag that allows you to cache/not cache in the first place. But open to ideas!

**Comment by hwchase17** [comment]
okay so possible modes would be:

1. no cache (do not read or write from cache)
2. cache (read and write from cache)
3. recompute (only write to cache)

is there ever use case for read only?

**Comment by devonbrackbill** [comment]
These modes are for each *step* in a chain, right? 

If that's right, then read-only wouldn't be a use case b/c I don't think the cache could have ever been created in the first place (unless I'm misunderstanding). The 3 you listed would be exhaustive.

In my use case, I could call cache (read and write) on the summarization step(s) and no cache (do not read or write) on the final generation step.

**Comment by hwchase17** [comment]
yup exactly. okay not 100% sure when ill have time to get to this, but seems clear what needs to be done

**Comment by devonbrackbill** [comment]
I'm happy to look at it too. Any ideas what the interface should look like? Should it be available for all chain types? My use case is summarization, so I was thinking something in the call to `load_summarize_chain(llm, chain_type="map_reduce", cache=["no_cache", "cache", "recompute"])`. Or would it be made in the call to `chain.run()` somehow?

Also, any pointers on where the cache gets written to or read from throughout the code? I see `lookup` and `update` in `langchain/cache.py`, but my search didn't reveal where they were getting called.

**Comment by hwchase17** [comment]
> I'm happy to look at it too. Any ideas what the interface should look like? Should it be available for all chain types? My use case is summarization, so I was thinking something in the call to `load_summarize_chain(llm, chain_type="map_reduce", cache=["no_cache", "cache", "recompute"])`. Or would it be made in the call to `chain.run()` somehow?
> 
> Also, any pointers on where the cache gets written to or read from throughout the code? I see `lookup` and `update` in `langchain/cache.py`, but my search didn't reveal where they were getting called.

okay i had more time than i thought. i didn't add the recompute mode (because now that im thinking about, when would you want to use recompute for an LLM and not just no-cache?)

pr here: https://github.com/hwchase17/langchain/pull/379

notebook with functionality here: https://github.com/hwchase17/langchain/blob/harrison/cache_mode/docs/examples/prompts/llm_caching.ipynb

very open to thoughts/feedback

**Comment by devonbrackbill** [comment]
Thanks, this works perfectly! I like the interface on turning off specific llms and then passing them into the `load_summarize_chain()` call.

**Comment by hwchase17** [comment]
glad to hear! just got released, will tweet about it tmrw!
