### ISSUE TITLE
How to Iteratively parse all the contents within links on a page?

### ISSUE THREAD

**Issue by nazkhan-8451** [hwchase17/langchain#2680]
The following only parse the info within the webpage. If there are links/other pages embedded into the webpage, how do I parse them iteratively?

`loader = WebBaseLoader("https://beta.ruff.rs/docs/faq/")`
`blog_docs = loader.load()`

print(blog_docs)

> [Document(page_content='\n\n\n\n\n\n\n\n\n\n\n\nFAQ - Ruff\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSkip to content\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nRuff\n\n\n\n\nFAQ\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nInitializing search\n\n\n\n\n\n\n\n\n\n\n\n\n\nruff\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nRuff\n\n\n\n\n\n\n\nruff\n\n\n\n\n\n\nOverview\n\n\n\n\nTutorial\n\n\n\n\nInstallation\n\n\n\n\nUsage\n\n\n\n\nConfiguration\n\n\n\n\nRules\n\n\n\n\nSettings\n\n\n\n\nEditor Integrations\n\n\n\n\n\nFAQ\n\n\n\nFAQ\n\n\n\n\nTable of contents\n\n\n\n\nIs Ruff compatible with Black?\n\n\n\n\nHow does Ruff compare to Flake8?\n\n\n\n\nHow does Ruff compare to Pylint?\n\n\n\n\nHow does Ruff compare to Mypy, or Pyright, or Pyre?\n\n\n\n\nWhich tools does Ruff replace?\n\n\n\n\nWhat versions of Python does Ruff support?\n\n\n\n\nDo I need to install Rust to use Ruff?\n\n\n\n\nCan I write my own plugins for Ruff?\n\n\n\n\nHow does Ruff\'s import sorting compare to isort?\n\n\n\n\nDoes Ruff support Jupyter Notebooks?\n\n\n\n\nDoes Ruff support NumPy- or Google-style docstrings?\n\n\n\n\nHow can I tell what settings Ruff is using to check my code?\n\n\n\n\nI want to use Ruff, but I don\'t want to use pyproject.toml. Is that possible?\n\n\n\n\nHow can I change Ruff\'s default configuration?\n\n\n\n\nRuff tried to fix something — but it broke my code?\n\n\n\n\nHow can I disable Ruff\'s color output?\n\n\n\n\n\n\n\nContributing\n\n\n\n\n\n\n\n\n\nFAQ#\nIs Ruff compatible with Black?#\nYes. Ruff is compatible with Black out-of-the-box, as long as\nthe line-length setting is consistent between the two.\nAs a project, Ruff is designed to be used alongside Black and, as such, will defer implementing\nstylistic lint rules that are obviated by autoformatting.\nHow does Ruff compare to Flake8?#\n(Coming from Flake8? Try flake8-to-ruff to\nautomatically convert your existing configuration.)\nRuff can be used as a drop-in replacement for Flake8 when used (1) without or with a small number of\nplugins, (2) alongside Black, and (3) on Python 3 code.\nUnder those conditions, Ruff implements every rule in Flake8. In practice, that means Ruff\nimplements all of the F rules (which originate from Pyflakes), along with a subset of the E and\nW rules (which originate from pycodestyle).\nRuff also re-implements some of the most popular Flake8 plugins and related code quality tools\nnatively, including:\n\nautoflake\neradicate\nflake8-2020\nflake8-annotations\nflake8-bandit (#1646)\nflake8-blind-except\nflake8-boolean-trap\nflake8-bugbear\nflake8-builtins\nflake8-commas\nflake8-comprehensions\nflake8-datetimez\nflake8-debugger\nflake8-django\nflake8-docstrings\nflake8-eradicate\nflake8-errmsg\nflake8-executable\nflake8-gettext\nflake8-implicit-str-concat\nflake8-import-conventions\nflake8-logging-format\nflake8-no-pep420\nflake8-pie\nflake8-print\nflake8-pyi\nflake8-pytest-style\nflake8-quotes\nflake8-raise\nflake8-return\nflake8-self\nflake8-simplify\nflake8-super\nflake8-tidy-imports\nflake8-type-checking\nflake8-use-pathlib\nisort\nmccabe\npandas-vet\npep8-naming\npydocstyle\npygrep-hooks (#980)\npyupgrade\ntryceratops\nyesqa\n\nNote that, in some cases, Ruff uses different rule codes and prefixes than would be found in the\noriginating Flake8 plugins. For example, Ruff uses TID252 to represent the I252 rule from\nflake8-tidy-imports. This helps minimize conflicts across plugins and allows any individual plugin\nto be toggled on or off with a single (e.g.) --select TID, as opposed to --select I2 (to avoid\nconflicts with the isort rules, like I001).\nBeyond the rule set, Ruff\'s primary limitation vis-à-vis Flake8 is that it does not support custom\nlint rules. (Instead, popular Flake8 plugins are re-implemented in Rust as part of Ruff itself.)\nThere are a few other minor incompatibilities between Ruff and the originating Flake8 plugins:\n\nRuff doesn\'t implement all the "opinionated" lint rules from flake8-bugbear.\nDepending on your project structure, Ruff and isort can differ in their detection of first-party\ncode. (This is often solved by modifying the src property, e.g., to src = ["src"], if your\ncode is nested in a src directory.)\n\nHow does Ruff compare to Pylint?#\nAt time of writing, Pylint implements ~409 total rules, while Ruff implements 440, of which at least\n89 overlap with the Pylint rule set (you can find the mapping in #970).\nPylint implements many rules that Ruff does not, and vice versa. For example, Pylint does more type\ninference than Ruff (e.g., Pylint can validate the number of arguments in a function call). As such,\nRuff is not a "pure" drop-in replacement for Pylint (and vice versa), as they enforce different sets\nof rules.\nDespite these differences, many users have successfully switched from Pylint to Ruff, especially\nthose using Ruff alongside a type checker,\nwhich can cover some of the functionality that Pylint provides.\nLike Flake8, Pylint supports plugins (called "checkers"), while Ruff implements all rules natively.\nUnlike Pylint, Ruff is capable of automatically fixing its own lint violations.\nPylint parity is being tracked in #970.\nHow does Ruff compare to Mypy, or Pyright, or Pyre?#\nRuff is a linter, not a type checker. It can detect some of the same problems that a type checker\ncan, but a type checker will catch certain errors that Ruff would miss. The opposite is also true:\nRuff will catch certain errors that a type checker would typically ignore.\nFor example, unlike a type checker, Ruff will notify you if an import is unused, by looking for\nreferences to that import in the source code; on the other hand, a type checker could flag that you\npassed an integer argument to a function that expects a string, which Ruff would miss. The\ntools are complementary.\nIt\'s recommended that you use Ruff in conjunction with a type checker, like Mypy, Pyright, or Pyre,\nwith Ruff providing faster feedback on lint violations and the type checker providing more detailed\nfeedback on type errors.\nWhich tools does Ruff replace?#\nToday, Ruff can be used to replace Flake8 when used with any of the following plugins:\n\nflake8-2020\nflake8-annotations\nflake8-bandit (#1646)\nflake8-blind-except\nflake8-boolean-trap\nflake8-bugbear\nflake8-builtins\nflake8-commas\nflake8-comprehensions\nflake8-datetimez\nflake8-debugger\nflake8-django\nflake8-docstrings\nflake8-eradicate\nflake8-errmsg\nflake8-executable\nflake8-gettext\nflake8-implicit-str-concat\nflake8-import-conventions\nflake8-logging-format\nflake8-no-pep420\nflake8-pie\nflake8-print\nflake8-pytest-style\nflake8-quotes\nflake8-raise\nflake8-return\nflake8-self\nflake8-simplify\nflake8-super\nflake8-tidy-imports\nflake8-type-checking\nflake8-use-pathlib\nmccabe\npandas-vet\npep8-naming\npydocstyle\ntryceratops\n\nRuff can also replace isort,\nyesqa, eradicate, and\nmost of the rules implemented in pyupgrade.\nIf you\'re looking to use Ruff, but rely on an unsupported Flake8 plugin, feel free to file an\nissue.\nWhat versions of Python does Ruff support?#\nRuff can lint code for any Python version from 3.7 onwards, including Python 3.10 and 3.11.\nRuff does not support Python 2. Ruff may run on pre-Python 3.7 code, although such versions\nare not officially supported (e.g., Ruff does not respect type comments).\nRuff is installable under any Python version from 3.7 onwards.\nDo I need to install Rust to use Ruff?#\nNope! Ruff is available as ruff on PyPI:\npip install ruff\n\nRuff ships with wheels for all major platforms, which enables pip to install Ruff without relying\non Rust at all.\nCan I write my own plugins for Ruff?#\nRuff does not yet support third-party plugins, though a plugin system is within-scope for the\nproject. See #283 for more.\nHow does Ruff\'s import sorting compare to isort?#\nRuff\'s import sorting is intended to be nearly equivalent to isort when used profile = "black".\nThere are a few known, minor differences in how Ruff and isort break ties between similar imports,\nand in how Ruff and isort treat inline comments in some cases (see: #1381,\n#2104).\nLike isort, Ruff\'s import sorting is compatible with Black.\nRuff does not yet support all of isort\'s configuration options, though it does support many of\nthem. You can find the supported settings in the API reference.\nFor example, you can set known-first-party like so:\n[tool.ruff]\nselect = [\n    # Pyflakes\n    "F",\n    # Pycodestyle\n    "E",\n    "W",\n    # isort\n    "I001"\n]\n\n# Note: Ruff supports a top-level `src` option in lieu of isort\'s `src_paths` setting.\nsrc = ["src", "tests"]\n\n[tool.ruff.isort]\nknown-first-party = ["my_module1", "my_module2"]\n\nDoes Ruff support Jupyter Notebooks?#\nRuff is integrated into nbQA, a tool for running linters and\ncode formatters over Jupyter Notebooks.\nAfter installing ruff and nbqa, you can run Ruff over a notebook like so:\n> nbqa ruff Untitled.ipynb\nUntitled.ipynb:cell_1:2:5: F841 Local variable `x` is assigned to but never used\nUntitled.ipynb:cell_2:1:1: E402 Module level import not at top of file\nUntitled.ipynb:cell_2:1:8: F401 `os` imported but unused\nFound 3 errors.\n1 potentially fixable with the --fix option.\n\nDoes Ruff support NumPy- or Google-style docstrings?#\nYes! To enable specific docstring convention, add the following to your pyproject.toml:\n[tool.ruff.pydocstyle]\nconvention = "google"  # Accepts: "google", "numpy", or "pep257".\n\nFor example, if you\'re coming from flake8-docstrings, and your originating configuration uses\n--docstring-convention=numpy, you\'d instead set convention = "numpy" in your pyproject.toml,\nas above.\nAlongside convention, you\'ll want to explicitly enable the D rule code prefix, like so:\n[tool.ruff]\nselect = [\n    "D",\n]\n\n[tool.ruff.pydocstyle]\nconvention = "google"\n\nSetting a convention force-disables any rules that are incompatible with that convention, no\nmatter how they\'re provided, which avoids accidental incompatibilities and simplifies configuration.\nHow can I tell what settings Ruff is using to check my code?#\nRun ruff check /path/to/code.py --show-settings to view the resolved settings for a given file.\nI want to use Ruff, but I don\'t want to use pyproject.toml. Is that possible?#\nYes! In lieu of a pyproject.toml file, you can use a ruff.toml file for configuration. The two\nfiles are functionally equivalent and have an identical schema, with the exception that a ruff.toml\nfile can omit the [tool.ruff] section header.\nFor example, given this pyproject.toml:\n[tool.ruff]\nline-length = 88\n\n[tool.ruff.pydocstyle]\nconvention = "google"\n\nYou could instead use a ruff.toml file like so:\nline-length = 88\n\n[pydocstyle]\nconvention = "google"\n\nRuff doesn\'t currently support INI files, like setup.cfg or tox.ini.\nHow can I change Ruff\'s default configuration?#\nWhen no configuration file is found, Ruff will look for a user-specific pyproject.toml or\nruff.toml file as a last resort. This behavior is similar to Flake8\'s ~/.config/flake8.\nOn macOS, Ruff expects that file to be located at /Users/Alice/Library/Application Support/ruff/ruff.toml.\nOn Linux, Ruff expects that file to be located at /home/alice/.config/ruff/ruff.toml.\nOn Windows, Ruff expects that file to be located at C:\\Users\\Alice\\AppData\\Roaming\\ruff\\ruff.toml.\nFor more, see the dirs crate.\nRuff tried to fix something — but it broke my code?#\nRuff\'s autofix is a best-effort mechanism. Given the dynamic nature of Python, it\'s difficult to\nhave complete certainty when making changes to code, even for the seemingly trivial fixes.\nIn the future, Ruff will support enabling autofix behavior based on the safety of the patch.\nIn the meantime, if you find that the autofix is too aggressive, you can disable it on a per-rule or\nper-category basis using the unfixable mechanic.\nFor example, to disable autofix for some possibly-unsafe rules, you could add the following to your\npyproject.toml:\n[tool.ruff]\nunfixable = ["B", "SIM", "TRY", "RUF"]\n\nIf you find a case where Ruff\'s autofix breaks your code, please file an Issue!\nHow can I disable Ruff\'s color output?#\nRuff\'s color output is powered by the colored crate, which\nattempts to automatically detect whether the output stream supports color. However, you can force\ncolors off by setting the NO_COLOR environment variable to any value (e.g., NO_COLOR=1).\ncolored also supports the the CLICOLOR and CLICOLOR_FORCE\nenvironment variables (see the spec).\n\n\n\n\n\nBack to top\n\n\n\n\n\n\nMade with\n\nMaterial for MkDocs\n\n\n\n\n\n\n\n\n\n\n\n\n', metadata={'source': 'https://beta.ruff.rs/docs/faq/'})]

**Comment by Ilikepizza2** [comment]
Hey did you find any solutions?

**Comment by moshekarmel1** [comment]
@nazkhan-8451 & @Ilikepizza2 an easier option would be to just use the `SitemapLoader` based on the `sitemap.xml` file. For your example it seems to be available here : https://beta.ruff.rs/docs/sitemap.xml . The code would look like this 
```python
from langchain.document_loaders.sitemap import SitemapLoader
...
loader = SitemapLoader(web_path="https://beta.ruff.rs/docs/sitemap.xml")
data = loader.load()
...
```
More info here : https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/sitemap.html

**Comment by jalcantarab** [comment]
You can set up your own loop, finding all links and if both robots.txt and your own rules allow you to follow, do. Here is a little example:

```py
def bootstrap_docs_build_urls():
    root_url = "https://getbootstrap.com/docs/5.3/getting-started/contents/"
    root_response = requests.get(root_url)
    root_html = root_response.content.decode("utf-8")
    soup = BeautifulSoup(root_html, 'html.parser')

    root_url_parts = urlparse(root_url)
    root_links = soup.find_all("a", attrs={"class": "bd-links-link d-inline-block rounded"}) // Here I'm looking for all the links in the content section

    result = set()
    for root_link in root_links:
        path = root_link.get("href")
        path = str(Path(path).resolve())
        path = urlparse(path).path  # remove the hashtag

        url = f"{root_url_parts.scheme}://{root_url_parts.netloc}{path}"

        if not url.endswith("/"):
            url = url + "/"

        result.add(url)
    return list(result)
```
