### ISSUE TITLE
Permission Error with PDF loader

### ISSUE THREAD

**Issue by realglyph123** [hwchase17/langchain#2698]
I was testing OnlinePDFLoader yesterday iirc and it was working fine. Today I tried experimenting and I keep getting this error

`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\REALGL~1\\AppData\\Local\\Temp\\tmp3chr08y0`

it may be occurring because the `tempfile.NamedTemporaryFile()` in `pdf.py` is still open when the PDF partitioning function is trying to access it

**Comment by tmtsmrsl** [comment]
I have the same problem when running PDF loader of local environment (no problem when running on Colab). Do you have any solution yet?

**Comment by realglyph123** [comment]
> I have the same problem when running PDF loader of local environment (no problem when running on Colab). Do you have any solution yet?

Go to the pdf.py and replace the function using the code below located on the `BasePDFLoader`. I am on the `.137` version of langchain.

```python
    file_path: str
    web_path: Optional[str] = None
    temp_file: Optional[tempfile.NamedTemporaryFile] = None

    def __init__(self, file_path: str):
        """Initialize with file path."""
        self.file_path = file_path
        if "~" in self.file_path:
            self.file_path = os.path.expanduser(self.file_path)

        if not os.path.isfile(self.file_path) and self._is_valid_url(self.file_path):
            r = requests.get(self.file_path)

            if r.status_code != 200:
                raise ValueError(
                    "Check the url of your file; returned status code %s"
                    % r.status_code
                )

            self.web_path = self.file_path
            self.temp_file = tempfile.NamedTemporaryFile(delete=False)
            self.temp_file.write(r.content)
            self.temp_file.close()
            self.file_path = self.temp_file.name
        elif not os.path.isfile(self.file_path):
            raise ValueError("File path %s is not a valid file or url" % self.file_path)

    def __del__(self) -> None:
        if self.temp_file is not None:
            self.temp_file.close()
            os.unlink(self.temp_file.name)
```

**Comment by nickmuchi87** [comment]
facing the same error for a while as well

**Comment by luca-git** [comment]
I still have this issue with 0.0.1.81 windows 11 bitdefender AV

**Comment by smharvey** [comment]
> > I have the same problem when running PDF loader of local environment (no problem when running on Colab). Do you have any solution yet?
> 
> Go to the pdf.py and replace the function using the code below located on the `BasePDFLoader` class. Note that my current version of langchain is `.137`
> 
> ```python
>     file_path: str
>     web_path: Optional[str] = None
>     temp_file: Optional[tempfile.NamedTemporaryFile] = None
> 
>     def __init__(self, file_path: str):
>         """Initialize with file path."""
>         self.file_path = file_path
>         if "~" in self.file_path:
>             self.file_path = os.path.expanduser(self.file_path)
> 
>         if not os.path.isfile(self.file_path) and self._is_valid_url(self.file_path):
>             r = requests.get(self.file_path)
> 
>             if r.status_code != 200:
>                 raise ValueError(
>                     "Check the url of your file; returned status code %s"
>                     % r.status_code
>                 )
> 
>             self.web_path = self.file_path
>             self.temp_file = tempfile.NamedTemporaryFile(delete=False)
>             self.temp_file.write(r.content)
>             self.temp_file.close()
>             self.file_path = self.temp_file.name
>         elif not os.path.isfile(self.file_path):
>             raise ValueError("File path %s is not a valid file or url" % self.file_path)
> 
>     def __del__(self) -> None:
>         if self.temp_file is not None:
>             self.temp_file.close()
>             os.unlink(self.temp_file.name)
> ```

**Comment by smharvey** [comment]
@realglyph123 Your fix worked for running on my local windows system. Thank you.

**Comment by M9S9D** [comment]
i want save my histogram with this code :
big_data=random.uniform(0.0,10.0,10000)
# print(big_data)
import matplotlib.pyplot as plt
plt.hist(big_data,500)
plt.savefig("big_data.pdf", format='pdf')
but i have this error : 
PermissionError: [Errno 13] Permission denied: 'big_data.pdf'
what should i do ?
