### ISSUE TITLE
question_answering chains answers cut off

### ISSUE THREAD

**Issue by MinhNguyen99AI** [hwchase17/langchain#2703]
Hi, I'm having some trouble finding the solution to this. 
I'm using Langchain on Colab, and for some reasons, the answers sometimes get cut off like below (screenshot attached)
I have 2 questions, and both are cut off, as you can see. 
I tried changing 'max_len_answer' but nothing changes
![image](https://user-images.githubusercontent.com/48023706/231097184-dc155701-25cd-4f27-8623-b6355be7646f.png)
Do you guys have any suggesting for this?
Thank you.

**Comment by dheerajiiitv** [comment]
@MinhNguyen99AI Try adding `max_tokens` in `OpenAI(..., max_tokens=1024)`
And this should solve your issue
