### ISSUE TITLE
Cannot import RetrievalQA from langchain.chains

### ISSUE THREAD

**Issue by Majidbadal** [hwchase17/langchain#2725]
Python version: 3.9.16
Langchain version: 0.0.109

The code:
```
from langchain.chains import RetrievalQA
from langchain.llms import OpenAI
```

the error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[123], line 1
----> 1 from langchain.chains import RetrievalQA
      2 from langchain.llms import OpenAI

ImportError: cannot import name 'RetrievalQA' from 'langchain.chains' (/opt/conda/envs/python39/lib/python3.9/site-packages/langchain/chains/__init__.py)
```

**Comment by joshsny** [comment]
Try updating your `langchain` version to the latest version, currently `0.0.137`

**Comment by dotandpixel** [comment]
Python version: 3.9.16
Langchain version: 0.0.137

`Traceback (most recent call last):
  File "/Users/andrewpeel/.pyenv/versions/3.11.3/envs/vikings/privateGPT/privateGPT.py", line 3, in <module>
    from langchain.chains import RetrievalQA
ImportError: cannot import name 'RetrievalQA' from 'langchain.chains' (/Users/andrewpeel/.pyenv/versions/vikings/lib/python3.11/site-packages/langchain/chains/__init__.py)`

**Comment by Jonyzqw** [comment]
> Python version: 3.11.3 Langchain version: 0.0.190
> 
> ```
> Traceback (most recent call last):
> 
>   File "/Users/user/.pyenv/versions/3.11.3/envs/vikings/privateGPT/privateGPT.py", line 3, in <module>
>     from langchain.chains import RetrievalQA
>     
> ImportError: cannot import name 'RetrievalQA' from 'langchain.chains' (/Users/user/.pyenv/versions/vikings/lib/python3.11/site-packages/langchain/chains/__init__.py)
> ```

解决了嘛，我也遇到同样的问题

**Comment by kikiWhite** [comment]
Same issue:
ImportError: cannot import name 'RetrievalQA' from 'langchain.chains' (/Users/xxxx/python3.7/site-packages/langchain/chains/__init__.py)

both langchain version 0.0.20 and 0.0.27 not work

**Comment by NarayananParthasarathy** [comment]
Getting an error  on "from langchain.chains import RetrievalQA"; error message is cannot import name 'NeptuneRdfGraph' from 'langchain_community.graphs' .  using langcain version 0.1.7

**Comment by Yogesh0801** [comment]
ImportError: cannot import name 'TypeBaseModel' from 'langchain_core.utils.pydantic' (C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain_core\utils\pydantic.py)

**Comment by shivarajkarki** [comment]
from langchain.chains.qa_with_sources.retrieval import RetrievalQAWithSourcesChain

**Comment by aliraza108** [comment]
Got same error on latest version

**Comment by aliraza108** [comment]
> from langchain.chains.qa_with_sources.retrieval import RetrievalQAWithSourcesChain

this works

**Comment by Buvaneshkumaar** [comment]
**importation:**

from langchain.chains.qa_with_sources.retrieval import RetrievalQAWithSourcesChain

**still facing the error from langchain package:**

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[23], [line 1](vscode-notebook-cell:?execution_count=23&line=1)
----> [1](vscode-notebook-cell:?execution_count=23&line=1) from langchain.chains.qa_with_sources.retrieval import RetrievalQAWithSourcesChain

ModuleNotFoundError: No module named 'langchain.chains'

**langchain version:**

Name: langchain
Version: 1.0.2

**Comment by rituuu** [comment]
Getting this error in the latest version of lanchain. If anyone knows how to resolve this issue please help: 
from langchain.chains.retrieval_qa.base import RetrievalQA
ModuleNotFoundError: No module named 'langchain.chains'

**Comment by ritik7jain** [comment]
ModuleNotFoundError: No module named 'langchain.chains'
this is not resoved with lastest verison too

**Comment by Fevzierenn** [comment]
Still same problem.

**Comment by qudsiramiz** [comment]
> Still same problem.

If you are still having issue, try this:
`from langchain_classic.chains.retrieval_qa.base import RetrievalQA`

This works for `langchain_classic.__version__ == 1.0.1` and `langchain.__version__ == 1.2.8`

**Comment by norm-gd** [comment]
try this library **`langchain-classic`**

```from langchain_classic.chains.qa_with_sources.retrieval import RetrievalQAWithSourcesChain```
