### ISSUE TITLE
How to load codes from file ,such like .py .java .cpp .js?

### ISSUE THREAD

**Issue by Minweiwangaaaa** [hwchase17/langchain#2749]
How to load codes from file ,such like .py .java .cpp .js?
And  how to embedding them to vectors?

**Comment by cnhhoang850** [comment]
You can use the unstructured file loader to load your text file and then split along class definition. Currently, there is only a python splitter in the python langchain text splitter. 

```
from langchain.document_loaders import UnstructuredFileLoader
from langchain.text_splitter import PythonCodeTextSplitter

loader = UnstructuredFileLoader("./example_data/state_of_the_union.txt")

docs = loader.load()

python_splitter = PythonCodeTextSplitter(chunk_size=30, chunk_overlap=0)
python_code = python_splitter.create_documents([docs])
```

**Comment by Minweiwangaaaa** [comment]
> 

Thank you for your professional response
