### ISSUE TITLE
QAGenerationChain is missing when langchain is pip installed

### ISSUE THREAD

**Issue by dallonasnes** [hwchase17/langchain#2771]
[Docs](https://python.langchain.com/en/latest/use_cases/evaluation/qa_generation.html) show a QAGenerationChain but that is not exposed via pip install.

**Comment by joshsny** [comment]
What `langchain` and `python` version are you using?

**Comment by dallonasnes** [comment]
ah looks like i was using an old langchain, just updated and it seems to work now. closing this. thanks!
