### ISSUE TITLE
ConversationChain with stream responses

### ISSUE THREAD

**Issue by LawlightXY** [hwchase17/langchain#2785]
i had see the example llm with streaming output:

from langchain.callbacks.base import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
chat = ChatOpenAI(streaming=True, callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]), verbose=True, temperature=0)
resp = chat([HumanMessage(content="Write me a song about sparkling water.")])

but how can i use ConversationChain with stream responses?

**Comment by jianhuihi** [comment]
how can i use ConversationChain with stream responses?

**Comment by MariuszT** [comment]
@LawlightXY Did you find a way to do this?

**Comment by PradHolla** [comment]
@LawlightXY did you achieve this? If so, can you elaborate?
