### ISSUE TITLE
Add support for memory flushing

### ISSUE THREAD

**Issue by andrewgleave** [hwchase17/langchain#285]
It would be useful in certain circumstances to be able to manually flush the memory buffer of an agent. There's no defined interface for doing it at present (though it can be accomplished by holding on to a buffer and clearing it directly).

Possibly something like and have define a `flush()` method on the `Memory` abstract class:

```
memory = ConversationBufferMemory(memory_key="chat_history")
llm_chain = LLMChain(llm=OpenAI(temperature=0), prompt=prompt, memory=memory)
agent = ZeroShotAgent(llm_chain=llm_chain, tools=tools, verbose=True)
agent.run("....")
...
agent.flush()  # calls Memory.flush()
```

Thoughts?

**Comment by hwchase17** [comment]
Love it, this is a great idea

**Comment by andrewgleave** [comment]
Ok, I'll see what I can do.

**Comment by hwchase17** [comment]
> I was able to set memory.buffer = [] (for the list based ones) and it worked. I guess a "clear()" method with specializations will work better.

yeah - i agree a clear() method would be nice for abstracting out the fact that the buffer is string/list. all for it

**Comment by hwchase17** [comment]
> > I was able to set memory.buffer = [] (for the list based ones) and it worked. I guess a "clear()" method with specializations will work better.
> 
> yeah - i agree a clear() method would be nice for abstracting out the fact that the buffer is string/list. all for it

and sounds like based on this it shouldn't be that bad which is nice!

**Comment by andrewgleave** [comment]
I'll do this in the next couple of days

**Comment by hwchase17** [comment]
your implementation looks pretty good to me, @andrewgleave were you imagining anything different?

**Comment by andrewgleave** [comment]
Nope. Functionally equivalent so given this has a test case, happy for this to be merged. 👍

**Comment by hwchase17** [comment]
closed in https://github.com/hwchase17/langchain/pull/305
