### ISSUE TITLE
Implement from_documents class method in weaviate VectorStore

### ISSUE THREAD

**Issue by hsm207** [hwchase17/langchain#2855]
We should implement all abstract methods in VectorStore so that users can use weaviate as the vector store for any use case.

Context:

https://github.com/hwchase17/langchain/blob/763f87953686a69897d1f4d2260388b88eb8d670/langchain/vectorstores/base.py#L104-L113

**Comment by Pouyanpi** [comment]
Hi @hsm207 ,

I think It doesn't need to be overridden by the parent. It only calls the `from_texts` method which is already implemented. The `page_content` and `metadata` are allready `Document` attributes. It is the case for all other vectorstores (e.g., faiss, milvus, etc.). Is it possible for you to test it and let me know?

Best,
Pouyan

**Comment by hsm207** [comment]
> Not sure what the best way of differentiating kwargs passed here is, maybe doing some popping from the kwargs so they don't get passed downstream once the client is created.

I suggest creating a dataclass and call it something like `WeaviateConfig` that contains the possible configs for the weaviiate client instead of relyingon kwargs. This way, it helps with type checking and intellisense.

**Comment by cs0lar** [comment]
@diego-escobedo  @hsm207 the weaviate client repo has just merged a [config dataclass PR](https://github.com/weaviate/weaviate-python-client/pull/302) which I am happy to add support for here if there are no objections.

**Comment by hsm207** [comment]
@cs0lar in my opinion, let's wait until that feature makes it to weaviate's official [docs](https://weaviate.io/developers/weaviate/client-libraries/python) to give time for the developers to finalise the interface.

**Comment by cs0lar** [comment]
@hsm207 agreed!

**Comment by hsm207** [comment]
@Pouyanpi 
> It is the case for all other vectorstores (e.g., faiss, milvus, etc.). Is it possible for you to test it and let me know?

[chroma](https://github.com/hwchase17/langchain/blob/b6e3ac17c419acb246e08bf9cd46f3ee0cf2909d/langchain/vectorstores/chroma.py#L385-L395), [pgvector](https://github.com/hwchase17/langchain/blob/b6e3ac17c419acb246e08bf9cd46f3ee0cf2909d/langchain/vectorstores/pgvector.py#L402-L411) and [tair](https://github.com/hwchase17/langchain/blob/b6e3ac17c419acb246e08bf9cd46f3ee0cf2909d/langchain/vectorstores/tair.py#L208-L216) to implement their own `from_documents` method.
Do you know why this is needed?

**Comment by hsm207** [comment]
can confirm that from_documents works fine now.

**Comment by hsm207** [comment]
from the stack trace, it looks like you have some issue with your machine's ssl config

**Comment by hsm207** [comment]
whoa, that is strange

**Comment by Idk507** [comment]
# Connect to Weaviate Cloud
client = weaviate.connect_to_weaviate_cloud(
    cluster_url= WEAVIATE_URL,
    auth_credentials=Auth.api_key(WEAVIATE_API_KEY),
)

print(client.is_ready())

db = WeaviateVectorStore.from_documents(docs, embeddings, client=client, index_name="LangChain")
