### ISSUE TITLE
GCP Matching Engine as Vector Store

### ISSUE THREAD

**Issue by tomaspiaggio** [hwchase17/langchain#2892]
We're working on an implementation for a vector store using the GCP Matching Engine.

We'll be contributing the implementation.

If you have any questions or suggestions please contact me (@tomaspiaggio) or @scafati98.

**Comment by olaf-hoops** [comment]
> We're working on an implementation for a vector store using the GCP Matching Engine.
> 
> We'll be contributing the implementation.
> 
> If you have any questions or suggestions please contact me (@tomaspiaggio) or @scafati98.

Lmk if you need someone to test this. I’m currently running a little app in Google Cloud which is using Pinecone as a vector store

**Comment by tomaspiaggio** [comment]
@olaf-hoops we might need peer reviews if you are available.

**Comment by tomaspiaggio** [comment]
Closing due to open pull request #3104

**Comment by nacartwright** [comment]
Are there any updates to this...?

**Comment by ojengwa** [comment]
@tomaspiaggio and @scafati98 Any progress on this? We have our stack on GCP and this furthers our cross-integrations.
