### ISSUE TITLE
OpenSearch: allow boolean filter search for ANN

### ISSUE THREAD

**Issue by duffn** [hwchase17/langchain#2924]
The OpenSearch documentation notes that you may use a boolean filter for ANN search: https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/#boolean-filter-with-ann-search

It would be nice to allow passing in a boolean filter to the OpenSearch vector store `similarity_search` function.

**Comment by naveentatikonda** [comment]
@duffn Thank you for creating this github issue. Will add support for passing a boolean filter to `similarity_search` function.
