### ISSUE TITLE
Will it support Dolly-V2?

### ISSUE THREAD

**Issue by stevexuzeta** [hwchase17/langchain#2928]
I hope that langchain can support dolly-v2 which is generated by Databricks employees and released under a permissive license (CC-BY-SA).

**Comment by DanqingZ** [comment]
It's already supported since dolly is on huggingface hub: https://huggingface.co/databricks/dolly-v2-3b
You simply need to define some local llm and pass it to the question answering chain.
```
from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig, pipeline
from langchain.llms import HuggingFacePipeline

from transformers import AutoModelForCausalLM, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("databricks/dolly-v2-3b", padding_side="left")
base_model = AutoModelForCausalLM.from_pretrained("databricks/dolly-v2-3b", device_map="auto")

pipe = pipeline(
    "text-generation",
    model=base_model,
    tokenizer=tokenizer,
    max_length=1024,
    temperature=0.6,
    pad_token_id=tokenizer.eos_token_id,
    top_p=0.95,
    repetition_penalty=1.2
)
local_llm = HuggingFacePipeline(pipeline=pipe)

from langchain.chains import RetrievalQA
qa = RetrievalQA.from_chain_type(llm=local_llm, chain_type="stuff", retriever=retriever)
```

**Comment by stevexuzeta** [comment]
@DanqingZ  Thank you very much, I tried and it worked.

**Comment by msinha251** [comment]
Hello all, Do we have any possibility to use an inference service (like an url) instead of loading model and then use llm.

**Comment by VedAustin** [comment]
> It's already supported since dolly is on huggingface hub: https://huggingface.co/databricks/dolly-v2-3b You simply need to define some local llm and pass it to the question answering chain.
> 
> ```
> from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig, pipeline
> from langchain.llms import HuggingFacePipeline
> 
> from transformers import AutoModelForCausalLM, AutoTokenizer
> tokenizer = AutoTokenizer.from_pretrained("databricks/dolly-v2-3b", padding_side="left")
> base_model = AutoModelForCausalLM.from_pretrained("databricks/dolly-v2-3b", device_map="auto")
> 
> pipe = pipeline(
>     "text-generation",
>     model=base_model,
>     tokenizer=tokenizer,
>     max_length=1024,
>     temperature=0.6,
>     pad_token_id=tokenizer.eos_token_id,
>     top_p=0.95,
>     repetition_penalty=1.2
> )
> local_llm = HuggingFacePipeline(pipeline=pipe)
> 
> from langchain.chains import RetrievalQA
> qa = RetrievalQA.from_chain_type(llm=local_llm, chain_type="stuff", retriever=retriever)
> ```

How can I pass my own set of documents?
