### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.agents'

### ISSUE THREAD

**Issue by ndelah** [hwchase17/langchain#2935]
Just installed Lanchain and followed the tutorials without a problem till I reached the agents part.

The following modules are not recognized.

```
from langchain.agents import initialize_agent
from langchain.agents import AgentType
```

I tried running lanchain in python 3.7, 3.8.11, 3.9 and 3.10 because other people suggested changing versions.

**Comment by AMK9978** [comment]
As you can see in the `agents/__init__.py`, there is no AgentType to be imported. Maybe you just need to adapt your tutorials to the current version of LangChain. Otherwise, you can search for the matched version of LangChain at the time of your tutorial.

**Comment by ndelah** [comment]
Switched to python 3.9 version 0.0.135 which seems to have fixed the issue.
