### ISSUE TITLE
Vector Store Creator from Figma loader throws an error

### ISSUE THREAD

**Issue by Bouhoum** [hwchase17/langchain#2996]
Hello everyone! I am new to using langchain and I am currently facing an issue with the figma loader. I have followed the steps outlined in the documentation, but I am receiving a TypeError with the following message:

`TypeError: expected string or bytes-like object`

The error occurs when I try to create a vector store index using the code `index = VectorstoreIndexCreator().from_loaders([figma_loader])`. I have been stuck on this for a while and would really appreciate any help that I can get.

`----> 2 index = VectorstoreIndexCreator().from_loaders([figma_loader])
      3 figma_doc_retriever = index.vectorstore.as_retriever()

11 frames
[/usr/lib/python3.9/http/client.py](https://localhost:8080/#) in putheader(self, header, *values)
   1260                 values[i] = str(one_value).encode('ascii')
   1261 
-> 1262             if _is_illegal_header_value(values[i]):
   1263                 raise ValueError('Invalid header value %r' % (values[i],))
   1264 

TypeError: expected string or bytes-like object`

I have already checked the repository's issue tracker but haven't found any solutions that address my specific problem. I have also provided relevant code snippets and steps I have taken so far.

Thank you in advance for your help! I am looking forward to hearing from you soon.

**Comment by mdyu1000** [comment]
How do you fix this?

**Comment by nbobbili-amazon** [comment]
Whats the fix for this issue?
