### ISSUE TITLE
Limit the db.similarity_search("some question", k=4) output.

### ISSUE THREAD

**Issue by VladoPortos** [hwchase17/langchain#3029]
I have generated the Chroma DB from a single file ( basically lots of questions and answers in one text file ), sometimes when I do 

```
db.similarity_search("some question", k=4)
```
And the question is too broad, it will rerun a **LOT** of results, since I'm using the result in next LLM query (prompt template) I often can hit the "maximum context length is 4097 tokens" how to deal with this ?

**Comment by anh** [comment]
when using vector store as retriever you can pass in search_kwargs some thing like this: 

```python 
retriever=vectorstore.as_retriever(search_kwargs={"k": 2})
```

**Comment by VladoPortos** [comment]
Hello @anh well, the behavior is kind of strange... mind you I'm playing with it just 3rd day :D  but my input is single txt file that have lots of info... 
I have split it with chunk_size=1100 and loaded to Chroma DB, stored to drive... other app is loading this DB.

This is the function to retrieve the data:

```python
def query_chromadb():
    client_settings = chromadb.config.Settings(
        chroma_db_impl="duckdb+parquet",
        persist_directory=DB_DIR,
        anonymized_telemetry=False
    )

    embeddings = OpenAIEmbeddings()

    vectorstore = Chroma(
        collection_name="langchain_store",
        embedding_function=embeddings,
        client_settings=client_settings,
        persist_directory=DB_DIR,
    )
    retun vectorstore.similarity_search(query=query, k=4)
```

What I noticed is that using k=2 will return a list. This list has two elements, both the same. So I changed it to k=1 this return just one element. But sometimes this element result[0].page_content is big, like 5000 tokens. 

What I do now, I simply cut it at 3500 which is kind of dumb approach.  

Maybe the query to Chroma is too broad, and it returns a lot of "relevant" data ?  Can't really pinpoint why sometimes it returns really nice relevant data and just few of them, and sometimes it looks like half of the original document is returned....

**Comment by anh** [comment]
I got it :), then you may take a look at `TextSplitters` with overlap option, I am using PGVector and my docs aren't that big.

https://python.langchain.com/en/latest/modules/indexes/text_splitters/getting_started.html

**Comment by VladoPortos** [comment]
Thanks ! @anh 
I understand what was wrong now... my input data were "formatted" wrongly... they were basically huge json:

```json
[
{ something, something something}
{something something something}
]

And I used split to chunks based on 1100 characters, so no wonder it returned the whole "file" where was the answer, but it was that huge 1100 chunk... 

Using the RecursiveCharacterTextSplitter and adding new line between the {something something} nicely split all the data and now returning much more precise and smaller chunks ! Love you man ! I was so confused why it is doing it....
