### ISSUE TITLE
OpenAI llm rounds frequency & presence penalties to ints

### ISSUE THREAD

**Issue by bvanslyke** [hwchase17/langchain#310]
In the OpenAI llm model, frequency_penalty and presence_penalty are annotated as ints when they should allow decimals between 0.0 and 2.0 inclusive.

**Comment by bvanslyke** [comment]
I can PR this myself later (& and add more details here since I’m phone-posting now), but just wanted to lay down an issue first.

**Comment by hwchase17** [comment]
thanks for posting - i think should be fixed on master (as of yesterday) actually! https://github.com/hwchase17/langchain/commit/7827f0a844f28453b2af4146984450b21c23e914

**Comment by bvanslyke** [comment]
Oh, awesome!
