### ISSUE TITLE
FAISS similarity search issue 

### ISSUE THREAD

**Issue by larry-fuy** [hwchase17/langchain#3147]
Recently I got a strange error when using FAISS `similarity_search_with_score_by_vector`.  The line (https://github.com/hwchase17/langchain/blob/575b717d108984676e25afd0910ccccfdaf9693d/langchain/vectorstores/faiss.py#L170) generates errors: 
```
 TypeError: IndexFlat.search() missing 3 required positional arguments: 'k', 'distances', and 'labels'
```
It looks like FAISS own `search` function has different arguments (using `IndexFlat`)
```
search(self, n, x, k, distances, labels)
```
But `similarity_search_with_score_by_vector` worked one day ago. So is there any hints for this?

**Comment by AmanSal1** [comment]
can you please give a small code to reproduce the error?

**Comment by AmanSal1** [comment]
@larry-fuy Basically FAISS has the same keyword and lang-chain also has the same then there is a mismatch right?

**Comment by kylaro** [comment]
Hey, just for posterity, I have the same issue. 

I am pickling the object returned from FAISS text splitting, and unpickling in my container image.
```
def create_db_from_text_file(file_path):
    loader = TextLoader(file_path, encoding='utf8')
    transcript = loader.load()
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=3950, chunk_overlap=300)
    docs = text_splitter.split_documents(transcript)

    db = FAISS.from_documents(docs, embeddings)
    return db  # This is what gets pickled
```

And I get the exact same error as above when I call:
```
docs = db.similarity_search(query, k=k)
```

The strange part is, the container image works on my local machine, but it doesn't work on Google Cloud Run.

I'll update if I fix it...

**Comment by cho4** [comment]
> Hey, just for posterity, I have the same issue.
> 
> I am pickling the object returned from FAISS text splitting, and unpickling in my container image.
> 
> ```
> def create_db_from_text_file(file_path):
>     loader = TextLoader(file_path, encoding='utf8')
>     transcript = loader.load()
>     text_splitter = RecursiveCharacterTextSplitter(chunk_size=3950, chunk_overlap=300)
>     docs = text_splitter.split_documents(transcript)
> 
>     db = FAISS.from_documents(docs, embeddings)
>     return db  # This is what gets pickled
> ```
> 
> And I get the exact same error as above when I call:
> 
> ```
> docs = db.similarity_search(query, k=k)
> ```
> 
> The strange part is, the container image works on my local machine, but it doesn't work on Google Cloud Run.
> 
> I'll update if I fix it...

Any luck?

**Comment by imldy** [comment]
I have two environments on Windows, one is normal (Python3.8.*), and the other reports this problem (anaconda Python3.11.*). The code remains the same, but changing the Python interpreter to the normal one allows it to run. Later, I will post the detailed differences in the environments.

Chinese original text：
我在Windows上有两套环境，一个正常（Python3.8.*），另一个报错这个问题（anaconda Python3.11.*），代码不变，Python解释器换成正常的就可以运行。
稍后我会贴出详细的环境区别。

**Comment by zubair-ahmed-ai** [comment]
I had to recreate my index on the cloud and it magically works now, no change in Faiss lib versions

**Comment by gpy1234** [comment]
@kylaro Any luck?

**Comment by kylaro** [comment]
I ended up using Pinecone instead of FAISS, sorry no luck with it. Pinecone has a similarity search via their API, so it is not done in the container.
