### ISSUE TITLE
does merging index1.merge_from(index2) dump index2?

### ISSUE THREAD

**Issue by qaiwiz** [hwchase17/langchain#3152]
I tried to merge two FAISS indices: 

index1 = FAISS.from_documents(doc1, embeddings)
index2=FAISS.from_documents(doc2, embeddings)

after I do index1.merge_from(index2), and then do 
ret = index2.as_retriever()
ret.get_relevant_documents(query)
it returns and empty list [].  

If index1 is saved_local, can I add index2 without loading index1 to memory, perhaps called merge_local? (open index.faiss and index.pkl and write line by line)

**Comment by ehsanmok** [comment]
This is how it is [implemented](https://github.com/facebookresearch/faiss/blob/d87888b13e7eb339bb9c45825e9d20def6665171/faiss/Index.h#L274) in faiss i.e. to move to index1 for memory efficiency. If you need index2, you can `copy.deepcopy(index2)`.

**Comment by qaiwiz** [comment]
Thanks. I doubled checked after posting, I think it should be noted in the documentation after merging the index is consumed, copy or make a local saved copy.
