### ISSUE TITLE
VectorStoreRetrieverMemory Not Available In Langchain.memory

### ISSUE THREAD

**Issue by aaudet** [hwchase17/langchain#3175]
The following link describes the VectorStoreRetrieverMemory class, which would be extremely useful for referencing an external vector DB & it's text/vectors:

https://python.langchain.com/en/latest/modules/memory/types/vectorstore_retriever_memory.html#create-your-the-vectorstoreretrievermemory) 

However, I'm following the documentation in the following link, and used the import copied from the documentation: 

`from langchain.memory import VectorStoreRetrieverMemory`

Here's the error that I'm receiving: 

ImportError: cannot import name 'VectorStoreRetrieverMemory' from 'langchain.memory' (D:\Anaconda_3\lib\site-packages\langchain\memory\__init__.py)

I've updated langchain as a dependency, and the issue is persisting. Is there a workaround or an issue with langchain? This is also my first github issue, so please let me know if more information is needed.

**Comment by outday29** [comment]
Hello!
I am able to import `VectorStoreRetrieverMemory` using langchain v0.0.144, can you check your langchain version and make sure that it is of latest version?

```python
import langchain
print(langchain.__version__)
```

**Comment by aaudet** [comment]
Ah, it turns out that my langchain version is '0.0.137'. That must be the issue. I'll update langchain to make sure that's the solution. Thanks!
