### ISSUE TITLE
Support for streaming when using LLMchain? 

### ISSUE THREAD

**Issue by KeshavSingh29** [hwchase17/langchain#3263]
I understand that streaming is now supported with chat models like `ChatOpenAI` with `callback_manager` and `streaming=True`. 

**But I cant seem to get streaming work if using it along with chaining.** 

Here is the code for better explanation: 
```python
# Defining model 
LLM = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0.1, openai_api_key=OPENAI_KEY, streaming=True, callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]))

# Defining ground truth prompt (hidden)

# Create chain
ground_truth_chain = LLMChain(llm=LLM, prompt=ground_truth_prompt, verbose=True)

# Get response    
ground_truth_chain.run(context_0=context[0], context_1=context[1], query_language=user_language, question=user_query)
```
Streaming doesnt work in this case!
Any help would be appreciated.

**Comment by KeshavSingh29** [comment]
Just had to add `verbose=True` to the following line
```python
LLM = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0.1, openai_api_key=OPENAI_KEY, streaming=True, callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]))
```

**Comment by KeshavSingh29** [comment]
@tylermaran Yes, it possible. 
Set `verbose=False` where you define you instantiate your LLMchain. 

``` python
# Create chain
# this will only stream response not the thought process
ground_truth_chain = LLMChain(llm=LLM, prompt=ground_truth_prompt, verbose=False) 
```

Note: When you define your model, you need to set verbose=True. 

The way it works is that when you define model like:
```python 
LLM = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0.1, openai_api_key=OPENAI_KEY, streaming=True, callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]))
``` 
Here, the streaming=true is for openAI to stream response. 
However, when you define your LLMChain, its langchain thought process (which we can set to verbose=False).

**Comment by hinthornw** [comment]
cc @eyurtsev

**Comment by baskaryan** [comment]
Updated recommendation to do this is with LCEL: https://python.langchain.com/docs/expression_language/streaming#chains
