### ISSUE TITLE
How to override prompt for JSON Agent

### ISSUE THREAD

**Issue by sid8491** [hwchase17/langchain#3293]
How can I override the prompt used in JSON Agent (https://github.com/hwchase17/langchain/blob/master/langchain/agents/agent_toolkits/json/prompt.py)

Also, how can I print/log what information/text is being sent on every execution?

**Comment by account00001** [comment]
When you call `create_json_agent()` there are parameters you can pass in for the prefix and suffix.

```python
my_prefix = "prefix here"
my_suffix = "suffix here"

def create_json_agent(
    llm=llm,
    prefix=my_prefix,
    suffix=my_suffix,
    verbose=True # verbose will print more detailed output
)
```

There are also verbosity settings you can set on your model, including different options for different chain types.
