### ISSUE TITLE
Tools with structured inputs are broken with new input parser logic when using REACT agents

### ISSUE THREAD

**Issue by danielchalef** [hwchase17/langchain#3299]
Upgrading to a recent langchain version with the new Tool input parsing logic, Tools with json structured inputs are now broken when using a REACT-like agent. Demonstrating below with a custom tool and the `CHAT_CONVERSATIONAL_REACT_DESCRIPTION` agent.

It appears the json input is no longer being passed as a string.

langchain 0.0.145

error:
```  File "/Users/danielchalef/dev/nimble/backend/.venv/lib/python3.11/site-packages/langchain/tools/base.py", line 104, in run
    observation = self._run(*tool_args, **tool_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SendMessageTool._run() got an unexpected keyword argument 'email'
```

```python
class SendMessageTool(BaseTool):
    name = "send_message_tool"
    description = (
        """useful for when you need to send a message to a human.
Format your input using the following template. 
{{
  "action": "get_days_elapsed",
  "action_input": {{"email": "<email_address>", "message": "<message>"}}
}}"""
    )

    def _run(self, query: str) -> str:
        """Use the tool."""

        # My custom validation logic would go here.

        return f"Sent {query}"

    async def _arun(self, query: str) -> str:
        """Use the tool asynchronously."""

        # My custom validation logic would go here.

        return f"Sent {query}"

agent_executor = initialize_agent(
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    llm=llm,
    tools=tools,
    memory=memory,
    callback_manager=cm,
)

result = agent_executor.run(
    {
        "input": "Message Mary to tell her lunch is ready."
    }
)
```

**Comment by vowelparrot** [comment]
Thanks for your patience on this backwards breaking change.  The immediate solution for this be to update `_run()` to reflect the schema you've presented.

```python
def _run(self, email: str, action_input: dict) -> str:
...
```

The intention of this change was to better support proper function typing rather than forcing users to deserialize the output.

I'll try to draft an approach that handles both cases

**Comment by danielchalef** [comment]
Thanks, Zander. The following works for me i.e. verbatim match to the `action_input` schema:

```
def _run(self, email: str, message: str) -> str:
```

It looks like BaseTool's `_run` and `_arun` signature needs to be updated to support the above.

I'm happy that y'all have moved to stronger function typing on tool inputs and that I can drop my own deserialization and validation code.
