### ISSUE TITLE
HNSWLib-node not found when using in a AWS Lambda function

### ISSUE THREAD

**Issue by joaotextor** [hwchase17/langchain#3304]
I recently made a simple Typescript function to create a VectorStore using HNSWLib-node.
It saves the vector store in a folder and then, in another script file, I load and execute a RetrievalQAChain using OpenAI.

Everything was working fine until I decided to put that in a AWS Lambda Function.

My package.json has the following dependencies:
```
    "hnswlib-node": "^1.4.2",
    "langchain": "^0.0.59",

```
Also, I double checked and the hnswlib-node folder is inside "node_modules" folder in my lambda function folder.

However, I keep getting the following error (from CloudWatch Logs):
```
ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Please install hnswlib-node as a dependency with,
 e.g. `npm install -S hnswlib-node`",
    "stack":["Error: Please install hnswlib-node as a dependency with, e.g. `npm install -S hnswlib-node`","    
    at Function.imports (/var/task/node_modules/langchain/dist/vectorstores/hnswlib.cjs:161:19)","
    at async Function.getHierarchicalNSW (/var/task/node_modules/langchain/dist/vectorstores/hnswlib.cjs:38:37)","
    at async Function.load (/var/task/node_modules/langchain/dist/vectorstores/hnswlib.cjs:123:23)"," 
    at async AMCompanion (/var/task/index.js:18:29)","    at async Runtime.exports.handler (/var/task/index.js:39:22)"]}
```

Also, this error is not thrown on importing HNSWLib, but only in the following line of code:

```
const vectorStore = await HNSWLib.load("data", new OpenAIEmbeddings(
            {
                openAIApiKey: process.env.OPENAI_API_KEY,
            } 
        ))
```

This is my import:

`const { HNSWLib } = require("langchain/vectorstores/hnswlib")`

It seems I'm not the only one with this problem. See [this post](https://github.com/hwchase17/langchain/issues/1364#issuecomment-1517134074)

**Expeted behavior:** code would be executed properly, just like when executed on my local machine.

**Actual behavior:** the error pasted above.

**Comment by ehsanmok** [comment]
May want to file it under the sister project [langchainjs](https://github.com/hwchase17/langchainjs). This project is the python version.

**Comment by joaotextor** [comment]
> May want to file it under the sister project [langchainjs](https://github.com/hwchase17/langchainjs). This project is the python version.

Thanks for the advice. I filed the issue on HNSWLib-node repository btw. I think it's more appropriate

**Comment by joaotextor** [comment]
> @joaotextor did you find any solution?

Stopped trying. It was just a sample project for educational purposes. But my is to use a simple rest api inside aws amplify to perform the actions and don't use lambda at all.

**Comment by Shusanta** [comment]
@raselSoftNode  @joaotextor  the solution to this is to upgrade your node version runtime.

**Comment by asancmat** [comment]
Hi, I found the same problem using this proyect as dependency on a Node 18.14.2 environment running into a RedHat docker container on Azure AKS.
On app node_modules folder I can find the hnswlib-node folder but if I look at "node_modules/langchain/node_modules" I only see a "binary-extensions" folder.
I think that it's a problem with dependency management below **node 19**

**Comment by amirgamil** [comment]
+1 also getting this error in a nextjs project

**Comment by Jack-kelly-22** [comment]
same problem fixed by removing cache + node_modules changing node version to 18

**Comment by Dawsoncodes** [comment]
Getting the same error in a Next.js project as well.

**Comment by tatianafrank** [comment]
Also getting this error on node18-alpine image

**Comment by dmb0058** [comment]
I assume that's Node19 on your own server, not on AWS Lambda (which I think only runs Node18)? If so, it's not the same issue, but it could be the same underlying problem. 

I've reported this as an issue on langchainjs, as the problem happens with HNSWlib and Faiss, essentially there are some missing libraries on AWS Lambda that might also be missing from your server (libgomp.so, libm.so.6, maybe others).

See https://github.com/hwchase17/langchainjs/issues/1930

**Comment by tatianafrank** [comment]
Im running it in a docker container.

**Comment by howdyhyber** [comment]
So confused, tried it running in local env, it is specified in their docs, i need to install visual studio code, https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/hnswlib
to properly install the library, havent tried in lambda yet though.

**Comment by howdyhyber** [comment]
Tried in Lambda a while agao, it doesnt work, event though the library has been installed already.

**Comment by howdyhyber** [comment]
Found a resource that might help : https://github.com/yoshoku/hnswlib-node/wiki/How-to-run-hnswlib-node-on-AWS-Lambda
