### ISSUE TITLE
Support for other OpenAI Embeddings (text-similarity, code-search)

### ISSUE THREAD

**Issue by varunnair18** [hwchase17/langchain#342]
Hello,

Could the `OpenAIEmbeddings` class support the other OpenAI embeddings, such as the text-similarity and code-search engines? 

Currently we can only specify the engine type (ada, babbage, curie, davinci) during instantiation and are forced to use the text-search engines. Native support for this would be appreciated instead of my workaround - happy to contribute a PR to this if needed. Thanks!

**Comment by hwchase17** [comment]
yes this is a great idea! if you have time, would be awesome to get a PR! if not, I'll try to tackle this weekend

**Comment by hwchase17** [comment]
due to new release, going to tackle this right now!

**Comment by varunnair18** [comment]
Awesome thanks!

**Comment by varunnair18** [comment]
Just approved it!
