### ISSUE TITLE
Question about setting LANGCHAIN_HANDLER environment variable

### ISSUE THREAD

**Issue by xuanxuanQAQ** [hwchase17/langchain#3443]
Hello, I came across a code snippet in the tutorial page on "Conversation Agent (for Chat Models)" that has left me a bit confused. The tutorial also mentioned a warning error like this:
`WARNING:root:Failed to default session, using empty session: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a1767c0>: Failed to establish a new connection: [Errno 61] Connection refused'))`
Then i found the line of code in question is:
`os.environ["LANGCHAIN_HANDLER"] = "langchain"`
When I remove this line from the code, the program still seems to work without any errors. So why is this line of code exists.
Thank you!

**Comment by arminta7** [comment]
I was wondering the same thing.

**Comment by matthew-walters** [comment]
It appears to be for [tracing](https://python.langchain.com/en/latest/tracing/local_installation.html#environment-setup)

**Comment by xuanxuanQAQ** [comment]
I see, thank you.

**Comment by walt798** [comment]
i have same issue please tell me where i can find and remove this line?
