### ISSUE TITLE
_collapse_docs should use self.llm_chain not elf.combine_document_chain.combine_docs

### ISSUE THREAD

**Issue by JohnNay** [hwchase17/langchain#356]
https://github.com/hwchase17/langchain/blob/c1b50b7b13545b1549c051182f547cfc2f8ed0be/langchain/chains/combine_documents/map_reduce.py#L120

**Comment by JohnNay** [comment]
currently

https://github.com/hwchase17/langchain/blob/c1b50b7b13545b1549c051182f547cfc2f8ed0be/langchain/chains/combine_documents/map_reduce.py#L119-L121

is applying a prompt to documents and asking it for a `FINAL ANSWER` and then it is going to combine those final answer LLM generations into a final prompt for

https://github.com/hwchase17/langchain/blob/c1b50b7b13545b1549c051182f547cfc2f8ed0be/langchain/chains/combine_documents/map_reduce.py#L126

where it will combine "final answer" output and call it "Content:". Which could be misleading for the model to try to interpet how to think about that text.

**Comment by JohnNay** [comment]
Ideally, we would use a different prompt here 

https://github.com/hwchase17/langchain/blob/c1b50b7b13545b1549c051182f547cfc2f8ed0be/langchain/chains/combine_documents/map_reduce.py#L119-L121

rather than this one:

https://github.com/hwchase17/langchain/blob/c1b50b7b13545b1549c051182f547cfc2f8ed0be/langchain/chains/qa_with_sources/map_reduce_prompt.py#L13-L47

we would have one that does not ask for a final answer. it would ask for a summary of those sublist/subdocs.

**Comment by JohnNay** [comment]
We could add in a `"collapse_prompt"`

**Comment by hwchase17** [comment]
https://github.com/hwchase17/langchain/pull/358

**Comment by JohnNay** [comment]
addressed
