### ISSUE TITLE
AttributeError when calling OpenAIEmbeddings model

### ISSUE THREAD

**Issue by laveshnk-crypto** [hwchase17/langchain#3586]
I am facing an error when calling the OpenAIEmbeddings model. This is my code.

````
import os

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "base-thing"
os.environ["OPENAI_API_KEY"] = "apikey"
from langchain.embeddings import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="model-name")
text = "This is a test document."
query_result = embeddings.embed_query(text)
doc_result = embeddings.embed_documents([text])
````

This is the error I am facing:
**AttributeError: module 'tiktoken' has no attribute 'model'**

**Comment by dholendar27** [comment]
What model you are using?

**Comment by geg00** [comment]
> I am facing an error when calling the OpenAIEmbeddings model. This is my code.
> 
> ```
> import os
> 
> os.environ["OPENAI_API_TYPE"] = "azure"
> os.environ["OPENAI_API_BASE"] = "base-thing"
> os.environ["OPENAI_API_KEY"] = "apikey"
> from langchain.embeddings import OpenAIEmbeddings
> 
> embeddings = OpenAIEmbeddings(model="model-name")
> text = "This is a test document."
> query_result = embeddings.embed_query(text)
> doc_result = embeddings.embed_documents([text])
> ```
> 
> This is the error I am facing: **AttributeError: module 'tiktoken' has no attribute 'model'**

Few things
I see that you are using Azure

This is the definition of OpenAIEmbeddings in longchain
OpenAIEmbeddings(
    *,
    client: Any = None,
    model: str = 'text-embedding-ada-002',
    document_model_name: str = 'text-embedding-ada-002',
    query_model_name: str = 'text-embedding-ada-002',
    embedding_ctx_length: int = 8191,
    openai_api_key: Optional[str] = None,
    openai_organization: Optional[str] = None,
    allowed_special: Union[Literal['all'], Set[str]] = set(),
    disallowed_special: Union[Literal['all'], Set[str], Tuple[()]] = 'all',
    chunk_size: int = 1000,
    max_retries: int = 6,
) -> None

1) Define in in the deployment models 
The model with the name text-embedding-ada-002 pointing to the model text-embedding-ada-002
OpneAIEmbeddings includes

2) modify your embeddings to look like this

embeddings = OpenAIEmbeddings(chunk_size=1)

One more thing
Every time that you see OpenAI in LLMs change it to AzureOpenAI and it will work

Good Luck man

**Comment by laveshnk-crypto** [comment]
UPDATE: I have updated tiktoken to the latest version and the error has disappeared, but am now facing another issues AuthenticationError. My key is completely fine and yet its unable to authenticate. Any help?

**Comment by geg00** [comment]
I have the following variable set after I set the environment variables

openai.api_type = "azure"
openai.api_base = "https://<deployment>.openai.azure.com/"
openai.api_version = "2023-03-15-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")
GPT_ENGINE = 'gpt-35-turbo'
EMBEDDING_ENGINE = 'text-embedding-ada-002'

That will set the variables

**Comment by laveshnk-crypto** [comment]
@geg00 Could you try it out with text-embedding-ada-002 and azure and let me know if that works?

**Comment by geg00** [comment]
embeddings = OpenAIEmbeddings(chunk_size=1)
text = "This is a test document."
query_result = embeddings.embed_query(text)
doc_result = embeddings.embed_documents([text])

Works 100%
![image](https://user-images.githubusercontent.com/10646838/234604580-875beaad-55b5-4a76-8712-30f4e063a9f2.png)

**Comment by laveshnk-crypto** [comment]
@geg00 Thank you for this! Could you send me the whole code if possible? Barring the keys and private stuff of course. Also did u run it locally or on a notebook

**Comment by joshmohrer** [comment]
I also got this today for the first time. 

<img width="994" alt="Screenshot 2023-04-26 at 8 59 30 PM" src="https://user-images.githubusercontent.com/440810/234733183-9acbc41c-2ab7-49e1-9845-364bb87e46cd.png">

**Comment by laveshnk-crypto** [comment]
@joshmohrer update tiktoken to the latest version and try again?

**Comment by joshmohrer** [comment]
<img width="990" alt="Screenshot 2023-04-26 at 9 15 13 PM" src="https://user-images.githubusercontent.com/440810/234735024-feeb53f5-e3b3-48ad-8256-d4606d4bcc28.png">

Might be doing it wrong, but did not work for me.

**Comment by laveshnk-crypto** [comment]
@joshmohrer your dependencies for gotrue and requests seem to be outdated. update those and try again?

**Comment by laveshnk-crypto** [comment]
UPDATE: Looks like there was some issues with regards to the version of some of the dependencies, specificially tiktoken. Updating seems to have resolved this error. But am now facing another issue referenced here https://github.com/hwchase17/langchain/issues/3632
