### ISSUE TITLE
ConversationalRetrievalChain with CSV file limited to first 4 rows of data

### ISSUE THREAD

**Issue by davidmcomfort** [hwchase17/langchain#3621]
I am having issues with using ConversationalRetrievalChain to chat with a CSV file. It only recognizes the first four rows of a CSV file. 

```
loader = CSVLoader(file_path=filepath, encoding="utf-8")
data = loader.load()

embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)
vectorstore = FAISS.from_documents(data, embeddings)

_template = """Given the following conversation and a follow-up question, rephrase the follow-up question to be a standalone question.
    Chat History:
    {chat_history}
    Follow-up entry: {question}
    Standalone question:"""

CONDENSE_QUESTION_PROMPT = PromptTemplate.from_template(_template)

qa_template = """"You are an AI conversational assistant to answer questions based on a context.
You are given data from a csv file and a question, you must help the user find the information they need. 
Your answers should be friendly, in the same language.
question: {question}
=========
context: {context}
=======
"""

QA_PROMPT = PromptTemplate(template=qa_template, input_variables=["question", "context"])

model_name = 'gpt-4'

from langchain.memory import ConversationBufferMemory
memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

chain = ConversationalRetrievalChain.from_llm(
llm = ChatOpenAI(temperature=0.0, 
model_name=model_name,
    openai_api_key=openai_api_key, 
    request_timeout=120),
retriever=vectorstore.as_retriever(),
 memory=memory)

query = """
How many headlines are in this data set
"""

result = chain({"question": query,})

result[ 'answer']
```
The response is `There are four rows in this data set.`

The data length is 151 lines so I know that this step is working properly. Could this be a token limitation of OpenAI?

**Comment by davidmcomfort** [comment]
Going to close this. Using pandas agent with a chain now

**Comment by ruben-quilez** [comment]
Hi David! Exactly the same thing happened to me. How did you solve it?  Thanks!

**Comment by davidmcomfort** [comment]
Hi Ruben, Try either:
'''
[llm = ChatOpenAI(temperature=0.0, 
model_name=model_name,
    openai_api_key=openai_api_key, 
    request_timeout=120)

df_agent = create_pandas_dataframe_agent(llm, 
df, 
verbose=True, 
openai_api_key=openai_api_key, 
) 

df_agent.run("How many rows in this data set")
](url)
'''
OR Also, defining the agent as a tool so that I can integrate it in with other solutions:

'''
def pandas_agent(input=""):
  pandas_agent_df = create_pandas_dataframe_agent(llm, df, verbose=True, openai_api_key=openai_api_key, ) 
  return pandas_agent_df

pandas_tool = Tool(
  name='Pandas Data frame tool',
  func=pandas_agent,
  description="Useful for when you need to answer questions about a Pandas Dataframe"
)

tools = [search, random_tool, life_tool, 
pandas_tool
]

# conversational agent memory
memory = ConversationBufferWindowMemory(
  memory_key='chat_history',
  k=3,
  return_messages=True
)

# Create our agent
conversational_agent = initialize_agent(
  agent='chat-conversational-react-description',
  tools=tools,
  llm=llm,
  verbose=True,
  max_iterations=3,
  early_stopping_method='generate',
  memory=memory
)
'''

There are some issues with output parsing which you might run into though.

**Comment by mahaboobkhan29** [comment]
@davidmcomfort i am also getting same four rows only so i use create_pandas_dataframe_agent but i don't know how to pass vectorstore in that. Can you please guide me

**Comment by ramitsurana** [comment]
Any more updates on this thread?

**Comment by aiakubovich** [comment]
@nareshr8 

thank you very much!

**Comment by runninghare** [comment]
I actually don't think embedding csv file is a good idea. csv is structured data but the question is unstructured. It does not make much sense to compare their similarity. Unless you can fit the entire csv content in one context window (gpt-3.5-turbo-16k, or gpt-4-32k), it's always better to use Panda agent.

**Comment by nareshr8** [comment]
I actually like the CSV over Pandas as it does schema

**Comment by aiakubovich** [comment]
@runninghare 
I have textual column with texts (~100-500 words in each cell) and I want chatbot understand this column. I do not think any agent without embeddings will work for it

**Comment by dnyandeepc16** [comment]
> Hi Ruben, Try either:
> 
> ```
> [llm = ChatOpenAI(temperature=0.0, 
> model_name=model_name,
>     openai_api_key=openai_api_key, 
>     request_timeout=120)
> 
> df_agent = create_pandas_dataframe_agent(llm, 
> df, 
> verbose=True, 
> openai_api_key=openai_api_key, 
> ) 
> 
> df_agent.run("How many rows in this data set")
> ](url)
> ```
> 
> OR Also, defining the agent as a tool so that I can integrate it in with other solutions:
> 
> ```
> def pandas_agent(input=""):
>   pandas_agent_df = create_pandas_dataframe_agent(llm, df, verbose=True, openai_api_key=openai_api_key, ) 
>   return pandas_agent_df
> 
> pandas_tool = Tool(
>   name='Pandas Data frame tool',
>   func=pandas_agent,
>   description="Useful for when you need to answer questions about a Pandas Dataframe"
> )
> 
> tools = [search, random_tool, life_tool, 
> pandas_tool
> ]
> 
> # conversational agent memory
> memory = ConversationBufferWindowMemory(
>   memory_key='chat_history',
>   k=3,
>   return_messages=True
> )
> 
> # Create our agent
> conversational_agent = initialize_agent(
>   agent='chat-conversational-react-description',
>   tools=tools,
>   llm=llm,
>   verbose=True,
>   max_iterations=3,
>   early_stopping_method='generate',
>   memory=memory
> )
> ```
> 
> There are some issues with output parsing which you might run into though.

Hi, 
i'm trying to have langchain tool made of csv_agent and want to run it using initialize_agent. But, when I'm trying to load the csv file path it's not accepting it. could you please guide me through how I can combine langchain agents with tools?

**Comment by meanirban100** [comment]
> retriever.search_kwargs = {'k':20}

Even if I use this it gives me partial result. My CSV has more than 700+ records and if I setup K as 700+ then it is crossing the input token count. If I use the less say 20 or 50 it is giving me incorrect result. 

I can't use the create_pandas_dataframe_agent becuase in our case input can be either csv or text or any file format. Is there any way we can have a generic solution for this.

**Comment by nareshr8** [comment]
Do u mean u need all 700+ records to get the accurate data or just few of those in that 700+ is required. If that's that case u must concentrate on tuning ur embeddings and similarity algo to suite ur requirement.

**Comment by arjunprmr** [comment]
what if we get 700+ records somehow using similarity algo but cant pass all those records to GPT as it has a window limit of tokens?
