### ISSUE TITLE
Add Support For OpenAI SSE Response

### ISSUE THREAD

**Issue by sam-h-bean** [hwchase17/langchain#363]
Add support for server-sent events from the OpenAI API. Because some of these generations take a bit of time to finish I'd like to stream tokens back as they become ready.

Documentation for this feature can be found [here](https://beta.openai.com/docs/api-reference/completions/create#completions/create-stream).

This seems like it could require a pretty substantial refactor. LangChain would need to continuously return `LLMResult`s while maintaining a connection to the server.

**Comment by sam-h-bean** [comment]
@hwchase17 Would you be interested in meeting synchronously to discuss how to handle this more holistically? The initial factoring will work but I have to break out of using the `LLMChain` class and handle history manually. Would be awesome to figure out how to both get streaming tokens out of OpenAI with langchain using `LLMChain` and reconcile the stream into the final string for conversational memory.

**Comment by hwchase17** [comment]
@sam-h-bean yeah lets do it - wanna shoot me an email hw.chase.17 @ gmail.com and we can coordinate?

**Comment by louis030195** [comment]
I'm not sure if streaming is possible as of now? Seeing https://github.com/hwchase17/langchain/pull/364/files

Can we stream using LLMChain somehow?
