### ISSUE TITLE
no 'persistent=True' tag

### ISSUE THREAD

**Issue by Amazingldl** [hwchase17/langchain#3641]
Follow the instruction: https://python.langchain.com/en/latest/modules/agents/tools/examples/bash.html 

![image](https://user-images.githubusercontent.com/54729177/234824204-0d44bcbc-bbda-4c57-948c-590b6900c922.png)

But I get the error:
```
    bash = BashProcess(persistent=True)
TypeError: BashProcess.__init__() got an unexpected keyword argument 'persistent'
```
The version of langchain is 0.0.150

**Comment by vowelparrot** [comment]
It was introduced in `0.0.151`. However you may run into issues still until 0.0.152 is released. See https://github.com/hwchase17/langchain/issues/3664
