### ISSUE TITLE
Azure OpenAI Embeddings model not working

### ISSUE THREAD

**Issue by laveshnk-crypto** [hwchase17/langchain#3648]
Hi, using the text-embedding-ada-002 model provided by Azure OpenAI doesnt seem to be working for me. Any fixes?

**Comment by vowelparrot** [comment]
Could you provide a minimal example of how to reproduce, as well as a more full description of the error you are seeing?

**Comment by anshumantanwar** [comment]
try naming your model as "text-embedding-ada-002". It worked in my case.

**Comment by laveshnk-crypto** [comment]
@anshumantanwar renaming it worked! thanks

**Comment by anshumantanwar** [comment]
it is not a fix (it is just how i made things work at first place)... thing is if you do not pass the deployment name while creating embeddings, it by default takes "text-embedding-ada-002". Correct way to code is. Feel free for further discussion.

`os.environ["OPENAI_API_KEY"] = API_KEY
os.environ["OPENAI_API_VERSION"] =  VERSION
os.environ["OPENAI_API_BASE"] = BASE_URL
os.environ["OPENAI_API_TYPE"] = OPEN_API_TYPE
embed = OpenAIEmbeddings(deployment="your_deployment_name")`

**Comment by lielu** [comment]
@anshumantanwar It appears to be a bug, and a regression - it was working in older version of langchain but now it breaks. You shouldn't have to name your deployment the same as the model.
