### ISSUE TITLE
AzureOpenAi - Sql Agent: must provide an `engine` or `deployment_id`

### ISSUE THREAD

**Issue by michal-aai** [hwchase17/langchain#3649]
Hi there,
I'm using Langchain + AzureOpenAi api. Based on that I'm trying to use the sql agent to run queries against the postgresql table (15.2). In many cases it works fine but once in a while I'm getting an error:

```
Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'>
```

The llm instance gets initiated as:
```
llm = AzureOpenAI(deployment_name=settings.OPENAI_ENGINE, model_name="code-davinci-002")
```

Here's an example of the Agent output:

```
....
> Entering new AgentExecutor chain...
Action: list_tables_sql_db
Action Input: ""
Observation: app_organisationadvertiser, app_transaction, app_publisher, app_basketproduct
Thought: I need to query the app_organisationadvertiser table to get the list of brands
Action: query_sql_db
Action Input: SELECT name FROM app_organisationadvertiser LIMIT 10
Observation: [('Your brand nr 1',)]
Thought: I should check my query before executing it
Action: query_checker_sql_db
Action Input: SELECT name FROM app_organisationadvertiser LIMIT 10
```

The final query looks good and is a valid SQL query, but the agent returns an exception with the error as described above.
Any ideas how to deal with that?

**Comment by ShilJain** [comment]
Hi ,

Were you able to solve this? I am getting the same error.

**Comment by michal-aai** [comment]
@ShilJain upgrading langchain to the latest version solved the problem for me.

**Comment by ShilJain** [comment]
I upgraded it to 0.0.152 but it then gives me below error. Any insights into why this might be happening? Appreciate your response.

_**ValidationError: 1 validation error for SQLDatabaseToolkit
llm
  field required (type=value_error.missing)**_

**Comment by michal-aai** [comment]
I think you need to pass both llm and db instance references:
```
SQLDatabaseToolkit(db=db, llm=llm)
```
