### ISSUE TITLE
FAISS remote saving and loading of indexes

### ISSUE THREAD

**Issue by olaf-hoops** [hwchase17/langchain#3673]
With FAISS you can save and load created indexes locally: 
db.save_local("faiss_index")
new_db = FAISS.load_local("faiss_index", embeddings)
In a production environment you might want to keep your indexes and docs separated from your application and access those remotely and not locally. 
How can that be achieved? Is there another option where you can host your own vector store separated from your llm agent?

**Comment by tk-o** [comment]
[facebookresearch/faiss](https://github.com/facebookresearch/faiss) stores the data in RAM, so it's not a good vector store (as RAM is temporary storage).

What is the use case you need to use FAISS for?

**Comment by olaf-hoops** [comment]
> [facebookresearch/faiss](https://github.com/facebookresearch/faiss) stores the data in RAM, so it's not a good vector store (as RAM is temporary storage).
> 
> What is the use case you need to use FAISS for?

Ahh I see, I completely misunderstood it. Use case is QA chain for docs in a locally hosted vector db.
I took a look at weaviate which should suffice my needs.

**Comment by vamsee9201** [comment]
I also want to save FAISS in cloud and load it locally . Did someone resolve it ?
