### ISSUE TITLE
SelfQueryRetriever  import failed  in langchain 0.0.152 and 0.0.151

### ISSUE THREAD

**Issue by rubensmau** [hwchase17/langchain#3705]
from langchain.retrievers.self_query.base import SelfQueryRetriever  failed 

File [~/anaconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/query_constructor/parser.py:41](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/rubensmau/luby/machine-learning/langchain/~/anaconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/query_constructor/parser.py:41)
      8 from langchain.chains.query_constructor.ir import (
      9     Comparator,
     10     Comparison,
   (...)
     13     Operator,
     14 )
     16 GRAMMAR = """
     17     ?program: func_call
     18     ?expr: func_call
   (...)
     37     %ignore WS
     38 """
---> 41 @v_args(inline=True)
     42 class QueryTransformer(Transformer):
     43     def __init__(
     44         self,
     45         *args: Any,
   (...)
     48         **kwargs: Any,
     49     ):
     50         super().__init__(*args, **kwargs)

NameError: name 'v_args' is not defined

**Comment by RubenAMtz** [comment]
`pip install lark` fixes the issue

**Comment by rubensmau** [comment]
As mentioned by @RubenAMtz , pip install lark fixes the issue
