### ISSUE TITLE
Quick Start example for Agents: Dynamically Call Chains Based on User Input is broken

### ISSUE THREAD

**Issue by acutting1755** [hwchase17/langchain#3757]
Commit: https://github.com/hwchase17/langchain/commit/4654c58f7238e10b35544633bd780b73bbb75c75
This commit appears to have broken the Quick Start example for Agents: Dynamically Call Chains Based on User Input. When attempting to follow along this now causes an error ValueError: ZeroShotAgent does not support multi-input tool Calculator.

**Comment by philipk19238** [comment]
I created a PR https://github.com/hwchase17/langchain/pull/3803 that removes the restrictive checking of multi-input in the Agent base class. Will need reviewers to +1 and merge.

**Comment by vowelparrot** [comment]
Fixed in 0.0.153

**Comment by ryanshrott** [comment]
> Fixed in 0.0.153

I have a the same issue on 0.0.153

**Comment by vowelparrot** [comment]
With the calculator tool?

**Comment by ryanshrott** [comment]
> With the calculator tool?

No I'm using the new playwright browser automation tool, but getting a similar error.
