### ISSUE TITLE
Agent + Memory Docs are outdated

### ISSUE THREAD

**Issue by andrewgleave** [hwchase17/langchain#380]
Since #372 docs on agents with memory are no longer valid

**Comment by hwchase17** [comment]
arg my bad! updating documentation with https://github.com/hwchase17/langchain/pull/382

**Comment by hwchase17** [comment]
@andrewgleave does this work for you now? sorry about that! https://langchain.readthedocs.io/en/latest/examples/memory/agent_with_memory.html

**Comment by andrewgleave** [comment]
Yeah works fine. Thanks!
