### ISSUE TITLE
S3FileLoader and S3DirectoryLoader does not work on AWS Lambda

### ISSUE THREAD

**Issue by wasa-ism** [hwchase17/langchain#3866]
Both the loaders fail with the error below-

```
[Errno 30] Read-only file system: '/home/sbx_user1051'
```

This is because of [this line](https://github.com/hwchase17/langchain/blob/f7cb2af5f40c958ac1b3d6ba243170ef627dbb6e/langchain/document_loaders/s3_file.py#L29). The only writable directory in AWS Lambda is `/tmp`, so there should be a way to set the directory.

**Comment by moshekarmel1** [comment]
Why was this issue closed? @wasa-ism how did you fix it?
