### ISSUE TITLE
AttributeError: 'Redis' object has no attribute 'module_list'

### ISSUE THREAD

**Issue by Ahmedniz1** [hwchase17/langchain#3893]
I'm trying to make a vectorstore using redis and store the embeddings in redis.
When I write the code
rds = Redis.from_documents(docs, embeddings, redis_url="redis://localhost:6379",  index_name='test_link')
I get the following error
AttributeError: 'Redis' object has no attribute 'module_list'.
Note: I'm trying to run redis locally on windows subsystem ubuntu.
Please help.

**Comment by tylerhutcherson** [comment]
Which version of the redis python client are you using?

**Comment by Ahmedniz1** [comment]
I have redis server in windows subsystem (ubuntu) and its Redis server v=6.0.16
on python side, its redis version 3.5.3

**Comment by tylerhutcherson** [comment]
Can you try with the latest redis client version (>=4.5.2)

**Comment by Ahmedniz1** [comment]
sorry for the late reply. I updated the redis version to 4.5.4. When I run the piece of code, it says
ValueError: Redis failed to connect: You must add the RediSearch (>= 2.4) module from Redis Stack. Please refer to Redis Stack docs: https://redis.io/docs/stack/
When I try to install redisearch==2.4 i get the error no such distribution found for redisearch
when I just install redisearch, it updates redis version to 3.5.3 
please help

**Comment by tylerhutcherson** [comment]
Ok so the redis client version fixed the initial error here.

For this one, you don't need to install a different client. You need to run the version of redis that has the search module installed on the database for vector search. (Redis is modular and has different developer capabilities). Did you checkout the link it provided?

Here is a [docker command](https://redis.io/docs/stack/get-started/install/docker/) to run the correct flavor of redis:

```bash
docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest
```

**Comment by iamadhee** [comment]
Hi, I'm also getting the same error. I'm using the below versions of the packages
```
redis==3.5.3
redisearch==2.1.1
```
The docker command also didn't actually solve the issue.

**Comment by tylerhutcherson** [comment]
Thanks for looking into that. 

The _redisearch_ client library should **not** be needed here. All search functionality required is in the standard redis Python client.

We need to make sure the redisearch pin is removed in favor of just redis. Will look into this.

cc @hwchase17

**Comment by iamadhee** [comment]
No, it's just that the error message suggests the user to install redisearch (>=2.4), I'm fixing that in the new PR

https://github.com/hwchase17/langchain/blob/1ed4228822498fd58d33d377572af0821c496b20/langchain/vectorstores/redis.py#LL59C35-L59C35

**Comment by nickstreletskij** [comment]
Still not working

**Comment by bhanu-Bigdata** [comment]
still not working

**Comment by shubh207** [comment]
Can anybody suggest a solution for this issue ..

**Comment by anmolagrwl** [comment]
Still facing the same issue while using redis-stack-server docker container:

Here is the full trace.
```
rds = Redis.from_texts(
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/redis/base.py", line 497, in from_texts
    instance, _ = cls.from_texts_return_keys(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/redis/base.py", line 414, in from_texts_return_keys
    instance = cls(
               ^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/redis/base.py", line 280, in __init__
    check_redis_module_exist(redis_client, REDIS_REQUIRED_MODULES)
  File "/usr/local/lib/python3.11/site-packages/langchain/utilities/redis.py", line 49, in check_redis_module_exist
    installed_modules = client.module_list()
                        ^^^^^^^^^^^^^^^^^^
AttributeError: 'Redis' object has no attribute 'module_list'

```

Was really looking forward to using Redis. Seems this issue has been there for a while. I will have to look into other vector DB options soon.

**Comment by shanshanRT** [comment]
still not working..

**Comment by GhaithDek** [comment]
these versions resolved my problem:

`pip install redis==4.5.4 redisearch==2.0.0`

let me know,
thanks

**Comment by tylerhutcherson** [comment]
FYI there is no dependency on `redisearch`; the **client** library here. Base `redis` is all that's needed from a client standpoint. 

You need to make sure search/query featured are enabled on your database... which is built-in if using the free Redis Stack docker image or Redis Enterprise.

**Comment by koorukuroo** [comment]
You guys all need to switch to Redis Stack, not just Redis.

```docker run -d --name redis-stack -p 6379:6379 redis/redis-stack:latest```

**Comment by sahilshaikh89** [comment]
I was facing the same issue with Conda as my package manager. 
langchain==0.3.4
langchain-community==0.3.3
redis==3.5.3

I was able to resolve the issue by installing langchain-redis==0.1.1 integration package which is mentioned on langchain 0.3 release notes. However, Conda doesn't have that langchain-redis  package on any of the channels so ended up installing using pip. I know its a mess to use two package managers in the same environment, but this resolved my issue.
