### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.schemas'

### ISSUE THREAD

**Issue by Aspyryan** [hwchase17/langchain#3960]
When installing `Langchain==0.0.155` I am getting the error that `langchain.schemas` does not exists. This is because the file is named langchain.schema so there is a typo. I will create a pull request and reference this issue.

**Comment by Candy75** [comment]
encountered same error, already fix it by your instructions, thanks!

**Comment by YHOYO** [comment]
> encountered same error, already fix it by your instructions, thanks!

how do you fix it?

**Comment by Candy75** [comment]
Click “Fix issue”, you will see the answer.
![IMG_4630](https://user-images.githubusercontent.com/20401200/235707375-da216392-42ae-44ff-a284-37b888b06cd2.jpeg)

**Comment by phdykd** [comment]
same here how do you fix it?

**Comment by Aspyryan** [comment]
Yea I implemented Pull Request #3961, sorry for not referencing it

**Comment by phdykd** [comment]
so what should I write instead of this code that I have "from langchain.document_loaders import UnstructuredPDFLoader
from langchain.indexes import VectorstoreIndexCreator"?

**Comment by Aspyryan** [comment]
> so what should I write instead of this code that I have "from langchain.document_loaders import UnstructuredPDFLoader from langchain.indexes import VectorstoreIndexCreator"?

You have to go into the source code, so where python is installed on your system, go to `site_package` and edit the file langchain/indexes/vectorstore.py with the changes

**Comment by phdykd** [comment]
thanks many

**Comment by brunooyague** [comment]
Thanks for the help, what would you do if you're deploying the code via github? Theres no source code in the repo or there is?

**Comment by Aspyryan** [comment]
> Thanks for the help, what would you do if you're deploying the code via github? Theres no source code in the repo or there is?

You got two options. You can wait for the maintainers to approve the pull request or you could create a fork of the project and fix it yourself, publish the package etc. (not shure how easy this part is)

**Comment by brunooyague** [comment]
> > Thanks for the help, what would you do if you're deploying the code via github? Theres no source code in the repo or there is?
> 
> You got two options. You can wait for the maintainers to approve the pull request or you could create a fork of the project and fix it yourself, publish the package etc. (not shure how easy this part is)

Just changed the requirements.txt to a previous version of langchain and worked :)

**Comment by manoloth** [comment]
Seems to have been fixed by #4003

**Comment by Aspyryan** [comment]
This is indeed fixed now, closing the issue
