### ISSUE TITLE
Seeking solution for combined retrievers, or retrieving from multiple vectorstores with sources, to maintain separate Namespaces.

### ISSUE THREAD

**Issue by simonfromla** [hwchase17/langchain#3991]
It seems maintaining separate namespaces in your vector DB is helpful and/or necessary in making sure an LLM can answer compare/contrast questions that need to reference texts separated by dates like "03/2023" vs. "03/2022" without getting confused.  

To that end, there's a need to retrieve from multiple vectorstores, yet I can't find a straightforward solution.  

I have tried a few things:  
1. Extending the `ConversationalRetrievalChain` to accept a list of retrievers:  
```
class MultiRetrieverConversationalRetrievalChain(ConversationalRetrievalChain):
    """Chain for chatting with multiple indexes."""

    retrievers: List[BaseRetriever]
    """Indexes to connect to."""

    def _get_docs(self, question: str, inputs: Dict[str, Any]) -> List[Document]:
        all_docs = []
        for retriever in self.retrievers:
            docs = retriever.get_relevant_documents(question)
            all_docs.extend(docs)
        return self._reduce_tokens_below_limit(all_docs)

    async def _aget_docs(self, question: str, inputs: Dict[str, Any]) -> List[Document]:
        all_docs = []
        for retriever in self.retrievers:
            docs = await retriever.aget_relevant_documents(question)
            all_docs.extend(docs)
        return self._reduce_tokens_below_limit(all_docs)
```
This became a bit unwieldy as it ran into validation errors with Pydantic, but I don't see why a more competent dev wouldn't be able to manage this.  

2. I tried combining retrievers (suggestion from kapa.ai):  
```
embeddings = OpenAIEmbeddings()
march_documents = Pinecone.from_existing_index(index_name="langchain2", embedding=embeddings, namespace="March 2023")
feb_documents = Pinecone.from_existing_index(index_name="langchain2", embedding=embeddings, namespace="February 2023")

combined_docs = feb_documents + march_documents
# Create a RetrievalQAWithSourcesChain using the combined retriever
chain = RetrievalQAWithSourcesChain.from_chain_type(OpenAI(temperature=0), chain_type="stuff", retriever=combined_docs) 
# does not work as as_retriever() either
``` 

3. Tried using an Agent with `VectorStoreRouterToolkit`, which seems to be built for this kind of task, yet provides terrible answers for some reason that I need to dive deeper into. Terrible answers being - does not listen when I instruct like "Do not summarize, list everything about XYZ..."
Further, I need/prefer the results from similarity_search, returning `top_k` for my use-case, which the agent doesn't seem to provide.  

Is there a workaround to my problem? How do I maintain separation of namespaces, so that I can have the LLM answer questions about separate documents, and also be able to provide the source for the separate documents all from within a single chain?

**Comment by simonfromla** [comment]
> Hi did you solve the problem?  

I've decided to go with separated vectorstores, passing similarity results over as context to the prompt. Also, FAISS has inbuilt methods for combining multiple vectorstores if needed, which is what I'm going with. The new updates to the agents seem like they would be perfect for the task. From cursory look, seems like you'd create several stores, add them as options to the agents tools, and let it do its thing.

**Comment by cancan101** [comment]
I did this (I swapped the return type out for `Iterable`):
```python
class CombineRetriever(BaseRetriever):
    def __init__(self, retrievers):
        self.retrievers = retrievers
        
    def get_relevant_documents(self, query: str) -> Iterable[Document]:
        for retriever in self.retrievers:
            for doc in retriever.get_relevant_documents(query):
                yield doc
    async def aget_relevant_documents(self, query: str) -> Iterable[Document]:
        for retriever in self.retrievers:
            for doc in await retriever.get_relevant_documents(query):
                yield doc        
```

**Comment by GDrupal** [comment]
@simonfromla 
@cancan101 
Hi guys! I just submitted an idea for a merger retriever that perhaps could help you with this use case?
Please take a look or give it a try and let me know.
https://github.com/hwchase17/langchain/pull/5798

**Comment by simonfromla** [comment]
#5798 ought to do it. Closing.

**Comment by Morriz** [comment]
> I did this (I swapped the return type out for `Iterable`):
> 
> ```python
> class CombineRetriever(BaseRetriever):
>     def __init__(self, retrievers):
>         self.retrievers = retrievers
>         
>     def get_relevant_documents(self, query: str) -> Iterable[Document]:
>         for retriever in self.retrievers:
>             for doc in retriever.get_relevant_documents(query):
>                 yield doc
>     async def aget_relevant_documents(self, query: str) -> Iterable[Document]:
>         for retriever in self.retrievers:
>             for doc in await retriever.get_relevant_documents(query):
>                 yield doc        
> ```

I just tried this and unfortunately the similarity score is per store and dependent on the data volume, so the small store gets matched quicker and thus results are not as expected ;(
