### ISSUE TITLE
First time install of v 0.0.155, errors in build wheel 

### ISSUE THREAD

**Issue by Boldingbroke** [hwchase17/langchain#3994]
I am installing LangChain for the first time. I opened a command box as Administrator to make sure the permissions were solid. It installed the build dependencies, then I got "ERROR: Command errored out with exit status 1:
   command: 'c:\python27\python.exe' 'c:\python27\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'c:\users\boldi\appdata\local\temp\tmpestjm8'" See attached screenshot. 
![LangChain Error](https://user-images.githubusercontent.com/7397536/235765715-3572adff-bb1c-4586-b8c0-0781e1f5202b.JPG)

I have had no problems installing other packages like OpenAI today.

**Comment by Aspyryan** [comment]
The current version of LangChain does not support python versions below 3 (source: https://pypi.org/project/langchain/)

**Comment by Boldingbroke** [comment]
I have version 3.1Sent from my iPhoneOn May 2, 2023, at 2:46 PM, Aspyryan ***@***.***> wrote:﻿
The current version of LangChain does not support python versions below 3 (source: https://pypi.org/project/langchain/)

**Comment by filippo82** [comment]
From your screenshot, you can clearly see that it mentions python 2.7. You might need to set up a virtual environment which uses Python 3.

**Comment by Boldingbroke** [comment]
Yes, I had older versions installed. But I also upgraded to 31. a month ago. And I checked my path variables. Not the issue. I even uninstalled 2.7 and reinstalled P 3.1 and reset my entire environment. Still a hot mess.
