### ISSUE TITLE
Reference error in Documentation

### ISSUE THREAD

**Issue by dheerajiiitv** [hwchase17/langchain#403]
Hey Team, 
`https://github.com/hwchase17/langchain/blob/master/docs/explanation/combine_docs.md#refine` Here as we can see 
There is an error in the description of the `Refine` method. The text describes the `Refine`method as having "Pros" (advantages) that include "Can pull in more relevant context, and may be less lossy than `RefineDocumentsChain.`" However, this makes no sense, as the `Refine` method is being described, not the `RefineDocumentsChain` method.

**Comment by dheerajiiitv** [comment]
I am working on this issue @hwchase17 .

**Comment by hwchase17** [comment]
thank you @dheerajiiitv !
