### ISSUE TITLE
Was Running Fine and now getting errors

### ISSUE THREAD

**Issue by scooter7** [hwchase17/langchain#4064]
Hi,

I had a streamlit app that was working perfectly for a while. Starting today, however, I am getting the following errors:

ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\schema.py)
Traceback:
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "C:\Users\jvineburgh\OneDrive - Clarus Corporation\Desktop\AWS\newui11.py", line 3, in <module>
    from gpt_index import SimpleDirectoryReader, GPTListIndex, GPTSimpleVectorIndex, LLMPredictor, PromptHelper
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\__init__.py", line 18, in <module>
    from gpt_index.indices.common.struct_store.base import SQLDocumentContextBuilder
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\indices\__init__.py", line 4, in <module>
    from gpt_index.indices.keyword_table.base import GPTKeywordTableIndex
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\indices\keyword_table\__init__.py", line 4, in <module>
    from gpt_index.indices.keyword_table.base import GPTKeywordTableIndex
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\indices\keyword_table\base.py", line 16, in <module>
    from gpt_index.indices.base import DOCUMENTS_INPUT, BaseGPTIndex
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\indices\base.py", line 23, in <module>
    from gpt_index.indices.prompt_helper import PromptHelper
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\indices\prompt_helper.py", line 12, in <module>
    from gpt_index.langchain_helpers.chain_wrapper import LLMPredictor
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\langchain_helpers\chain_wrapper.py", line 13, in <module>
    from gpt_index.prompts.base import Prompt
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\prompts\__init__.py", line 3, in <module>
    from gpt_index.prompts.base import Prompt
File "C:\Users\jvineburgh\AppData\Local\Programs\Python\Python311\Lib\site-packages\gpt_index\prompts\base.py", line 9, in <module>
    from langchain.schema import BaseLanguageModel
    
  Any idea how to fix?
  
  Thanks!

**Comment by vowelparrot** [comment]
This was a breaking change from the [callbacks refactor](https://github.com/hwchase17/langchain/commit/d3ec00b5664798be74daa9bdc28ae7c2c86ee22e).

Changing `from langchain.schema import BaseLanguageModel` to `from langchain.base_language import BaseLanguageModel` should fix it

**Comment by scooter7** [comment]
Hi,

Thanks for the prompt response!

Where do I make that change that you provided?

Thanks again!

**Comment by vowelparrot** [comment]
Oh it seems to be happening in GPTIndex. I believe LlamaIndex has updated already so if you are able to update that package, it should probably fix the error. What version of GPTIndex/LlamaIndex are you using?

**Comment by JordanTreDaniel** [comment]
I am doing a fresh install of `llama-index` from running `poetry install` in my [chatgpt plugin repo](https://github.com/openai/chatgpt-retrieval-plugin) and it is still telling me
```
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema'
```
I have 
```
name = "llama-index"
version = "0.5.4"
```
 and 
 ```
 name = "langchain"
version = "0.0.165"
```

**Comment by JordanTreDaniel** [comment]
I am using poetry for the dependency management, but can't:
1. find a proper version of the packages that will result in no error being thrown
2. Nor can I find a way to manually edit the code that actually takes effect when i run `poetry run dev`. 

To me those would be the best workarounds. If anyone better with Python packages/poetry can help, lmk plz.

**Comment by ArCoBVerse** [comment]
Hi, someone got a solution? I am getting the same message:    from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema'

**Comment by vowelparrot** [comment]
`BaseLanguageModel` is in `langchain.base_language` now. 

If this is also about llama-index / gpt-index, you could try installing `llama-index>=0.6.0`

**Comment by jbuusao** [comment]
I've got the same issue, that was fixed with the following versions:
```
pip install llama-index==0.5.6
pip install langchain==0.0.148
```

**Comment by michaelstec** [comment]
Thank you jbuusao.... that worked!

**Comment by Dave86ch** [comment]
Thank you @jbuusao, now it works again also for me the only problem is that apparently, because of the old version, I can't implement the structured agent, any suggestion?

```agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION```

```AttributeError: STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION. Did you mean: 'CHAT_ZERO_SHOT_REACT_DESCRIPTION'?```

**Comment by vowelparrot** [comment]
STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION was introduced after version 0.0.148. You'll need to upgrade langchain (and llama index if that's what you're using) to a more recent version

**Comment by alijavaidistar** [comment]
Hello,

I have followed all the instructions in the comments above but still coming the same issue:

Here are my import statements:
from llama_index import SimpleDirectoryReader, GPTListIndex, readers, GPTSimpleVectorIndex, LLMPredictor, PromptHelper
from langchain import OpenAI
import sys
import os
from IPython.display import Markdown, display

Here is the error:
    from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema' (C:\Users\ali\PycharmProjects\GeoAnalyticsFeatures\venv\lib\site-packages\langchain\schema.py)

What I have tried:
upgrade PIP
upgrade lama

**Comment by vowelparrot** [comment]
Update the import to `from langchain.base_language import BaseLanguageModel`

**Comment by alijavaidistar** [comment]
Hello Zander,

Thank you for the quick response, but I have tried that as well but it is still the same issue, any thoughts?

from llama_index import SimpleDirectoryReader, GPTListIndex, readers, GPTSimpleVectorIndex, LLMPredictor, PromptHelper
from langchain import OpenAI
from langchain.base_language import BaseLanguageModel
import sys
import os
from IPython.display import Markdown, display

**Comment by Dave86ch** [comment]
Same problem, any suggestions?

Thanks

**Comment by aj11081981** [comment]
Thanks @JordanTreDaniel, it worked for me
pip install langchain==0.0.118
pip install gpt_index==0.4.24

**Comment by marcoslozadaf** [comment]
still getting the following error on Python 3.11 : 

from langchain.schema import BaseLanguageModel
ImportError: cannot import name 'BaseLanguageModel' from 'langchain.schema'

**Comment by ajaysunil4** [comment]
@marcoslozadaf 

 Try:
Uninstalling gpt-index, langchain and llama-index and, try installing these 3 lib:

pip install gpt-index
pip install langchain
pip install llama-index
