### ISSUE TITLE
minor issue in code( base_language.py) comments

### ISSUE THREAD

**Issue by pulkitmehtawork** [hwchase17/langchain#4082]
While going through base_language.py code , in _get_num_tokens_default_method .. code makes instance of gpt2 tokenizer while comment says "    # tokenize the text using the GPT-3 tokenizer" . this needs to be corrected to gpt-2 

    # create a GPT-2 tokenizer instance
    tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

    # tokenize the text using the GPT-3 tokenizer
    tokenized_text = tokenizer.tokenize(text)

**Comment by vowelparrot** [comment]
I'd approve the PR!

**Comment by pulkitmehtawork** [comment]
please some one assign to me . I will do this small change .

**Comment by pulkitmehtawork** [comment]
please review my pull request https://github.com/hwchase17/langchain/pull/4084
