### ISSUE TITLE
Sequential Chains Pass All Prior Inputs

### ISSUE THREAD

**Issue by chasemcdo** [hwchase17/langchain#4116]
I am currently working with SequentialChains with the goal to moderate input using the OpenAI moderation endpoint.
ie:
```
# Pseudo Code
SequentialChain(chains=[OpenAIModerationChain(), ConversationChain()])
```

From what I can tell SequentialChain combines the list of current inputs with new inputs and passes that to the next chain in the sequence, based on [this line](https://github.com/hwchase17/langchain/blob/624554a43a1ab0113f3d79ebcbc9e726faecb339/langchain/chains/sequential.py#L103). This means that `ConversationChain()` gets both the output of `OpenAIModerationChain()` and the original input as input_variables, which breaks the chain as `ConversationChain()` ends up receiving an extra input and fails validation.

The behaviour I expected is that the next chain only receives the output from the previous chain.

That behaviour is implemented in [this PR](https://github.com/hwchase17/langchain/pull/4115), but would be interested to hear if there are reasons we want to maintain the old functionality and I am able to help with further development if we want to maintain both.

- https://github.com/hwchase17/langchain/pull/4115

**Comment by hwchase17** [comment]
@chasemcdo this is actually not a bug with the chains, but rather with memory. because there are now multiple inputs, you need to specify the memory key:

```
from langchain.chains import SequentialChain, OpenAIModerationChain, ConversationChain
from langchain.llms import OpenAI
from langchain.memory import ConversationBufferMemory

chain = SequentialChain(chains=[OpenAIModerationChain(), ConversationChain(llm=OpenAI(), memory=ConversationBufferMemory(input_key="input"))], input_variables=["input"])
```

as to whether we WANT to pass along previous keys - yes, we do. there are lots of use cases where that is desirable

hope this help!
