### ISSUE TITLE
GoogleSerperAPIWrapper: HTTPError: 403 Client Error: Forbidden error

### ISSUE THREAD

**Issue by alexcg1** [hwchase17/langchain#4162]
### System Info

Jupyter Lab notebook 3.6.3
Python 3.10
Langchain ==0.0.158

### Who can help?

@vowelparrot 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

This behavior is inconsistent. Sometimes happens, sometimes not. Running this code alone in a notebook works most of the time, but running in a more complex notebook often fails with error.

Note: `OPENAPI_API_KEY` and `SERPER_API_KEY` are both set properly.

```python
from langchain.utilities import GoogleSerperAPIWrapper
search = GoogleSerperAPIWrapper()

results = search.results('oyakodon recipe')
```

Results in error:
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[26], line 1
----> 1 results = search.results('oyakodon recipe')

File /mnt/data/work/sandbox/langchain-test/langchain/foodie/env/lib/python3.10/site-packages/langchain/utilities/google_serper.py:53, in GoogleSerperAPIWrapper.results(self, query, **kwargs)
     51 def results(self, query: str, **kwargs: Any) -> Dict:
     52     """Run query through GoogleSearch."""
---> 53     return self._google_serper_search_results(
     54         query,
     55         gl=self.gl,
     56         hl=self.hl,
     57         num=self.k,
     58         tbs=self.tbs,
     59         search_type=self.type,
     60         **kwargs,
     61     )

File /mnt/data/work/sandbox/langchain-test/langchain/foodie/env/lib/python3.10/site-packages/langchain/utilities/google_serper.py:153, in GoogleSerperAPIWrapper._google_serper_search_results(self, search_term, search_type, **kwargs)
    146 params = {
    147     "q": search_term,
    148     **{key: value for key, value in kwargs.items() if value is not None},
    149 }
    150 response = requests.post(
    151     f"[https://google.serper.dev/{](https://google.serper.dev/%7Bsearch_type)[search_type](https://google.serper.dev/%7Bsearch_type)}", headers=headers, params=params
    152 )
--> 153 response.raise_for_status()
    154 search_results = response.json()
    155 return search_results

File /mnt/data/work/sandbox/langchain-test/langchain/foodie/env/lib/python3.10/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   1016     http_error_msg = (
   1017         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1018     )
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 403 Client Error: Forbidden for url: https://google.serper.dev/search?q=oyakodon+recipe&gl=us&hl=en&num=10
```

### Expected behavior

A dict of search results

**Comment by alexcg1** [comment]
I've been doing more testing and this behavior is very inconsistent. Sometimes it works, sometimes not. Tried in local notebook and Colab notebook

**Comment by alexcg1** [comment]
Hmmm....loading env vars from `load_dotenv()` seems to trigger this.

Explicitly stating the env var in the code seems to be fine

**Comment by alexcg1** [comment]
Closing this. Turns out to be a bug in my own code. Whoops!

**Comment by ividal** [comment]
@alexcg1 Can you share what bug that was? I'm on the verge of opening a new issue with very similar symptoms (Forbidden 403 - and adding user-agent to the headers does not solve it). Perhaps I made the same mistake and no need to add that issue...

Thanks!

**Comment by alexcg1** [comment]
@ividal , sorry - it was so long ago that I've completely forgotten about that code. Let me try to dig out the notebook

**Comment by alexcg1** [comment]
@ividal [here](https://colab.research.google.com/drive/1Jofji2a53xLlxTBj6rQd-Nv2WcDzknyH?usp=sharing) you go

**Comment by shinefairy** [comment]
@alexcg1 The new website had moved to https://serper.dev/api-key, After you sign in the new site and paste new key in you code, you can see everything going right.
![1729759919200](https://github.com/user-attachments/assets/5e2db262-8e2d-4533-b5b9-bbe26a2cd3bd)
