### ISSUE TITLE
Enable virtual time in Generative Agents

### ISSUE THREAD

**Issue by ifsheldon** [hwchase17/langchain#4165]
### Feature request

Add extra input to the components of generative agents to enable virtual time instead of wall time

### Motivation

Because generative agents can "live in another world", it makes sense to enable virtual time

### Your contribution

I can submit a PR, in which I modified everything related to `datetime.now()`.

**Comment by rick2047** [comment]
Can you give an example usecase for this? I don't even know where these agents use wall time

**Comment by ifsheldon** [comment]
@rick2047 
> I don't even know where these agents use wall time

You can check my PR.

> Can you give an example usecase for this?

The game in the paper of Generative Agents is exactly the use case.

**Comment by rick2047** [comment]
I went through your PR. Makes more sense now. I had somehow not seen this whole part of the tooling
