### ISSUE TITLE
DOC: Issues with the SageMakerEndpoint example

### ISSUE THREAD

**Issue by schapirama** [hwchase17/langchain#4168]
### Issue with current documentation:

When I run the example from https://python.langchain.com/en/latest/modules/models/llms/integrations/sagemaker.html#example

I first get the following error: 

```
line 49, in <module>
    llm=SagemakerEndpoint(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SagemakerEndpoint
content_handler
  instance of LLMContentHandler expected (type=type_error.arbitrary_type; expected_arbitrary_type=LLMContentHandler)
```

I can replace `ContentHandlerBase` with `LLMContentHandler`.

Then I get the following (against an Alexa 20B model running on SageMaker):

```
An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from primary and could not load the entire response body. See ...
```

The issue, I believe, is here:

```
    def transform_input(self, prompt: str, model_kwargs: Dict) -> bytes:
        input_str = json.dumps({prompt: prompt, **model_kwargs})
        return input_str.encode('utf-8')
```

The Sagemaker endpoints expect a body with `text_inputs` instead of `prompt` (see, e.g. https://aws.amazon.com/blogs/machine-learning/alexatm-20b-is-now-available-in-amazon-sagemaker-jumpstart/):

```
        input_str = json.dumps({"text_inputs": prompt, **model_kwargs})
```

Finally, after these fixes, I get this error:

```
line 44, in transform_output
    return response_json[0]["generated_text"]
KeyError: 0
```

The response body that I am getting looks like this:

```
{"generated_texts": ["Use the following pieces of context to answer the question at the end. Peter and Elizabeth"]}
```

so I think that `transform_output` should do:

```
        return response_json["generated_texts"][0]
```

(That response that I am getting from the model is not very impressive, so there might be something else that I am doing wrong here)

**Comment by sigvamo** [comment]
To use SageMaker embeddings you can use the following example, the one in the LangChain documentation needs to be fixed. There is open issue #5741 related to it, but still not fixed. Putting the code here, if someone faces the same issue:

 ```
from typing import Dict, List
from langchain.embeddings import SagemakerEndpointEmbeddings
from langchain.embeddings.sagemaker_endpoint import EmbeddingsContentHandler
import json

class ContentHandler(EmbeddingsContentHandler):
    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, inputs: list[str], model_kwargs: Dict) -> bytes:
        input_str = json.dumps({"text_inputs": inputs, **model_kwargs})
        return input_str.encode("utf-8")

    def transform_output(self, output: bytes) -> List[List[float]]:
        response_json = json.loads(output.read().decode("utf-8"))
        return response_json["embedding"]

content_handler = ContentHandler()

embeddings = SagemakerEndpointEmbeddings(
    endpoint_name=<SageMaker endpoint_name>,
    region_name=<region>,
    content_handler=content_handler
)
```

**Comment by DirtyPi** [comment]
1 validation error for SagemakerEndpoint
credentials_profile_name
  extra fields not permitted (type=value_error.extra)
