### ISSUE TITLE
DOC: Llama-cpp (CallbackManager)

### ISSUE THREAD

**Issue by yunghoy** [hwchase17/langchain#4195]
### Issue with current documentation:

https://python.langchain.com/en/latest/modules/models/llms/integrations/llamacpp.html

It seems like the example in the document simply does not work due to the code below.

```
from langchain.callbacks.manager import CallbackManager    // Missing CallbackManager
```

I searched the issue in this repository but it seems like there is a problem related to CallbackManager.
Could you fix the code sample?

### Idea or request for content:

Would you be able to mark the document as "Incomplete" document if it does not provide proper example?

**Comment by yunghoy** [comment]
It is added into the 0.0.154

**Comment by kaleavess** [comment]
Hi @yunghoy It is happening again in version 0.0.168.
