### ISSUE TITLE
LLMChain throwing error > value is not a valid

### ISSUE THREAD

**Issue by TechnoRahmon** [hwchase17/langchain#4281]
### System Info

I am getting an error when using LLMChain  with openai model, here is the code :

```python
    # prepare the prompt
    prompt = PromptTemplate(
        input_variables=give_assistance_input_variables,
        template=give_assistance_prompt
    )
    prompt = prompt.format(command=query, context="this is test context")

    tokens = tiktoken_len(prompt)
    print(f"prompt  : {prompt}")
    print(f"prompt tokens : {tokens}")

    llm = OpenAI(
        model_name="text-davinci-003",
        temperature=0,
        #max_tokens=256,
        #top_p=1.0,
        #n=1,
        #best_of=1
    )

    # connect to the LLM
    llm_chain = LLMChain(prompt=prompt, llm=llm)
```

the issue is with line : 
```python
    # connect to the LLM
     llm_chain = LLMChain(prompt=prompt, llm=llm)
```

error : 
**llm_chain = LLMChain(prompt=prompt, llm=llm)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
prompt
  value is not a valid dict (type=type_error.dict)**
  
  **any idea to solve this ?** 

### Who can help?

@hwchase17 
@agola

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

    # prepare the prompt
    prompt = PromptTemplate(
        input_variables=give_assistance_input_variables,
        template=give_assistance_prompt
    )
    prompt = prompt.format(command=query, context="this is test context")

    tokens = tiktoken_len(prompt)
    print(f"prompt  : {prompt}")
    print(f"prompt tokens : {tokens}")

    llm = OpenAI(
        model_name="text-davinci-003",
        temperature=0,
        #max_tokens=256,
        #top_p=1.0,
        #n=1,
        #best_of=1
    )

    # connect to the LLM
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    response = llm_chain.run()

### Expected behavior

I should get a response from openai API

**Comment by vanillechai** [comment]
> prompt = PromptTemplate(
>     input_variables=give_assistance_input_variables,
>     template=give_assistance_prompt
> )

Assuming that `give_assistance_input_variables` and `give_assistance_prompt` are strings, you have now a Prompt in the variable `prompt`.

> prompt = prompt.format(command=query, context="this is test context")

Assuming that `query` is a string, you have now replace the Prompt with a string in `prompt`.

> # connect to the LLM
> llm_chain = LLMChain(prompt=prompt, llm=llm)

LLMChain does not expect a string as `prompt`, hence the error.

See https://python.langchain.com/en/latest/modules/chains/getting_started.html

**Comment by TechnoRahmon** [comment]
> > prompt = PromptTemplate(
> > input_variables=give_assistance_input_variables,
> > template=give_assistance_prompt
> > )
> 
> Assuming that `give_assistance_input_variables` and `give_assistance_prompt` are strings, you have now a Prompt in the variable `prompt`.
> 
> > prompt = prompt.format(command=query, context="this is test context")
> 
> Assuming that `query` is a string, you have now replaced the Prompt with a string in `prompt`.
> 
> > llm_chain = LLMChain(prompt=prompt, llm=llm)
> 
> LLMChain does not expect a string as `prompt`, hence the error.
> 
> See https://python.langchain.com/en/latest/modules/chains/getting_started.html

Thank you @vanillechai 
I just changed the prompt to be PromptTemplate type and it worked

**Comment by mneedham** [comment]
I'm seeing a similar issue when using GPT4All. I have the following code:

```python
import gpt4all
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain import PromptTemplate, LLMChain
from langchain.llms import GPT4All

template = """
You are a friendly chatbot assistant that responds in a conversational
manner to users questions. Keep the answers short, unless specifically
asked by the user to elaborate on something.

Question: {question}

Answer:"""
prompt = PromptTemplate(template=template, input_variables=["question"])

llm = gpt4all.GPT4All(
    model_name="ggml-gpt4all-j-v1.3-groovy",
    model_path="/Users/markhneedham/Library/Application Support/nomic.ai/GPT4All/",
)

print("calling LLMChain#init")
llm_chain = LLMChain(prompt=prompt, llm=llm)
```

And it throws the error on that file line:

```
Traceback (most recent call last):
  File "/Users/markhneedham/projects/docs-bot/gpt4all_chain.py", line 22, in <module>
    llm_chain = LLMChain(prompt=prompt, llm=llm)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markhneedham/projects/docs-bot/env/lib/python3.11/site-packages/langchain/load/serializable.py", line 64, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
```

So I put some `println` in the serializable file and it seems like there's one call with an empty dictionary:

```
calling LLMChain#init
kwargs {'prompt': PromptTemplate(input_variables=['question'], output_parser=None, partial_variables={}, template='\nYou are a friendly chatbot assistant that responds in a conversational\nmanner to users questions. Keep the answers short, unless specifically\nasked by the user to elaborate on something.\n\nQuestion: {question}\n\nAnswer:', template_format='f-string', validate_template=True), 'llm': <gpt4all.gpt4all.GPT4All object at 0x102dbb850>}
kwargs {}
Traceback (most recent call last):
  File "/Users/markhneedham/projects/docs-bot/gpt4all_chain.py", line 22, in <module>
    llm_chain = LLMChain(prompt=prompt, llm=llm)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/markhneedham/projects/docs-bot/env/lib/python3.11/site-packages/langchain/load/serializable.py", line 65, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
```
I got it to print the stack up to that line and this is the output:

```
kwargs {'prompt': PromptTemplate(input_variables=['question'], output_parser=None, partial_variables={}, template='\nYou are a friendly chatbot assistant that responds in a conversational\nmanner to users questions. Keep the answers short, unless specifically\nasked by the user to elaborate on something.\n\nQuestion: {question}\n\nAnswer:', template_format='f-string', validate_template=True), 'llm': <gpt4all.gpt4all.GPT4All object at 0x100a43850>}
  File "/Users/markhneedham/projects/docs-bot/gpt4all_chain.py", line 22, in <module>
    llm_chain = LLMChain(prompt=prompt, llm=llm)
  File "/Users/markhneedham/projects/docs-bot/env/lib/python3.11/site-packages/langchain/load/serializable.py", line 67, in __init__
    traceback.print_stack()

kwargs {}
  File "/Users/markhneedham/projects/docs-bot/gpt4all_chain.py", line 22, in <module>
    llm_chain = LLMChain(prompt=prompt, llm=llm)
  File "/Users/markhneedham/projects/docs-bot/env/lib/python3.11/site-packages/langchain/load/serializable.py", line 68, in __init__
    super().__init__(**kwargs)
  File "/Users/markhneedham/projects/docs-bot/env/lib/python3.11/site-packages/langchain/load/serializable.py", line 67, in __init__
    traceback.print_stack()
```

It's not obvious to me why there are two calls and in the second one the dictionary is empty?

**Comment by mneedham** [comment]
I should also say that if I switch out the `llm` for one from Hugging Face I'm seeing the same empty dictionary passed down, but no validation exception.
