### ISSUE TITLE
Issue: Can not configure serpapi base url via env

### ISSUE THREAD

**Issue by yanghua** [hwchase17/langchain#4328]
### Issue you'd like to raise.

Currently, the base URL of Serpapi is been hard coded.

While some search services(e.g. Bing, `BING_SEARCH_URL`) are configurable.

In some companies, the original can not be allowed to access. We need to use nginx redirect proxy.

So we need to make the base URL configurable via env.

### Suggestion:

Make serpapi base url configurable via env

**Comment by yanghua** [comment]
@hwchase17 WDYT?

**Comment by vowelparrot** [comment]
This makes sense to me. I could review a PR
