### ISSUE TITLE
https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2 not found? HTTP 401

### ISSUE THREAD

**Issue by jeannekamikaze** [hwchase17/langchain#4379]
### System Info

langchain 0.0.162
python 3.8
HuggingFace free tier server

### Information

- [x] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.embeddings import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings()
```

```
/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/user/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 2, in <module>
    embeddings = HuggingFaceEmbeddings()
  File "/home/user/.local/lib/python3.8/site-packages/langchain/embeddings/huggingface.py", line 54, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/home/user/.local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "/home/user/.local/lib/python3.8/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1604, in model_info
    hf_raise_for_status(r)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6459cb14-023db7f06244e0660677dfb9)
```

### Expected behavior

Successfully creates an embeddings model.

**Comment by jeannekamikaze** [comment]
This appears to be the default model for `HuggingFaceEmbeddings` in langchain 0.0.162:

https://python.langchain.com/en/latest/_modules/langchain/embeddings/huggingface.html

But the URL does not appear to be valid (or has it moved?):

https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2

**Comment by pulkitmehtawork** [comment]
For me , it is working .. I also installed sentence transformer lib in my env before running below 
pip install sentence_transformers

>>> from langchain.embeddings import HuggingFaceEmbeddings
>>> embeddings = HuggingFaceEmbeddings()
>>> embeddings
HuggingFaceEmbeddings(client=SentenceTransformer(
  (0): Transformer({'max_seq_length': 384, 'do_lower_case': False}) with Transformer model: MPNetModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Normalize()
), model_name='sentence-transformers/all-mpnet-base-v2', cache_folder=None, model_kwargs={})

**Comment by Vikkas-goel** [comment]
Which langchain version you are using ... 

i have used both 0.0.160 and 0.0.162 

same result

**Comment by aaroncueckermann** [comment]
I am getting a similar issue when trying to boot all-MiniLM-L6-v2 in a docker container

`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2`

**Comment by NiVisser** [comment]
Same here, it worked just about 12 hours ago...

**Comment by pulkitmehtawork** [comment]
must be my local one .

**Comment by pulkitmehtawork** [comment]
temp workaround provided in hugging face issue by some user .. you may download models from below https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/      . Issue reference - https://github.com/UKPLab/sentence-transformers/issues/1915#issuecomment-1539617923

**Comment by jeannekamikaze** [comment]
The workaround works, thank you, and the sentence-transformer's copy of the model is also back up.
