### ISSUE TITLE
Do Q/A with csv agent and multiple txt files at the same time.

### ISSUE THREAD

**Issue by tianshubao1** [hwchase17/langchain#4423]
### Issue you'd like to raise.

I want to do Q/A with csv agent and multiple txt files at the same time. But I do not want to use csv loader and txt loader because they did not perform very well when handling cross file scenario. For example, the model needs to find answers from both the csv and txt file and then return the result.

How should I do it? I think I may need to create a custom agent.

**Comment by vowelparrot** [comment]
You could try giving the agent access to a ReadFile tool and the CSV agent.

**Comment by tianshubao1** [comment]
> You could try giving the agent access to a ReadFile tool and the CSV agent.

Would you mind I ask how to do it?

**Comment by Mohammedvaraliya** [comment]
Yes yes you can do this, checkout this github repo where i am training my txt files and csv too

github repo url : https://github.com/Mohammedvaraliya/chatbot-with-custom-knowledge-testing

right now, you wont see any csv file on my context data directory, becuase i have tried to ask the question which was related to that csv file, the bot had respond me but not that much good, i would say, we have to format our csv in a right format, then only it will able to give accurate response

**Comment by ViolaSongsy** [comment]
I tried using multiple tools and created an agent with those tools. The tools include dataframe tool and directoryloader tool. The answers were really good compared with directly asking the tool. Does anyone have ideas on how to improve this?

**Comment by tianshubao1** [comment]
> I tried using multiple tools and created an agent with those tools. The tools include dataframe tool and directoryloader tool. The answers were really good compared with directly asking the tool. Does anyone have ideas on how to improve this?

Would you mind sharing your code? Thanks

**Comment by alinayawar** [comment]
![3](https://github.com/hwchase17/langchain/assets/58339227/f07c9a17-629a-478d-983e-fda41e17fd38)
![2](https://github.com/hwchase17/langchain/assets/58339227/b1d0d8b1-e3b7-440c-a857-d7d489fedf6c)
 
Actually, I am having an issue with the agent. When the agent finds the right Dataframe and columns then the agent should stop the observation but the agent still doing observation multiple times. I want the agent to just give the final answer with the right observation. 

kindly suggest something how can I overcome this issue.
