### ISSUE TITLE
Add huggingface tokenizer support for splitting text

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchain#45]
Would be good to have some methods that split on tokens as in the OpenAI example

https://github.com/openai/openai-cookbook/blob/459afa7d9bf026c4434f54458dc7d9e7d9f9f5fe/examples/Obtain_dataset.ipynb

**Comment by hadsed** [comment]
So NLTK's sentence and word tokenizers are pretty robust and fast.

(Leaving the [module link here](https://github.com/hwchase17/langchain/blob/master/langchain/text_splitter.py) for easy reference)
