### ISSUE TITLE
Problem with SelfQueryRetriever

### ISSUE THREAD

**Issue by Dmaturana81** [hwchase17/langchain#4587]
### System Info

Mac OSX10.16
python 3.9
langchain 0.0.166

### Who can help?

@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am following the example for the SelfQueryRetriever (https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/self_query_retriever.html), but I am using Chroma

When I try to create the SelfQueryRetriever from llm_chain 
SelfQueryRetriever.from_llm(
    vectorstore=db_chroma,
    llm=llm,
    document_contents=document_content_info,
    metadata_field_info=metadata_field_info
)

or I try to create the chain with 
load_query_constructor_chain(
    llm=llm, 
    document_contents=document_content_info,
    attribute_info=metadata_field_info,
    allowed_comparators=ChromaTranslator.allowed_comparators,
    allowed_operators=ChromaTranslator.allowed_operators)

 I receive the same error:
def get_parser(
    126     allowed_comparators: Optional[Sequence[Comparator]] = None,
    127     allowed_operators: Optional[Sequence[Operator]] = None,
    128 ) -> Lark:
--> 129     transformer = QueryTransformer(
    130         allowed_comparators=allowed_comparators, allowed_operators=allowed_operators
    131     )
    132     return Lark(GRAMMAR, parser="lalr", transformer=transformer, start="program")

TypeError: 'NoneType' object is not callable

I tried to create a QueryTransformer as follow:
QueryTransformer(allowed_comparators=ChromaTranslator.allowed_comparators,
    allowed_operators=ChromaTranslator.allowed_operators)

Same error.

### Expected behavior

I would expect to create the selfQueryRetriever to be able to retrieve the documents from the retriever.

**Comment by dev2049** [comment]
believe you need to pip install lark

**Comment by dev2049** [comment]
also for chroma can use this notebook: https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/chroma_self_query_retriever.html

**Comment by Dmaturana81** [comment]
I did think the same, but I installed and did fix the problem
Name: lark
Version: 1.1.5
Summary: a modern parsing library
Home-page: https://github.com/lark-parser/lark
Author: Erez Shinan
Author-email: erezshin@gmail.com
License: MIT

**Comment by Dmaturana81** [comment]
Hi @hwchase17 , yes I did follow that notebook as well (they are pretty similar) but still with the problem.

**Comment by Dmaturana81** [comment]
Ja, I needed to restart the kernel, jsut that. Demed
