### ISSUE TITLE
Getting time our while trying to use HuggingFaceHub

### ISSUE THREAD

**Issue by moshere** [hwchase17/langchain#461]
Hi,
I'm trying to use LLM chain with HuggingFaceHub (facebook/opt-1.3b) and I'm getting time out error:
`ValueError: Error raised by inference API: Model facebook/opt-1.3b time out`

I would like to know if I'm doing something wrong? or there is a real issue.
This is my [collab](https://colab.research.google.com/drive/158xobl37kvMlvAvwzmSngENYm3GvrFlC?usp=sharing
).

Appreciate your assistance.

**Comment by hwchase17** [comment]
this is likely an issue on hugging face's end. are you able to access other models?

**Comment by moshere** [comment]
Yes, seems you're right. Other models worked ok. Thank you
