### ISSUE TITLE
SQLDatabaseChain has no attribute from_llm

### ISSUE THREAD

**Issue by akash-ravikumar** [hwchase17/langchain#4618]
### System Info

langchain==0.0.167
python=3.10.10
system: Windows

### Who can help?

@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`# !pip install langchain==0.0.167

from langchain import OpenAI, SQLDatabase, SQLDatabaseChain

db = SQLDatabase.from_uri("mysql+pymysql://user:pass@some_mysql_db_address/db_name")
llm = OpenAI(temperature=0, verbose=True)

db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)

db_chain.run("How many employees are there?")
`

### Expected behavior

Should not throw AttributeError: type object 'SQLDatabaseChain' has no attribute 'from_llm'

**Comment by lohithreddy2002** [comment]
seems to work fine for me, can you check the version of langchain once

**Comment by akash-ravikumar** [comment]
Whatever the problem was, I'm not able to reproduce it after reinstalling langchain. Closing the issue as it's probably installation related.

**Comment by linhmx** [comment]
same error happened to me. pleaes let me know if you find the solution.

**Comment by lohithreddy2002** [comment]
Try reinstalling langchain or install a newer version

**Comment by linhmx** [comment]
I updated langchain but still the same error

**Comment by FangNera** [comment]
could you give me the version number? same error to me.
