### ISSUE TITLE
OpenAIEmbeddings has "AuthenticationError"

### ISSUE THREAD

**Issue by avishaan** [hwchase17/langchain#4639]
### System Info

Google Colab

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from langchain.embeddings.openai import OpenAIEmbeddings
embeder = OpenAIEmbeddings(openai_api_key="redacted_api_key")
query_result = embeder.embed_query("show us the embeddings")
```

causes the following error
```
AuthenticationError                       Traceback (most recent call last)
[<ipython-input-30-45e396cd020f>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 embeddings = OpenAIEmbeddings(openai_api_key="key")
----> 7 docsearch = Chroma.from_documents(texts,embeddings)

17 frames
[/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    685         stream_error = stream and "error" in resp.data
    686         if stream_error or not 200 <= rcode < 300:
--> 687             raise self.handle_error_response(
    688                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    689             )

AuthenticationError: <empty message>
```

### Expected behavior

Expected there to be no error message. I also checked that my API key is working

**Comment by Badrul-Goomblepop** [comment]
Just so it's clear for others that get the same error, make sure you have a line that says:
embeddings = OpenAIEmbeddings(openai_api_key="YOUR API KEY")
