### ISSUE TITLE
Error in on_llm callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_llm'

### ISSUE THREAD

**Issue by princelai** [hwchase17/langchain#4714]
### System Info

langchain version:0.0.168
python version 3.10

### Who can help?

@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

When using the RetrievalQA chain, an error message "Error in on_llm callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_llm'"

This code can run at version 0.0.164

```python

class Chain:
    def __init__(self):
        self.cb_mngr_stdout = AsyncCallbackManager([StreamingStdOutCallbackHandler()])
        self.cb_mngr_aiter = AsyncCallbackManager([AsyncIteratorCallbackHandler()])
        self.qa_stream = None
        self.qa = None

        self.make_chain()

    def make_chain(self):
        chain_type_kwargs = {"prompt": MyPrompt.get_retrieval_prompt()}
        qa = RetrievalQA.from_chain_type(llm=ChatOpenAI(model_name="gpt-3.5-turbo", max_tokens=1500, temperature=.1), chain_type="stuff",
                                         retriever=Retrieval.vectordb.as_retriever(search_kwargs={"k": Retrieval.context_num}),
                                         chain_type_kwargs=chain_type_kwargs, return_source_documents=True)
        qa_stream = RetrievalQA.from_chain_type(llm=ChatOpenAI(model_name="gpt-3.5-turbo", max_tokens=1500, temperature=.1,
                                                               streaming=True, callback_manager=self.cb_mngr_aiter),
                                                chain_type="stuff", retriever=Retrieval.vectordb.as_retriever(search_kwargs={"k": Retrieval.context_num}),
                                                chain_type_kwargs=chain_type_kwargs, return_source_documents=True)
        self.qa = qa
        self.qa_stream = qa_stream

```

call function
```python
resp = await chains.qa.acall({"query": "xxxxxxx"}) # no problem
resp = await chains.qa_stream.acall({"query": "xxxxxxxx"}) # error
```

### Expected behavior

self.qa_stream return result like self.qa,or like langchain version 0.0.164

**Comment by bjk95** [comment]
Same issue here when using the AsyncCallbackHandler. 

Error in on_llm callback: 'StreamingCallbackHandler' object has no attribute 'on_llm'

**Comment by jordanparker6** [comment]
Same issue, but the `OpenAICallbackHandler` is also raising this error as well.
