### ISSUE TITLE
Issue: Weaviate: why similarity_search uses with_near_text?

### ISSUE THREAD

**Issue by hsm207** [hwchase17/langchain#4742]
### Issue you'd like to raise.

[similarity_search](https://github.com/hwchase17/langchain/blob/09587a32014bb3fd9233d7a567c8935c17fe901e/langchain/vectorstores/weaviate.py#L174-L175) in weaviate uses near_text.

This requires weaviate to be set up with a [text2vec module](https://weaviate.io/developers/weaviate/modules/retriever-vectorizer-modules).

At the same time, the weaviate also takes an [embedding model](https://github.com/hwchase17/langchain/blob/09587a32014bb3fd9233d7a567c8935c17fe901e/langchain/vectorstores/weaviate.py#L86) as one of it's init parameters.

Why don't we use the embedding model to vectorize the search query and then use weaviate's near_vector operator to do the search?

### Suggestion:

If a user is using langchain with weaviate, we can assume that they want to use langchain's features to generate the embeddings and as such, will not have any text2vec module enabled.

**Comment by dev2049** [comment]
what's the concrete suggestion here (like the code change)?

**Comment by hsm207** [comment]
if the team agrees with the suggestion, then the code change is to rewrite similarity_search so that it embeds the query using the embedding model the class was initialised with and then passes it to similarity_search_by_vector

**Comment by dev2049** [comment]
i'm for it. feel free to open a PR, otherwise I can get to it in a few hours

**Comment by hwchase17** [comment]
can we have a way to toggle between the two? eg keep both functionality and let the user decide?

**Comment by hsm207** [comment]
> can we have a way to toggle between the two? eg keep both functionality and let the user decide?

@hwchase17 sure. PR #4365 supports this requirement. We can close this issue once that PR is merged
