### ISSUE TITLE
some thing wrong with tracing

### ISSUE THREAD

**Issue by jyC23333** [hwchase17/langchain#4762]
### System Info

I just set up a local tracing server, I change the port to 8005.
![image](https://github.com/hwchase17/langchain/assets/110331827/b06d5948-1676-46b6-a8e3-3c4e01cf35e8)
when I visit localhost:4173, It shows:
![image](https://github.com/hwchase17/langchain/assets/110331827/abae4119-1c2d-4470-9ba2-1986f6762e65)
and the error is:
```
langchain-langchain-frontend-1  |   ➜  Local:   http://localhost:4173/
langchain-langchain-frontend-1  |   ➜  Network: http://172.18.0.4:4173/
langchain-langchain-backend-1   | INFO:     Application startup complete.
langchain-langchain-backend-1   | INFO:     Uvicorn running on http://0.0.0.0:8005 (Press CTRL+C to quit)
langchain-langchain-frontend-1  | TypeError: fetch failed
langchain-langchain-frontend-1  |     at fetch (/app/node_modules/undici/index.js:105:13)
langchain-langchain-frontend-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
langchain-langchain-frontend-1  |     at async fetchData (file:///app/.svelte-kit/output/server/entries/pages/sessions/_page.server.ts.js:7:17)
langchain-langchain-frontend-1  |     at async file:///app/.svelte-kit/output/server/index.js:489:86
langchain-langchain-frontend-1  |     at async Promise.all (index 0)
langchain-langchain-frontend-1  |     at async unwrap_promises (file:///app/.svelte-kit/output/server/index.js:489:9)
langchain-langchain-frontend-1  |     at async load_server_data (file:///app/.svelte-kit/output/server/index.js:537:25)
langchain-langchain-frontend-1  |     at async file:///app/.svelte-kit/output/server/index.js:1500:18
```

### Who can help?

@agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

run ```langchain-server``` in terminal 

### Expected behavior

how to fix this bug?

**Comment by flavorfan** [comment]
Same issue. Check the log:
langchain-langchain-db-1        | performing post-bootstrap initialization ... ok
langchain-langchain-backend-1   | INFO:     Started server process [1]
langchain-langchain-backend-1   | INFO:     Waiting for application startup.
langchain-langchain-backend-1   | ERROR:    Traceback (most recent call last):
langchain-langchain-backend-1   |   File "/usr/local/lib/python3.10/site-packages/pg8000/core.py", line 214, in __init__
langchain-langchain-backend-1   |     self._usock = socket.create_connection(
langchain-langchain-backend-1   |   File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
langchain-langchain-backend-1   |     raise err
langchain-langchain-backend-1   |   File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
langchain-langchain-backend-1   |     sock.connect(sa)
langchain-langchain-backend-1   | ConnectionRefusedError: [Errno 111] Connection refused

it seem like is network problem of container.

**Comment by jyC23333** [comment]
I fixed this, thanks.
It seems that I have to change the IP manually.
By the way, the backend port must be set to 8000.

But I still don't know why this works.

![image](https://github.com/hwchase17/langchain/assets/110331827/ba28c8f1-3582-4452-936d-1513dfca781b)
