### ISSUE TITLE
Resource does not exists when using both OpenAIEmbeddings and AzureChatOpenAI in two different Azure region/ endpoints

### ISSUE THREAD

**Issue by Pilosite** [hwchase17/langchain#4819]
### System Info

langchain 171, gpt4 model in a region, text-embedding-ada002 in another

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Create an embedding on ADA002 in a region, with os.environ settings :
 os.environ["OPENAI_API_TYPE"] = "azure"
    os.environ["OPENAI_API_KEY"] = ""
    os.environ["OPENAI_API_BASE"] = ""
    os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"
    embeddings = OpenAIEmbeddings(model="")  
 text = "This is a test document." 
    embeddings.embed_query(text) 

this works.

If I try to add a LLM to do later doc retrieval, like this I got the followin exception:
Create an embedding on ADA002 in a region, with os.environ settings :
 os.environ["OPENAI_API_TYPE"] = "azure"
    os.environ["OPENAI_API_KEY"] = ""
    os.environ["OPENAI_API_BASE"] = ""
    os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"
    embeddings = OpenAIEmbeddings(model="")  

    llm = AzureChatOpenAI( 
        openai_api_key = "",
        openai_api_base = "",
        model_name=""
    )        
    
    #result = llm([HumanMessage(content="Translate this sentence from English to French. I love programming.")])
    #print(result)
    text = "This is a test document." 
    embeddings.embed_query(text)  

Exception has occurred: InvalidRequestError
The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

### Expected behavior

I should be able to have 2 distincts GPT and ADA setup not on the same API base.

**Comment by Pilosite** [comment]
I think the issue is  that both AzureChatOpenAI and OpenAIEmbedding import openai module and set openai.api_type = openai_api_type
            openai.api_base = openai_api_base
            openai.api_version = openai_api_version
            openai.api_key = openai_api_key, and this change the openai global context

**Comment by Pilosite** [comment]
related to this: https://github.com/hwchase17/langchain/issues/4775 we can close this one

**Comment by Pilosite** [comment]
related to this one : https://github.com/hwchase17/langchain/issues/4775

**Comment by SSabev** [comment]
@Pilosite did you solve this somehow?

**Comment by Pilosite** [comment]
@SSabev yes there is a workaround [her](https://github.com/hwchase17/langchain/issues/4775)e and a PR is in progress to solve this natively

**Comment by vermaat** [comment]
For me the following fixed this by not using the environment variables but by passing them in during creation of `OpenAIEmbeddings`

https://github.com/langchain-ai/langchain/issues/8687#issuecomment-1673345226

**Comment by truedat101** [comment]
Based on @vermaat ... this is the work around.  Also, worth adding, this affects use of ChatOpenAI / AzureChatOpenAI api calls as well.  The only workaround found after several hours of experimentation was **not** using environment variables.  Not sure why that would be the case, but I have observed problems on other projects not using the same pathways to evaluate internal state when dealing with Environment Variables vs .env files, vs api calls.  This is probably a bug in the handling of reading from the environment.
