### ISSUE TITLE
pinecone.similarity_search -> TypeError: OpenAIEmbeddings.embed_query() missing 1 required positional argument: 'text'

### ISSUE THREAD

**Issue by virtustate** [hwchase17/langchain#4821]
### System Info

LangChain 0.0.171, Python 3.10.10

running the code:

index = pinecone.Index('ssk')
print(index.describe_index_stats())
vectorstore = Pinecone(index=index, embedding_function=OpenAIEmbeddings.embed_query, text_key='text')
documents = vectorstore.similarity_search('How can several llama_indexes be composed?')

print(index.describe_index_stats()) gives the following
{'dimension': 1536,
 'index_fullness': 0.0,
 'namespaces': {'': {'vector_count': 335}},
 'total_vector_count': 335}

but gives an error in the vectorstore.similarity_search call

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[46], line 4
      2 print(index.describe_index_stats())
      3 vectorstore = Pinecone(index=index, embedding_function=OpenAIEmbeddings.embed_query, text_key='text')
----> 4 documents = vectorstore.similarity_search('How can several llama_indexes be composed?')

File ~/anaconda3/envs/langchain_play/lib/python3.10/site-packages/langchain/vectorstores/pinecone.py:155, in Pinecone.similarity_search(self, query, k, filter, namespace, **kwargs)
    136 def similarity_search(
    137     self,
    138     query: str,
   (...)
    142     **kwargs: Any,
    143 ) -> List[Document]:
    144     """Return pinecone documents most similar to query.
    145 
    146     Args:
   (...)
    153         List of Documents most similar to the query and score for each
    154     """
--> 155     docs_and_scores = self.similarity_search_with_score(
    156         query, k=k, filter=filter, namespace=namespace, **kwargs
    157     )
    158     return [doc for doc, _ in docs_and_scores]

File ~/anaconda3/envs/langchain_play/lib/python3.10/site-packages/langchain/vectorstores/pinecone.py:115, in Pinecone.similarity_search_with_score(self, query, k, filter, namespace)
    113 if namespace is None:
    114     namespace = self._namespace
--> 115 query_obj = self._embedding_function(query)
    116 docs = []
    117 results = self._index.query(
    118     [query_obj],
    119     top_k=k,
   (...)
    122     filter=filter,
    123 )

TypeError: OpenAIEmbeddings.embed_query() missing 1 required positional argument: 'text'

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

run code like:

index = pinecone.Index('ssk')
print(index.describe_index_stats())
vectorstore = Pinecone(index=index, embedding_function=OpenAIEmbeddings.embed_query, text_key='text')
documents = vectorstore.similarity_search('How can several llama_indexes be composed?')

### Expected behavior

for a valid pinecone index, expect documents to be populated without error

**Comment by ceniy** [comment]
I have the same issue before. What I found is that I passed a wrong parameter to the embedding_function.

Wrong:
from langchain.embeddings.openai import OpenAIEmbeddings
embedding_function=OpenAIEmbeddings

Correct:
from langchain.embeddings.openai import OpenAIEmbeddings
embedding_function=OpenAIEmbeddings()

**Comment by virtustate** [comment]
Here's working code:

index = pinecone.Index('ssk')
print(index.describe_index_stats())
vectorstore = Pinecone.**from_existing_index**(index_name='ssk', embedding=OpenAIEmbeddings(), namespace='github-llama-index')
documents = vectorstore.similarity_search('How can several llama_indexes be composed?')
len(documents)

**Comment by shiny-caroline** [comment]
@virtustate Does this line vectorstore = Pinecone.from_existing_index(index_name='ssk', embedding=OpenAIEmbeddings(), namespace='github-llama-index') work for you?
