### ISSUE TITLE
Handling Errors in SQL Statements That Involve Multiple Table Joins

### ISSUE THREAD

**Issue by merikoxuren** [hwchase17/langchain#4832]
### System Info

I encountered an issue when executing a SQL statement that involves joining multiple tables. I am working with a SQL Server database, and the following SQL query is returning an error:

SELECT TOP 50000 [StoreNo], [StoreName], [Quantity], [GoodsName], [GoodsNo] 
FROM [JBStore] 
JOIN [CKCurrStore] ON [JBStore].[StoreNo] = [CKCurrStore].[StoreNo] 
JOIN [JBGoods] ON [CKCurrStore].[GoodsNo] = [JBGoods].[GoodsNo]

The error seems to arise because the [StoreNo] and [GoodsNo] fields are not prefixed with the table names, which causes the query to fail.

Here are my table definitions:
table_info = {
    "CKXSCheck": """
        CREATE TABLE CKXSCheck (
            "OrderNo" VARCHAR PRIMARY KEY, 
            "OrderDate" DATETIME,
            "Amount" REAL, 
            "InOutTypeNo" INTEGER, 
            "CKAmount" REAL,
            PRIMARY KEY ("OrderNo")
        )""",
    "CKXSCheckDetail": """
        CREATE TABLE CKXSCheckDetail (
            "OrderNo" VARCHAR,
            "SerialNo" INTEGER,
            "GoodsNo" INTEGER,
            "Amount" REAL,
            "Quantity" REAL,
            "Price" REAL,
            PRIMARY KEY ("OrderNo", "SerialNo"),
            FOREIGN KEY ("OrderNo") REFERENCES CKXSCheck("OrderNo"),
            FOREIGN KEY ("GoodsNo") REFERENCES JBGoods("GoodsNo")
        )""",
    "JBGoods": """
        CREATE TABLE JBGoods (
            "GoodsNo" INTEGER PRIMARY KEY,
            "GoodsCode" VARCHAR,
            "GoodsName" VARCHAR,
            PRIMARY KEY ("GoodsNo")
        )""",
    "CKCurrStore": """
        CREATE TABLE CKCurrStore (
            "StoreNo" VARCHAR,
            "GoodsNo" VARCHAR,
            "Quantity" REAL,
            FOREIGN KEY ("StoreNo") REFERENCES CKXSCheck("JBStore"),
            FOREIGN KEY ("GoodsNo") REFERENCES JBGoods("GoodsNo")
        )""",
    "JBStore": """
        CREATE TABLE JBStore (
            "StoreNo" VARCHAR PRIMARY KEY,
            "StoreName" VARCHAR,
            PRIMARY KEY ("StoreNo")
        )""",
}

How can I resolve this issue?

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [x] Embedding Models
- [x] Prompts / Prompt Templates / Prompt Selectors
- [x] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Send a request to the '/api/query' endpoint

### Expected behavior

import os
import sqlite3
import pymssql
import tkinter as tk
import tkinter.ttk as ttk
from langchain.agents import create_sql_agent, ZeroShotAgent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain import OpenAI, SQLDatabase, SQLDatabaseChain
from langchain.prompts.prompt import PromptTemplate
from typing import Dict, Any
from langchain import LLMChain
from typing import Any, List, Tuple
from urllib.parse import quote_plus as urlquote
from sqlalchemy import create_engine
from sqlalchemy.engine import reflection
from sqlalchemy import inspect
from sqlalchemy.orm import sessionmaker
import pandas as pd
from sqlalchemy.sql import text as sql_text
from sqlalchemy import Table, MetaData, select
from sqlalchemy.sql import text
import json
import decimal
import datetime
import time
from sql_utils import add_table_prefix_to_columns

from flask import Flask, request, render_template,jsonify

import re
#查询全部商品
#查询销售额前100的所有商品
#查询库存数量明细表 显示仓库序号 仓库名称 数量 商品名称 商品序号
# 替换为你的 API 密钥
 
# Customized English prompt
_DEFAULT_TEMPLATE = """You are an MS SQL expert. Given an input question, first create a syntactically correct MS SQL query to run, then look at the results of the query and return the answer to the input question. Note that you should never perform any operations that could modify the database. This includes UPDATE, DELETE, or INSERT operations. Your job is only to read data and answer questions.
Unless the user specifies in the question a specific number of examples to obtain, query for 50000 results using the TOP clause as per MS SQL. You can order the results to return the most informative data in the database.
Never query for all columns from a table. You must query only the columns that are needed to answer the question. Wrap each column name in square brackets ([]) to denote them as delimited identifiers.
Pay attention to use only the column names you can see in the tables below. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.
Use the following format:
Question: "Question here"
SQLQuery: "SQL Query to run"
SQLResult: "Result of the SQLQuery" 

Only use the following tables:
{table_info}
Question: {input}"""

PROMPT = PromptTemplate(
    input_variables=["input", "table_info"], template=_DEFAULT_TEMPLATE
)
custom_table_info_OLD= {
    "v_CKXSDetail": """CREATE TABLE v_CKXSDetail (
        "OrderNo" VARCHAR , -- 单据编号，
        "OrderDate":DATETime,-- 销售日期 
        "GoodsCode":VARCHAR,-- 商品编号 
        "GoodsName":VARCHAR,-- 商品名称 
        "OrderDate":DATETime,-- 销售日期 
        
        "Amount" numeric(18,2), --  销售金额,
        "InOutTypeNo" INTEGER, -- 值为2表示退货
        "Quantity" INTEGER, -- 销售数量
        "CKAmount" REAL--  成本金额
  
    )"""}
custom_table_info = {
    "CKXSCheck": """CREATE TABLE CKXSCheck (
        "OrderNo" VARCHAR PRIMARY KEY, -- 单号，字符型主键
        "OrderDate":DATETime,-- 销售日期 
        "Amount" REAL, --  整单销售金额,(case InOutTypeNo when 2 then -Amount else Amount end)
        "InOutTypeNo" INTEGER, -- 值为2表示退货
        "CKAmount" REAL,--  整单成本金额
        PRIMARY KEY ("OrderNo"), -- 将 OrderNo 主键
    )""",
    "CKXSCheckDetail": """CREATE TABLE CKXSCheckDetail (
        "OrderNo" VARCHAR, -- 单号 ，外键
        "SerialNo" INTEGER, -- 序列号 ，主键
        "GoodsNo" INTEGER, -- 商品序号，外键
        "Amount" REAL, --  商品销售金额
        "Quantity" REAL, --  商品销售数量
        "Price" REAL, --  销售单价
        PRIMARY KEY ("OrderNo", "SerialNo"), -- 将 OrderNo 和 SerialNo 设为联合主键
        FOREIGN KEY ("OrderNo") REFERENCES CKXSCheck("OrderNo"), -- OrderNo 是 CKXSCheck 表的外键
        FOREIGN KEY ("GoodsNo") REFERENCES JBGoods("GoodsNo") -- GoodsNo 是 JBGoods 表的外键
    )""",
    "JBGoods": """CREATE TABLE JBGoods (
        "GoodsNo" INTEGER PRIMARY KEY, -- 商品序号，主键
        "GoodsCode" VARCHAR, -- 商品编号
        "GoodsName" VARCHAR, -- 商品名称
         PRIMARY KEY ("GoodsNo") -- 将 GoodsNo 设为主键
    )""",
   "CKCurrStore": """CREATE TABLE CKCurrStore (
        "StoreNo" VARCHAR, -- 仓库序号，外键
        "GoodsNo" VARCHAR, -- 商品序号，外键
        "Quantity" REAL, -- 库存数量
        FOREIGN KEY ("StoreNo") REFERENCES CKXSCheck("JBStore"), -- StoreNo 是 JBStore 表的外键
        FOREIGN KEY ("GoodsNo") REFERENCES JBGoods("GoodsNo") -- GoodsNo 是 JBGoods 表的外键
    )""",
  "JBStore": """CREATE TABLE JBStore (
       "StoreNo" VARCHAR, -- 仓库序号，主键
       "StoreName" VARCHAR, -- 仓库名称
       PRIMARY KEY ("StoreNo") -- 将 GoodsNo 设为主键
   )""",
}

db = SQLDatabase.from_uri(f"mssql+pymssql://{user_name}:{urlquote(psw)}@{ip}/{database}", include_tables=['CKXSCheck', 'CKXSCheckDetail', 'JBGoods', 'CKCurrStore', 'JBStore'], custom_table_info=custom_table_info)

llm=OpenAI(temperature=0)

class CustomSQLQueryChain(SQLDatabaseChain):
    def _call(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        prompt = self.prompt or SQL_PROMPTS.get(self.database.dialect, PROMPT)

        llm_chain = LLMChain(llm=self.llm, prompt=prompt)
        input_text = f"{inputs[self.input_key]}\nSQLQuery:"
        self.callback_manager.on_text(input_text, verbose=self.verbose)
        table_names_to_use = inputs.get("table_names_to_use")
        table_info = self.database.get_table_info(table_names=table_names_to_use)
        llm_inputs = {
            "input": input_text,
            "top_k": self.top_k,
            "dialect": self.database.dialect,
            "table_info": table_info,
            "stop": ["\nSQLResult:"],
        }
        intermediate_steps = []
        sql_cmd = llm_chain.predict(**llm_inputs).strip()  # simplified this line
        intermediate_steps.append({"SQLQuery": sql_cmd})
        self.callback_manager.on_text(sql_cmd, color="green", verbose=self.verbose)

        chain_result: Dict[str, Any] = {
            "intermediate_steps": intermediate_steps,
            "result": sql_cmd,
        }

        return chain_result

custom_db_chain = CustomSQLQueryChain(llm=llm, database=db, prompt=PROMPT, verbose=True, return_intermediate_steps=True)

def display_table(tree, columns, data):
    print(data)
    print(columns)

    # 删除所有的列
    tree['columns'] = []

    # 重新设置列
    tree["columns"] = columns
    tree["show"] = "headings"

    for col in columns:
        tree.heading(col, text=col)
        tree.column(col, width=100)

    # 删除所有的数据
    for i in tree.get_children():
        tree.delete(i)

    # 插入新的数据
    for row in data:
        tree.insert("", "end", values=row)

root = tk.Tk()
root.title("Chat with your Tabular Data")

entry = ttk.Entry(root, font=("Arial", 14))
entry.pack(padx=20, pady=20, fill=tk.X)

def get_chinese_col_names(field_names, conn):
    # 使用 XTSQLField 表查询中文列名
    field_names_str = ', '.join(f"'{field_name}'" for field_name in field_names)  # 将字段名列表转换为适合SQL查询的字符串
    query = f"""
    WITH numbered_rows AS (
        SELECT SqFieldName, 
               (CASE SqFieldName WHEN 'GoodsCode' THEN '商品编号' WHEN 'GoodsName'  THEN '商品名称' WHEN 'Quantity'  THEN '数量' ELSE CClientName END) as CClientName, 
               ROW_NUMBER() OVER (PARTITION BY SqFieldName ORDER BY CClientName) AS rn
        FROM XTSQLField
        WHERE SqFieldName in ({field_names_str})  
        AND ASCII(LEFT(CClientName, 1)) > 127  -- 添加这个条件以仅选择CClientName为中文的行
    )
    SELECT SqFieldName, CClientName
    FROM numbered_rows
    WHERE rn = 1;
    """
    print(query)

    result_proxy = conn.execute(query)
    name_mapping = {row['SqFieldName']: row['CClientName'] for row in result_proxy}  # 创建一个字段名到中文名的映射字典

    chinese_col_names = []
    for field_name in field_names:
        chinese_name = name_mapping.get(field_name, field_name)  # 如果没有找到中文名，就使用原始的字段名
        chinese_col_names.append(chinese_name)

    return chinese_col_names

class DecimalEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, decimal.Decimal):
            return float(obj)
        return super(DecimalEncoder, self).default(obj)

app = Flask(__name__)

#分页查询
@app.route('/api/get-messages', methods=['POST'])
def get_messages():
    # 获取前端传过来的分页参数
    page = request.args.get('page', default = 1, type = int)

    # 连接数据库
    engine = create_engine(f"mssql+pymssql://{user_name}:{urlquote(psw)}@{ip}/{database}")
    metadata = MetaData(bind=engine)

    # 创建一个表对象，反映AiQuery表
    AiQuery = Table('AiQuery', metadata, autoload_with=engine)

    with engine.connect() as conn:
        # 查询AiQuery表
        pagesize = 4
        select_stmt = select(AiQuery).order_by(AiQuery.columns.ID.desc()).limit(pagesize).offset((page - 1) * pagesize)
        result_proxy = conn.execute(select_stmt)

        # 将 LegacyRow 对象转换为字典
        result_data = [dict(row) for row in result_proxy.fetchall()]

    # 根据你的需求格式化返回的数据
    messages = []
    for data in result_data:
        messages.append({
            "text": data['QueryStr'],
            "time": data['UsedTime'],
            "records": data['ResultRecords'],
            "timestamp": data['CreateDate'].strftime("%Y-%m-%d %H:%M"),  # 将日期转换为字符串
            "id": data['ID']
        })

    return jsonify(messages)

@app.route('/api/query', methods=['POST'])
def do_query():
    data = request.get_json()
    query = data.get('query')
    start_time = time.time()  # 记录查询开始的时间

    engine = create_engine(f"mssql+pymssql://{user_name}:{urlquote(psw)}@{ip}/{database}")
    metadata = MetaData(bind=engine)

    # 创建一个表对象，反映AiQuery表
    AiQuery = Table('AiQuery', metadata, autoload_with=engine)

    inserted_id = None # 用于保存新插入的行的ID

    with engine.connect() as conn:
        # 检查AiQuery表中是否已经有该查询
        select_stmt = select(AiQuery).where(AiQuery.columns.QueryStr == query)
        result_proxy = conn.execute(select_stmt)
        print(select_stmt.compile(compile_kwargs={"literal_binds": True}))

        # 如果有结果，那么直接返回结果
        row = result_proxy.fetchone()
        print(row)
        if row:
            # 从 AiQuery 表中获取SQL查询字符串
            sql_query = row.SQLStr

            # 执行查询字符串，获取结果
            result_proxy = conn.execute(sql_query)

            # 将 LegacyRow 对象转换为字典
            result_data = [dict(row) for row in result_proxy.fetchall()]

            column_names = list(result_proxy.keys())
            sorted_result_data = []
            for resrow in result_data:
                sorted_row = [resrow[column_name] for column_name in column_names]
                sorted_result_data.append(sorted_row)
            result_data = sorted_result_data

            column_names = get_chinese_col_names(column_names, conn)
            inserted_id = row.ID  # 获取已经存在的行的ID

            used_time = round(time.time() - start_time, 2)  # 计算查询耗时
            refresh_date = datetime.datetime.now()  # 获取当前时间
            result_records = len(result_data)  # 获取结果记录数
            isAdd = False

            # 更新RefreshDate，ResultRecords和UsedTime字段
            update_stmt = AiQuery.update(). \
                where(AiQuery.columns.ID == inserted_id). \
                values(RefreshDate=refresh_date, ResultRecords=result_records, UsedTime=used_time,
                       Result_data=json.dumps(result_data, cls=DecimalEncoder))
            conn.execute(update_stmt)
        else:
            # 如果没有结果，那么执行GPT查询
            result = custom_db_chain(query)
            sql_query = result['result']
            sql_query = add_table_prefix_to_columns(sql_query, custom_table_info)
            print(sql_query)
            result_proxy = conn.execute(sql_query)

            # 将 LegacyRow 对象转换为字典
            result_data = [dict(row) for row in result_proxy.fetchall()]
            column_names = list(result_proxy.keys())
            sorted_result_data = []
            for resrow in result_data:
                sorted_row = [resrow[column_name] for column_name in column_names]
                sorted_result_data.append(sorted_row)
            result_data = sorted_result_data

            column_names = get_chinese_col_names(column_names, conn)

            used_time = round(time.time() - start_time, 2) # 计算查询耗时
            result_records = len(result_data) # 获取结果记录数

            # 将结果保存到AiQuery表中，包括新的字段
            insert_stmt = AiQuery.insert().values(QueryStr=query, SQLStr=sql_query, Column_names=json.dumps(column_names, cls=DecimalEncoder), Result_data=json.dumps(result_data, cls=DecimalEncoder), ResultRecords=result_records, UsedTime=used_time)

            result = conn.execute(insert_stmt)
            inserted_id = result.inserted_primary_key[0] # 获取新插入的行的ID
            isAdd = True

    return jsonify({'isAdd': isAdd, 'column_names': column_names, 'result_data': result_data, 'inserted_id': inserted_id})

if __name__ == '__main__':
    app.run(debug=True)

tree = ttk.Treeview(root)
tree.pack(padx=20, pady=20, fill=tk.X)
def on_click():
    query = entry.get()

    result = custom_db_chain(query)
    sql_query = result['result']

    engine = create_engine(f"mssql+pymssql://{user_name}:{urlquote(psw)}@{ip}/{database}")
    with engine.connect() as conn:
        result_proxy = conn.execute(sql_query)

        # 同样，将 LegacyRow 对象转换为字典
        result_data = [dict(row) for row in result_proxy.fetchall()]
        column_names = list(result_proxy.keys())
        column_names = get_chinese_col_names(column_names, conn)

    # 新增：清空 Treeview
    for item in tree.get_children():
        tree.delete(item)

    # 新增：显示查询结果
    display_table(tree, column_names, result_data)

    # 新增：显示查询结果
   # display_table(tree, [header["label"] for header in dataTable["headers"]], dataTable["contents"])

   # except Exception as err:
     #   print("Error occurred:", err)

button = ttk.Button(root, text="Chat", command=on_click)
button.pack(padx=20, pady=20)

text = tk.Text(root, height=10, width=60, font=("Arial", 14))
text.pack(padx=20, pady=20)

root.mainloop()

**Comment by merikoxuren** [comment]
close

**Comment by darshan8850** [comment]
Hello @merikoxuren I was encountered with the similar issue , could you please let me know how you tackle it,
