### ISSUE TITLE
DOC: Get only the sql query not the output of the query in SQLDatabaseChain

### ISSUE THREAD

**Issue by gopesh97** [hwchase17/langchain#4853]
### Issue with current documentation:

Hi, 
I need to get just the query only for a natural language input query. 
I don't want to get the results/output of the query from the db, how do I do that?

Thanks!

**Comment by Tajcore** [comment]
I would also like to know

**Comment by richarddli** [comment]
I have this need as well. The patch is straightforward (see https://github.com/hwchase17/langchain/blob/master/langchain/chains/sql_database/base.py) and I'm happy to open a PR on this if one of the maintainers (@imeckr ? @hwchase17 ?) wants to comment on the best approach.

I'd propose setting a `return_sql=True` similar to `return_direct=True`, and more-or-less implementing how `return_direct` works.

(My use case is that I want to do some processing of the SQL query before execution.)

**Comment by imeckr** [comment]
I am not maintainer but I find the feature request super useful. For what I can see I would recommend creating another chain `SQLQueryGenChain` and not introduce a new parameter, also use it in`SQLDatabaseChain` (composability). Though this approach would be different from the existing approach where depending upon parameters such as `return_direct` or `use_query_checker`  llm chains are being called inside the `_call` method. And, if we would have a `SQLQueryCheckerChain` it allows independent use as will as inside `SQLDatabaseChain` as well. 

What do you think @hwchase17 @dev2049 ? I could pick this up if you find it's interesting.

**Comment by Tajcore** [comment]
Isn't it possible to actually duplicate the functionality of the sql generator with a normal LLMChain?

**Comment by imeckr** [comment]
Yes very much possible but it would be great to have it handy though.

**Comment by lingster** [comment]
hi, I was looking to add an additional function that could be passed to the SQLDatabaseChain. The idea being that this function is passed the generated sql and could sanity check it before it is executed. Currently the flat `query_checker_prompt` would send the resulting sql back to llm to verify it's correct. What I would like to do is to be able to check, using something like sqlparse, that the syntax is correct or that the query that is returned could be adjusted for additional filtering/checking. 

Happy to submit a PR for this, but would like to have suggestions on how best this ought to be implemented.

**Comment by olahsymbo** [comment]
What I did instead was:

1. Goto the file `sql_database/base.py` and set `intermediate_step to **True**`
```
class SQLDatabaseChain(Chain):
    """Chain for interacting with SQL Database.

    Example:
        .. code-block:: python

            from langchain import SQLDatabaseChain, OpenAI, SQLDatabase
            db = SQLDatabase(...)
            db_chain = SQLDatabaseChain(llm=OpenAI(), database=db)
    """

    llm: BaseLanguageModel
    """LLM wrapper to use."""
    database: SQLDatabase = Field(exclude=True)
    """SQL Database to connect to."""
    prompt: BasePromptTemplate = PROMPT
    """Prompt to use to translate natural language to SQL."""
    top_k: int = 5
    """Number of results to return from the query"""
    input_key: str = "query"  #: :meta private:
    output_key: str = "result"  #: :meta private:
    return_intermediate_steps: bool = True
    """Whether or not to return the intermediate steps along with the final answer."""
    return_direct: bool = False
    """Whether or not to return the result of querying the SQL table directly."""
```


2. Goto the file `chains/base.py` and updated `run.py` as:

```
    def run(self, *args: Any, **kwargs: Any) -> str:
        """Run the chain as text in, text out or multiple variables, text out."""
        # if len(self.output_keys) != 1:
        #     raise ValueError(
        #         f"`run` not supported when there is not exactly "
        #         f"one output key. Got {self.output_keys}."
        #     )

        if args and not kwargs:
            if len(args) != 1:
                raise ValueError("`run` supports only one positional argument.")
            print(self.output_keys)
            return self(args[0])[self.output_keys[0]], self(args[0])[self.output_keys[1]]

        if kwargs and not args:
            return self(kwargs)[self.output_keys[0]]

        raise ValueError(
            f"`run` supported with either positional arguments or keyword arguments"
            f" but not both. Got args: {args} and kwargs: {kwargs}."
        )
```

Hence, to make a request, I just run this:

```
db = SQLDatabase.from_uri(os.getenv('POSTGRES_URI'))
llm = OpenAI(model_name="text-davinci-003", temperature=0.0)
db_chain = SQLDatabaseChain(llm=llm, database=db, verbose=True)
output, sql_cmd = db_chain.run(str(query))
```
Hence, it returns both the results and the sql query.

**Comment by gopesh97** [comment]
Thanks @olahsymbo 
This is a great solution

Closing the issue.

**Comment by richarddli** [comment]
I don't think this issue should be closed, as it requires code changes to mainline with every release.

**Comment by codelife31** [comment]
I  found SQLDatabaseSequentialChain can get intermediate_steps all information if u set intermediate_steps is True.(see https://github.com/hwchase17/langchain/blob/master/tests/integration_tests/chains/test_sql_database.py)

**Comment by richarddli** [comment]
Yes, but it still executes the query.

**Comment by Ed1123** [comment]
The issue shouldn't be closed. The solution accepted executes the query instead of just returning it before execution.

**Comment by keenborder786** [comment]
I will be working on making this feature a possibility.

**Comment by xingbow** [comment]
My soln/workaround:
- set `return_intermediate_steps = True`
- get the latest `sql_cmd` key in the intermediate results (since there maybe some SQL errors emerge and be fixed during the process)
```python
db_chain = SQLDatabaseChain.from_llm(llm, db,  return_intermediate_steps=True, verbose=True)
response = db_chain(prompt)
sql_cmd = ""
for r in response["intermediate_steps"]:
    if type(r) is dict:
        if "sql_cmd" in r.keys():
            sql_cmd = r["sql_cmd"]

**Comment by GustavoContreiras** [comment]
I'd like to do the same thing but using the MultiQueryRetriever. I can't return only the generated queries, it asks for a "run_manager" parameter.

**Comment by mfernandezsidn** [comment]
Any solution to this problem without having to edit source code?

**Comment by pmatrasc** [comment]
Please reopen

**Comment by r4kh4t** [comment]
Please reopen

**Comment by fafaschiavo** [comment]
Please reopen
