### ISSUE TITLE
Issue: The agent with the text-davinci-003 model and serpapi tool attempted to utilize a non-existent tool

### ISSUE THREAD

**Issue by teng1996** [hwchase17/langchain#4863]
### code
```python
tool_ = load_tools(["serpapi"],  serpapi_api_key=serpapi_api_key)
agent = initialize_agent(tool_, llm, agent="zero-shot-react-description", verbose=True, return_intermediate_steps=True)
response = agent({"input":"45*456=?"})
```
### log
> Entering new AgentExecutor chain...
 I need to calculate this
Action: Search
Action Input: 45\*456
Observation: A. A person who is in a position of trust and confidence to a vulnerable adult shall use the vulnerable adult's assets solely for the benefit of the vulnerable ...
Thought: This isn't what I'm looking for
Action: Search
Action Input: 45\*456 math
Observation: The GCF of 45 and 456 is 3. Steps to find GCF. Find the prime factorization of 45 45 = 3 × 3 × 5; Find the prime factorization of 456
Thought: I can use this to calculate the answer
Action: Calculate
Action Input: 45\*456/3
Observation: Calculate is not a valid tool, try another one.
.......

> Finished chain.

text-davinci-003 failed to adhere to the prompt "Action: the action to take, should be one of [Search]." Therefore, we need to modify the prompt based on the LLM (Language Model) that we are utilizing.

**Comment by teng1996** [comment]
> Could you share your code ?

Yes, I have added my code

**Comment by imeckr** [comment]
@teng1996 The input (math expression) you have provided is not _easily_ solvable by the `serapi` tool which is meant for utilizing a search engine, hence after a few steps its hallucinating and suggesting an action `Calculate` which isn't a valid tool.
Why aren't you providing an calculator tool to ease it out for the chain ?
```
from langchain.agents import load_tools, initialize_agent
from langchain.llms import OpenAI

llm = OpenAI(model_name='text-davinci-003', verbose=True)
tool_ = load_tools(["serpapi", "llm-math"], llm=llm)
agent = initialize_agent(tool_, llm, agent="zero-shot-react-description", verbose=True, return_intermediate_steps=True)
response = agent({"input":"45*456=?"})
```
