### ISSUE TITLE
ValueError(f"Got unknown tool {name}") hardcoded for custom tools in load_tools.py

### ISSUE THREAD

**Issue by luca-git** [hwchase17/langchain#4884]
### Issue you'd like to raise.

Hi there, the load_tools function implemented in https://python.langchain.com/en/latest/_modules/langchain/agents/load_tools.html won't accept custom tools. I'm trying to enrich Agent debates with tools discussed here https://python.langchain.com/en/latest/use_cases/agent_simulations/two_agent_debate_tools.html with a new prompt based tool: 

```
@tool("optimistic_string")
def optimistic_string(input_string: str) -> str:
    """Rewrites the input string with a more optimistic tone."""
    # Add your logic to process the input_string and generate the output_string
    prompt = "Rewrite the following sentence with a more optimistic tone: {{input_string}}"
    output_string = llm.generate(prompt) # Replace this with the actual call to the language model
    return output_string
```
But it's not possible at the moment as an error is encoded in load_tools for unrecognized tools. How do we add custom tools to the simulation? Can anyone provide guidance? It is paramaunt to be able to customize tools to fully take advantage of agent based simulation. Thanks! :)

**Comment by GraesonB** [comment]
Hi there,

A couple things to note:
-  I think you might be a bit confused with how prompt templating works, your function it actually never uses the input_string argument
- llm.generate takes a list of inputs, and generates multiple outputs, whereas you are trying to return a single string
-  Your agent is expecting a single string, so even if generate were to be setup properly, I don't think your agent would know what to do with the list of outputs

Below is a working version of your tool:

```python
from pydantic import BaseModel, Field
from langchain import PromptTemplate

class OptimisticString(BaseModel):
    input_string: str = Field(description="should be a string with any tone")

@tool("optimistic_string", args_schema=OptimisticString)
def optimistic_string(input_string: str) -> str:
    """Rewrites the input string with a more optimistic tone."""
    # Add your logic to process the input_string and generate the output_string
    template = "Rewrite the following sentence with a more optimistic tone: {input_string}"
    prompt = PromptTemplate(template=template, input_variables=["input_string"])

    output_string = test(prompt.format(input_string=input_string)) # Replace this with the actual call to the language model
    return output_string
```

**Comment by luca-git** [comment]
Thanks a lot for your kindness and patience in helping me. 🙏

**Comment by luca-git** [comment]
Thanks to @GraesonB the function now outputs the appropriate string, still not sure on how to integrate that in load_tools.py, I tryied to do so by hard coding it in load_tools, but when called I get a it throws: 
```
Observation: optimistic_string is not a valid tool, try another one.
```
this is how I hard coded it in load_tools.py:
```
_BASE_TOOLS: Dict[str, Callable[[], BaseTool]] = {
    "python_repl": _get_python_repl,
    "requests": _get_tools_requests_get,  # preserved for backwards compatability
    "requests_get": _get_tools_requests_get,
    "requests_post": _get_tools_requests_post,
    "requests_patch": _get_tools_requests_patch,
    "requests_put": _get_tools_requests_put,
    "requests_delete": _get_tools_requests_delete,
    "terminal": _get_terminal,
    "optimistic_string": _get_optimistic_string,

}

class OptimisticString(BaseModel):
    input_string: str = Field(description="should be a string")

def optimistic_string(input_string: str) -> str:
    """use this to make your arguments more compelling"""
    # Add your logic to process the input_string and generate the output_string
    template = "Rewrite the following sentence with a more optimistic tone: {input_string}"
    prompt = PromptTemplate(template=template, input_variables=["input_string"])

    output_string = llm(prompt.format(input_string=input_string)) # Replace this with the actual call to the language model
    return output_string

def _get_optimistic_string(llm: BaseLanguageModel) -> BaseTool:
    return Tool(
        name="optimistic_string",
        description= "use this to make your arguments more compelling",
        func=optimistic_string,
    )
    ```
    Any guidance on how to integrate custom tools in the agent simulation mentioned above would be truly appreciated.

**Comment by GraesonB** [comment]
Are you trying to give your agent access to this tool plus some other prebuilt tools?

**Comment by luca-git** [comment]
Yes, that would be my goal, the toolset will be vastly expanded to accomodate for some specific agent frameworks exitsintg in the literature.

**Comment by GraesonB** [comment]
```python
from langchain.agents import initialize_agent

class OptimisticString(BaseModel):
    input_string: str = Field(description="should be a string with any tone")


@tool("optimistic_string", args_schema=OptimisticString)
def optimistic_string(input_string: str) -> str:
    """Rewrites the input string with a more optimistic tone."""
    # Add your logic to process the input_string and generate the output_string
    template = (
        "Rewrite the following sentence with a more optimistic tone: {input_string}"
    )
    prompt = PromptTemplate(template=template, input_variables=["input_string"])

    output_string = llm(
        prompt.format(input_string=input_string)
    )  # Replace this with the actual call to the language model
    return output_string


agent = initialize_agent(llm=llm, tools=[optimistic_string], verbose=True)
result = agent.run("I feel like I'm never going to recover from this illness")
print(result)
```

Does this help you? All you have to do is put the tools you want to use in an array, and use that as the tools argument when initializing the agent.

**Comment by luca-git** [comment]
Thank you very much; that's great! However, there is one thing I am unsure about. I have two potential approaches. I could write the whole simulation from scratch, or, being a dwarf standing on the shoulders of giants, I could leverage existing LangChain agent implementations, like this one: https://python.langchain.com/en/latest/use_cases/agent_simulations/two_agent_debate_tools.html.

The script you kindly provided works perfectly in isolation. My problem arises when trying to integrate it with the aforementioned script, which relies on load_tools.py: https://python.langchain.com/en/latest/_modules/langchain/agents/load_tools.html. The issue is that the program isn't accepting custom agents that aren't listed in the load_tools function.

Ideally, I'd like to use  the pre-coded agents for tasks such as browsing and maths, while adding my own custom ones. However, if I hard-code them as I tried in my last post, in the load_tools.py, they don't work. Additionally, I understand that modifying native LangChain functions is a bad practice.

So my question is: Is there a way to integrate custom tools, like the one you provided, into the two_agent_debate_tools.html. code? Simply adding it to the code and appending it in the tools list results in an error, as load_tools.py does not recognize it.

Is there a workaround for this issue? Or will I have to write the entire code from scratch, which would be a significant task given my current abilities?

**Comment by luca-git** [comment]
The trick was to update the tool list via 
        self.tools.extend(my_tools)
