### ISSUE TITLE
langchain AzureOpenAI Embeddings

### ISSUE THREAD

**Issue by ZohaibRamzan** [hwchase17/langchain#4925]
### System Info

langchain-0.0.173

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am using the same code provided here. [](https://python.langchain.com/en/latest/modules/models/text_embedding/examples/azureopenai.html)
My code is like:

```
from langchain.embeddings.openai import OpenAIEmbeddings
# open ai key
openai.api_type = "azure"
openai.api_version = "2023-03-15-preview"
openai.api_base = 'https://xxxxxopenai.openai.azure.com/'
openai.api_key = "xxxxxxxxxxxxxxxxxxxxxxxx"
embeddings = OpenAIEmbeddings(deployment='Embedding_Generation' )
print(embeddings.embed_query("Hi How are You"))
```

I also tried other options but getting the same error on print statement.
AuthenticationError: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

### Expected behavior

I want to generate the embneddings.

**Comment by abishsteel** [comment]
I would double check if 'Embedding_Generation' is the name of your azure deployment for the embedding ada model

**Comment by axiangcoding** [comment]
try set env, it works for me
```
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "https://xxx.openai.azure.com/"
os.environ["OPENAI_API_KEY"] = "xxx"
os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"
```

**Comment by ZohaibRamzan** [comment]
> try set env, it works for me
> 
> ```
> os.environ["OPENAI_API_TYPE"] = "azure"
> os.environ["OPENAI_API_BASE"] = "https://xxx.openai.azure.com/"
> os.environ["OPENAI_API_KEY"] = "xxx"
> os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"
> ```

It worked for me. Thanks
