### ISSUE TITLE
Azure OpenAI Embeddings failed due to no deployment_id set.

### ISSUE THREAD

**Issue by tot0** [hwchase17/langchain#5001]
### System Info

Broken by #4915 

Error: `Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>`

I'm putting a PR out to fix this now.

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Run example notebook: https://github.com/hwchase17/langchain/blob/22d844dc0795e7e53a4cc499bf4974cb83df490d/docs/modules/models/text_embedding/examples/azureopenai.ipynb

### Expected behavior

Embedding using Azure OpenAI should work.

**Comment by tot0** [comment]
Thanks @dev2049

**Comment by assert6** [comment]
I'm sorry about that PR 😣
