### ISSUE TITLE
ChatOpenAI models don't work with prompts created via ChatPromptTemplate.from_role_strings

### ISSUE THREAD

**Issue by UmerHA** [hwchase17/langchain#5027]
### System Info

LangChain version = 0.0.167
Python version = 3.11.0
System = Windows 11 (using Jupyter)

### Who can help?

- @hwchase17
- @agola11
- @UmerHA (I have a fix ready, will submit a PR)

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
import os
os.environ["OPENAI_API_KEY"] = "..."

from langchain.chains import LLMChain
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.prompts.chat import ChatPromptTemplate
from langchain.schema import messages_from_dict

role_strings = [
    ("system", "you are a bird expert"), 
    ("human", "which bird has a point beak?")
]
prompt = ChatPromptTemplate.from_role_strings(role_strings)
chain = LLMChain(llm=ChatOpenAI(), prompt=prompt)
chain.run({})
```

### Expected behavior

Chain should run

**Comment by vanillechai** [comment]
Not completely sure what you want to achieve, but I think you should use `HumanMessagePromptTemplate` or `AIMessagePromptTemplate` here.

See the docs for examples how to use this, e.g. https://python.langchain.com/en/latest/modules/chains/getting_started.html.
