### ISSUE TITLE
AzureOpenAI example error (embeddding)

### ISSUE THREAD

**Issue by slix88** [hwchase17/langchain#5042]
### System Info

I have tried to run the AzureOpenAI example here for embedding: https://python.langchain.com/en/latest/modules/models/text_embedding/examples/azureopenai.html

Doing so, I get the following error:
`InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>`

I am using the current versions:
```
openai==0.27.7
langchain==0.0.174
```

I have even followed the issue described in #1560 to no avail

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

https://python.langchain.com/en/latest/modules/models/text_embedding/examples/azureopenai.html

### Expected behavior

No errors

**Comment by poikladevv88** [comment]
I have the same issue

**Comment by slix88** [comment]
Agree that this is now solved in 0.0.175. Thanks @poikladevv88
