### ISSUE TITLE
[AsyncCallbackHandler] on_llm_new_token not being called

### ISSUE THREAD

**Issue by virattt** [hwchase17/langchain#5074]
### System Info

Django backend that is using an `AsyncWebsocketConsumer`.  

Goal: Stream LLM messages to a frontend React client via an `AsyncWebsocketConsumer`, using a custom `AsyncCallbackHandler`.

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

I'm using the async handler to stream the LLM's output from a Django backend that is using an `AsyncWebsocketConsumer`.

I'm trying to stream the `ChatOpenAI` LLM's output via a custom subclass of the `AsyncCallbackHandler` (`streaming` is set to `True`).

However, the async `on_llm_new_token` function is never being called.

Unsure what the issue may be, as extending the `BaseCallbackHandler` works well for writing to stdout.  

Here's the code that's not being called in the async on_llm_new_token: https://github.com/virattt/chat_app/pull/5/files#diff-176a7b37329b8a2846ff511f4dc15edd7d17d1478e7b4742f97700d97319b578R101-R103

Any thoughts or suggestions would be helpful.

### Expected behavior

The async `on_llm_new_token` function should get called when a new token is received from the LLM.

**Comment by agola11** [comment]
which version of langchain are you on?

**Comment by virattt** [comment]
Hey @agola11 - I'm on `0.0.176` (link to my [requirements.txt](https://github.com/virattt/chat_app/pull/5/files#diff-a780f027052bed3bff6ce9850db4a0e66358b86503cf4586e846ce88afa2e9bcR26))

**Comment by virattt** [comment]
Figured out the issue.  I needed to call `arun()` on the agent instead of just `run()`:

```
 response = await self.agent.arun(message)
```

Once I do that, the whole code async code flow executes.  Previously, I was just calling:
```
 response = self.agent.run(message)
```

I realized this after running the PyCharm debugger; the code execution was going down the `ChatOpenAI._generate(...)` [path](https://github.com/hwchase17/langchain/blob/c9a362e4821b5fcdc81366ca2230df77f0a113fc/langchain/chat_models/openai.py#L272) instead of `ChatOpenAI._agenerate(...)` [path](https://github.com/hwchase17/langchain/blob/c9a362e4821b5fcdc81366ca2230df77f0a113fc/langchain/chat_models/openai.py#L318).  

This meant that the [async callback handler](https://github.com/hwchase17/langchain/blob/c9a362e4821b5fcdc81366ca2230df77f0a113fc/langchain/chat_models/openai.py#L336) was never called.

**Comment by Ajaypawar02** [comment]
@virattt I am using pusher for streaming purpose.
I am getting error as "Response payload is not completed"


async def pusher__cal(new_payload, token):
    # print(token)
    session_id = new_payload["session_id"]
    session_id_channel = f"{session_id}_channel"
    user_id = new_payload["user_id"]
    message_id = new_payload["message_id"]
    status = "processing"

    await asyncio.sleep(0)  # Allow other async tasks to run
    pusher_client.trigger(session_id_channel ,'query_answer_stream', {
                        "user_id": user_id,
                        "session_id": session_id,
                        "message_id": message_id,
                        "answer": token,
                        "status": status
                        },
                        )


class MyCallbackHandler(AsyncCallbackHandler):
    def __init__(self,new_payload : Dict):
        self.new_payload = new_payload
        self.user_id = new_payload["user_id"]
        self.session_id = new_payload["session_id"]
        self.message_id = new_payload["message_id"]
        self.session_id_channel = f"{self.session_id}_channel"
        self.status = "streaming"
        self.list = []

    async def on_llm_new_token(self, token, **kwargs) -> None:

        if token != "":
            await pusher__cal(self.new_payload,token)
