### ISSUE TITLE
load_summarize_chain doesn't return the specified max_tokens in OpenAI LLM

### ISSUE THREAD

**Issue by frandominguezl** [hwchase17/langchain#5093]
### System Info

**LangChain version:** 0.0.176
**Platform:** Local Ubuntu 22.04
**Python version:** 3.10

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

This is the code example I'm currently using. It's a slightly modified version of [LangChain summarize docs](https://python.langchain.com/en/latest/modules/chains/index_examples/summarize.html)

```py
from pdfminer.high_level import extract_text
from langchain.llms import OpenAI
from langchain.docstore.document import Document
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains.summarize import load_summarize_chain

text_splitter = CharacterTextSplitter()

def file_summarizer(file):
    read_file = extract_text(file.name)
    texts = text_splitter.split_text(read_file)

    docs = [Document(page_content=t.replace("\t", " ").strip()) for t in texts[:1]]

    llm = OpenAI(temperature=0, max_tokens=2000)

    for d in docs:
        print(llm.get_num_tokens(d.page_content)) # This prints 1054

    chain = load_summarize_chain(llm, chain_type="map_reduce")

    result = chain.run(docs).strip()

    print(llm.get_num_tokens(result)) # This prints 87

    return result
```

### Expected behavior

It looks like it's ignoring the value of the `max_tokens` parameter (or that I'm misunderstanding that it does), but no matter what value I pass to that parameter, I always receive very short answers, no matter the token size of the prompt.

`text-davinci-003` has 4097 tokens, which means that for my previous example, I should've had around ~3000 tokens available for my summary, however, I just received 87.

Am I missing or misunderstanding any bit of documentation?

Thanks in advance!

**Comment by NickL77** [comment]
I believe this `max_tokens` parameter is passed to the openAI API (https://platform.openai.com/docs/api-reference/completions/create#completions/create-max_tokens).

Changing this parameter won't trigger the model to provide longer responses. Instead, I'd suggest you to try using a `custom_prompt` detailed here: https://python.langchain.com/en/latest/modules/chains/index_examples/summarize.html. The default prompt is
```
"""Write a concise summary of the following:

"{text}"

CONCISE SUMMARY:"""
```

You can use a different descriptor than "concise" or even specify "in X sentences"
