### ISSUE TITLE
GoogleDriveLoader seems to be pulling trashed documents from the folder

### ISSUE THREAD

**Issue by acetinick** [hwchase17/langchain#5104]
### System Info

Hi

testing this loader, it looks as tho this is pulling trashed files from folders.  I think this should be default to false if anything and be an opt in.

### Information

- [X] The official example notebooks/scripts

### Related Components

- [X] Document Loaders
### Reproduction

use GoogleDriveLoader

1. point to folder
2. move a file to trash in folder

Reindex

File still can be searched in vector store.

### Expected behavior

Should not be searchable

**Comment by NickL77** [comment]
Do you have more details on reproducing? Are you using `google_drive.ipynb`?

Looking through the code, if `folder_id` is provided, the loader only fetches the files after `load()` is called. This would be surprising behavior unless there is lag on Google's side.

On the other hand, if `document_ids` or `file_ids` is provided, it makes sense to me why this would be happening (although unclear if it's desirable), as the google-provided id may stay the same even if the document is moved to the trash.

**Comment by Klaudioz** [comment]
It's happening the same to me, so I've recorded a [video](https://cln.sh/NdSVqD8GytP05hfr0crv) showing the issue.

This is the script I've used for the test:

```
from langchain.document_loaders import GoogleDriveLoader

loader = GoogleDriveLoader(
    folder_id="<ADD YOUR FOLDER ID",
    file_types=["sheet", "document", "pdf"],
    recursive=False,
    credentials_path="credentials.json",
    token_path="token.json"
)

docs = loader.load()
print(len(docs))
```

**Comment by Klaudioz** [comment]
It's working well if I go to the trash in Google Drive, and click "Empty Trash".

**Comment by NickL77** [comment]
> It's working well if I go to the trash in Google Drive, and click "Empty Trash".

+1, I just tested this and saw the same behavior. This seems like a Google Drive pattern.

**Comment by NickL77** [comment]
I found a way to check if a file is trashed, fill send out a PR tonight.
