### ISSUE TITLE
Issue: LlamaCPP still uses cpu after passing the n_gpu_layer param

### ISSUE THREAD

**Issue by allthatido** [hwchase17/langchain#5187]
### Issue you'd like to raise.

Langchain == 0.0.178
llama-cpp-python == 0.1.54

LLM def: 

`callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])`
`llm = LlamaCpp(model_path=f"{self.llm_path}/{self.selection}.bin", n_gpu_layers=25, n_ctx=1024, n_threads=8, callback_manager=callback_manager, verbose=True)`

Loaded model info:

> llama.cpp: loading model from models/gpt4all-13B/gpt4all-13B.bin
> llama_model_load_internal: format     = ggjt v3 (latest)
> llama_model_load_internal: n_vocab    = 32000
> llama_model_load_internal: n_ctx      = 1024
> llama_model_load_internal: n_embd     = 5120
> llama_model_load_internal: n_mult     = 256
> llama_model_load_internal: n_head     = 40
> llama_model_load_internal: n_layer    = 40
> llama_model_load_internal: n_rot      = 128
> llama_model_load_internal: ftype      = 9 (mostly Q5_1)
> llama_model_load_internal: n_ff       = 13824
> llama_model_load_internal: n_parts    = 1
> llama_model_load_internal: model size = 13B
> llama_model_load_internal: ggml ctx size =    0.09 MB
> llama_model_load_internal: mem required  = 11359.05 MB (+ 1608.00 MB per state)
> .
> llama_init_from_file: kv self size  =  800.00 MB
> AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |

I do not see any info regarding no of layers offloaded to gpu. 

### Code Repo:
[GitHub](https://github.com/allthatido/FileGPT)

**Comment by Blucknote** [comment]
Did you compile llama.cpp with BLAS support? For now you have BLAS = 0
https://github.com/ggerganov/llama.cpp#blas-build

https://github.com/abetlen/llama-cpp-python#installation-with-openblas--cublas--clblast

**Comment by allthatido** [comment]
Oh I though the default pip install llama-cpp-python chooses that automatically as per the system. Will force the blas param to 1. Thanks. Will check and revert back.

**Comment by allthatido** [comment]
> Did you compile llama.cpp with BLAS support? For now you have BLAS = 0 https://github.com/ggerganov/llama.cpp#blas-build
> 
> https://github.com/abetlen/llama-cpp-python#installation-with-openblas--cublas--clblast

This solves the issue. Thanks

**Comment by Apicchoc** [comment]
I still have the BLAS=0, despite following the steps provided in the links. Any idea on how I can troubleshoot the problem ?

**Comment by apoorv-98** [comment]
I am still facing the same issue on my environment which has Tesla T4 gpu but i am able to load on colab on Tesla T4.
And i also followed the documentation of llama_cpp with CuBLAS.
