### ISSUE TITLE
ChatVertexAI is not imported

### ISSUE THREAD

**Issue by marouane-tradelab** [hwchase17/langchain#5233]
### System Info

Hello, 

I'm trying to use ChatVertexAI and I noticed that the following import is not working : 

```python 
from langchain.chat_models import ChatVertexAI
```
But this one is working correctly : 
```python
from langchain.chat_models.vertexai import ChatVertexAI
```

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. install the main branch: `pip install git+https://github.com/hwchase17/langchain.git`
2. try to import `from langchain.chat_models import ChatVertexAI`
3. try to import `from langchain.chat_models.vertexai import ChatVertexAI`

### Expected behavior

The import `from langchain.chat_models import ChatVertexAI` should work

**Comment by jmho** [comment]
Hey @marouane-tradelab! I was unable to replicate this. Can you provide more details on what version of langchain you were using or how you ran into this issue?

For context I ran the following code in Google Colab and ran into no issues:

`
!pip install git+https://github.com/hwchase17/langchain.git
!pip install google-cloud-aiplatform

from langchain.chat_models import ChatVertexAI
`

**Comment by marouane-tradelab** [comment]
I confirm that it's working now. 
Thank you
