### ISSUE TITLE
python SDK can't query documents from an existing collection

### ISSUE THREAD

**Issue by qlql489** [hwchase17/langchain#5276]
### Feature request

In the JS SDK of Milvus, there is a function to query documents from an existing collection, while in the Python SDK, this function is not available. Instead, the collection can be constructed using the following way:
```python
vector_db = Milvus.from_documents(
    docs,
    embeddings,
    connection_args={"host": "127.0.0.1", "port": "19530"},
)
```

### Motivation

I cannot ask multiple questions

### Your contribution

no

**Comment by YLFxGen** [comment]
I haven't used Milvus but I just checked the source code.
```
vector_db = cls(
    embedding_function=embedding,
    collection_name=collection_name,
    connection_args=connection_args,
    consistency_level=consistency_level,
    index_params=index_params,
    search_params=search_params,
    drop_old=drop_old,  # default to False
    **kwargs,
)
vector_db.add_texts(texts=texts, metadatas=metadatas)
```
This is what get executed when you invoke _from_documents()_. If you don't mention it explicitly, the default value for drop_old is False. So it will try to reuse the existing collection and ingest the docs there if it exists. Here is the source code:
  
```
# Grab the existing colection if it exists
if utility.has_collection(self.collection_name, using=self.alias):
    self.col = Collection(
        self.collection_name,
        using=self.alias,
    )
# If need to drop old, drop it
if drop_old and isinstance(self.col, Collection):
    self.col.drop()
    self.col = None
```
If you only want to ask questions without ingesting new data, what you can do is:
```
from langchain.vectorstores import Milvus
vector_db = Milvus(
    embedding_function = embeddings,
    collection_name = "YOUR_COLLECTION_NAME",
    connection_args = {"host": "127.0.0.1", "port": "19530"},
)
vector_db.similarity_search("add your query here")
```

**Comment by qlql489** [comment]
it work
