### ISSUE TITLE
Validation Error importing OpenAPI planner when OpenAI credentials not in environment

### ISSUE THREAD

**Issue by shvjds** [hwchase17/langchain#5361]
### System Info

Name: langchain, Version: 0.0.180
Name: openai, Version: 0.27.7

macOS Mojave 10.14.6

### Who can help?

@vowelparrot 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps:

1. Do _not_ load open ai key into env with the intention of wanting to pass it as a parameter when instantiating the llm

```
from dotenv import dotenv_values
openai_api_key = dotenv_values('.env')['OPENAI_API_KEY']
```

2. Load the planner:

```
from langchain.llms.openai import OpenAI
from langchain.agents.agent_toolkits.openapi import planner
``` 

### Expected behavior

A validation error should not be raised during the importing of the module.
We should be able to pass the open api key as an argument.

That is, the following should work:
```
from langchain.llms.openai import OpenAI
from langchain.agents.agent_toolkits.openapi import planner

llm = OpenAI(model_name="gpt-4", temperature=0.0, open_api_key=open_api_key)
```

**Comment by vowelparrot** [comment]
Thanks for raising this issue - we'll get a fix in for the next release
