### ISSUE TITLE
Could not parse LLM output

### ISSUE THREAD

**Issue by greboide** [hwchase17/langchain#549]
```python
from langchain.agents import load_tools, initialize_agent, get_all_tool_names
from langchain.llms.huggingface_pipeline import HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

model_id = "sberbank-ai/mGPT"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id)
pipe = pipeline(
    "text-generation", model=model, tokenizer=tokenizer, max_new_tokens=10
)

hf = HuggingFacePipeline(pipeline=pipe)
news_api_key = "oops my api key"
tool_names = ["news-api", "llm-math"]
tools = load_tools(tool_names, llm=hf, news_api_key=news_api_key)
agent = initialize_agent(tools, hf, agent="zero-shot-react-description", verbose=True, return_intermediate_steps=True)
response = agent({"input":"how many people live in Brazil?"})
print(response["intermediate_steps"])
```

I have the code above but it doesnt work as expected, it just says:

`ValueError: Could not parse LLM output: ' I know that there are more than 100,000'`

What am I doing wrong?

**Comment by hwchase17** [comment]
the agent expects the LLM to return text in a specific format (that it can parse in order to use it as a tool)

the LLM you are using is not returning output in that format... this often happens with smaller/less good models

**Comment by greboide** [comment]
Hmm i see, how can i know what format the agent is expecting?

**Comment by rbodkin** [comment]
I see similar issues in trying to use google/flan-t5-xl ... I'd like to see langchain work with a greater diverse of LLMs and outputs

**Comment by cosimo** [comment]
Would be useful to know what was done to resolve the issue.
