### ISSUE TITLE
Bug with LLM caching

### ISSUE THREAD

**Issue by Shivanshu-Gupta** [hwchase17/langchain#551]
This line seems to be incorrect: https://github.com/hwchase17/langchain/blob/1f248c47f36af986be7ea647a6af223c9bb34b2b/langchain/llms/base.py#L112. Should be either `prompts = prompts[missing_prompt_idxs[i]` or `prompts = missing_prompts[i]`.

**Comment by hwchase17** [comment]
good catch, will fix and add unit test
