### ISSUE TITLE
Sampling parameters are ignored by vertexai

### ISSUE THREAD

**Issue by khallbobo** [hwchase17/langchain#5531]
start_chat() constructs a vertextai _ChatSession and sets class variables with the parameters, but send_message() will not use those parameters if send_message is called w/o parameters.  This is because send_message() has default values for the parameters which are set to global variables.
You can fix this by moving **self._default_params to the send_message() call.

https://github.com/hwchase17/langchain/blob/359fb8fa3ae0b0904dbb36f998cd2339ea0aec0f/langchain/chat_models/vertexai.py#LL122C75-L122C75

**Comment by mheguy-stingray** [comment]
@khallbobo your PR didn't properly close this issue.

**Comment by khallbobo** [comment]
Apologies.  Thanks for closing it.
