### ISSUE TITLE
Add Tigris vectorstore for vector search

### ISSUE THREAD

**Issue by adilansari** [hwchase17/langchain#5535]
### Feature request

Support Tigris as a vector search backend

### Motivation

Tigris is a Serverless NoSQL Database and Search Platform and have their [vector search](https://www.tigrisdata.com/docs/concepts/vector-search/python/) product. It will be great option for users to use an integrated database and search product.

### Your contribution

I can submit a a PR

**Comment by dev2049** [comment]
love it! would gladly review if you want to take a stab at implementing

**Comment by taimurshaikh** [comment]
Would love to help out on this if need be

**Comment by adilansari** [comment]
Thanks @taimurshaikh, maybe you can help with a review or enriching the jupyter notebook example in https://github.com/hwchase17/langchain/pull/5703
