### ISSUE TITLE
Issue: How to run GPT4All on GPU?

### ISSUE THREAD

**Issue by PavelAgurov** [hwchase17/langchain#5577]
### Issue you'd like to raise.

Is it possible at all to run Gpt4All on GPU? For example for llamacpp I see parameter n_gpu_layers, but for gpt4all.py - not.
Sorry for stupid question :)

**Comment by gehlotabhishek** [comment]
I'm also looking for the same.

**Comment by PavelAgurov** [comment]
Found opened ticket https://github.com/nomic-ai/gpt4all/issues/835 - GPT4ALL doesn't support Gpu yet. So, langchain can't do it also. I will close this ticket and waiting for implementation from GPT4ALL.

**Comment by oalfarisi** [comment]
Thank you, is there any update on GPT4All run on GPU
