### ISSUE TITLE
count tokens used in chain

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchain#558]
should be doable with callbacks

**Comment by dheerajiiitv** [comment]
@hwchase17 , is this related to calculating token_usage in chain?

**Comment by cyberandy** [comment]
Yes, it would be idea to calculate token_usage for every chain/agent and add it to the output.

**Comment by Mehuldobriyal123** [comment]
It should be doable with callbacks to the output

**Comment by hwchase17** [comment]
done! https://langchain.readthedocs.io/en/latest/modules/llms/examples/token_usage_tracking.html
