### ISSUE TITLE
Issue: Does langchain store the database in memory?

### ISSUE THREAD

**Issue by saswat0** [hwchase17/langchain#5600]
### Issue you'd like to raise.

Say I have a huge database stored in BigQuery, and I'd like to use the SQL Database Agent to query this database using natural language prompts. I can't store the data in memory because it's too huge. Does the [`SQLDatabase`](https://python.langchain.com/en/latest/modules/agents/toolkits/examples/sql_database.html#sql-database-agent) function store this in memory? 

If so, can I directly query the source data without loading everything? I'm comfortable with the latencies involved with read operations on disk. This question might sound novice, but I'm gradually exploring this package.

**Comment by willsmithorg** [comment]
No, the SQLDatabase agent only does 4 things, with access to 4 tools:

- query names of tables on the database
- given a table, return the table schema and the first 3 rows on the table (select * from table limit 3)
- execute arbitrary SQL on the database to see what comes back, typically this is trying to answer your query
- check the syntax of a query

So typically it will retrieve the table names, then query the schema of the most relevant tables and the few sample rows, then immediately start to generate hopefully correct SQLs to answer your question.  It's also explicitly limited (via prompt engineering) to only retrieving the top 10 rows of any query unless the user explictly requests more.

**Comment by saswat0** [comment]
Got it @willsmithorg 
Thanks a lot!

**Comment by naam-nrj** [comment]
Hi @willsmithorg I was trying out Langchain agent 'ZERO_SHOT_REACT_DESCRIPTION' to query our database. There are around 140 tables with many columns. And probably due to that <db = SQLDatabase.from_uri(conn_str)> is taking around 13 minutes to connect to database.
Can you please let me know if there is any solution for this?
