### ISSUE TITLE
Issue: ConversationalRetrievalQAChain returns the qaTemplate condensed question as the first token

### ISSUE THREAD

**Issue by seakkus** [hwchase17/langchain#5608]
### Issue you'd like to raise.

I am using the ConversationalRetrievalQAChain to retrieve answers for questions while condensing the chat history to a standalone question. The issue I am facing is that the first token returned by the chain.call handleLLMNewToken is the standalone condensed question when there is a chat_history provided. Ideally, I do not want the condensed question to be sent via the handleLLMNewToken instead I want just the answer tokens. Is there any way to achieve that? Here is the code I am running:

`import { CallbackManager } from "langchain/callbacks";
import { ConversationalRetrievalQAChain } from "langchain/chains";
import { ChatOpenAI } from "langchain/chat_models";
import { PineconeStore } from "langchain/vectorstores/pinecone";

const CONDENSE_PROMPT = `Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:`;

const QA_PROMPT = `You are an AI assistant. Use the following pieces of context to answer the question at the end.
If you don't know the answer, just say you don't know. DO NOT try to make up an answer.
If the question is not related to the context, politely respond that you are tuned to only answer questions that are related to the context.

{context}

Question: {question}
Helpful answer in markdown:`;

export const makeChain = (
    vectorstore: PineconeStore,
    onTokenReceived: (data: string) => void
) => {
    const model = new ChatOpenAI({
        temperature: 0,
        streaming: true,
        modelName: "gpt-3.5-turbo",
        openAIApiKey: process.env.OPENAI_API_KEY as string,
        callbackManager: CallbackManager.fromHandlers({
            async handleLLMNewToken(token) {
                onTokenReceived(token);
            },
            async handleLLMEnd(result) {},
        }),
    });

    return ConversationalRetrievalQAChain.fromLLM(
        model,
        vectorstore.asRetriever(),
        {
            qaTemplate: QA_PROMPT,
            questionGeneratorTemplate: CONDENSE_PROMPT,
            returnSourceDocuments: true, // The number of source documents returned is 4 by default
        }
    );
};
`

**Comment by Sujal-Chouhan** [comment]
Having the same issue

**Comment by cormacncheese** [comment]
same

**Comment by cdoneshot** [comment]
same question and use [this](https://js.langchain.com/docs/modules/chains/index_related_chains/conversational_retrieval#streaming) solved

**Comment by priyank96** [comment]
same

**Comment by seakkus** [comment]
The solution is to pass a separate questionGeneratorModel via llm options:

`
    const questionGenerationModel = new ChatOpenAI({
        temperature: 0,
        modelName: 'gpt-3.5-turbo',
        openAIApiKey: env.OPENAI_API_KEY,
    });

    return ConversationalRetrievalQAChain.fromLLM(
        model,
        vectorstore.asRetriever(),
        {
            qaTemplate: qaPrompt,
            questionGeneratorTemplate: CONDENSE_PROMPT,
            returnSourceDocuments: true, // The number of source documents returned is 4 by default
            questionGeneratorChainOptions: {
                llm: questionGenerationModel,
            },
        }
    );
`

If you don't pass that, the conversational model is used for generating the condensed question as well - hence tokens are flushed out via the main model.

**Comment by seakkus** [comment]
The solution is to pass a separate question generator model via questionGeneratorChainOptions options:

`const questionGenerationModel = new ChatOpenAI({
        temperature: 0,
        modelName: 'gpt-3.5-turbo',
        openAIApiKey: env.OPENAI_API_KEY,
    });

    return ConversationalRetrievalQAChain.fromLLM(
        model,
        vectorstore.asRetriever(),
        {
            qaTemplate: qaPrompt,
            questionGeneratorTemplate: CONDENSE_PROMPT,
            returnSourceDocuments: true, // The number of source documents returned is 4 by default
            questionGeneratorChainOptions: {
                llm: questionGenerationModel,
            },
        }
    );
`

If you don't pass that, the conversational model is used for generating the condensed question as well - hence tokens are flushed out via the main model.

**Comment by manuel-84** [comment]
does token usage tracking works well with your solution?
i have similar code and cannot manage to track tokens

**Comment by esponges** [comment]
Both `qaTemplate` and `question `questionGeneratorTemplate` are marked as `deprecated`.  Updating `questionGeneratorTemplate` is quite straight forward, but implementing the `qaChainOptions.prompt`is not. 

Any idea how?

```ts
  return ConversationalRetrievalQAChain.fromLLM(model, vectorStore.asRetriever(), {
    // todo: deprecated
    qaTemplate: QA_PROMPT,
    // todo: how to implement this? Requires BasePromptTemplate
    // qaChainOptions: { prompt: QA_PROMPT },
    questionGeneratorChainOptions: { template: CONDENSE_PROMPT },
    memory: new BufferMemory({
      inputKey: "question",
      memoryKey: "chat_history",
      outputKey: "text",
    }),
  });
```

**Comment by bx-h** [comment]
Python version here : https://python.langchain.com/docs/use_cases/question_answering/how_to/chat_vector_db

**Comment by navidkpr** [comment]
This is caused because ConversationalRetrievalQAChain uses the same llm for condensing the QA if you don't provide it with the condense_question_llm parameter. And since your llm has a callback handler, that callback handler gets called when it tries to condense the query.

You can fix this by creating a new llm (without a callback handler) and sending it in using the condense_question_llm parameter into ConversationalRetrievalQAChain.
