### ISSUE TITLE
ValueError: Not a valid json with Directory Loader function

### ISSUE THREAD

**Issue by evaagustine** [hwchase17/langchain#5707]
Hi, I load a folder with txt file and using Directory Loader. It keeps show this error

> File "/Users/mekari/test-venv/lib/python3.8/site-packages/unstructured/partition/json.py", line 45, in partition_json
>     raise ValueError("Not a valid json")
> ValueError: Not a valid json

When I tried with just 10 txt file before, it was fine. Now I loaded around hundred files it shows that error. After searched, probably caused by one of the documents is not valid when parsing it to json. But I struggle to track which document caused the error. Maybe any ways to do it? Here is my code

> def construct_document(directory_path, persists_directory):
>   loader = DirectoryLoader(directory_path, glob="**/*.txt")
>   documents = loader.load()
>   text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
>   texts = text_splitter.split_documents(documents)
>   embeddings = OpenAIEmbeddings(openai_api_key=os.environ["OPENAI_API_KEY"])
>   vectordb = Chroma.from_documents(texts, embeddings, 
>                                   persist_directory=persists_directory)
>   vectordb.persist()
>   return embeddings

Thank you

**Comment by czhiqing** [comment]
There are symbols in the text: [], {}, which are detected as json.

**Comment by czhiqing** [comment]
Effective but ugly solution:
In line 129 of .../site-packages/unstructured/file _ utils/filetype.py, insert:
"txt": FileType.TXT,

Then use the type to specify:
DirectoryLoader('./docs/title/', glob="*.txt", loader_kwargs={'content_type': 'txt'})

**Comment by mirodrr** [comment]
Having this problem as well. Ideally the program should take the file extension at face value, and treat ".txt" files as text files and not try to be smart and detect that they are json

**Comment by mirodrr** [comment]
Reproduced the issue and can confirm that @czhiqing is correct. Did this to solve my problem without having to mess with the langchain code. Not ideal, but fine for my usecase

`for filename in os.listdir(source_directory):
    if filename.endswith(".txt"):
        with open(os.path.join(source_directory, filename), 'r') as f:
            s = f.read()
            with open(os.path.join(target_directory, filename), "w") as text_file:
                text_file.write(s.replace("{", "").replace("{", "").replace("[", "").replace("]", ""))`

**Comment by evaagustine** [comment]
@czhiqing, as you say in one of my documents there is "[]" and detected as a not valid json. Also @mirodrr your workaround is perfectly worked in my case! Thank youu

**Comment by bainningking** [comment]
i try this:
loader = DirectoryLoader(md_path, glob='**/*.txt', show_progress=True, loader_kwargs={'content_type': 'text/plain','encoding':'utf-8'})
and is solved

**Comment by hsleonis** [comment]
> i try this: loader = DirectoryLoader(md_path, glob='**/*.txt', show_progress=True, loader_kwargs={'content_type': 'text/plain','encoding':'utf-8'}) and is solved

This is works, thanks!

**Comment by webnautes** [comment]
> i try this: loader = DirectoryLoader(md_path, glob='**/*.txt', show_progress=True, loader_kwargs={'content_type': 'text/plain','encoding':'utf-8'}) and is solved

Thnks
