### ISSUE TITLE
Capture agent observations for further processing

### ISSUE THREAD

**Issue by KBB99** [hwchase17/langchain#5787]
### Feature request

I would like a way to capture observations in the same way you can capture new llm tokens using the callback's on_llm_new_token.

### Motivation

I've written a basic self-improving agent. I get it to "self-improve" by feeding the entire previous chain output to a meta agent that then refines the base agent's prompt. I accomplish this by appending all the tokens using the callback on_llm_new_token. However I realized it is not capturing observations as they are not llm generated tokens. How can I capture the observation as well?

### Your contribution

I've written an article detailing the process I've created for the self-improving agent along with the code [here](https://medium.com/p/d31204e1c375). Once I figure out how to also capture the agent observations I will add the solution to the documentation under a header such as "Agent observability - capture the entire agent chain"

**Comment by bbellcopperleaf** [comment]
@KBB99 did you try accessing the intermediate steps as described here?
https://python.langchain.com/docs/modules/agents/how_to/intermediate_steps

I was able to capture the raw observations using this approach.  I know it isn't exactly using callbacks, but I think you could find a means to use them for your purposes.

**Comment by KBB99** [comment]
That sees like a good approach. I ended up using onText() method in the BaseCallbackManager and put the callback within agent.run() instead of llm(). Then it worked.

**Comment by lynnna-xu** [comment]
@KBB99 Hi Could you share more details about your solution?
