### ISSUE TITLE
 SelfAskWithSearchChain error when followup required

### ISSUE THREAD

**Issue by rubensmau** [hwchase17/langchain#58]
I have just updated to version 0.0.7

1- When running a simple question like: "What is the capital of Idaho?" , the result is OK

2- When running a question like: "What is the hometown of the reigning men's U.S. Open champion?"

I got the following error:
What is the hometown of the reigning men's U.S. Open champion?
Are follow up questions needed here: Yes.
Follow up: Who is the reigning men's U.S. Open champion?
(.......)

File ~/anaconda3/envs/nlp/lib/python3.10/site-packages/langchain/chains/self_ask_with_search/base.py:166, in SelfAskWithSearchChain.run(self, question)
    152 def run(self, question: str) -> str:
    153     """Run self ask with search chain.
    154 
    155     Args:
   (...)
...
--> 107 elif "snippet" in res["organic_results"][0].keys():
    108     toret = res["organic_results"][0]["snippet"]
    109 else:
KeyError: 'organic_results'

**Comment by hwchase17** [comment]
hm im having trouble replicating. what version of `google-search-results` are you using? `pip show google-search-results`

**Comment by rubensmau** [comment]
Version: 2.4.1

**Comment by mshumer** [comment]
I'm getting the same error. V 2.4.1.

**Comment by hwchase17** [comment]
okay - i see a few edges in the search code, will work on fixing those. however, i am not quite sure why this is erroring for this particular question. could you try running https://colab.research.google.com/drive/19LKe4p0qUv8aemB9P3xMnoQwVJBGSNkb#scrollTo=FkHWIJlimHIE? is this exactly what you were running locally or are there any differences?

**Comment by hwchase17** [comment]
i added some better handling for error messages - can you see if this helps? https://github.com/hwchase17/langchain/pull/70

**Comment by rubensmau** [comment]
Yes, it is running OK now. Thanks

**Comment by hwchase17** [comment]
awesome! going to resolve for now, but if it reappears feel free to recomment/open
