### ISSUE TITLE
Issue: OpenAIEmbeddings class about Azure Openai usage example error

### ISSUE THREAD

**Issue by Magicen0722** [hwchase17/langchain#5816]
https://github.com/hwchase17/langchain/blob/b3ae6bcd3f42ec85ee65eb29c922ab22a17a0210/langchain/embeddings/openai.py#L100
I was profoundly misled by it when using it, the parameters used in the use case depicted in the example have been renamed to openai_api_base, which seems to be an exact bug, the correct example:
```
import os
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "https://<your-endpoint.openai.azure.com/"
os.environ["OPENAI_API_KEY"] = "your AzureOpenAI key"
os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"
os.environ["OPENAI_PROXY"] = "http://your-corporate-proxy:8080"

from langchain.embeddings.openai import OpenAIEmbeddings
embeddings = OpenAIEmbeddings(
    deployment="your-embeddings-deployment-name",
    model="your-embeddings-model-name",
    openai_api_base="https://your-endpoint.openai.azure.com/",
    openai_api_type="azure",
)
text = "This is a test query."
query_result = embeddings.embed_query(text)
```

**Comment by Magicen0722** [comment]
https://github.com/hwchase17/langchain/blob/master/langchain/chat_models/azure_openai.py#L36
It seems that anything involving Azure OpenAI has a similar problem

**Comment by hanit-com** [comment]
Seems it was fixed.

**Comment by hanit-com** [comment]
@hwchase17 BTW how can I get permissions to assign tickets to myself?
