### ISSUE TITLE
langchain-server: ModuleNotFoundError: No module named 'langchain.cli'

### ISSUE THREAD

**Issue by firezym** [hwchase17/langchain#5833]
### System Info

WSL Ubuntu 20.04

langchain                     0.0.192
langchainplus-sdk             0.0.4

### Who can help?

@agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [x] Callbacks/Tracing
- [ ] Async

### Reproduction

I did as instructed in the link
https://python.langchain.com/en/latest/tracing/local_installation.html

```shell
pip install langchain --upgrade
langchain-server
```

### Expected behavior

❯ langchain-server
Traceback (most recent call last):
  File "/home/usr/miniconda3/envs/dev/bin/langchain-server", line 5, in <module>
    from langchain.server import main
  File "/home/usr/miniconda3/envs/dev/lib/python3.11/site-packages/langchain/server.py", line 5, in <module>
    from langchain.cli.main import get_docker_compose_command
ModuleNotFoundError: No module named 'langchain.cli'

**Comment by happyhappy-jun** [comment]
same same issue

mac os 
langchain 0.0.193
use poetry for env

**Comment by abhinavsood** [comment]
Same issue

RHEL 7
Python 3.8.14 and venv
langchain-0.0.194

**Comment by agawronski** [comment]
same issue:
mac os
Python 3.10.9
langchain 0.0.194

**Comment by gonzoramos** [comment]
same here
mac os
python 3.11
langchain 0.0.194

**Comment by gonzoramos** [comment]
I installed langchain.cli manually and things seems to be working. e.g.

`pipenv install langchain.cli`

**Comment by robertverdes** [comment]
@gonzoramos unfortunately that downgrades langchain to 0.0.139. And won't work with 0.0.196.

I suspect langchain.cli (https://pypi.org/project/langchain-cli/) is not the same thing as the orphaned module in `server.p`: 
`from langchain.cli.main import get_docker_compose_command`
