### ISSUE TITLE
why azure langchain  answer question  confusion

### ISSUE THREAD

**Issue by zhuyaguang** [hwchase17/langchain#5871]
### System Info

0.0.191 mac os python 3.9

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

just simple demo 

simply asked who you are, and he answered a lot of inexplicable words

![image](https://github.com/hwchase17/langchain/assets/8857976/a0ee7d19-2cc3-4574-a03b-dcceb53c269b)

### Expected behavior

no

**Comment by axiangcoding** [comment]
I believe you are using Completion model, instead of Chat Completion model, So llm has continued your sentence.
try `AzureChatOpenAI` instead of `AzureOpenAI`
https://python.langchain.com/en/latest/modules/models/chat/integrations/azure_chat_openai.html

**Comment by zhuyaguang** [comment]
> I believe you are using Completion model, instead of Chat Completion model, So llm has continued your sentence. try `AzureChatOpenAI` instead of `AzureOpenAI` https://python.langchain.com/en/latest/modules/models/chat/integrations/azure_chat_openai.html

👌 thanks
