### ISSUE TITLE
Errors with .txt & .xlsx files.

### ISSUE THREAD

**Issue by AASPLLC** [hwchase17/langchain#5883]
### System Info

I pulled random info online for the .xlsx.
I used state of the union for the .txt
.docx works without error
.pdf works without error

All data was coded using documentation here:
https://python.langchain.com/en/latest/modules/indexes/document_loaders.html

versions:
python-3.10.11-amd64
langchain                   0.0.192
chromadb                    0.3.23

I just need to know how to install a version that works by the looks of this error.
.xlsx error:
```
Traceback (most recent call last):
  File "C:\*\buildchroma.py", line 93, in <module>
    CreateVectorExcelFiles( x );
  File "C:\*\buildchroma.py", line 77, in CreateVectorExcelFiles
    loader = UnstructuredExcelLoader(doc_path+x, mode="elements")
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\excel.py", line 16, in __init__
    validate_unstructured_version(min_unstructured_version="0.6.7")
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\unstructured.py", line 31, in validate_unstructured_version
    raise ValueError(
ValueError: unstructured>=0.6.7 is required in this loader.
PS C:\*> pip install UnstructuredExcelLoader
ERROR: Could not find a version that satisfies the requirement UnstructuredExcelLoader (from versions: none)
ERROR: No matching distribution found for UnstructuredExcelLoader
```

**Text files should work since it is an example from the start. I copy/pasted the state of union txt files from right here in github.**
.txt error:
```
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\text.py", line 41, in load
    text = f.read()
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1225: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\*\buildchroma.py", line 87, in <module>
    CreateVectorTxtFiles( x );
  File "C:\*\buildchroma.py", line 40, in CreateVectorTxtFiles
    txtdocuments = txtloader.load()
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\document_loaders\text.py", line 54, in load
    raise RuntimeError(f"Error loading {self.file_path}") from e
RuntimeError: Error loading C:\*\source_documents\state_of_the_union.txt
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
import os
from langchain import OpenAI

from langchain.document_loaders import UnstructuredWordDocumentLoader
from langchain.document_loaders import UnstructuredExcelLoader
from langchain.document_loaders import PyPDFLoader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.document_loaders import TextLoader

persist_directory = 'db'
embeddings = OpenAIEmbeddings()
```

Excel:
```
	loader = UnstructuredExcelLoader(filepath, mode="elements")
	docs = loader.load()
	vectordb = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory=persist_directory)
	vectordb.persist()
	vectordb = None
```
Txt:
```
	txtloader = TextLoader(filepath)
	txtdocuments = txtloader.load()
	text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
	docs = text_splitter.split_documents(txtdocuments)
	vectordb = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory=persist_directory)
	vectordb.persist()
	vectordb = None
```

### Expected behavior

Just needs to load and create vectorstores for .xlsx and .txt files without errors.

**Comment by albertovilla** [comment]
What's the encoding of the text file? If you don't specify the encoding then the constructor would use the system encoding which may be different than the one in the text file.

`TextLoader(file_path: str, encoding: Optional[str] = None, autodetect_encoding: bool = False)`

You could try to set `autodetect_encoding` to `True` or define the `encoding` parameter to see if that solves the issue.

**Comment by wrharper-AASP** [comment]
i removed state of the union and it loaded the other txt files so it must be something to do with copy/pasting right from github which is a little weird. this issue is technically resolved now.
