### ISSUE TITLE
Langchain model using wikipedia tool fails to return response, but generates it successfully

### ISSUE THREAD

**Issue by efeerrejota** [hwchase17/langchain#5928]
### Langchain agent error

I have the following error while trying to load an llm agent and connecting to wikipedia tool, it seems that the response is generated but throws an error when trying to convert the response to the right format.
Am I missing something or doing something wrong?
Thank you in advanced :)

```python
from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.agents import AgentType
from langchain.memory import ConversationBufferMemory
from langchain.llms import AzureOpenAI

import openai

openai.api_type = "azure"
openai.api_base = "api_base"
openai.api_version = "2022-12-01"
openai.api_key = "key"

memory = ConversationBufferMemory(memory_key="chat-history", return_messages=True,output_key='answer')
llm = AzureOpenAI(deployment_name="text-davinci-003", model_name="text-davinci-003", openai_api_key="key",openai_api_version = "2022-12-01")
tools = load_tools (['wikipedia'], llm=llm)

agent = initialize_agent(
            tools,
            agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
            verbose=True,
            memory=memory,
            llm=llm)

response = {}
response['input'] = "When did Cristobal Colon discover America?"
response['chat_history'] = []
res = agent.run(response) 
```
![errrrCapture](https://github.com/hwchase17/langchain/assets/89514540/9b570bf7-00b4-41b7-8e83-4bdb7a2be49b)

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Execute the code snippet above to reproduce the error

### Expected behavior

We are expecting the generated response as an output but seems to not be working

**Comment by albertovilla** [comment]
I might be wrong but do you need to pass the chat history as input to the agent? You have defined the variable `memory` as `ConversationBufferMemory` so if you want that memory to be empty (i.e. like starting from scratch), I think that you should use that memory variable to set it as empty rather passing the `chat_memory` as input for the agent. The error message is indicating that it expects only one input but you're passing two, the question (input) and the history (chat_history).

**Comment by efeerrejota** [comment]
> I might be wrong but do you need to pass the chat history as input to the agent? You have defined the variable `memory` as `ConversationBufferMemory` so if you want that memory to be empty (i.e. like starting from scratch), I think that you should use that memory variable to set it as empty rather passing the `chat_memory` as input for the agent. The error message is indicating that it expects only one input but you're passing two, the question (input) and the history (chat_history).

I didn't need memory in my process, and I removed it. Now it works perfectly, thank you :)
![image](https://github.com/hwchase17/langchain/assets/89514540/f3a4888f-8f06-41cc-87a7-0e5f59367ff7)
