### ISSUE TITLE
[Chain] Summarize returns empty result when intermediate documents contain hashtag `#`

### ISSUE THREAD

**Issue by vertinski** [hwchase17/langchain#603]
Summarize returns empty result when intermediate documents contain hashtag `#`. Otherwise using different prompt which doesn't generate hashtags all is cool. 

prompt_template = """Write a tweet from the following text:
{text}
"""

PROMPT = PromptTemplate (template=prompt_template, input_variables=["text"])
chain = load_summarize_chain (llm, chain_type="map_reduce", map_prompt=PROMPT, combine_prompt=PROMPT)
chain.run (docs)
''

**Comment by hwchase17** [comment]
![Screen Shot 2023-01-13 at 5 38 16 PM](https://user-images.githubusercontent.com/11986836/212444700-a26618ef-ed9d-45b3-9e7e-e98807c27b1d.png)
hmm its not giving me any issues (see above)

do you want to create a google collab notebook with an example so i can replicate there?

**Comment by vertinski** [comment]
here's the notebook:

https://github.com/vertinski/langchain_bugtest/blob/main/langchain_test_001.ipynb

I think it might be the davinci-003 issue, because often it returns inconsistent results.... 
(also sorry for posting notebook on github!)

**Comment by vertinski** [comment]
The issue was in prompting. I submitted a pull request ✌️ 
https://github.com/hwchase17/langchain/pull/660

**Comment by hwchase17** [comment]
thanks for raising and fixing!
