### ISSUE TITLE
Issue: langchain + pgvector fail to create new tables in postgresql db

### ISSUE THREAD

**Issue by mihailyanchev** [hwchase17/langchain#6045]
### Issue you'd like to raise.

I am trying to load llama-ccp embeddings into a postgresql with the vector extension. The db has the vector extension installed. I am using a user that has the correct privileges to create a new table and insert the embeddings. The code runs smoothly without any errors, but the collection is not being created as a new table in the db. The db name is `embeddings` and the schema name is `vector_store`.

From pgadmin I can see that the there is the following query, which means the embeddings are created and are ready to be loaded:
`INSERT INTO langchain_pg_embedding (collection_id, embedding, document, cmetadata, custom_id, uuid) VALUES ('d10c0cd8-300f-4592-aa2a-42f827...`

However, it seems that no new table is created and the table names do not correspond to the collection name I am setting - `vector_store.test_table`. Any help will be appreciated.

packages:
pgvector                       0.1.8
psycopg2-binary         2.9.6
langchain                      0.0.149

This is my code:
```
from langchain import PromptTemplate, LLMChain
from langchain.llms import GPT4All
from langchain.callbacks.base import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.document_loaders import TextLoader
from langchain.document_loaders import UnstructuredPDFLoader
from langchain.document_loaders import PyPDFLoader
from langchain.document_loaders import DirectoryLoader
from langchain.indexes import VectorstoreIndexCreator
from langchain.embeddings import LlamaCppEmbeddings
from langchain.vectorstores.faiss import FAISS
import os
import datetime

from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores.pgvector import PGVector
from langchain.docstore.document import Document

gpt4all_path = '../models/gpt4all-converted.bin' 
llama_path = '../models/ggml-model-q4_0.bin' 

embeddings = LlamaCppEmbeddings(model_path=llama_path)

loader = TextLoader('../data/test.txt')
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
docs = text_splitter.split_documents(documents)

import os
CONNECTION_STRING = PGVector.connection_string_from_db_params(
    driver=os.environ.get("PGVECTOR_DRIVER", "psycopg2"),
    host=os.environ.get("PGVECTOR_HOST", "xxxxxxxxxxx"),
    port=int(os.environ.get("PGVECTOR_PORT", "5432")),
    database=os.environ.get("PGVECTOR_DATABASE", "embeddings"),
    user=os.environ.get("PGVECTOR_USER", "xxxxxxxx"),
    password=os.environ.get("PGVECTOR_PASSWORD", "xxxxxxxxxxx"),
)

db = PGVector.from_documents(
    embedding=embeddings,
    documents=docs,
    collection_name="vector_store.test_table",
    connection_string=CONNECTION_STRING,
    pre_delete_collection=True
)
```

**Comment by gauravdd** [comment]
I have the same issue and I have updated the latest version of langchain, but its not working.

I'm using PGVector.from_texts() 
Can anyone guide?

**Comment by mihailyanchev** [comment]
> I have the same issue and I have updated the latest version of langchain, but its not working.
> 
> I'm using PGVector.from_texts() Can anyone guide?

If the method passes without error it is quite possible that it was successful. Langchain writes to the default schema, which is probably public and creates two tables where the embeddings for all collections are stored. Look through the public schema for table names containing langchain (langchain_pg_embedding) and will probably find them.

**Comment by gauravdd** [comment]
Hello @mihailyanchev, thanks for your response.

It is writing the entries of the given collection name ("test_embedding")  at  **langchain_pg_collection** and the embeddings at **langchain_pg_embedding**.   I was expecting it should be creating a new table with embeddings with the collection name  **("test_embedding")**? No new tables were created and everything goes to langchain_pg_embedding and there is no issue with create permissions.

Please help, i'm stuck on this.  Please see the code

EMBEDDINGS_TABLE_NAME = "test_embedding"

PGVector.from_texts(
                texts=[content],
                metadatas=[metadata],
                collection_name=EMBEDDINGS_TABLE_NAME,
                connection_string=CONNECTION_STRING,
                embedding =embeddings,

    )

**Comment by mihailyanchev** [comment]
@gauravdd Yes, this is how this method works. Initially, I was also hoping to set the schema and table name as well, but the functionality is not as flexible. collection_name is just the specific text collection and all collections are saved in the same two tables. 
I am not sure what behavior you are expecting.

**Comment by gauravdd** [comment]
I was under the impression that I could segregate my embeddings results into different tables based on different type of search scopes and not mix them all in one, and collection_name allows me to do so.   

Could I have the these two tables under a schema instead of public now? 

one more question please, the pg_collection has cmetadata column, what is the intended use? and how do I set it?

**Comment by mihailyanchev** [comment]
@gauravdd I have not found a way to use a different schema, although it might be something related to sqlalchemy or psycopg2.

I have not tried setting any metadata either.

**Comment by gauravdd** [comment]
Thanks @mihailyanchev , your inputs have given me good clarity.

**Comment by deepak-hl** [comment]
@mihailyanchev , Is the above problem solved?
Actually I am also get stucked there, how can you can resolve above issue?

**Comment by subhsaha** [comment]
create a feature request - https://github.com/langchain-ai/langchain/discussions/25522
