### ISSUE TITLE
tables names are not case insensitive in the Snowflake Client

### ISSUE THREAD

**Issue by RoniFinTech2** [hwchase17/langchain#6052]
### System Info

langchain==0.0.195
python 3.9

the client doesn't recognize 'MY_TABLE' and 'my_table' as the same table.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

when initializing the sql client, add the param `include_tables` and set the strings in upper case fashion.
`sql_database = SQLDatabase(engine,view_support=True, include_tables=["MY_TRADE"])`

you should see this error:
`ValueError: include_tables {'MY_TRADE'} not found in database`

However, everything should go through with:
`sql_database = SQLDatabase(engine,view_support=True, include_tables=["my_trade"])`

### Expected behavior

`sql_database = SQLDatabase(..., include_tables=["MY_TRADE"])`
to be equal to 
`sql_database = SQLDatabase(..., include_tables=["my_trade"])`

**Comment by devstein** [comment]
_Generated by 🤖_

### Answer

To make LangChain's Snowflake Client recognize table names as case insensitive, you can update the `_execute_query` method to set the `QUOTED_IDENTIFIERS_IGNORE_CASE` parameter to `True` when connecting to Snowflake. Modify the `conn` variable assignment as follows:
```py
conn = snowflake.connector.connect(
    user=self.user,
    password=self.password,
    account=self.account,
    warehouse=self.warehouse,
    role=self.role,
    database=self.database,
    schema=self.schema,
    parameters=self.parameters,
    session_parameters={"QUOTED_IDENTIFIERS_IGNORE_CASE": True},
)
```

This will make Snowflake treat 'MY_TABLE' and 'my_table' as the same table.

### Sources 
- [langchain/document_loaders/snowflake_loader.py](https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/snowflake_loader.py)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant
