### ISSUE TITLE
Enhancement: Multiple calls of MapReduceDocumentsChain should run asynchronously

### ISSUE THREAD

**Issue by TomTom101** [hwchase17/langchain#6082]
### Issue you'd like to raise.

When executing `arun()` of the `MapReduceDocumentsChain` multiple times in an async loop, the requests are not run concurrently. 

Given the example: 

```python
import asyncio
from langchain.llms import OpenAI
from langchain.chains.summarize import load_summarize_chain
from langchain.schema import Document

summary_chain = load_summarize_chain(
    OpenAI(temperature=0),
    chain_type="map_reduce",
)

docs = [
    Document(page_content="A doc"),
    Document(page_content="Another doc"),
]

tasks = [
    summary_chain.arun({"input_documents": docs}),
    summary_chain.arun({"input_documents": docs})
]

await asyncio.gather(*tasks)
```

While the mapping step is run asynchronously, the combine step is not. We can see that that the last two requests run sequentially:

<img width="817" alt="image" src="https://github.com/hwchase17/langchain/assets/872712/0472a000-4eb2-43bd-8f97-2e66869c857c">

This is due to the `async acombine()` method also calling the synchronous _process_results() method.

```python
async def acombine_docs(…):
    …
    return self._process_results(...)

def _process_results(…):
    ...
```

## How I can contribute
Will provide a PR! 

The fact that an redundant mapping call is made in case the `input_documents` array contains a single document, is addressed in https://github.com/hwchase17/langchain/pull/5942

@agola11

**Comment by TomTom101** [comment]
Has been taken care of by @MalhotraVijay

**Comment by ShantanuNair** [comment]
@TomTom101 Curious - what tool are you using to monitor/intercept your python processes' http requests?

**Comment by TomTom101** [comment]
[Proxyman](https://proxyman.io/). You can however also use the langchain tracing server to observe that behaviour.
