### ISSUE TITLE
Issue: <search tool only uses its snippets to answer the question, that is not sufficient>

### ISSUE THREAD

**Issue by samantha0-ops** [hwchase17/langchain#6085]
### search tool only uses its snippets to answer the question, that is not sufficient

I found that when calling search tools like 'bing search', 'google search' in an agent, these original api simply returns several urls and their snippets(main topic of the whole webpage). 
However, LangChain directly use these snippets to answer the question, like in bing search:
```python
def run(self, query: str) -> str:
        """Run query through BingSearch and parse result."""
        snippets = []
        results = self._bing_search_results(query, count=self.k)
        if len(results) == 0:
            return "No good Bing Search Result was found"
        for result in results:
            snippets.append(result["snippet"])

        return " ".join(snippets)
```
This concise message passed to the large language model is not sufficient to answer detailed questions, thus leading to bad answers.
Does anyone has a solution to this?

**Comment by LaxmanSinghTomar** [comment]
A possible solution to this would be to do the following:

- Obtain the links from the search results.
- Use these links with [URL document loaders](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/url.html) in LangChain to fetch actual HTML of pages.
- Parse these HTML using [HTML document loaders](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/html.html) to obtain the raw text.

You can consolidate these different steps into a single function and use [tool decorator](https://python.langchain.com/en/latest/modules/agents/tools/custom_tools.html#using-the-tool-decorator) to create a custom search tool that can be consumed by your agent. If the final text happens to be large enough, you may want to adopt approaches like ranking or summarization to get only the most important chunks from this large text with the only downside being the time taken for these steps.

**Comment by samantha0-ops** [comment]
> 

that solves my problem. thanks 😊
