### ISSUE TITLE
This new feature return_intermediate_steps=True is not working as intended, can you please update

### ISSUE THREAD

**Issue by sarath-nalluri** [hwchase17/langchain#6098]
https://github.com/hwchase17/langchain/blame/ee3d0513addae0680a30afa384431a032244e76b/langchain/chains/graph_qa/cypher.py#L40

@tomasonjo This new feature **return_intermediate_steps=True** is not working as intended, can you please update

There is some issue in line number 258 of "langchain\chains\base.py"
 **return self(args[0], callbacks=callbacks)[self.output_keys[0]]** 
the above line always makes it to return only the result and not the intermediate steps.

As a temporary solution I modified line no: 130 of "langchain\chains\graph_qa\cypher.py" to return **{"result":chain_result}** which works.

Thanks in advance!

**Comment by tomasonjo** [comment]
It works as intended, the problem you are having is that you are running the `run` method. Take a look at the example:

```
chain = GraphCypherQAChain.from_llm(
    ChatOpenAI(temperature=0), graph=graph, verbose=True, return_intermediate_steps=True
)
result = chain("Who played in Top Gun?")
print(f"Intermediate steps: {result['intermediate_steps']}")
print(f"Final answer: {result['result']}")
```
![Screenshot from 2023-06-13 19-20-02](https://github.com/hwchase17/langchain/assets/19948365/67671e28-2f30-4612-9133-58eaa66a8bf8)

**Comment by sarath-nalluri** [comment]
Thank You :)
