### ISSUE TITLE
Issue: Update OpenAI model token mapping to reflect new API update 2023-06-13

### ISSUE THREAD

**Issue by eoriont** [hwchase17/langchain#6118]
### Issue you'd like to raise.

The blog post here
https://openai.com/blog/function-calling-and-other-api-updates

specifies
>  - new 16k context version of gpt-3.5-turbo (vs the standard 4k version)

The `langchain/llms/openai.py` `model_token_mapping` should be changed to reflect this.

### Suggestion:

Add `gpt-3.5-turbo-16k` property to `model_token_mapping` with value 16k

**Comment by Ooho1997** [comment]
![image](https://github.com/hwchase17/langchain/assets/38323944/b4d650e6-cdcf-4fb8-be82-d6e86c82a663)
My attempt to add 16k models with model_token_mapping did not affect the token_max value when calling the map_reduce chain

**Comment by eoriont** [comment]
The `combine_docs` function on the `MapReduceDocumentsChain` has the following header:
```py
    def combine_docs(
        self,
        docs: List[Document],
        token_max: int = 3000,
        callbacks: Callbacks = None,
        **kwargs: Any,
    ) -> Tuple[str, dict]:
```
The token_max parameter has a default value, which it looks like you're supposed to change depending on your model. Lmk if this helps!

**Comment by Ooho1997** [comment]
You were right,I am now fixing the problem temporarily by changing the value of token_max,But token_max need to change the value depending on the model
