### ISSUE TITLE
Issue: <Please write a comprehensive title after the 'Issue: ' prefix>

### ISSUE THREAD

**Issue by seohyunjun** [hwchase17/langchain#6129]
### Issue you'd like to raise.

https://openai.com/blog/function-calling-and-other-api-updates

chatgpt-3.5-turbo model can receive 16k so need fixing code l`lm.chains` and `get_openai_callback`

if use max_tokens parameters `openai.error.InvalidRequestError`
```bash
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4133 tokens. Please reduce the length of the messages.
```

**Comment by eoriont** [comment]
See #6118, I think it's basically the same issue. Note that the 16k model is actually separate from the 4k model, as in `gpt-3.5-turbo` vs `gpt-3.5-turbo-16k`.

**Comment by seohyunjun** [comment]
Thank you 🙏
