### ISSUE TITLE
[Docs] Wrap text in code snippets to make prompts easier to read

### ISSUE THREAD

**Issue by aavetis** [hwchase17/langchain#613]
Consider adding `white-space: break-spaces;` to `<pre>` tags on the docs to improve readability of code snippets, especially since there's usually a lot of text in the prompt to read through. As a side-effect, they will make pages seem longer. But that might not be a major issue. In a bit I can add this in a PR when I get a chance; but if someone has the local env setup already and can make this change to the sphinx docs, that would be great.

Before:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/3076502/212448408-096ed88e-6bbe-4571-9dee-09b61b8d02dd.png">

After:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/3076502/212448362-2f4b9d98-f828-405e-8479-9c032b477c71.png">

**Comment by hwchase17** [comment]
this is a great suggestion, will take a stab
