### ISSUE TITLE
OpenAICallbackHandler is not updating values when used in ConversationalRetrievalChain

### ISSUE THREAD

**Issue by ketank1000** [hwchase17/langchain#6158]
### System Info

langchain : 0.0.197
docker python alpine image : 3.11.3

ConversationalRetrievalChain works perfectly and i get awesome output. at the same time i also need to track my usage on openai api call.

Im setting the qa object as below
```
qa = ConversationalRetrievalChain.from_llm(
        model,
        retriever=retriever,
        verbose=True,
        # callback in not updating the cost
        callbacks=[OpenAICallbackHandler()]
    )
```

I see the callback is printing the all openai info on console, which means callback is getting triggered.
But I always see all values to Zero.

### Who can help?

@ag

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create qa object as show in disciption with callback.
2. Pass the question chat history  to qa object 

### Expected behavior

Callback show update all the values for openai traceback

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

It seems like the issue might be related to the way you are accessing the values of the OpenAICallbackHandler instance. The provided test cases show that the values are being updated correctly when the `on_llm_end` method is called.

To access the updated values of the OpenAICallbackHandler instance, you should store the instance in a variable and then access its attributes after the ConversationalRetrievalChain has been used. Here's an example:

```python
callback_handler = OpenAICallbackHandler()

qa = ConversationalRetrievalChain.from_llm(
    model,
    retriever=retriever,
    verbose=True,
    callbacks=[callback_handler]
)

# Use the qa object to process questions and chat history

# Access the updated values of the callback_handler
print("Successful requests:", callback_handler.successful_requests)
print("Total tokens:", callback_handler.total_tokens)
print("Prompt tokens:", callback_handler.prompt_tokens)
print("Completion tokens:", callback_handler.completion_tokens)
print("Total cost:", callback_handler.total_cost)
```

Make sure you are accessing the attributes of the `callback_handler` instance after using the `qa` object to process questions and chat history.

### Sources
- [tests/unit_tests/callbacks/test_openai_info.py](https://github.com/hwchase17/langchain/blob/master/tests/unit_tests/callbacks/test_openai_info.py)

---

This response is meant to be useful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by ketank1000** [comment]
Thanks it working ..

**Comment by gustavz** [comment]
@devstein this doesn't work for streaming responses though.
Is there any way to make `OpenAICallbackHandler` work with `ChatOpenAI(streaming=True)` ?
The issue is that `on_llm_end` is entered before the response is complete which leads to usage being 0.
