### ISSUE TITLE
OPENAI_FUNCTIONS agent doesn't accept python_repl or google-search or wolfram-alpha tool

### ISSUE THREAD

**Issue by alonsosilvaallende** [hwchase17/langchain#6209]
### System Info

Langchain 0.0.200
Python 3.11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [x] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Here is my [gist](https://gist.github.com/alonsosilvaallende/17968208a14994e8285d91abdd79efab) to reproduce the error and my current workaround.
The description of my gist is basically:
1. I followed the [example notebook](https://github.com/hwchase17/langchain/blob/master/docs/modules/agents/agents/examples/openai_functions_agent.ipynb) for OPENAI_FUNCTIONS Agent
2. In the tools, add `python_repl` as follows: `load_tools(['python_repl'])[0]` so that the Tools are modified as follows:
```python
tools = [
    Tool(
        name = "Search",
        func=search.run,
        description="useful for when you need to answer questions about current events. You should ask targeted questions"
    ),
    Tool(
        name="Calculator",
        func=llm_math_chain.run,
        description="useful for when you need to answer questions about math"
    ),
    Tool(
        name="FooBar-DB",
        func=db_chain.run,
        description="useful for when you need to answer questions about FooBar. Input should be in the form of a question containing full context"
    ),
    load_tools(['python_repl'])[0]
]
```

### Expected behavior

I expect the agent to run normally, however it gives me the error:
'Python REPL' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.4.name'
Here is my [gist](https://gist.github.com/alonsosilvaallende/17968208a14994e8285d91abdd79efab) to see the error and my current workaround.
If I understand correctly, the agent doesn't like that the name has a space. Indeed, if I redefine `python_repl` as:
```python
Tool(name='Python',
        func=python_repl.run,
        description='A Python shell. Use this to execute python commands. Input should be a valid python command. If you want to see the output of a value, you should print it out with `print(...)`.'
    ),
```
the problem disappears.  It's a workaround but I expect that either this agent not to have problems with names with spaces or to rename Python REPL as Python_REPL and similarly the other tools as Wolfram_Alpha, etc.

**Comment by vermaat** [comment]
I'm getting a similar error when using the OPENAI_FUNCTIONS Agent in combination with `google-search`:

```
'Google Search' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'
```

However, it works when using the `zero-shot-react-description` agent.

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

The error occurs because the name "Python REPL" contains a space, which doesn't match the regular expression `^[a-zA-Z0-9_-]{1,64}$`. To fix this issue, you can change the name to "Python_REPL" or any other valid name without spaces. 

For example:
```python
class PythonREPLTool(BaseTool):
    """A tool for running python code in a REPL."""

    name = "Python_REPL"
    ...
```

### Sources 
- [langchain/tools/python/tool.py](https://github.com/hwchase17/langchain/blob/master/langchain/tools/python/tool.py)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by alonsosilvaallende** [comment]
It has been solved in pull request [6185](https://github.com/hwchase17/langchain/pull/6185) and in the updated version 0.0.201.
