### ISSUE TITLE
Tools with only default arguments still require a parameter to `run()`

### ISSUE THREAD

**Issue by ahakanbaba** [hwchase17/langchain#6337]
### Issue you'd like to raise.

This issue is created at langchain v0.0.202

Consider the [ListDirectoryTool](https://github.com/hwchase17/langchain/blob/0475d015fe0eb4a997c7d37867e316a23dde8aaa/langchain/tools/file_management/list_dir.py#L21)

Its only parameter has a default value as the `.` current dir. 

Its json-schema suggests no parameter is required 

```
>>> pprint.pprint(langchain.tools.format_tool_to_openai_function(t))
{'description': 'List files and directories in a specified folder',
 'name': 'list_directory',
 'parameters': {'description': 'Input for ListDirectoryTool.',
                'properties': {'dir_path': {'default': '.',
                                            'description': 'Subdirectory to '
                                                           'list.',
                                            'title': 'Dir Path',
                                            'type': 'string'}},
                'title': 'DirectoryListingInput',
                'type': 'object'}}
```
                
 However calling the `run` function without any parameters creates a runtime error 
 
```python
import langchain
t  = langchain.tools.ListDirectoryTool(root_dir="~/misc")
t.run()
```

With this error 
```
>>> t.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: BaseTool.run() missing 1 required positional argument: 'tool_input'
```

This is not a huge problem but at least it creates an inconsistency expectations by the schema and the `run` function call. 

### Suggestion:

If the schema had no required arguments, the run function should not create a runtime error if called without any arguments. At least that would be more expected.

**Comment by vowelparrot** [comment]
It accepts a dictionary with the values contained within it

**Comment by ahakanbaba** [comment]
@vowelparrot 
The point of this ticket was that it **requires** that dictionary even though all Tool parameters have default values.
