### ISSUE TITLE
Supporting Similarity Search with Threshold on PGVector retriever

### ISSUE THREAD

**Issue by hanit-com** [hwchase17/langchain#6346]
### Feature request

Implementing `_similarity_search_with_relevance_scores` on PGVector so users can set search_type to "similarity_score_threshold" without raising **NotImplementedError**.

`
    retriever = pgvector.as_retriever(search_type="similarity_score_threshold", search_kwargs={"score_threshold": 0.7})
    results = retriever.get_relevant_documents(query)
`

### Motivation

Using the search threshold on PGVector to avoid unrelated documents in the results.

### Your contribution

Pull request will be submitted.

**Comment by mrgiba** [comment]
@hanit-com Am I mistaken or similarity search has been removed from PGVector retriever ?

Looking at release 0.0.235: https://github.com/langchain-ai/langchain/blob/v0.0.235/langchain/vectorstores/pgvector.py#L35
