### ISSUE TITLE
About the token_max variable in the "langchain\chains\combine_documents\map_reduce.py" file.

### ISSUE THREAD

**Issue by Ooho1997** [hwchase17/langchain#6397]
### Feature request

About the token_max variable in the "langchain\chains\combine_documents\map_reduce.py" file.
I think the value of token_max should be related to the max_token of the model, rather than setting token_max to 3000.

### Motivation

When I was using the "gpt-3.5-turbo-16k" model, I used the map_reduce chain to process a paper with 30,000 tokens，I always get ValueError
"A single document was so long it could not be combined "
"with another document, we cannot handle this."
I think these are because of the trouble caused by token_max 3000.
When I use a large token model, it is correct that token_max should also be larger.

### Your contribution

I am currently working on my problem by setting token_max to 6000, but this is not perfect, I hope to fix it to dynamically fetch token_max based on different models.
@Harrison Chase

**Comment by Ooho1997** [comment]
@hwchase17 
Hope to gain attention

**Comment by ShantanuNair** [comment]
@Ooho1997 I am discussing with langchain team regarding overhauling the  mapreduce implementation itself. If you want to be able to set `token_max` until then here is how you can do that :) You can close the issue

```
res = await chain(inputs={'input_documents': texts, 'token_max': 12000}, return_only_outputs=True)
```
