### ISSUE TITLE
Structured Tools don't work with OpenAI's new functions

### ISSUE THREAD

**Issue by erdillon** [hwchase17/langchain#6428]
### System Info

Python 3.11
Langchain 201

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [x] Agents / Agent Executors
- [x] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I created a Structured tool, including definitions with Pydantic, and want to use it with an `OpenAIFunctionsAgent`.
I create the tool with `StructuredTool.from_function(my_func)`.

OpenAI doesn't use the schema correctly. After a bit of digging I realized that the "pydantic schema" is provided to the openAI call instead of the "JSON schema".

In `langchain.tools.convert_to_openai.py` see:
```python
def format_tool_to_openai_function(tool: BaseTool) -> FunctionDescription:
    """Format tool into the open AI function API."""
    if isinstance(tool, StructuredTool):
        schema_ = tool.args_schema.schema() # <============================== HERE
        # Bug with required missing for structured tools.
        required = sorted(schema_["properties"])  # BUG WORKAROUND
        return {
            "name": tool.name,
            "description": tool.description,
            "parameters": {
                "type": "object",
                "properties": schema_["properties"],
                "required": required,
            },
        }
 ...
```

I got it to successfully work with this code instead, getting the JSON schema from pydantic instead of the "pydantic schema".
With this openai correctly parses the schema and the tool functions as expected.
```python
def format_tool_to_openai_function(tool: BaseTool) -> FunctionDescription:
    """Format tool into the open AI function API."""
    if isinstance(tool, StructuredTool):
        
        schema_ = tool.args_schema.schema_json()
        return {
            "name": tool.name,
            "description": tool.description,
            "parameters": json.loads(schema_),
        }
...
```

### Expected behavior

Use the JSON schema instead of the pydantic schema to call openAI.

**Comment by zhiyanliu** [comment]
Is this the case should be supported by design of current OpenAIFunctionsAgent? With the doc [0], format_tool_to_openai_function() seems like for ChatModel usage directly instead of an Agent.

So may I know why you close this issue?  @erdillon
