### ISSUE TITLE
How to calculate cost of LLMchain?

### ISSUE THREAD

**Issue by dheerajiiitv** [hwchase17/langchain#644]
Hey Team,
I am running a recursive summarization using MapReduce Chain. I want to calculate cost of running the summarization and for that I want to know about the total token_usage. How can I achieve this functionality?

**Comment by abhimanyupallavisudhir** [comment]
The problem is equivalent to calculating time complexity of a program, isn't it? Not possible to implement in general (halting problem) but possible in cases without while loops and such.

**Comment by solyarisoftware** [comment]
To count token maybe you could use add to LLM the `size` method. 
BTW the token count depends on the LLM implementation; for Openai models maybe you could use their OSS library
https://github.com/openai/tiktoken

**Comment by hwchase17** [comment]
do you want to estimate the cost of this before running, or track the cost after running? we recently added token tracking which should help with the latter: https://langchain.readthedocs.io/en/latest/modules/llms/examples/token_usage_tracking.html

**Comment by dheerajiiitv** [comment]
Yes @hwchase17 It solves my issue.
Thanks :-)
