### ISSUE TITLE
Wrong implementation of score_threshold in Faiss vectorstore

### ISSUE THREAD

**Issue by LIHANG-HONG** [hwchase17/langchain#6526]
### System Info

Langchain Version: 0.0.207

### Who can help?

@hwchase17 

Hi, I am now having a deep dive into the vectorstores and found a wrong implementation in faiss.

The relevant file is as below:
https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/faiss.py#L210

In the similarity_search, the score returned from index is either L2 or inner production, basically the smaller the score is, the more similar. But when the score_threshold is passed to the method, it filters the search result by **similarity >= score_threshold**. 

I think the correct implementation is to change the code to
**similarity <= score_threshold** 
or 
**self.relevance_score_fn(score) >= score_threshold**

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

None

### Expected behavior

None

**Comment by raymond-yuan** [comment]
This is correct for the default implementation, L2, and the comparator of the similarity should be <= the score threshold. However FAISS also supports different metrics (and correspondingly different index types, see [here](https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances) [here](https://github.com/facebookresearch/faiss/blob/main/faiss/IndexFlat.cpp#L44) which will use a min heap vs a max heap). Jaccard and inner product similarity metrics increase as the vectors and more similar. Take a look at this https://github.com/hwchase17/langchain/pull/6564

**Comment by LIHANG-HONG** [comment]
@raymond-yuan 
Hi, thanks for your update! 
Oh yeah, my fault. The comparator of inner production is opposite to L2. I saw the pull request [#6570](https://github.com/hwchase17/langchain/pull/6570). Waiting for the update!

**Comment by LIHANG-HONG** [comment]
Thank you

**Comment by jpzhangvincent** [comment]
> #6564

For the FAISS, 
```
cmp = (
                operator.ge
                if self.distance_strategy
                in (DistanceStrategy.MAX_INNER_PRODUCT, DistanceStrategy.JACCARD)
                else operator.le
            )
docs = [
                (doc, similarity)
                for doc, similarity in docs
                if cmp(similarity, score_threshold)
            ]
```

Hmm, why "DOT_PRODUCT" and "COSINE" score are not applied for the same - meaning the score increase as the vectors are more similar? (i.e operator.ge if self.distance_strategy
                in (DistanceStrategy.MAX_INNER_PRODUCT, DistanceStrategy.JACCARD, DistanceStrategy.DOT_PRODUCT, DistanceStrategy.COSINE))

**Comment by Cognitus-Stuti** [comment]
the relevance scores are negative
 /python3.10/site-packages/langchain_core/vectorstores.py:330: UserWarning: Relevance scores must be between 0 and 1, got [
