### ISSUE TITLE
langchain use AzureOpenai would generate the wrong content

### ISSUE THREAD

**Issue by Light-jason** [hwchase17/langchain#6529]
### System Info

langchain version:0.0.207
python version: 3.9.7

When I use the AzureOpenai  llms of Langchain. It doesn't generate the right result according to my prompt.
But when i use the AzureOpenai of openai. It can generate the right result.

langchain's AzureOpenai:
![image](https://github.com/hwchase17/langchain/assets/50695030/673e907f-34fe-4458-9618-3071cfc141f6)

openai AzureOpenai:
![image](https://github.com/hwchase17/langchain/assets/50695030/51e1869f-f593-4fa5-92a5-fbb666c19d63)

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Here are the code example and the output result
```python
  from langchain.llms import AzureOpenAI
  from langchain.chat_models import ChatOpenAI
  from langchain.prompts import PromptTemplate
  from langchain.chains import LLMChain
  
  def tool_select_chain(azure=True):
      prompt_template = """
      imagine you are a tool selector,
      user input: {input}
      now give the following tool list and tool function description [查询天气, 查询食品, 查询衣服]
      please find the most suitable tool according to the content of the user input and output the tool name.
      the output format is json format, the field is tool.
      tool[查询天气]: used to search the weather 
      tool[查询食品]: used to search the food
      tool[查询衣服]: used to search the clothes
      If you can't find the right tool, output [无]
      just output the tool name with the json format answer:
      """
      PROMPT = PromptTemplate(
          template=prompt_template, input_variables=["input"]
      )
      if not azure:
          llm = ChatOpenAI(temperature=0,
                           model_name='gpt-3.5-turbo-0301',
                           )
      else:
          llm = AzureOpenAI(temperature=0,
                            deployment_name="gpt-35-turbo",
                            model_name='gpt-35-turbo')
  
      chain = LLMChain(llm=llm, prompt=PROMPT)
      return chain
```

### Expected behavior

Find out the reason why this condition appeared and fix this error.
Thank you~

**Comment by hanit-com** [comment]
Try using AzureChatOpenAI instead of AzureOpenAI.

**Comment by Light-jason** [comment]
> Try using AzureChatOpenAI instead of AzureOpenAI.

Thanks you. This issue has been solved
Another question is why AzureOpenai and AzureChatOpenai not generate the same result?

**Comment by hanit-com** [comment]
They are meant to be used with different models so the completions should be different as well.

**Comment by TomTom101** [comment]
Thanks @hanit-com, I also did not realize their was a separate chat model. @Light-jason please close as your original question is answered.
