### ISSUE TITLE
Issue: Changing Prompt (from Default) when Using ConversationalRetrievalChain?

### ISSUE THREAD

**Issue by sooolee** [hwchase17/langchain#6530]
### Issue you'd like to raise.

Hello!

First, thanks a lot for this awesome framework!

My question is: As I was trying out ConversationalRetrievalChain, I see that it has the prompt saying:
"System: Use the following pieces of context to answer the users question. 
If you don't know the answer, just say that you don't know, don't try to make up an answer."

Is there a way for me to change this generic prompt? I'm talking about the prompt that comes with the retriever results, not the "condense_question_prompt". 

I could modify "condense_question_prompt" where the default template is 'Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.\n\nChat History:\n{chat_history}\nFollow Up Input: {question}\nStandalone question:'

The reason I'm asking this is.... as the conversation gets longer (k > 4 or 5), the model start hallucinating. I was expecting it would answer based on the retrieved context every single time. But later conversation tends to go astray. Is there a way to control that behavior, if not through prompts? (still think prompts are the best way....)

Thank you!!

**Comment by sooolee** [comment]
Hi. I found a way to get what I want by using load_qa_chain and adding memory, instead of using ConversationalRetrievalChain. I am closing this issue. Thanks!

**Comment by fengziadmin** [comment]
why close the issue ?

**Comment by sooolee** [comment]
@fengziadmin Well, I closed it because there is another question-answering chain to which I can add my custom prompt. But now seeing your question, I think it would be still nice to be able to change the main prompt in ConversationalRetrievalChain. So for the sake of asking a new feature, I will reopen this. :-)

**Comment by ShantanuNair** [comment]
You can pass it in via `combine_docs_chain_kwargs` if you instantiate the chain using from_llm
```
ConversationalRetrievalChain.from_llm(combine_docs_chain_kwargs={"prompt": your_prompt}))
```

**Comment by cresshounnoukon** [comment]
> load_qa_chain



> Hi. I found a way to get what I want by using load_qa_chain and adding memory, instead of using ConversationalRetrievalChain. I am closing this issue. Thanks!

Hello .
I have the same issue. Can you share the source code?

**Comment by ShantanuNair** [comment]
@sooolee You can close it now :)

**Comment by thekkanathashish95** [comment]
Hi, @sooolee - Can you discuss a bit more about how you resolved the issue using load_qa_chain and adding memory? Thanks in advance. 

I am new to LLM's and condense_question_prompt is rephrasing my question beyond any meanings. Would you share your inputs on how to resolve this issue?

**Comment by sooolee** [comment]
Hi @thekkanathashish95,
Just seeing this. Using load_qa_chain with memory is pretty straight forward. LangChain docs have lots of examples. Here's my example:

`
from langchain.chains.question_answering import load_qa_chain
template = """
{Your Prompt}

CONTEXT:
=========
{context}
=========

QUESTION: 
````````
{query}
````````
CHAT HISTORY: 
{chat_history}

ANSWER:
"""

prompt = PromptTemplate(input_variables=["chat_history", "query", "context"], template=template)
memory = ConversationBufferMemory(memory_key="chat_history", input_key="query")

chain = load_qa_chain(ChatOpenAI(temperature=0), chain_type="stuff", memory=memory, prompt=prompt)
`

**Comment by andrewsanchez** [comment]
> You can pass it in via `combine_docs_chain_kwargs` if you instantiate the chain using from_llm
> 
> ```
> ConversationalRetrievalChain.from_llm(combine_docs_chain_kwargs={"prompt": your_prompt}))
> ```

This does not seem to work as described here:  https://github.com/langchain-ai/langchain/issues/11656

I had the same result:

```
2023-10-18 17:30:53.774 Uncaught app exception
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ankihubai/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/Users/andrewsanchez/Projects/ankihubai/streamlit_app.py", line 35, in <module>
    qa_chain = utils.chroma.initialize_chain(db, memory)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrewsanchez/Projects/ankihubai/utils/chroma.py", line 62, in initialize_chain
    qa_chain = ConversationalRetrievalChain.from_llm(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ankihubai/lib/python3.11/site-packages/langchain/chains/conversational_retrieval/base.py", line 358, in from_llm
    doc_chain = load_qa_chain(
                ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ankihubai/lib/python3.11/site-packages/langchain/chains/question_answering/__init__.py", line 249, in load_qa_chain
    return loader_mapping[chain_type](
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ankihubai/lib/python3.11/site-packages/langchain/chains/question_answering/__init__.py", line 73, in _load_stuff_chain
    llm_chain = LLMChain(
                ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ankihubai/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ankihubai/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for LLMChain
prompt
  value is not a valid dict (type=type_error.dict)
```

**Comment by andrewsanchez** [comment]
It looks like you have to pass in a `ChatPromptTemplate`.  The default that is passed into `LLMChain` in my case is defined here:  

https://github.com/langchain-ai/langchain/blob/4adabd33ac56995542a60f69d89762d3f80ae939/libs/langchain/langchain/chains/question_answering/stuff_prompt.py#L10-L28

**Comment by deepak-habilelabs** [comment]
@sooolee Can u pls help me as I am new to langchain, I am trying to add memory , but not able to further proceed it, below is my code 
`def generate_custom_prompt(new_project_qa,query,name,not_uuid):  
    check = query.lower() 
    result = new_project_qa(query)
    relevant_document = result['source_documents']
    context_text="\n\n---\n\n".join([doc.page_content for doc in relevant_document])
    # print(context_text,"context_text")
    user_experience_inst = UserExperience.objects.get(not_uuid=not_uuid)
    greetings = ['hi', 'hello', 'hey', 'hui', 'hiiii', 'hii', 'hiii', 'heyyy']
    if check in greetings:
        custom_prompt_template = f"""
        Just simply reply with "Hello {name}! How can I assist you today?"
        """
    elif check not in greetings and user_experience_inst.custom_prompt:
        custom_prompt_template = f"""Answer the question based only on following context: ```{context_text} ```
        You are a chatbot designed to provide answers to User's Questions:```{check}```, delimited by triple backticks.
        Generate your answer to match the user's requirements: {user_experience_inst.custom_prompt}

        If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
        - Before saying 'I don't know,' please re-verify your vector store to ensure the answer is not present in the database.

        Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, feel free to ask for clarification.

        User's Question: ```{check}```
        AI Answer:"""
    else:
        # Create the custom prompt template
        custom_prompt_template = f"""Generate your response exclusively from the provided context: {{context_text}}. You function as a chatbot specializing in delivering detailed answers to the User's Question: ```{{check}} ```, enclosed within triple backticks.
            Generate your answer in points in the following format:
            1. Point no 1
                1.1 Its subpoint in details
                1.2 More information if needed.
            2. Point no 2
                2.1 Its subpoint in details
                2.2 More information if needed.
            …
            N. Another main point.

            If you encounter a question for which you don't know the answer based on the predefined points, please respond with 'I don't know' and refrain from making up an answer.
            However, if the answer is not present in the predefined points, then Provide comprehensive information related to the user's query.
            Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

            User's Question: ```{{check}} ```  
            AI Answer:"""


    # Create the PromptTemplate
    custom_prompt = ChatPromptTemplate.from_template(custom_prompt_template)
    formatted_prompt = custom_prompt.format(context_text=context_text, check=check)
    return formatted_prompt
    
    def retreival_qa_chain(chroma_db_path):
    embedding = OpenAIEmbeddings()
    vectordb = Chroma(persist_directory=chroma_db_path, embedding_function=embedding)
    llm = ChatOpenAI(model="gpt-3.5-turbo-16k",temperature=0.1)
    retriever = vectordb.as_retriever(search_kwargs={"k": 2})
    memory = ConversationSummaryBufferMemory(llm=llm,output_key='answer',memory_key='chat_history',return_messages=True)
    # qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever,return_source_documents=True)
    qa=ConversationalRetrievalChain.from_llm(llm=llm,memory=memory,chain_type="stuff",retriever=retriever,return_source_documents=True,get_chat_history=lambda h : h,verbose=True)
    return qa`
    Thanks in advance :))

**Comment by sooolee** [comment]
@deepak-habilelabs Unfortunately, I have not been working in this field for a while... and feel Lang Chain has been updated a lot since. I hope someone who's better equipped can answer your question! :-)

**Comment by deepak-habilelabs** [comment]
> @deepak-habilelabs Unfortunately, I have not been working in this field for a while... and feel Lang Chain has been updated a lot since. I hope someone who's better equipped can answer your question! :-)

No problem, thanks anyway

**Comment by nis12ram** [comment]
through these code also we can modify the both CONDENSE_QUESTION_PROMPT and QA_PROMPT

**Code

````
    llm = ChatGroq(groq_api_key=groq_api_key, model_name="llama3-8b-8192")

    memory = ConversationBufferMemory(
        memory_key='chat_history', return_messages=True)
    custom_condense_question_template = """Given the following conversation and a follow-up message, rephrase the follow-up message to a stand-alone question or instruction that represents the user's intent, add all context needed if necessary to generate a complete and unambiguous question or instruction. Only modify the original question if the chat history provides important context or relevance to it. Maintain the same language as the follow-up input message.

Chat History:
{chat_history}

Follow Up Input: {question}
Standalone question or instruction:
"""
    conversation_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=vectorstore.as_retriever(
            search_kwargs={"k": 3}),
        memory=memory,
        verbose=True,
        condense_question_prompt=PromptTemplate.from_template(
            custom_condense_question_template)

    )

    try:
        conversation_chain.combine_docs_chain.llm_chain.prompt.template = """Analyze the context very properly and then try to answer thw question based on the understanding that you gain from the context.

{context}

Question: {question}
Helpful Answer:"""

    except Exception as e:
        if str(e) == '"ChatPromptTemplate" object has no field "template"':
            print("Error: ChatPromptTemplate has no 'template' field. Using fallback.")
            qa_template = SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[
                'context'], template="Analyze the context very properly and then try to answer thw question based on the understanding that you gain from the context..\n----------------\n{context}"))
            conversation_chain.combine_docs_chain.llm_chain.prompt.messages[0] = qa_template
        else:
            print(f"Unexpected error: {e}")  # Handle other exceptions

``

**Comment by ArturasGrygelis** [comment]
So somebody can give valid solution??
