### ISSUE TITLE
Not able to clear Conversationbuffermemory.

### ISSUE THREAD

**Issue by NageshMashette** [hwchase17/langchain#6585]
### Feature request

The current implementation of ConversationBufferMemory lacks the capability to clear the memory history. When using the load_qa_chain function with ConversationBufferMemory and uploading the abc.pdf file for the first time, subsequent questions based on that document yield expected answers. However, if I then change the file to 123.pdf and ask the same questions as before, the system provides the same answers as those given for the previous pdf.

Unfortunately, I have not found a clear_history function within the ConversationBufferMemory, which would enable me to reset or remove the previous memory records.

### Motivation

add that clear_history under ConversationBufferMemory to clear all previous saved messages.

### Your contribution

no

**Comment by Avinash-Raj** [comment]
what's wrong with `memory.clear()` ?

**Comment by NageshMashette** [comment]
ok thanks @Avinash-Raj , let me try.

**Comment by CodiTrixta** [comment]
Yea that does work but thats not what im looking for. Do you know of a way to  clear only the last response? or maybe replace it with some other text?

**Comment by NageshMashette** [comment]
working fine, thanks
