### ISSUE TITLE
ChromaDB Chroma.from_documents error:   AttributeError: 'Collection' object has no attribute 'upsert'

### ISSUE THREAD

**Issue by luca-git** [hwchase17/langchain#6721]
### System Info

windows 11, python 3.9.16 , langchain-0.0.215

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The loaded documents succesfully get indexd in FAISS, Deeplake and Pinecone, so I guess the issue is not there. When using  Chroma.from_documents the error is thrown:

```
  File ~\...langchain\vectorstores\chroma.py:149 in add_texts
    self._collection.upsert(
        AttributeError: 'Collection' object has no attribute 'upsert'
```
Code:
```python
with open('docs.pkl', 'rb') as file:
    documents= pickle.load(file)   
text_splitter = RecursiveCharacterTextSplitter(chunk_size=512, chunk_overlap=200)
docs = text_splitter.split_documents(documents)
chroma_dir = base_dir + "ChromaDB" + "_" + str(chunk_size) + "_" + str(overlap)
db2 = Chroma.from_documents(docs, embeddings, persist_directory=chroma_dir)
```
Uploaded the pickle zipped as .pkl is not supported for upload.
[docs.zip](https://github.com/hwchase17/langchain/files/11860249/docs.zip)

### Expected behavior

Index the docs

**Comment by devstein** [comment]
@luca-git What version of `chroma` do you have installed? The `upsert` function for ChromaDB collection is relatively new

**Comment by luca-git** [comment]
I'm dumb as a donkey (donkeys are lovely BTW). the basics damn, silly me.

Fix:  Update Chroma and install lark.
