### ISSUE TITLE
TypeError: __init__() takes exactly 1 positional argument (2 given)

### ISSUE THREAD

**Issue by heavenkiller2018** [hwchase17/langchain#6730]
### System Info

langchain:0.0.215

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.indexes import VectorstoreIndexCreator
from langchain.embeddings import OpenAIEmbeddings
index = VectorstoreIndexCreator(embedding=OpenAIEmbeddings('gpt2')).from_loaders([loader])


```

error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 3
      1 from langchain.indexes import VectorstoreIndexCreator
      2 from langchain.embeddings import OpenAIEmbeddings
----> 3 index = VectorstoreIndexCreator(embedding=OpenAIEmbeddings('gpt2')).from_loaders([loader])

File [~/micromamba/envs/openai/lib/python3.11/site-packages/pydantic/main.py:332], in pydantic.main.BaseModel.__init__()

TypeError: __init__() takes exactly 1 positional argument (2 given)
```

### Expected behavior

no

**Comment by pingsutw** [comment]
@heavenkiller2018 you can fix it by using keyword arguments.
```python
index = VectorstoreIndexCreator(embedding=OpenAIEmbeddings(model='gpt2'))
```

**Comment by heavenkiller2018** [comment]
Great to hear! I'm glad the issue has been resolved.
