### ISSUE TITLE
id type in SupabaseVectorStore doesn't match SQL column

### ISSUE THREAD

**Issue by xleven** [hwchase17/langchain#6743]
### System Info

LangChain version: 0.0.214

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Same as [Supabase docs](https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/supabase) with the exact table and function created, where `id` column has type of bigint.

```Python
from supabase.client import Client, create_client
from langchain.embeddings import OpenAIEmbeddings
from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import SupabaseVectorStore

loader = TextLoader("../../../state_of_the_union.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()

supabase_client: Client = create_client(
    supabase_url=os.getenv("SUPABASE_URL"),
    supabase_key=os.getenv("SUPABASE_SERVICE_KEY"),
)

supabase_vector_store = SupabaseVectorStore.from_documents(
    documents=docs,
    client=supabase_client,
    embedding=embeddings,
)
```

Got
> APIError: {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type bigint: "64f03aff-0c0e-4f24-91e2-e01fcaxxxxxx"'}

### Expected behavior

Successfully insert and embed the split docs into Supabase.

To be helpful, I believe it was introduced by [this commit](https://github.com/hwchase17/langchain/commit/be02572d586bcb33fffe89c37b81d5ba26762bec) regarding the List[str] type `ids`. But not sure if it was intended with docs not updated yet, or otherwise.

**Comment by xleven** [comment]
Forget to mention: after change id type to uuid in SQL DDL, it will work. So maybe it's the example doc to be updated. Just not sure.

**Comment by siddarthvader** [comment]
facing the same problem and it can be resolved with changes in DLL, but i am using TS module for the retrieval, where my code refuses to run. @xleven  did you also face the same kin
![Screenshot 2023-06-27 at 12 09 13 AM](https://github.com/hwchase17/langchain/assets/7977737/753b90f7-4eca-49ac-8de3-b24c52cdde54)
d of issue?

**Comment by zhangbaoliang** [comment]
> ### System Info
> LangChain version: 0.0.214
> 
> ### Who can help?
> _No response_
> 
> ### Information
> * [x]  The official example notebooks/scripts
> * [ ]  My own modified scripts
> 
> ### Related Components
> * [ ]  LLMs/Chat Models
> * [ ]  Embedding Models
> * [ ]  Prompts / Prompt Templates / Prompt Selectors
> * [ ]  Output Parsers
> * [ ]  Document Loaders
> * [x]  Vector Stores / Retrievers
> * [ ]  Memory
> * [ ]  Agents / Agent Executors
> * [ ]  Tools / Toolkits
> * [ ]  Chains
> * [ ]  Callbacks/Tracing
> * [ ]  Async
> 
> ### Reproduction
> Same as [Supabase docs](https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/supabase) with the exact table and function created, where `id` column has type of bigint.
> 
> ```python
> from supabase.client import Client, create_client
> from langchain.embeddings import OpenAIEmbeddings
> from langchain.document_loaders import TextLoader
> from langchain.text_splitter import CharacterTextSplitter
> from langchain.vectorstores import SupabaseVectorStore
> 
> loader = TextLoader("../../../state_of_the_union.txt")
> documents = loader.load()
> text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
> docs = text_splitter.split_documents(documents)
> 
> embeddings = OpenAIEmbeddings()
> 
> supabase_client: Client = create_client(
>     supabase_url=os.getenv("SUPABASE_URL"),
>     supabase_key=os.getenv("SUPABASE_SERVICE_KEY"),
> )
> 
> supabase_vector_store = SupabaseVectorStore.from_documents(
>     documents=docs,
>     client=supabase_client,
>     embedding=embeddings,
> )
> ```
> 
> Got
> 
> > APIError: {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type bigint: "64f03aff-0c0e-4f24-91e2-e01fcaxxxxxx"'}
> 
> ### Expected behavior
> Successfully insert and embed the split docs into Supabase.
> 
> To be helpful, I believe it was introduced by [this commit](https://github.com/hwchase17/langchain/commit/be02572d586bcb33fffe89c37b81d5ba26762bec) regarding the List[str] type `ids`. But not sure if it was intended with docs not updated yet, or otherwise.

Downgrading langchain to version 0.0.200 resolved the issue.

**Comment by siddarthvader** [comment]
> > ### System Info
> > LangChain version: 0.0.214
> > ### Who can help?
> > _No response_
> > ### Information
> > 
> > * [x]   The official example notebooks/scripts
> > * [ ]   My own modified scripts
> > 
> > ### Related Components
> > 
> > * [ ]   LLMs/Chat Models
> > * [ ]   Embedding Models
> > * [ ]   Prompts / Prompt Templates / Prompt Selectors
> > * [ ]   Output Parsers
> > * [ ]   Document Loaders
> > * [x]   Vector Stores / Retrievers
> > * [ ]   Memory
> > * [ ]   Agents / Agent Executors
> > * [ ]   Tools / Toolkits
> > * [ ]   Chains
> > * [ ]   Callbacks/Tracing
> > * [ ]   Async
> > 
> > ### Reproduction
> > Same as [Supabase docs](https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/supabase) with the exact table and function created, where `id` column has type of bigint.
> > ```python
> > from supabase.client import Client, create_client
> > from langchain.embeddings import OpenAIEmbeddings
> > from langchain.document_loaders import TextLoader
> > from langchain.text_splitter import CharacterTextSplitter
> > from langchain.vectorstores import SupabaseVectorStore
> > 
> > loader = TextLoader("../../../state_of_the_union.txt")
> > documents = loader.load()
> > text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
> > docs = text_splitter.split_documents(documents)
> > 
> > embeddings = OpenAIEmbeddings()
> > 
> > supabase_client: Client = create_client(
> >     supabase_url=os.getenv("SUPABASE_URL"),
> >     supabase_key=os.getenv("SUPABASE_SERVICE_KEY"),
> > )
> > 
> > supabase_vector_store = SupabaseVectorStore.from_documents(
> >     documents=docs,
> >     client=supabase_client,
> >     embedding=embeddings,
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Got
> > > APIError: {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type bigint: "64f03aff-0c0e-4f24-91e2-e01fcaxxxxxx"'}
> > 
> > 
> > ### Expected behavior
> > Successfully insert and embed the split docs into Supabase.
> > To be helpful, I believe it was introduced by [this commit](https://github.com/hwchase17/langchain/commit/be02572d586bcb33fffe89c37b81d5ba26762bec) regarding the List[str] type `ids`. But not sure if it was intended with docs not updated yet, or otherwise.
> 
> Downgrading langchain to version 0.0.200 resolved the issue.

change the DLL of your match function and table in supabase, change `id bigint` to `id uuid` and it should work with latest version.

**Comment by MarkEdmondson1234** [comment]
@xleven @ShantanuNair  Is this the DDL thats ok to use? (Gpt-4 suggested ;) )

```
- 1. Add a new column
ALTER TABLE langchain ADD COLUMN uuid_id UUID;

-- 2. Populate the new column with UUIDs (assuming that you want to generate new UUIDs)
UPDATE langchain SET uuid_id = uuid_generate_v4();

-- Before proceeding, make sure that the new UUIDs are unique and not null

-- 3. Drop the old id column
ALTER TABLE langchain DROP COLUMN id;

-- 4. Rename the new uuid_id column to id
ALTER TABLE langchain RENAME COLUMN uuid_id TO id;
```

**Comment by xleven** [comment]
@MarkEdmondson1234  I guess the alter sql will do. But please take a look at [DDL in the doc](https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/supabase), which shall work now.

**Comment by MarkEdmondson1234** [comment]
@xleven I updated from the doc which worked ok for similar search, but when I tried to add new documents I got the error above, so needed to run the DDL above to modify the existing databases.  It looks like it worked ok.

**Comment by demonhunter3333** [comment]
> @zhangbaoliang change the DDL of your match function and table in supabase, change `id bigint` to `id uuid` and it should work with latest version.

but we have to use `id bigint` for the js SupabaseVectorStore to work. why did you guys swtich to `id uuid`?
