### ISSUE TITLE
LLM中文应用交流微信群

### ISSUE THREAD

**Issue by Anna10071** [hwchase17/langchain#6745]
LLM中文应用和技术交流群，如果二维码过期可加微信备注LLM应用：yydsa0007

![9cfa9a394442162b466b747db86b5c9](https://github.com/hwchase17/langchain/assets/90118245/27869c08-69aa-4cea-9a6b-f54ba020e9d2)

**Comment by java668** [comment]
yydsa0007 查不到用户
