### ISSUE TITLE
Recent tags change causes AttributeError: 'str' object has no attribute 'value' on initialize_agent call

### ISSUE THREAD

**Issue by LittleColin** [hwchase17/langchain#6756]
### System Info

- Langchain: 0.0.215
- Platform: ubuntu
- Python 3.10.12

### Who can help?

@vowelparrot 

https://github.com/hwchase17/langchain/blob/d84a3bcf7ab3edf8fe1d49083e066d51c9b5f621/langchain/agents/initialize.py#L54

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Fails if agent initialized as follows:
```python
agent = initialize_agent(
        agent='zero-shot-react-description',
        tools=tools,
        llm=llm,
        verbose=True,
        max_iterations=30,
        memory=ConversationBufferMemory(),
        handle_parsing_errors=True)
```
With
```
...
lib/python3.10/site-packages/langchain/agents/initialize.py", line 54, in initialize_agent
    tags_.append(agent.value)
AttributeError: 'str' object has no attribute 'value'
````

### Expected behavior

Expected to work as before where agent is specified as a string (or if this is highlighting that agent should actually be an object, it should indicate that instead of the error being shown).

**Comment by nithinjp1997** [comment]
yes i also got this error

**Comment by Zero-coder** [comment]
agree!the same to me!

**Comment by vowelparrot** [comment]
Will land a fix. Thanks for raising this!

**Comment by Zero-coder** [comment]
> Will land a fix. Thanks for raising this!

Thank you,it's working now.
