### ISSUE TITLE
Request to Support other VertexAI's LLM model Support

### ISSUE THREAD

**Issue by techwithshadab** [hwchase17/langchain#6779]
### Feature request

Right now only `text-bison` model is support by Google PaLM. When tried `code-bison` its throwing below error:
```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[39], line 1
----> 1 llm = VertexAI(model_name='code-bison')

File /opt/conda/envs/python310/lib/python3.10/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for VertexAI
__root__
  Unknown model publishers/google/models/code-bison; {'gs://google-cloud-aiplatform/schema/predict/instance/text_generation_1.0.0.yaml': <class 'vertexai.language_models._language_models._PreviewTextGenerationModel'>} (type=value_error)
```

Can we get other model supports as well?

### Motivation

Support for many other PaLM models

### Your contribution

I can update and test the code for different other models

**Comment by Jflick58** [comment]
Believe this was implemented in #6354

**Comment by HassanOuda** [comment]
Just update to the latest version of langchain and you should be able to use the Codey models.

**Comment by techwithshadab** [comment]
`codey` is supported, but still `chat-bison` and `codechat-bison` are throwing error

**Comment by techwithshadab** [comment]
> Just update to the latest version of langchain and google-cloud-aiplatform and you should be able to use the Codey models.

Any example link for this?

**Comment by opyate** [comment]
Same here:

```
model = TextGenerationModel.from_pretrained("code-bison")  # also tried code-bison@001
```

Error:

> ValueError: Unknown model publishers/google/models/code-bison; {'gs://google-cloud-aiplatform/schema/predict/instance/text_generation_1.0.0.yaml': <class 'vertexai.language_models._language_models._PreviewTextGenerationModel'>}

Using latest stable `google-cloud-aiplatform==1.30.1` at time of writing.

**Comment by mmkamani7** [comment]
Seems that the newer model from Google is not supported. Getting the same error for `text-unicorn@001`:

```cli
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatVertexAI
__root__
  Unknown model publishers/google/models/text-unicorn; {'gs://google-cloud-aiplatform/schema/predict/instance/chat_generation_1.0.0.yaml': <class 'vertexai.language_models.ChatModel'>} (type=value_error)
```

**Comment by elhadik** [comment]
__root__
  Unknown model publishers/google/models/gemini-pro; {'gs://google-cloud-aiplatform/schema/predict/instance/text_generation_1.0.0.yaml': <class 'vertexai.preview.language_models._PreviewTextGenerationModel'>} (type=value_error)

**Comment by gpy1234** [comment]
> **root** Unknown model publishers/google/models/gemini-pro; {'gs://google-cloud-aiplatform/schema/predict/instance/text_generation_1.0.0.yaml': <class 'vertexai.preview.language_models._PreviewTextGenerationModel'>} (type=value_error)

Can you share a snippet of your code?

**Comment by PalTAJ** [comment]
i was trying to use 

I was following this, to use google models:

[ Retrieval Augmented Generation (RAG) with Codey API](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/code/code_retrieval_augmented_generation.ipynb)


it uses code-bison, but i needed to use "codechat-bison" and when i changed the model name it gave me the error you are facing.

i managed to solve it doing the following:

1.  Install langchain community :  pip install langchain-community
2. Use ChatVertexAI from  langchain_community instead of VertexAI when calling the model

this is the code i used:

```
from langchain_community.chat_models import ChatVertexAI

code_llm = ChatVertexAI(
    model_name="codechat-bison",
    max_output_tokens=2048,
    temperature=0.1,
    verbose=False,
    )

```

replacing this:

```
from langchain.llms import VertexAI

code_llm = VertexAI(
    model_name="code-bison@002",
    max_output_tokens=2048,
    temperature=0.1,
    verbose=False,
)
```
restart kernel and run again.

then the code worked fine, hope this helps.
i found this  [here](https://python.langchain.com/docs/integrations/chat/google_vertex_ai_palm.html#code-generation-chat-models)

**Comment by narayan-h** [comment]
I am getting error with medlm-large

pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatVertexAI
__root__
  Unknown model publishers/google/models/medlm-large; {'gs://google-cloud-aiplatform/schema/predict/instance/chat_generation_1.0.0.yaml': <class 'vertexai.language_models.ChatModel'>} (type=value_error)

**Comment by AtulVishwakarmaCP** [comment]
> I am getting error with medlm-large
> 
> pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatVertexAI **root** Unknown model publishers/google/models/medlm-large; {'gs://google-cloud-aiplatform/schema/predict/instance/chat_generation_1.0.0.yaml': <class 'vertexai.language_models.ChatModel'>} (type=value_error)

I am facing same issue iwth medLm models, If you got solution please post it here
