### ISSUE TITLE
General OpenAI Function Mapping from Pydantic, Dicts directly to function, parameters, and properties

### ISSUE THREAD

**Issue by enjuichang** [hwchase17/langchain#6933]
### Feature request

A universal approach to add openai functions specifically for output format control to `LLMchain`. Create a class that takes in dict, json, pydantic, or even rail specs (from guardrails) to preprocess classes or dictionaries into openai functions (function, parameters, and properties) for the `llm_kwargs` in `LLMChain` class in conjunction with the openai function parsers.

### Motivation

It is hard to use the function calling feature right now if you are not working with agents (can access using `format_tool_to_openai_function`) or a specific use case, such as the Extractor or QA chains. The idea is to create a general class that takes in dict, json, pydantic, or even rail specs (from guardrails) to preprocess classes or dictionaries into openai functions for better control of the output format.

### Your contribution

I can help with this, should I put this in the `docs/modules` folder?

**Comment by Krumil** [comment]
This will be very useful. Right now i can't understand how to correctly define an LLMChain that use the openai function parameter.

**Comment by bradcrossen** [comment]
Agreed on this. Function calling structured output doesn't look so simple with langchain and already looks included with llamaindex.

**Comment by Krumil** [comment]
Tried llama_index after your comment. This is exactly what I need. (btw I'm not complaining about langchain, what you did in this weeks has been incredible and i really don't need llama_index othewise).

**Comment by enjuichang** [comment]
Yeah exactly! Gonna try to push something let me know what you guys think about it

**Comment by bradcrossen** [comment]
I would use it for sure.

**Comment by bradcrossen** [comment]
FYI there is a good example of how to do this with langchain in this twitter thread.

https://twitter.com/ethanjdev/status/1676320043456397312

**Comment by enjuichang** [comment]
Added a PR that should work!

**Comment by enjuichang** [comment]
@bradcrossen yeah that's exactly what I am proposing. I just want to wrap everything into a function so. that it can be similar to `PromptTemplate` class, nice and readable.

**Comment by enjuichang** [comment]
Seems like this is mostly solved [here](https://github.com/hwchase17/langchain/blob/master/langchain/chains/openai_functions/base.py)
