### ISSUE TITLE
add `Brave` Search

### ISSUE THREAD

**Issue by leo-gan** [hwchase17/langchain#6939]
### Feature request

[Brave Search](https://api.search.brave.com/app/dashboard) is a new interesting search engine
It can be used in place of the `Google Search`.

### Motivation

Users who are subscribers of Brave Search can use this.

### Your contribution

I can try to implement it if somebody is interested in this integration.

**Comment by JoseHervas** [comment]
Hey leo, 

You mean something like this?

https://python.langchain.com/docs/modules/agents/tools/integrations/brave_search

**Comment by leo-gan** [comment]
@JoseHervas Yes, that's it! Thanks for pointing this!
