### ISSUE TITLE
HuggingFacePipeline not working

### ISSUE THREAD

**Issue by GuillemGSubies** [hwchase17/langchain#6970]
### System Info

langchain==0.0.219

### Who can help?

    @hwchase17
    @agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

>>> from langchain import HuggingFacePipeline
>>> mod = HuggingFacePipeline(model_id="tiiuae/falcon-7b-instruct", task="text-generation")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guillem.garcia/miniconda3/envs/rene/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFacePipeline
task
  extra fields not permitted (type=value_error.extra)

### Expected behavior

I expect it to work. When I instance a Pipeline with falcon using hugginface it works.

Also, Is there a way to deactivate pydantic? It makes it impossible to modify anything or make langchain compatible with our code

**Comment by albertovilla** [comment]
@GuillemGSubies I think there's a mistake in your code, it should be:

`mod = HuggingFacePipeline.from_model_id(model_id="tiiuae/falcon-7b-instruct", task="text-generation")`

You have to use the `from_model_id` method, the constructor doesn't expect a `task` parameter.

**Comment by GuillemGSubies** [comment]
Indeed, thank you very much
