### ISSUE TITLE
Using JSONLinesLoader in Python

### ISSUE THREAD

**Issue by arozbiz** [hwchase17/langchain#6973]
### Feature request

It would be great if the [JSONLinesLoader](https://js.langchain.com/docs/modules/indexes/document_loaders/examples/file_loaders/jsonlines) that's available in the JS version of Langchain could be ported to the Python version.

### Motivation

I find working with jsonl files to be frequently easier than json files.

### Your contribution

Not sure---I'm quite new to Python and so don't how to implement this.

**Comment by keenborder786** [comment]
Hey, I would work on this enhancement.

**Comment by keenborder786** [comment]
Something like this will work. Correct @arozbiz

JSONL File:
```json
{"html": "This is a sentence."}
{"html": "This is another sentence."}
```


```python
from langchain.document_loaders import JSONLinesLoader

jl = JSONLinesLoader(file_path=".jsonl", jq_schema=".html")
jl.load()

```

**Comment by arozbiz** [comment]
Yup, that's what I'm looking for.

**Comment by keenborder786** [comment]
ok great.

**Comment by rlancemartin** [comment]
See -

https://github.com/hwchase17/langchain/pull/6913

Does this resolve what you are looking for?

**Comment by arozbiz** [comment]
It does, thank you!
