### ISSUE TITLE
InvalidRequestError: This model's maximum context length

### ISSUE THREAD

**Issue by ninjiakill** [hwchase17/langchain#7054]
### System Info

langchain: 0.0.221

python:3.10.2

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.document_loaders import TextLoader

from langchain.document_loaders import TextLoader

loader = TextLoader("my_file.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=10, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()

### Expected behavior

I‘m follow the smae code on official wbsite "https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/faiss",but replace the txt file content with another (http://novel.tingroom.com/jingdian/5370/135425.html),and the CharacterTextSplitter chunk_size set to10 ,or 100 whatever,then the error kept on raising up:InvalidRequestError: This model's maximum context length is 8191 tokens, however you requested 10137 tokens (10137 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.

is this “from_documents” method has some kind of character restriction,or it just dont support Long text？

**Comment by HashemAlsaket** [comment]
8191 tokens is the limit set by the OpenAI API. Langchain is respecting this limit by support explicit proxy for OpenAI:
https://github.com/hwchase17/langchain/blob/6d15854cda60823d1c2a8efc395d9c074336bdca/langchain/embeddings/openai.py#L161

**Comment by GeneralLHW** [comment]
I also encountered this problem, but I haven't found a solution yet. I only asked 1+1, and this error occurred. I want to know how to see the content of prompt and completion when he said that the length is exceeded.
