### ISSUE TITLE
HuggingFaceEndpoint Class Bug

### ISSUE THREAD

**Issue by syeminpark** [hwchase17/langchain#7353]
### System Info

the provided class
[langchain/langchain/llms/huggingface_endpoint.py](https://github.com/hwchase17/langchain/blob/370becdfc2dea35eab6b56244872001116d24f0b/langchain/llms/huggingface_endpoint.py)
 class HuggingFaceEndpoint(LLM): 

has a bug.
it should be
```python
if self.task == "text-generation":
# Text generation return includes the starter text.
text = generated_text[0]["generated_text"]
```
not
```python
text = generated_text[0]["generated_text"][len(prompt) :]
```

the current class will likely just return a 0.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
    llm= HuggingFaceEndpoint(endpoint_url=os.getenv('ENDPOINT_URL'),task="text-generation",
                              model_kwargs={"temperature":0.7, "max_length":512})
 conversation_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=vectorstore.as_retriever(),
        memory=memory
    )

```

### Expected behavior

the output is 0

**Comment by HashemAlsaket** [comment]
Good catch. Related conversation on Hugging Face 2 weeks ago: https://huggingface.co/tiiuae/falcon-40b-instruct/discussions/51

I tested your code and received blank response using `text-generation`.
When using `text2text-generation` , `1871` is returned.
