### ISSUE TITLE
Have set my langchain+ tracing key, it is not being recognized

### ISSUE THREAD

**Issue by solarslurpi** [hwchase17/langchain#7431]
### System Info

```
$ uname -a
MINGW64_NT-10.0-19045 LAPTOP-4HTFESLT 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys

$ python --version
Python 3.10.11

$ pip show langchain
Name: langchain
Version: 0.0.228
Summary: Building applications with LLMs through composability
Home-page: https://www.github.com/hwchase17/langchain
Author:
Author-email:
License: MIT
Location: c:\users\happy\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages
Requires: aiohttp, async-timeout, dataclasses-json, langchainplus-sdk, numexpr, numpy, openapi-schema-pydantic, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by:



```

### Who can help?

I cannot get a trace on langchain. Error:
```
File "c:\Users\happy\Documents\Projects\askjane\.venv\lib\site-packages\langchain\callbacks\manager.py", line 1702, in _configure
    logger.warning(
Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'
Arguments: (LangChainPlusUserError('API key must be provided when using hosted LangChain+ API'),)
```
I do this check:
```
print(os.environ["LANGCHAIN-API-KEY"])
```
the correct LangchainPlus/langsmith/langchain api key is shown.  I thought this was how it was done.  I do set the other os envionment variables.

It doesn't pick up my api key.

i apologize if i am doing something stupid. but it's not working to the best of my knowledge.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

import os
os.environ["OPENAI_API_KEY"] = "..."
os.environ["LANGCHAIN-API-KEY"] = "..."
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.langchain.plus"
os.environ["LANGCHAIN_PROJECT"] = "Explore Evaluating index using LLM" 

print(os.environ["LANGCHAIN-API-KEY"])

from langchain import OpenAI
OpenAI().predict("Hello, world!")

### Expected behavior

go to langsmith and see the trace.

**Comment by solarslurpi** [comment]
oh my.  i stared at this too long i guess. Stupid on my part.

**Comment by dtthanh1971** [comment]
```
import os
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_API_KEY"] = "my API key"
os.environ["LANGCHAIN_PROJECT"] = 'default'

from langchain.chat_models import ChatOpenAI

llm1 = ChatOpenAI()
llm1.predict("Hello, world!")


```
 I have also the message:
 
 Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the  LANGCHAIN_TRACING_V2 environment variables.'
Arguments: (TypeError("Retry.__init__() got an unexpected keyword argument 'allowed_methods'"),)

'Hello there! How can I assist you today?'

**Comment by Khadija-Bayoud** [comment]
same problem!
