### ISSUE TITLE
BUG with OpenAI(maxToken=-1) when Caching enabled

### ISSUE THREAD

**Issue by thepok** [hwchase17/langchain#747]
```
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain.llms import OpenAI
from langchain.chains import LLMChain
from langchain.cache import SQLiteCache
import langchain

langchain.llm_cache=SQLiteCache(".langchain.db")
OpenAI(temperature=0, max_tokens=-1)("hallo")
OpenAI(temperature=0, max_tokens=-1)("hallo")

```
ValueError                                Traceback (most recent call last)
Cell In [22], line 1
----> 1 OpenAI(temperature=0, max_tokens=-1)("hallo")
      2 OpenAI(temperature=0, max_tokens=-1)("hallo")

File C:\Repos\langchain\langchain\llms\base.py:134, in BaseLLM.__call__(self, prompt, stop)
    132 def __call__(self, prompt: str, stop: Optional[List[str]] = None) -> str:
    133     """Check Cache and run the LLM on the given prompt and input."""
--> 134     return self.generate([prompt], stop=stop).generations[0][0].text

File C:\Repos\langchain\langchain\llms\base.py:102, in BaseLLM.generate(self, prompts, stop)
    100 except Exception as e:
    101     self.callback_manager.on_llm_error(e, verbose=self.verbose)
--> 102     raise e
    103 self.callback_manager.on_llm_end(new_results, verbose=self.verbose)
    104 for i, result in enumerate(new_results.generations):

File C:\Repos\langchain\langchain\llms\base.py:99, in BaseLLM.generate(self, prompts, stop)
     95 self.callback_manager.on_llm_start(
     96     {"name": self.__class__.__name__}, missing_prompts, verbose=self.verbose
     97 )
     98 try:
---> 99     new_results = self._generate(missing_prompts, stop=stop)
    100 except Exception as e:
...
    149     prompts[i : i + self.batch_size]
    150     for i in range(0, len(prompts), self.batch_size)
    151 ]

ValueError: max_tokens set to -1 not supported for multiple inputs.

**Comment by hwchase17** [comment]
not a bug per se, this was somewhat intentional - i wasn't 100% sure what to pass in as the max_tokens when multiple prompts exist. 

what would you suggest? just taking the value that would work for all of them? aka the minimum max token of all the individual prompts?

**Comment by thepok** [comment]
i made a fix

https://github.com/hwchase17/langchain/pull/777

i hope somebody can clean it up to the repository standards

**Comment by hwchase17** [comment]
> i made a fix
> 
> #777
> 
> i hope somebody can clean it up to the repository standards

will clean up now - thanks!
