### ISSUE TITLE
0.0.229 breaks existing code that works with 0.0.228 for ConverstaionalRetrievalChain

### ISSUE THREAD

**Issue by MarkEdmondson1234** [hwchase17/langchain#7481]
### System Info

Works in 0.0.228 but breaks in 0.0.229

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The latest version of Langchain (0.229) seems to break working code in 0.0.228.

e.g this code works in 0.228

```python
def qna(question: str, vector_name: str, chat_history=[]):

    logging.debug("Calling qna")

    llm, embeddings, llm_chat = pick_llm(vector_name)

    vectorstore = pick_vectorstore(vector_name, embeddings=embeddings)

    retriever = vectorstore.as_retriever(search_kwargs=dict(k=3))

    prompt = pick_prompt(vector_name)

    logging.basicConfig(level=logging.DEBUG)
    logging.debug(f"Chat history: {chat_history}")
    qa = ConversationalRetrievalChain.from_llm(ChatOpenAI(model="gpt-4", temperature=0.2, max_tokens=5000),
                                               retriever=retriever, 
                                               return_source_documents=True,
                                               verbose=True,
                                               output_key='answer',
                                               combine_docs_chain_kwargs={'prompt': prompt},
                                               condense_question_llm=OpenAI(model="gpt-3.5-turbo", temperature=0))

    try:
        result = qa({"question": question, "chat_history": chat_history})
    except Exception as err:
        error_message = traceback.format_exc()
        result = {"answer": f"An error occurred while asking: {question}: {str(err)} - {error_message}"}
    
    logging.basicConfig(level=logging.INFO)
    return result
```

But in 0.229 it errors like this:

```
INFO:openai:error_code=None error_message='This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?' error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
```

### Expected behavior

Same output

**Comment by kdcokenny** [comment]
I would recommend using `ChatOpenAI` rather than `OpenAI` when working with a chat model (like gpt-3.5-turbo). Based on the error, I believe that change will fix it.

**Comment by Karimium0** [comment]
It would be great if you can lay out a prompt instead and elaborate further on what vector_name is supposed to be here.
I want to try your fix but I'm not sure what the prompt is supposed to be too. 
info: I'm using ChromaDB and a local llm / embeddings model. Thanks
