### ISSUE TITLE
RetrievalQAWithSourcesChain acall does not write fromatted prompt to terminal if verbose=True

### ISSUE THREAD

**Issue by jlootensdataroots** [hwchase17/langchain#7526]
### System Info

python==3.10
langchain==0.0.169

### Who can help?

@agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [X] Async

### Reproduction

Steps to reproduce:
1. Open the [example notebook](https://colab.research.google.com/drive/1ut3LVSSxsN_C52Pn1ceqWdHjSzhxuZol?usp=sharing)  
2. Replace ```insert API key here```with your API key  
3. Run all cells

### Expected behavior

Asynchronously calling the RetrievalQAWithSourcesChain with ```chain_type_kwargs = {"prompt": prompt, "verbose": True}``` should result in the same terminal output as the synchronous version instead of skipping "Prompt after formatting: ..."

```result = chain(query)``` output:

```
> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:
PROMPT_AFTER_FORMATTING

> Finished chain.

> Finished chain.
```

Wrong ```result = await chain.acall(query)``` output:
```
> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...

> Finished chain.

> Finished chain.
```

**Comment by jlootensdataroots** [comment]
@tleers, @andreabenevenut, @SenneDataroots

**Comment by tleers** [comment]
Is it possible to update langchain to see if that fixes it?

langchain==0.0.169 is a relatively old version?

**Comment by jlootensdataroots** [comment]
Solved in latest version apparently
