### ISSUE TITLE
PGVector.from_documents breaking from 0.0.229 to 0.0.230

### ISSUE THREAD

**Issue by dcieslak19973** [hwchase17/langchain#7577]
### System Info

langchain==0.0.230

### Who can help?

@raymond-yuan 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Fill in appropriate values for parameters
```
db = PGVector.from_documents(
    embedding=embeddings,
    documents=docs,
    collection_name=COLLECTION_NAME,
    connection_string=CONNECTION_STRING,
    pre_delete_collection=True,
)
```

Produces:
```
Traceback (most recent call last):
  File "create_pgvector_index_hr.py", line 70, in <module>
    db = PGVector.from_documents(
  File "/home/coder/venv-openai-slackbot/lib/python3.8/site-packages/langchain/vectorstores/pgvector.py", line 578, in from_documents
    return cls.from_texts(
  File "/home/coder/venv-openai-slackbot/lib/python3.8/site-packages/langchain/vectorstores/pgvector.py", line 453, in from_texts
    return cls.__from(
  File "/home/coder/venv-openai-slackbot/lib/python3.8/site-packages/langchain/vectorstores/pgvector.py", line 213, in __from
    store = cls(
TypeError: ABCMeta object got multiple values for keyword argument 'connection_string'
```

and appears related to this change: https://github.com/hwchase17/langchain/blame/master/langchain/vectorstores/pgvector.py#L213-L220

### Expected behavior

Above code works with langchain==0.0.229

Code should not throw an exception as it did prior to 0.0.230

**Comment by raymond-yuan** [comment]
I believe this is fixed in master already https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/pgvector.py#L190. I also believe the change introduced by that PR shouldn't have caused this issue.

**Comment by dcieslak19973** [comment]
Confirmed working in 0.0.231
