### ISSUE TITLE
namespace parameter is gone in pinecone from_existing_index method

### ISSUE THREAD

**Issue by kkbpower** [hwchase17/langchain#7589]
### System Info

I am using langchain v0.0.228. But namespace parameter is gone in existing_index() of v0.0.230.
Why the namespace is gone?

@hwchase17 @eyurtsev @agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

No need.

### Expected behavior

should be used from_existing_index method with namespace parameter

**Comment by devstein** [comment]
Relates to https://github.com/hwchase17/langchain/pull/7473#issuecomment-1631830182

**Comment by baskaryan** [comment]
change reverted in 0.0.231
