### ISSUE TITLE
Is it possible to use open source embedding methods rather than OpenAIEmbeddings?

### ISSUE THREAD

**Issue by ykemiche** [hwchase17/langchain#7619]
### System Info

LangChain version :  0.0.216
Python version : 3.11.4
System: Windows

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I want to create a chatbot to retrieve information from my own pdf  in response to a query  using google PaLM model, I followed these steps : 
-load the pdf
-split it using RecursiveCharacterTextSplitter
-store its embeddings in a Chroma vectorestore
and then create a chain ...

```
from langchain.document_loaders import PyPDFLoader
from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.embeddings.openai import OpenAIEmbeddings

import langchain

loader=PyPDFLoader("path/to/pdf.pdf")
chroma_dir="./chroma
pages=loader.load()
splitter=RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=150,
    separators=['\n\n','\n'," ",""]
)

splits=splitter.split_documents(pages)

#I want to change this with another embedding method which doesn't require API authentification
embeddings=OpenAIEmbeddings()

vector_db=Chroma.from_documents(
documents=splits,
embedding=embeddings,
persist_directory=chroma_dir
)

```

But the only embedding method that is available in the LangChain documentation is OpenAIEmbeddings,how can we do without it?

### Expected behavior

all the splits embeddings stored in Chroma vectorestore without using OpenAIEmbeddings()

**Comment by mswoff** [comment]
If you want Google PALM
```
from langchain.embeddings.google_palm import GooglePalmEmbeddings
...
embeddings = GooglePalmEmbeddings()
```

You can alternatively use VertexAIEmbeddings as an alternative to OpenAIEmbeddings. This method does not require API authentication. Here is how you can modify your code:

```
from langchain.embeddings.vertexai import VertexAIEmbeddings

# Replace OpenAIEmbeddings with VertexAIEmbeddings
embeddings = VertexAIEmbeddings()

vector_db = Chroma.from_documents(
    documents=splits,
    embedding=embeddings,
    persist_directory=chroma_dir
)
```
