### ISSUE TITLE
HuggingFaceTextGenInference: required fields not permitted, e.g. 'truncate'

### ISSUE THREAD

**Issue by RobertoDonPedro** [hwchase17/langchain#7650]
### System Info

langchain==0.0.229
text-generation==0.6.0

Python 3.10.12

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The class [HuggingFaceTextGenInference](https://github.com/hwchase17/langchain/blob/master/langchain/llms/huggingface_text_gen_inference.py) does not support all parameters of the HuggingFace text generation inference API.

Especially we need the attribute `truncate`.

E.g. 
```
            llm = HuggingFaceTextGenInference(
                inference_server_url="http://localhost:8080/",
                temperature=0.9,
                top_p=0.95,
                repetition_penalty=1.2,
                top_k=50,
                truncate=1000,
                max_new_tokens=1024                         
            )
```
results in the error message 
```
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceTextGenInference
truncate
  extra fields not permitted (type=value_error.extra)
```

### Expected behavior

No error

**Comment by baskaryan** [comment]
@RobertoDonPedro thanks for flagging! would gladly review a PR if you wanted to add the attribute. otherwise can get to it in next few days
