### ISSUE TITLE
DOC: ContextualCompressionRetriever - is it possible to retain sources

### ISSUE THREAD

**Issue by dcieslak19973** [hwchase17/langchain#7661]
### Issue with current documentation:

I'd like to pass in documents to a chain created from `load_qa_with_sources_chain` that are the results of `compression_retriever.get_relevant_documents(user_query)`.  It's not clear from the documentation whether this is possible, and, if so, how to accomplish it.

### Idea or request for content:

An example demonstrating this if it is currently possible.

If it is not currently possible, a feature request to make it so

**Comment by dcieslak19973** [comment]
i think i sorted myself

**Comment by watermeleon** [comment]
Hi there, I am running into the same problem. Do you mind sharing your solution?
