### ISSUE TITLE
DOC: SupabaseVectorStore.from_documents read operation timed out.

### ISSUE THREAD

**Issue by shangdev** [hwchase17/langchain#7823]
### Issue with current documentation:

```
# We're using the default `documents` table here. You can modify this by passing in a `table_name` argument to the `from_documents` method.
vector_store = SupabaseVectorStore.from_documents(docs, embeddings, client=supabase)
```

### Idea or request for content:

throw error: httpx.ReadTimeout: The read operation timed out

Is it because the documents are too large? Is there a way to change the timeout?

**Comment by Mr-Ye-Cao** [comment]
How was this addressed? Is there solution other than the bot's?
