### ISSUE TITLE
Error in OpenAI Functions Agent 

### ISSUE THREAD

**Issue by orlandombaa** [hwchase17/langchain#8009]
### Issue with current documentation:

Hello every one! 

I am following the tutorial of the use of agents. Specifically, now I am exploring the type [OpenAIFunctions. ](https://python.langchain.com/docs/modules/agents/agent_types/openai_functions_agent).

I am following the exact same tutorial and I get some error when I want to use the agent to solve some math problems or connect to my SQL Data base which are tools that the agents have available. The error that I have is the following: 

```python
ValidationError: 1 validation error for AIMessage
content
  none is not an allowed value (type=type_error.none.not_allowed)
```

Does any one know what is causing this error? 

Best regards, 
Orlando

**Comment by keenborder786** [comment]
@orlandombaa you are correct. With the new update, if AIMessage is not passed in extra_prompt_messages, the `intialize_agent` gives a validation error. I will create a PR to update the documentation.

**Comment by keenborder786** [comment]
@orlandombaa update the issue has been fixed in the new newer version. Please update your langchain package and you should not experience the error. I just test out the version `0.0.237`

**Comment by orlandombaa** [comment]
Hello @keenborder786 
I appreciate your answer, I just upgrade Langchain to the newest version, and now works well. 
Thank you!
