### ISSUE TITLE
Support (optional) direct return on `SQLDatabaseChain` to prevent passing data to LLM

### ISSUE THREAD

**Issue by zachschillaci27** [hwchase17/langchain#821]
Thanks for the amazing open source work!

For certain data-sensitive projects, it may be important to silo the database and its contents (aside from table/column names) from any calls to the LLM. This means the LLM cannot be used for formatting the output of the SQL query. I suppose one way to support this would be to allow something like the `Tool` option `return_direct` in the `SQLDatabaseChain` chain, but perhaps there's a better way. I'm happy to help contribute as needed.

**Comment by hwchase17** [comment]
love this idea, let me get on it

**Comment by hwchase17** [comment]
thoughts on the above pr?

**Comment by zachschillaci27** [comment]
> thoughts on the above pr?

Looks great, thanks for the quick response!
