### ISSUE TITLE
tutorial for chat-langchain

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchain#823]
a tutorial that slowly adds complexity would be great, looking around in here and the web right now for that. By that I mean going from a simple vector store, to a chain (e.g. qa), to adding memory and chat history, slowly creating a custom env/chain/etc.

**Comment by pruksmhc** [comment]
I would be interested to pick this up.
What's the thinking behind starting with a vector chain as the most simple version?
I would think the simple to hard version would look like this:
End goal: An assistant that is able to answer questions and cite them. Specifically, we will ask about the nearest health sites (e.g. pharmacies, clinics, etc) and answers questions about cancer navigation (grounded in a cancer navigation document). 
Phase 1: Build a chain for getting nearest health site (Probably will need to integrate with Google Maps API)
Phase 2: Create a vector store for cancer navigation
Phase 3: Create a QA with sources chain for cancer navigation questions
Phase 4: Create an agent
Phase 5: Create an agent w/ memory, especially for elaborating on questions about cancer navigation. 

I can also swap cancer care for a health coach type assistant as well.

**Comment by hwchase17** [comment]
done with https://blog.langchain.dev/tutorial-chatgpt-over-your-data/
