### ISSUE TITLE
[Feature Request] Relax template validation to allow for passing objects as inputs with jinja2

### ISSUE THREAD

**Issue by Glavin001** [hwchase17/langchain#840]
## Use Case

I have complex objects with inner properties I want to use within the Jinja2 template.

Prior to https://github.com/hwchase17/langchain/pull/148 I believe it was possible. Fairly certain I have an older project with older langchain using this approach. Now when I update langchain I'm not able to do this.

### Example

```python
template = """The results are:
---------------------
{% for result in results %}
{{ result.someProperty }}
{% endfor %}
---------------------

{{ text }}

# {% for result in results %}
{{ result.anotherProperty }}
{% endfor %}
"""

prompt = PromptTemplate(
    input_variables=["text", "results"],
    template_format="jinja2",
    template=template,
)
```

#### Output with error:

```
UndefinedError                            Traceback (most recent call last)
Cell In[15], line 38
...
File ~/.cache/pypoetry/virtualenvs/REDACTED/lib/python3.11/site-packages/pydantic/main.py:340, in pydantic.main.BaseModel.__init__()
...
--> 485     return getattr(obj, attribute)
    486 except AttributeError:
    487     pass

UndefinedError: 'str object' has no attribute 'someProperty'
```

## Workaround

Pass in a list of strings instead of objects..

## Proposed Solution

I think this is the applicable code:
https://github.com/hwchase17/langchain/blame/b0d560be5636544aa9cfe305febf01a98fd83bc6/langchain/prompts/base.py#L43-L46

Even disabling validation of templates would be sufficient.

Thanks!

**Comment by hwchase17** [comment]
does the above pr help?

**Comment by Glavin001** [comment]
Wow, you're fast! 🚀  Thank you so much! I expect this will work for me ✅ 

FYI I'll definitely be trying to contribute _with code/PRs_ in the future to `langchain`. I'm primarily a web developer, and re-learning Python now solely to be able to use `langchain`. I have other changes locally I'll try to generalize and contribute back when I have some time -- or if you and team haven't already finished those already, too 😉

**Comment by hwchase17** [comment]
ooc, what languages are you most familiar with? javascript by any chance?

**Comment by Glavin001** [comment]
Yes, JavaScript/TypeScript. Haven't written Python in years (maybe 10+).

**Comment by andersonbcdefg** [comment]
@hwchase17  It would be awesome if you could add Jinja2 example(s) back to the LangChain docs. There's like, ghost references to them in various places, but no working examples I can find (had to come here to find one, lol). Would especially appreciate an example with the ChatPromptTemplate, since using OAI chat models is so common now. The use case I'm trying to hack out right now is a multiple-choice question, where I want to just be able to pass the question in and use Jinja2 template to format it. 

## Example
```
# Define prompt template
system_template = """You are a legal expert who specializes in professional ethics. \
When prompted with a multiple-choice question about legal professional ethics, please identify the correct answer. \
Your response should be one of "a", "b", "c", or "d", with no additional information."""
system_message_prompt = SystemMessagePromptTemplate.from_template(system_template)
human_template="""QUESTION: {{ question.question }}

OPTIONS:
a. {{ question.options.a }}
b. {{ question.options.b }}
c. {{ question.options.c }}
d. {{ question.options.d }}

ANSWER:"""
human_message_prompt = HumanMessagePromptTemplate.from_template(human_template, template_format="jinja2", input_variables=["question"])
chat_prompt = ChatPromptTemplate.from_messages([system_message_prompt, human_message_prompt])

example_question = {
    "question":"What color is the sky?",
    "options": {
        "a": "blue",
        "b": "red",
        "c": "green"
    }
}

chat_prompt.format(question=example_question)
```

## Output
```
System: You are a legal expert who specializes in professional ethics. When prompted with a multiple-choice question about legal professional ethics, please identify the correct answer. Your response should be one of "a", "b", "c", or "d", with no additional information.
Human: QUESTION: { question.question }

OPTIONS:
a. { question.options.a }
b. { question.options.b }
c. { question.options.c }
d. { question.options.d }

ANSWER:
```

What I'd expect/hope is that, since the human template is a Jinja2 template, that the chat template would be able to pass along / handle the Jinja2 template inside of it. Clearly there's some interaction here that's not working.
