### ISSUE TITLE
Erroneous routing to tiktoken vocab

### ISSUE THREAD

**Issue by spolu** [hwchase17/langchain#843]
https://github.com/hwchase17/langchain/blob/bfabd1d5c0bf536fdd1e743e4db8341e7dfe82a9/langchain/llms/openai.py#L246

You should probably route according to this here: https://github.com/openai/tiktoken/issues/27

:)

**Comment by hauntsaninja** [comment]
I just released tiktoken v0.2.0 which will let you do `tiktoken.encoding_for_model("text-davinci-003")`
