### ISSUE TITLE
FAISS should save/load its index_to_id map

### ISSUE THREAD

**Issue by xloem** [hwchase17/langchain#853]
The save_local, load_local member functions in vectorstore.faiss seem firstly to need to read/write the index_to_id map as well as the main index file. This would then fully separate the storage concerns between the Docstore and the VectorStore.

As it is now, the index_to_id map is an additional component the user must separately serialize/deserialize to reload an FAISS index associated with a Docstore.

**Comment by ShreyJ1729** [comment]
Check out https://github.com/hwchase17/langchain/issues/789 and https://github.com/hwchase17/langchain/pull/880.

**Comment by xloem** [comment]
Thanks for your work on this. It looks like the code currently in tree is broken and any change could be an improvement. Closing this as it is a duplicate.
