### ISSUE TITLE
HuggingFaceInstructEmbeddings not working.

### ISSUE THREAD

**Issue by shyam-santoki** [hwchase17/langchain#867]
I am getting an error when using HuggingFaceInstructEmbeddings.

**Error:**
The error says **Dependencies for InstructorEmbedding not found.**

**Traceback:**
```
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[/usr/local/lib/python3.8/dist-packages/langchain/embeddings/huggingface.py](https://localhost:8080/#) in __init__(self, **kwargs)
    102         try:
--> 103             from InstructorEmbedding import INSTRUCTOR
    104 

ModuleNotFoundError: No module named 'InstructorEmbedding'

The above exception was the direct cause of the following exception:

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-3-e0422159889a>](https://localhost:8080/#) in <module>
----> 1 embeddings = HuggingFaceInstructEmbeddings(query_instruction="Represent the query for retrieval: ")

[/usr/local/lib/python3.8/dist-packages/langchain/embeddings/huggingface.py](https://localhost:8080/#) in __init__(self, **kwargs)
    105             self.client = INSTRUCTOR(self.model_name)
    106         except ImportError as e:
--> 107             raise ValueError("Dependencies for InstructorEmbedding not found.") from e
    108 
    109     class Config:

ValueError: Dependencies for InstructorEmbedding not found.
```

**Cause of error:**
The error is occurring in ```langchain/embeddings/huggingface.py``` file at ```Line 103```.

**Comment by sanzgiri** [comment]
@shyam-santoki - in order to use these embeddings, you need ``InstructorEmbedding`` installed. I don't see it in the docs. Have you submitted a PR for this?

**Comment by Adonis2018** [comment]
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/LangChain_LLM_ChatBot-main/chatbot.py", line 57, in <module>
    main()
  File "/LangChain_LLM_ChatBot-main/chatbot.py", line 48, in main
    embedding_model = get_huggingfaceEmbedding_model(model_name="meta-llama/Llama-2-13b-chat-hf")
  File "/LangChain_LLM_ChatBot-main/models/embedding_model.py", line 9, in get_huggingfaceEmbedding_model
    return HuggingFaceInstructEmbeddings(model_name=model_name)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/langchain/embeddings/huggingface.py", line 152, in __init__
    raise ImportError("Dependencies for InstructorEmbedding not found.") from e
ImportError: Dependencies for InstructorEmbedding not found.
```

I also have this problem, but I have installed 'InstructorEmbedding'

**Comment by homosapienssapiens** [comment]
`Traceback (most recent call last):
  File "D:\Github\curso-langchain\hashira\conversation_ai.py", line 57, in <module>
    main()
  File "D:\Github\curso-langchain\hashira\conversation_ai.py", line 44, in main
    embedding = HuggingFaceInstructEmbeddings(
  File "C:\Users\Miguel\AppData\Local\pypoetry\Cache\virtualenvs\hashira-twXMOMRH-py3.9\lib\site-packages\langchain\embeddings\huggingface.py", line 152, in __init__
    raise ImportError("Dependencies for InstructorEmbedding not found.") from e
ImportError: Dependencies for InstructorEmbedding not found.`
Same here. Installed InstructorEmbedding and it's not working.

**Comment by homosapienssapiens** [comment]
Same here. Installed InstructorEmbedding and it's not working.

**Comment by sanzgiri** [comment]
I assume your are using the HuggingFace Instructor to generate embeddings instead of using `text-embedding-ada-002`. If that's the case, you need to install the following packages:
sentence-transformers
InstructorEmbedding

Also, you will need to generate the embeddings on a machine with GPU.

**Comment by homosapienssapiens** [comment]
Thank you!
