### ISSUE TITLE
from_tiktoken_encoder creating over-sized chunks

### ISSUE THREAD

**Issue by phil-scholarcy** [hwchase17/langchain#872]
Hi there

Thanks for creating such a useful library. It's a game-changer for working efficiently with LLMs!

I'm trying to get `CharacterTextSplitter.from_tiktoken_encoder()` to chunk large texts into chunks that are under the token limit for GPT-3.

The problem is that no matter what I set the `chunk_size` to, the chunks created are too large, and I get this error

```
INFO - error_code=None error_message="This model's maximum context length is 2049 tokens, however you requested 3361 tokens (2961 in your prompt; 400 for the completion). Please reduce your prompt; or completion length." error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
```

Is there a magic incantation to get chunk sizes under the input limit?

Cheers

**Comment by aparekh5** [comment]
having the same issue ^ 
```
text_splitter = CharacterTextSplitter.from_tiktoken_encoder(chunk_size=100, chunk_overlap=0)
text = text_splitter.split_text(extract_text())
```

**Comment by aparekh5** [comment]
Actually was able to fix it. Seems like the library will only split the tokens around the separator which by default is \n\n. So if the separator is not present it will not split the text . You probably have to use a different separator. I am not sure if you can pass multiple separators into the function

**Comment by phil-scholarcy** [comment]
@aparekh5 Yes, if you have a long paragraph of text that contains no line breaks, the chunking seems not to work.

Maybe we first need to run a sentence splitter on the input to chunk sentences into `\n\n` delimited sentences.

**Comment by jamescalam** [comment]
You can change the default `separator`:

```python
text_splitter = CharacterTextSplitter.from_tiktoken_encoder(
    separator='.\n',
    encoding_name=encoder_name,  # tiktoken encoding name
    chunk_size=max_tokens,
    chunk_overlap=100  # let's add a small overlap
)
texts = text_splitter.split_text(text)
```

It will still not split if the separator doesn't exist however

**Comment by phil-scholarcy** [comment]
@jamescalam thanks, this was the magic I was missing :)

I got the `encoding_name` from the mappings in `tiktoken.model.MODEL_TO_ENCODING` and I first run a sentence splitter on the input text so that the `separator` matches how the text is actually separated. 

Works a treat - thanks again!

**Comment by aparekh5** [comment]
could it be possible to have the ability of passing an array of different separators ? rather than having to run the function multiple times

**Comment by jamescalam** [comment]
@aparekh5 this would be better, although I tested this and I think there may be another issue — on my own data I can write a function to split with a given separator and it works fine, however when using the langchain implementation it doesn't work, despite the separate being in the text that should be broken up

I'm not sure why this is yet, and it didn't seem to happen too frequently - however I did notice that there were more chunks that were longer than the limit that what was being printed by the text_splitter function
