### ISSUE TITLE
page does not exist

### ISSUE THREAD

**Issue by suppathak** [hwchase17/langchain#933]
Hello ,
I am looking into the docs getting started page. While going through the link in the [page](https://github.com/hwchase17/langchain/blob/master/docs/use_cases/question_answering.md) . I got the broken link. It says the page does not exist. Can you please point me to the link, "[Question Answering Notebook](https://github.com/hwchase17/langchain/blob/master/modules/chains/combine_docs_examples/question_answering.ipynb): A notebook walking through how to accomplish this task"

Thank you!

**Comment by concaption** [comment]
Kindly see it on documentation [Documentation](https://langchain.readthedocs.io/en/latest/use_cases/question_answering.html)

**Comment by suppathak** [comment]
Thank you!!
