### ISSUE TITLE
Connect Using Azure OpenAI Resource

### ISSUE THREAD

**Issue by anurag899** [hwchase17/langchain#971]
To setup the environment for azure openAI, We may require to setup couple of other values along with api key (refer -https://learn.microsoft.com/en-us/azure/cognitive-services/openai/quickstart?pivots=programming-language-python).
I am not able to find how to integrate this library with the azure api. 
What keys/parameter I should pass to setup these values?

**Comment by hwchase17** [comment]
@gojira any insight here?

**Comment by anurag899** [comment]
@hwchase17 @gojira  I am able to see integrate langchain to azure openAI 
`# Import Azure OpenAI
from langchain.llms import AzureOpenAI
import os
# Set this to `azure`
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = '2022-12-01'
os.environ["OPENAI_API_BASE"] = "https://<resource-name>.openai.azure.com/"
os.environ["OPENAI_API_KEY"] = "<key_value>"
llm = AzureOpenAI(deployment_name="<model_deployment>", model_name="text-davinci-002",temperature=0)
`
But I couldn't find something similar when it comes to openAI embedding. 
`from langchain.embeddings.openai import OpenAIEmbeddings`
As in above class, there is no argument to separately provide azure openai ada embedding. 
Let me know if I am missing something here. Thanks

**Comment by anurag899** [comment]
@hwchase17 - I think you can mark this as new feature. correct me if I am wrong but probably there is no functionality yet for having azure openAI embedding 
![image](https://user-images.githubusercontent.com/14952229/218196929-654a72c9-f764-4163-9f1c-dacbee6b2da8.png)

**Comment by gojira** [comment]
You should be able to call with `engine` set to your Azure OpenAI embedding deployment name.  @anurag899

**Comment by anurag899** [comment]
@gojira  - Thanks for your suggestion. I have tried to initialize AzureOpenAI class before embedding class. This resolved my issue. I have passed my model name like below -
`embeddings = OpenAIEmbeddings(document_model_name=azure_embd_model,query_model_name=azure_embd_model)`
