### ISSUE TITLE
SQLite Cache memory for async agent runs fails in concurrent calls

### ISSUE THREAD

**Issue by cacorrea-bci** [hwchase17/langchain#983]
I have a slack bot using slack bolt for python to handle various request for certain topics.

Using the SQLite Cache as described in here 
https://langchain.readthedocs.io/en/latest/modules/llms/examples/llm_caching.html

Fails when asking the same question mutiple times for the first time with error

> (sqlite3.IntegrityError) UNIQUE constraint failed: full_llm_cache.prompt, full_llm_cache.llm, full_llm_cache.idx

As an example code:

```python3
from langchain.cache import SQLiteCache
langchain.llm_cache = SQLiteCache(database_path=".langchain.db")

import asyncio
from slack_bolt.async_app import AsyncApp
from slack_bolt.adapter.socket_mode.async_handler import AsyncSocketModeHandler

# For simplicity lets imagine that here we 
# instanciate LLM , CHAINS and AGENT

app = AsyncApp(token=SLACK_BOT_API_KEY)

async def async_run(self, agent_class, llm, chains):
      
       @app.event('app_mention')
        async def handle_mention(event, say, ack):
            # Acknowlegde message to slack
            await ack()

            # Get response from agent
            response = await agent.arun(message)

           #Send response to slack
            await say(response)


        handler = AsyncSocketModeHandler(app, SLACK_BOT_TOKEN)
        await handler.start_async()


asyncio.run(async_run(agent, llm, chains))

```

I imagine that this has something to do with how the async calls interact with the cache, as it seems that the first async call creates the prompt in the sqlite mem cache but without the answer, the second one (and other) async calls tries to create the same record in the sqlite db, but fails because of the first entry.

**Comment by ahoho** [comment]
I'm getting this error too, but I'm not using async. I'm not sure, but I think it may be the result of repeated prompts within a batch?
